export const DATE_FORMAT = {
  DATE: {
    HYPHEN: 'YYYY-MM-DD',
    SLASH: 'YYYY/MM/DD',
    DOT: 'YYYY.MM.DD',
    DOT_DATE: 'YYYY.MM.DD ddd',
    MONTH: 'YYYY.MM',
    STRING: 'MMMM DD, YYYY',
    MONTH_HYPHEN: 'YYYY-MM',
    DATE_HYPHEN: 'MM-DD',
    YEAR: 'YYYY',
    DOT_SHORTEN: 'YY.MM.DD',
  },
  DATE_TIME: {
    HYPHEN: 'YYYY-MM-DD HH:mm',
    SLASH: 'YYYY/MM/DD hh:mm',
    DOT: 'YYYY.MM.DD hh:mm',
    DOWNLOAD: 'YYYY-MM-DD_hh:mm',
    AM_PM: 'YYYY-MM-DD, HH A',
    CUSTOM: 'YYYY-MM-DD / hh:mm',
  },
  DATE_TIME_SECOND: {
    HYPHEN: 'YYYY-MM-DD hh:mm:ss',
    SLASH: 'YYYY/MM/DD hh:mm:ss',
    DOT: 'YYYY.MM.DD hh:mm:ss',
    DOWNLOAD: 'YYYY-MM-DD_hh:mm:ss',
    ISO8601: 'YYYY-MM-DDTHH:mm:ss',
    CUSTOM: 'YYYY-MM-DD / hh:mm:ss',
  },
  TIME: {
    _12H: 'A hh:mm',
    PICKER: 'hh:mm::ss',
    PICKER_HOUR_MIN: 'HH:mm',
    _12H_PICKER: 'hh:mm A',
    _24H: 'H:m',
    _60P: 'mm:ss',
  },
};
