def FAILED_STAGE

pipeline {
    agent {
        node {
            label 'kv3-linux-1'
        }
    }
    environment {
        ENV_VERSION = '1.0.2'
        WEBHOOK_URL = 'https://api.telegram.org/bot488971840:AAEFGkq4Dv4990OacTpn0pp4zlVhWOnZzpI/sendMessage'
        USERID= '-577425048'
        SERVICE_NAME= 'oneweb'
        INFRA_GIT='git@scm.devops.vnpt.vn:erp.ptpm1.onebss/OneAPI/infra.git'
        JOB="KV3.onebss.oneweb"
    }

    stages {
        stage('test') {
            steps {
                script {
                    FAILED_STAGE=env.STAGE_NAME
                    sh "echo ${BRANCH_NAME}"
                    sh 'sleep 1'
                }
            }
        }
        stage('run sonarque test') {
            when {
            	branch 'develop'
            }
            steps {
                script {
                    FAILED_STAGE=env.STAGE_NAME
                    //sh 'sonar-scanner -X'
                    //sh 'sleep 1'
                }
            }
        }


        stage('unit test') {
            steps {
                script {
                    FAILED_STAGE=env.STAGE_NAME
                    sh 'sleep 1'
                    //junit 'src/test/**/*.xml'
                }
            }
        }
        stage('build & push image branch master') {
            when {
            	branch 'master'
            }
            agent {
                node {
                    label 'erp-linux-ptpm'
                }
            }               
            steps {
                script {
                    FAILED_STAGE=env.STAGE_NAME
                    sh 'docker build -t  crelease.devops.vnpt.vn:10100/onebss/onebss-oneweb-prod:1.0.${BUILD_NUMBER} -f Dockerfile.${BRANCH_NAME} .'
                    sh 'docker push  crelease.devops.vnpt.vn:10100/onebss/onebss-oneweb-prod:1.0.${BUILD_NUMBER} '              
                }
            }
        }
        stage('build & push image branch develop') {
            when {
            	branch 'develop-test'
            }
            agent {
                node {
                    label 'erp-linux-ptpm'
                }
            }
            steps {
                script {
                    FAILED_STAGE=env.STAGE_NAME
                    sh 'docker build -t crelease.devops.vnpt.vn:10100/onebss/onebss-oneweb-${BRANCH_NAME}:1.0.${BUILD_NUMBER} -f Dockerfile.${BRANCH_NAME} .'
                    sh 'docker push crelease.devops.vnpt.vn:10100/onebss/onebss-oneweb-${BRANCH_NAME}:1.0.${BUILD_NUMBER}'    
                }
            }
        }
        stage('Deployment oneweb branch master') {
            when {
            	branch 'master'
            }
            agent {
                node {
                    label 'erp-linux-ptpm'
                }
            }
            steps {
                script {
                    FAILED_STAGE=env.STAGE_NAME  
                    sh "kubectl --kubeconfig /kubeconfig/onebss_pro.yaml -n vnpt-onebss-web set image deployment/${SERVICE_NAME} ${SERVICE_NAME}=crelease.devops.vnpt.vn:10100/onebss/onebss-oneweb-prod:1.0.${BUILD_NUMBER}" 
                    // sh "sleep 1"         
                }
            }
        }   
        //stage('Deployment oneweb branch master to DR-Site') {
        //    when {
        //    	branch 'master'
        //    }
        //    agent {
        //        node {
        //            label 'erp-linux-ptpm'
        //        }
        //    }
        //    steps {
        //        script {
        //            FAILED_STAGE=env.STAGE_NAME  
        //            sh "kubectl --kubeconfig /kubeconfig/onebss_pro.yaml -n vnpt-onebss-web set image deployment/${SERVICE_NAME} ${SERVICE_NAME}=crelease.devops.vnpt.vn:10100/onebss/onebss-oneweb-prod:1.0.${BUILD_NUMBER}"      
        //        thiếu file kubeconfig của drsite trên server jenkin ERP
        //        }
        //    }
        //}


        // stage('Deployment  oneweb branch develop') {
        //     when {
        //     	branch 'develop'
        //     }
        //     steps {
        //      script {
        //         FAILED_STAGE=env.STAGE_NAME  
        //         sh "git clone ${INFRA_GIT}"
        //         sh "git config --global user.email 'jenkinsit3@vnpt.vn'"
        //         sh "git config --global user.name 'jenkins' "
        //         dir("infra") {
        //         sh " cd ./${SERVICE_NAME}/overlay/${BRANCH_NAME} && kustomize edit set image crelease.devops.vnpt.vn:10100/onebss/onebss-${SERVICE_NAME}-${BRANCH_NAME}:1.0.${BUILD_NUMBER} "
        //         sh "git add . && git commit -m 'publish ${SERVICE_NAME}-${BRANCH_NAME}:1.0.${BUILD_NUMBER}' && git push origin master || echo 'no change'"
        //         }      
        //     }
        //     }
        //     } 

        stage('Deployment oneweb branch develop') {
            when {
            	branch 'develop-test'
            }
            steps {
                script {
                    FAILED_STAGE=env.STAGE_NAME  
                    sh "kubectl --kubeconfig ~/.kubeconfig/kubeconfig-onebss-dev-ntl.yaml -n onebss-dev set image deployment/${SERVICE_NAME} ${SERVICE_NAME}=crelease.devops.vnpt.vn:10100/onebss/onebss-oneweb-${BRANCH_NAME}:1.0.${BUILD_NUMBER}"
                    // sh "sleep 1"         
                }
            }
        }      
        stage('push nexus vnpt ') {
            when {
            	branch 'master'
            }  
            steps {
                script {
                    FAILED_STAGE=env.STAGE_NAME                
                    sh 'sleep 1'
                }
            }
        }
        stage('run jmeter ') {
            when {
            	branch 'demo'
            }
            steps {
                script {
                    FAILED_STAGE=env.STAGE_NAME                
                    sh 'sleep 1'           
                }
            }
        }
    }

    
    post {
        success {
            sh """
    curl -X POST \
     -H 'Content-Type: application/json' \
     -d '{"chat_id": "${USERID}", "text": " \ud83d\udc4d \ud83d\udc4d \ud83d\udc4d \nJobname: ${JOB_NAME} \nBuild number: ${BUILD_NUMBER} \nStatus: SUCCESS \nCommit: ${GIT_COMMIT} ", "disable_notification": true}' \
     ${WEBHOOK_URL}
            """   
        }

        failure {
            script {
        sh 'sleep 10'            
        env.LINK= sh(returnStdout: true, script: "curl -i -H 'Authorization:Basic YXV0b19rdjNfaXQ6dk5wdElUMyMxMjM0QA==' http://auto_kv3_it:Mvck2x%21e@cbuild.devops.vnpt.vn:8080/job/${JOB}/job/${BRANCH_NAME}/${BUILD_NUMBER}/consoleText | tail -n 1000 | head -n 990 | nc termbin.com 9999").trim()

        sh """
    curl -X POST \
     -H 'Content-Type: application/json' \
     -d '{"chat_id": "${USERID}", "text": " \ud83d\ude21 \ud83d\ude21 \ud83d\ude21 \nJobname: ${JOB_NAME} \nBuild number: ${BUILD_NUMBER} \nStatus: FAILURE \nStage: ${FAILED_STAGE} \nCommit: ${GIT_COMMIT} \nLog: ${LINK} ", "disable_notification": true}' \
     ${WEBHOOK_URL}
        """
            }
        }

        aborted {
        sh """
    curl -X POST \
     -H 'Content-Type: application/json' \
     -d '{"chat_id": "${USERID}", "text": " \u2620\ufe0f \u2620\ufe0f \u2620\ufe0f \nJobname: ${JOB_NAME} \nBuild number: ${BUILD_NUMBER} \nStatus: ABORTED \nStage: ${FAILED_STAGE} \nCommit: ${GIT_COMMIT} ", "disable_notification": true}' \
     ${WEBHOOK_URL}
        """
        }

        unstable {
        sh """
    curl -X POST \
     -H 'Content-Type: application/json' \
     -d '{"chat_id": "${USERID}", "text": " \ud83d\ude4a \ud83d\ude4a \ud83d\ude4a \nJobname: ${JOB_NAME} \nBuild number: ${BUILD_NUMBER} \nStatus: UNSTABLE \nStage: ${FAILED_STAGE} \nCommit: ${GIT_COMMIT} ", "disable_notification": true}' \
     ${WEBHOOK_URL}
        """
        }

        always {
            deleteDir()
        }
    }

}
