 # Unique ID for this project
sonar.projectKey=VNPT-IT.OneBSS.oneweb
sonar.projectName=IT.ERP.PTPM.OneBSS.ONEWEB
sonar.projectVersion=1.0
sonar.sources=src/.
sonar.sourceEncoding=UTF-8
sonar.exclusions=tsconfig.json, **/*.sh
sonar.login=00b72b84b25b54b6c5f672523f4f460eaea04ef2
#sonar.nodejs.executable=/usr/bin/nodejs
# sonar.css.node=/usr/bin/node
#sonar.skippedModules=ShellCheck
