export default{
    Xuat_HDDT_LOAD: (axios, data) => axios.post('/web-hopdong/hopdong/fn_xuat_hddt_load', data),
    Change_MauSo: (axios, data) => axios.post('/web-ccdv/thanhtoan/sp_lay_ds_seri_dientu_v2', data),
    HienThiThongTin: (axios, data) => axios.post('/web-hopdong/hopdong/fn_xuat_hddt_hienthi_thongtin', data),
    listInvByCus_VTT: (axios, data) => axios.post('/tichhop/vnptinvoice/listInvByCus', data),
    thongtin_nguoidung2: (axios, data) => axios.post('/quantri/user/thongtin_nguoidung2', data),
  
  
    downloadInvPDFFkeyNoPay: (axios, data) => axios.post('/tichhop/vnptinvoice/downloadInvPDFFkeyNoPay', data), 
    downloadInvFkeyNoPay: (axios, data) => axios.post('/tichhop/vnptinvoice/downloadInvFkeyNoPay', data), 
    downloadInvNoPay: (axios, data) => axios.post('/tichhop/vnptinvoice/downloadInvNoPay', data), 
    getInvViewNoPay: (axios, data) => axios.post('/app-com/hoadon_dientu/getInvViewNoPay', data),
  
    CapNhat: (axios, data) => axios.post('/web-hopdong/hopdong/fn_xuat_hddt_capnhat', data),
    // ds_para = {
    //     donvi_id: 186,
    //     hddt_fkey: "03HPG2022000927505",
    //     hdkh_id: 5147167,
    //     invoice_action: "ImportAndPublishInv_V2",
    //     ip_cn: "127.0.0.1",
    //     js_bd_hddt: [{…}],
    //     js_bd_hddt_ct: (4) [{…}, {…}, {…}, {…}],
    //     ketqua_capnhat: "OK",
    //     loaihoadon_id: 22,
    //     ma_gd: "HPG-LD/00717942",
    //     ma_nd: "test_app.hpg",
    //     may_cn: "localhost",
    //     ngay_cn: "01/04/2022",
    //     nguoidung_id: 999999,
    //     nhanvien_hd_id: 7037,
    //     nhanvien_id: 13431,
    //     phieutt_id: 2124927,
    //     seri: "AC/18E",
    //     seri_id: 38,
    //     soseri: 123,
    //     tag_form: 1,
    //     thaotac: 6,
    // }
    UpdateCus: (axios, data) => axios.post('/tichhop/vnptinvoice/updateCus', data),
    ImportAndPublishInv_VTT: (axios, data) => axios.post('/tichhop/vnptinvoice/importAndPublishInv', data),
    //form hóa đơn điện tử
    hoadon_dientu_load: (axios, data) => axios.get('/web-hopdong/hopdong/fn_hoadon_dientu_load', data),
    hoadon_dientu_change_mauso:(axios, data) => axios.post('/web-hopdong/hopdong/fn_hoadon_dientu_cbopattern', data),
    hienthidanhsach_hdkh:(axios, data) => axios.post('/web-hopdong/hopdong/fn_hoadon_dientu_hienthidanhsach_hdkh', data),
    hienthidanhsach_hdtb:(axios, data) => axios.post('/web-hopdong/hopdong/fn_hoadon_dientu_gvdanhsach', data),
    doi_so_sang_chu:(axios, data) => axios.post('/web-tracuu/tracuu_th/fn_doisosangchu', data),
    //upload file
    upload_file: async (axios, data,header) => axios.post('/web-quantri/upload', data,header),
    POST_GET_KEYS: async (axios, data) => axios.post('/web-quantri/donvitinh/get_keys', data),
    GET_FKEY: (axios, data) => axios.get('/web-hopdong/ThayDoiHopDong/sinh_fkey', data),
  
  
    TraCuuThueBao: (axios, data) => axios.post('/visa-app/lookupRASAccountJson', data),
    removeVNN: (axios, data) => axios.post('/visa-app/lookupRASAccountJson', data),
    GetSubscriberInfo: (axios, data) => axios.post('/vasc-service-new/getSubscriberInfo', data),
    CancelSubscriberV2: (axios, data) => axios.post('/vasc-service-new', data),
    DeleteMyTV: (axios, data) => axios.post('/vasc-service-new', data),
    HUY_THUEBAO: (axios, data) => axios.post('/sps/sps_service_ims_deactive', data),
  
    ChangeCustomerType: (axios, data) => axios.post('/visa-app/changeCustomerType', data),
    convertForVerifyFkey: (axios, data) => axios.post('tichhop/vnptinvoice/convertForVerifyFkey', data),
    unConfirmPaymentFkey: (axios, data) => axios.post('tichhop/vnptinvoice/unConfirmPaymentFkey', data),
    ConfirmPaymentFkey: (axios, data) => axios.post('tichhop/vnptinvoice/confirmPaymentFkey', data),
    adjustInvoiceAction_tt78: (axios, data) => axios.post('tichhop/vnptinvoice/adjustInvoiceAction', data),
    adjustInvoiceAction_v2: (axios, data) => axios.post('tichhop/vnptinvoice/adjustInv', data),
  
    replaceInvoiceAction:(axios, data) => axios.post('tichhop/vnptinvoice/replaceInvoiceAction', data),
    cancelInv:(axios, data) => axios.post('tichhop/vnptinvoice/cancelInv', data),
    unConfirmPaymentFkey:(axios, data) => axios.post('tichhop/vnptinvoice/replaceInvoiceAction', data),
    convertForStor:(axios, data) => axios.post('tichhop/vnptinvoice/convertForStor', data),
    DoiCongMegavnn:(axios, data) => axios.post('tichhop/visa-app/changePortMegaVNN', data),
    modifyServiceTypeMegaVNN:(axios, data) => axios.post('tichhop/visa-app/modifyServiceTypeMegaVNN', data),
    modifyServiceTypeMegaVNN1:(axios, data) => axios.post('tichhop/visa-app/modifyServiceTypeMegaVNN1', data),
    changeBillingInfo:(axios, data) => axios.post('tichhop/visa-app/changeBillingInfo', data),
    ThayDoiHTTT:(axios, data) => axios.post('tichhop/visa-app/modifyTariffType', data),
    updateDeviceInfo:(axios, data) => axios.post('tichhop/vasc/updateDeviceInfo', data),
    unReservedAccount:(axios, data) => axios.post('tichhop/visa-app/unReservedAccount', data),
    sps_service_ims_deactive:(axios, data) => axios.post('tichhop/sps/sps_service_ims_deactive', data),
    disconnectSubscriber:(axios, data) => axios.post('tichhop/vtn/disconnectSubscriber', data),
    
    }