export default {
    getTrangThaiDonHang: (axios) => axios.get(`/web-qlvt/api/tra-cuu-hop-dong-don-hang/trang-thai-don-hang`),
    getDSHopDong: (axios, donViId) => axios.get(`/web-qlvt/api/tra-cuu-hop-dong-don-hang/hop-dong-dang-ky/${donViId}`),
    getDSKhoNhaCungCap: (axios, kieu) => axios.get(`/web-qlvt/api/tra-cuu-hop-dong-don-hang/kho-nha-cung-cap/${kieu}`),
    getTrangThaiHopDong: (axios, kieu) => axios.get(`/web-qlvt/api/tra-cuu-hop-dong-don-hang/trang-thai-hop-dong/${kieu}`),
    getDSHopDongTheoDK: (axios, donViId) => axios.get(`/web-qlvt/api/don-hang/hop-dong-dat-dieu-kien?donvi-id=${donViId}`),
    getDSLoaiDonHang: (axios) => axios.get(`/web-qlvt/api/don-hang/loai-don-hang`),
    getDSDonHangTheoDieuKien: (axios, data) => axios.post(`/web-qlvt/api/don-hang/don-hang-theo-dieu-kien`, data),
    getDSComboDonHang: (axios, data) => axios.post(`/web-qlvt/api/don-hang/combo-don-hang`, data),
    getDSThongTinHopDong: (axios, hdmsId) => axios.get(`/web-qlvt/api/don-hang/ds-thong-tin-hop-dong?hdms-id=${hdmsId}`),
    getDSDuAn: (axios, hdmsId) => axios.get(`/web-qlvt/api/don-hang/danh-sach-du-an?hdms-id=${hdmsId}`),
    getTenNguoiDungTheoDonHang: (axios, donHangId) => axios.get(`/web-qlvt/api/don-hang/ten-nguoi-dung-theo-don-hang?donhang-id=${donHangId}`),
    getDSVatTuHopDong: (axios, data) => axios.get(`/web-qlvt/api/don-hang/vat-tu-tu-chi-tiet-hop-dong?hdms-id=${data.hdmsId}&donhang-id=${data.donHangId}`),
    getDSVatTuDonHang: (axios, donHangId) => axios.get(`/web-qlvt/api/tra-cuu-hop-dong-don-hang/chi-tiet-don-hang/${donHangId}`),
    getTenNguoiCapNhap: (axios, donHangId) => axios.get(`/web-qlvt/api/don-hang/kiem-tra-nguoi-cap-nhat?donhang-id=${donHangId}`),
    // getDSChiTietDonHang: (axios, donHangId) => axios.get(`/web-qlvt/api/tra-cuu-hop-dong-don-hang/chi-tiet-don-hang/${donHangId}`),
    getNgayKy: (axios, hdmsId) => axios.get(`/web-qlvt/api/don-hang/ngay-dang-ky?hdms-id=${hdmsId}`),
    getDSLoaiDonHangTheoId: (axios, donHangId) => axios.get(`/web-qlvt/api/don-hang/loai-don-hang-theo-id?donhang-id=${donHangId}`),
    getThongTinDonHangCha: (axios, donHangId) => axios.get(`/web-qlvt/api/don-hang/kiem-tra-don-hang-cha?donhangcha-id=${donHangId}`),
    getKey: (axios, data) => axios.post('/web-qlvt/api/cap-phat-ccdc/get-key', data),
    getMaDonHang: (axios, maHopDong) => axios.get(`/web-qlvt/api/don-hang/sinh-ma-don-hang?hdms-id=${maHopDong}`),
    themMoiDonHang: (axios, data) => axios.post('/web-qlvt/api/don-hang/them-moi-don-hang', data),
    getTTDonHangTheoDHId: (axios, donHangId) => axios.get(`/web-qlvt/api/don-hang/trang-thai-don-hang-theo-id?donhang-id=${donHangId}`),
    capNhatTrangThaiNTDonHang: (axios, data) => axios.get(`/web-qlvt/api/don-hang/cap-nhat-trang-thai-nt-don-hang?donhang-id=${data.donHangId}&hdms-id=${data.hdmsId}&nhanvien-id=${data.nhanVienId}`),
    getDSVatTuTuDonHangTT: (axios, donHangId) => axios.get(`/web-qlvt/api/thanh-toan-don-hang/vat-tu-theo-don-thanh-toan?donhang-id=${donHangId}`),
    xoaDonHang: (axios, donHangId) => axios.delete(`/web-qlvt/api/don-hang/xoa-don-hang?donhang-id=${donHangId}`),
    getLoaiDHVaTrangThaiDH: (axios, donHangId) => axios.get(`/web-qlvt/api/don-hang/loai-va-trang-thai-don-hang?donhang-id=${donHangId}`),
    getChiTietDHCha: (axios, donHangId) => axios.get(`/web-qlvt/api/don-hang/kiem-tra-don-hang-cha?donhangcha-id=${donHangId}`),
    insertBackupDonHang: (axios, data) => axios.put('/web-qlvt/api/don-hang/tao-backup-vat-tu-hop-dong', data),
    updateBackupDonHang: (axios, data) => axios.put('/web-qlvt/api/don-hang/cap-nhat-backup-vat-tu-hop-dong', data),
    xoaChiTietDonHang: (axios, data) => axios.post('/web-qlvt/api/don-hang/xoa-chi-tiet-don-hang', data),
    getNgayNghiemThuNhapKho: (axios, donHangId) => axios.get(`/web-qlvt/api/don-hang/ngay-nghiem-thu-nhap-kho?donhang-id=${donHangId}`),
    getDSQuyen: (axios, nguoiDungId) => axios.get(`/web-qlvt/api/tra-cuu-ton-kho-user/ds-quyen-nd/${nguoiDungId}`),
    getThamSoMacDinh: (axios, thamSo) => axios.get(`/web-qlvt/api/tiep-nhan-thiet-bi-bao-hanh/tham-so-mac-dinh/${thamSo}`),
    getDSTrangThaiDHHT: (axios) => axios.get(`/web-qlvt/api/tra-cuu-hop-dong-don-hang/trang-thai-don-hang`),
    updateChiTietDonHang: (axios, data) => axios.post('/web-qlvt/api/don-hang/cap-nhat-chi-tiet-don-hang', data),
    getDSDonViTinh: (axios) => axios.get(`/web-qlvt/api/tra-cuu-hop-dong-don-hang/don-vi-tinh`),
    getDSNoiDung: (axios, hdmsId) => axios.get(`/web-qlvt/api/don-hang/noi-dung-hop-dong-mua-sam?hdms-id=${hdmsId}`),
    getTSMacDinh: (axios, tsmd) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/lay-ds-thamso-md-mats/${tsmd}`),
    getDSThaoTac: (axios,) => axios.get(`/web-qlvt/api/don-hang/ds-huong-giao-thao-tac`),
    kySoDonHang: (axios, data) => axios.post(`/web-qlvt/api/don-hang/xu-ly-nhap-kho-don-hang`, data),
    getTaiKhoanKySo: (axios, data) => axios.get(`/web-qlvt/api/giao-phieu/tk-ky-so`),
    kiemTraMaDonHang: (axios, data) => axios.post(`/web-qlvt/api/don-hang/so-luong-don-hang`, data),
    capNhatMaDonHang: (axios, data) => axios.post(`/web-qlvt/api/don-hang/cap-nhat-ma-don-hang-co-quyen`, data),
}