export default {
    getDSTongHopThang: (axios, data) => axios.post(`/web-qlvt/api/dot-tong-hop/ds-tong-hop-thang?page-no=${data.pageNo}&page-size=${data.pageSize}`,data.dataRequest),
    getDSDotDk: (axios) => axios.get(`/web-qlvt/api/dang-ky-cap-phat/ds-dot-dang-ky`),
    getDotTongHop: (axios, data) => axios.post(`/web-qlvt/api/dot-tong-hop/ds-dot-tong-hop`,data),
    getKey: (axios, data) => axios.post(`/web-qlvt/api/cap-phat-ccdc/get-key`,data),
    capNhapDotTongHop: (axios, data) => axios.post(`/web-qlvt/api/dot-tong-hop/cap-nhat-dot-tong-hop`,data),
    kiemTraVatTuTongHop: (axios, tongHopId) => axios.get(`/web-qlvt/api/dot-tong-hop/kiem-tra-vat-tu-tong-hop/${tongHopId}`),
    getDSFileCVTongHop: (axios, tongHopId) => axios.get(`/web-qlvt/api/dot-tong-hop/ds-file-cv-tong-hop/${tongHopId}`),
    kiemTraDotTongHop: (axios, data) => axios.post(`/web-qlvt/api/dot-tong-hop/kiem-tra-dot-tong-hop`,data),
    duyetDotTongHop: (axios, data) => axios.post(`/web-qlvt/api/dot-tong-hop/duyet-dot-tong-hop`,data),
    kiemTraHopDongDaLap: (axios, tongHopId) => axios.get(`/web-qlvt/api/dot-tong-hop/kiem-tra-hop-dong-huy-duyet/${tongHopId}`),
    kiemTraChungTuDaLap: (axios, tongHopId) => axios.get(`/web-qlvt/api/dot-tong-hop/kiem-tra-chung-tu-huy-duyet/${tongHopId}`),
    getDSDangKyTongHop: (axios, data) => axios.post(`/web-qlvt/api/dot-tong-hop/ds-dang-ky-tong-hop`,data),
    getDSFileCV: (axios, tongHopId) => axios.get(`/web-qlvt/api/dot-tong-hop/ds-file-cv/${tongHopId}`),
    capNhapFileCV: (axios, data) => axios.post(`/web-qlvt/api/dot-tong-hop/cap-nhat-file-cv`,data),
    getMaxDotTongHop: (axios, data) => axios.post(`/web-qlvt/api/dot-tong-hop/max-dot-tong-hop`,data),
    kiemTraDangKyDotTH: (axios, data) => axios.post(`/web-qlvt/api/dot-tong-hop/kiem-tra-dangky-dot-th`,data),
    taoDanhSachTongHopDangKy: (axios, data) => axios.post(`/web-qlvt/api/dot-tong-hop/tao-dang-ky-dot-th`,data),
    xoaDanhSachTongHop: (axios, data) => axios.post(`/web-qlvt/api/dot-tong-hop/xoa-dang-ky-dot-th`,data),

    uploadFile: (axios, data) => axios.post(`/web-qlvt/api/storage/uploadFile`,data),
    downloadFile: (axios, linkFile) => axios.get(`/web-qlvt/api/storage/downloadFile?fileSource=${linkFile}`),
    getLinkFile: (axios, data) => axios.post(`/web-qlvt/api/storage/getPresignedUrl`,data),
    checkFileExist: (axios, data) => axios.post(`/web-qlvt/api/storage/checkExistsFile`,data),
    deleteFile: (axios, data) => axios.post(`/web-qlvt/api/storage/deleteFile`,data),
}