export default {
    getThamSoMacDinh: (axios, thamSo) => axios.get(`/web-qlvt/api/tiep-nhan-thiet-bi-bao-hanh/tham-so-mac-dinh/${thamSo}`),
    getDSQuyen: (axios, nguoiDungId) => axios.get(`/web-qlvt/api/tra-cuu-ton-kho-user/ds-quyen-nd/${nguoiDungId}`),
    getDSDonViGiaoNhanChungTu: (axios, data) => axios.get(`/web-qlvt/api/nhan-chung-tu-hoan-tra/ds-don-vi-giao-nhan-ct?nguoiDung=${data.nguoiDungId}&donViId=${data.donViId}&donViDlId=${data.donViDlId}`),
    getDSKhoNhanChungTuHCM: (axios,) => axios.get(`/web-qlvt/api/nhan-chung-tu-hoan-tra/ds-kho-nhan-ct-hcm`),
    getDSKhoGiaoChungTuHCM: (axios,nhanVienId) => axios.get(`/web-qlvt/api/nhan-chung-tu-hoan-tra/ds-kho-giao-ct-vt/${nhanVienId}`),
    getDSDonViDuyet: (axios,) => axios.get(`/web-qlvt/api/nhan-chung-tu-hoan-tra/ds-don-vi-duyet-ct-hoan-tra`),
    getDSKhoNhanChungTuHaNoi: (axios,nhanVienId) => axios.get(`/web-qlvt/api/nhan-chung-tu-hoan-tra/ds-kho-nhan-ct-hoan-tra-hni/${nhanVienId}`),
    getDSHoanTraChungTu: (axios, data) => axios.post(`/web-qlvt/api/nhan-chung-tu-hoan-tra/ds-hoan-tra`,data),
    getDSFileCongVan: (axios,vanBanId) => axios.get(`/web-qlvt/api/nhan-chung-tu-hoan-tra/ds-file-cv-theo-vb/${vanBanId}`),
    getDSChiTietVatTu: (axios,data) => axios.get(`/web-qlvt/api/nhan-chung-tu-hoan-tra/ds-giao-hoan-tra-ct-tbi?chungTuId=${data.chungTuId}&kieu=${data.kieu}&tag=${data.tag}`),
    getDSChiTietVatTuDaChia: (axios,chungTuId) => axios.get(`/web-qlvt/api/tra-cuu-chung-tu/lay-ds-vattu-chungtu/${chungTuId}`),
    getDSThietBiDaChia: (axios,chungTuId) => axios.get(`/web-qlvt/api/tra-cuu-chung-tu/lay-ds-thietbi-chungtu/${chungTuId}`),
    getDSThietBi: (axios,data) => axios.get(`/web-qlvt/api/nhan-chung-tu-hoan-tra/ds-giao-hoan-tra-ct-tbi?chungTuId=${data.chungTuId}&kieu=${data.kieu}&tag=${data.tag}`),
    getDSXuatDaChia: (axios,chungTuId) => axios.get(`/web-qlvt/api/nhan-chung-tu-hoan-tra/ds-hoan-tra-v2/${chungTuId}`),
    giaoPhieuHoanTraChungTu: (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/giao-phieu-hoan-tra`,data),
    kiemTraHanChungTu: (axios, data) => axios.post(`/web-qlvt/api/duyet-dang-ky-cap-phat/kiem-tra-han-chung-tu`,data),
    kiemTraDaXoaPhieu: (axios,chungTuId) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-xoa-phieu-hoan-thanh/${chungTuId}`),
    xoaPhieuDaHoanThanh: (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/xoa-phieu-da-hoan-thanh`,data),
    kiemTraHoanThienChungTu: (axios,chungTuId) => axios.get(`/web-qlvt/api/nhap-xuat-vt/kiem-tra-hoan-thien-chung-tu-v1?chung-tu-id=${chungTuId}`),
    hoanThienChungTu: (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-vt/hoan-thien-chung-tu`,data),
    uploadFile: (axios, data) => axios.post(`/web-qlvt/api/storage/uploadFile`,data),
    downloadFile: (axios, linkFile) => axios.get(`/web-qlvt/api/storage/downloadFile?fileSource=${linkFile}`),
    getLinkFile: (axios, data) => axios.post(`/web-qlvt/api/storage/getPresignedUrl`,data),
    checkFileExist: (axios, data) => axios.post(`/web-qlvt/api/storage/checkExistsFile`,data),
    getDSLoaiKho: (axios,) => axios.get(`/web-qlvt/api/tra-cuu-ton-kho-user/ds-loai-khotd`),
    getDSKhoTTVT: (axios,) => axios.get(`/web-qlvt/api/dang-ky-cap-phat/ds-kho-theo-donvi-vattu`),
    getDSKhoDen: (axios,nhanVienId) => axios.get(`/web-qlvt/api/nhan-chung-tu-hoan-tra/ds-kho-den/${nhanVienId}`),
    getDSMaKhoKT: (axios,loaiKhoId) => axios.get(`/web-qlvt/api/tra-cuu-ton-kho/danh-sach-vat-tu/${loaiKhoId}`),
    getParamsBaoCao: (axios, maBc) => axios.get(`/web-qlvt/api/in-phieu/ds-param-bc?maBc=${maBc}`),
}