export default {    
    getDSVatTuTuDonHang: (axios, donHangId) => axios.get(`/web-qlvt/api/tra-cuu-hop-dong-don-hang/chi-tiet-don-hang/${donHangId}`),
    getDSFileNghiemThu: (axios, donHangId) => axios.get(`/web-qlvt/api/nghiem-thu-don-hang/ds-file-bien-ban-nghiem-thu/${donHangId}`),
    KTDonHangDaCoChungTu: (axios, donHangId) => axios.get(`/web-qlvt/api/nghiem-thu-don-hang/kiem-tra-don-hang-chung-tu/${donHangId}`),
    xoaNghiemThu: (axios, donHangId) => axios.get(`/web-qlvt/api/nghiem-thu-don-hang/xoa-nghiem-thu/${donHangId}`),
    capNhatHopDong: (axios, data) => axios.post(`/web-qlvt/api/nghiem-thu-don-hang/cap-nhat-hop-dong?hdmsId=${data.hdmsId}&kieu=${data.kieu}`),
    capNhatTTNghiemThuDonHang: (axios, data) => axios.get(`/web-qlvt/api/don-hang/cap-nhat-trang-thai-nt-don-hang?donhang-id=${data.donHangId}&hdms-id=${data.hdmsId}&nhanvien-id=${data.nhanVienId}`),
    getTSMacDinh: (axios, tsmd) => axios.get(`/web-qlvt/api/nghiem-thu-don-hang/tham-so-mac-dinh-theo-ma/${tsmd}`),
    insertBackupDonHang: (axios, data) => axios.post(`/web-qlvt/api/nghiem-thu-don-hang/tao-backup-vat-tu-don-hang`,data),
    getDSVatTuNghiemThu: (axios, hdmsId) => axios.get(`/web-qlvt/api/nghiem-thu-don-hang/ds-vat-tu-nghiem-thu/${hdmsId}`),
    getTTHopDongDonHang: (axios, data) => axios.get(`/web-qlvt/api/nghiem-thu-don-hang/ds-thong-tin-hop-dong/${data.hdmsId}/${data.donHangId}`),
    getDSChiTietDonHang: (axios, donHangId) => axios.get(`/web-qlvt/api/nghiem-thu-don-hang/ds-chi-tiet-don-hang/${donHangId}`),
    getDSDonViTinh: (axios) => axios.get(`/web-qlvt/api/tra-cuu-hop-dong-don-hang/don-vi-tinh`),
    uploadFile: (axios, data) => axios.post(`/web-qlvt/api/storage/uploadFile`,data),
    downloadFile: (axios, linkFile) => axios.get(`/web-qlvt/api/storage/downloadFile?fileSource=${linkFile}`),
    getLinkFile: (axios, data) => axios.post(`/web-qlvt/api/storage/getPresignedUrl`,data),
    checkFileExist: (axios, data) => axios.post(`/web-qlvt/api/storage/checkExistsFile`,data),
    capNhatFile: (axios, data) => axios.post(`/web-qlvt/api/nghiem-thu-don-hang/cap-nhat-don-hang`,data),
    deleteFile: (axios, data) => axios.post(`/web-qlvt/api/storage/deleteFile`,data),
    capNhatNgayNghiemThuBanGiao: (axios, data) => axios.post(`/web-qlvt/api/nghiem-thu-don-hang/nghiem-thu-kt-donhang`,data),
    getNgayNghiemThuBanGiao: (axios, donHangId) => axios.get(`/web-qlvt/api/nghiem-thu-don-hang/lay-ngay-nghiem-thu/${donHangId}`),
}