export default {
    getDSDonHangTheoDK: (axios, data) => axios.get(`/web-qlvt/api/tra-cuu-hop-dong-don-hang/don-hang-dang-ky/${data.donHangChaId}`),
    getDSDonHangTheoDV: (axios, data) => axios.get(`/web-qlvt/api/thanh-toan-don-hang/don-hang-theo-don-vi?donvi-id=${data.donvi_id}`),
    getDSHinhThucTra: (axios, data) => axios.get(`/web-qlvt/api/thanh-toan-don-hang/hinh-thuc-tra?kieu=${data.kieu}`, ),
    getDSNhanVienThuNgan: (axios, data) => axios.post(`/web-qlvt/api/thanh-toan-don-hang/nhan-vien-thu-ngan`,data),
    getDSDonViTinh: (axios, data) => axios.get(`/web-qlvt/api/tra-cuu-hop-dong-don-hang/don-vi-tinh`),
    getDSVatTuLuaChon: (axios, data) => axios.get(`/web-qlvt/api/dang-ky-cap-phat/ds-vat-tu-lua-chon`),
    KiemTraNgayTT: (axios, data) => axios.post(`/web-qlvt/api/thanh-toan-don-hang/kiem-tra-ngay-thanh-toan`,data),
    getKeys: (axios, data) => axios.post(`/web-qlvt/api/cap-phat-ccdc/get-key`,data),
    getDSThanhToanDK: (axios, data) => axios.get(`/web-qlvt/api/thanh-toan-don-hang/thanh-toan-theo-dang-ky?donvi-id=${data.donvi_id}&donhang-id=${data.donhang_id}`),
    getDSVatTuTheoDH: (axios, data) => axios.get(`/web-qlvt/api/thanh-toan-don-hang/vat-tu-theo-don-thanh-toan?donhang-id=${data.donhang_id}`),
    getDSVatTuThanhToan: (axios, data) => axios.get(`/web-qlvt/api/thanh-toan-don-hang/vat-tu-thanh-toan?phieutt-id=${data.phieutt_id}`),
    XoaPhieuThanhToan: (axios, data) => axios.delete(`/web-qlvt/api/thanh-toan-don-hang/xoa-phieu-thanh-toan-don-hang/?phieutt-id=${data.phieutt_id}`),
    CapNhatTrangThaiDH: (axios, data) => axios.get(`/web-qlvt/api/thanh-toan-don-hang/trang-thai-don-hang?donhang-id=${data.donhang_id}`),
    TaoBackUpDSVatTu: (axios, data) => axios.put(`/web-qlvt/api/thanh-toan-don-hang/xu-li-backup-don-hang-thanh-toan?type=${data.type}`,data.params),
    XoaChungTuPhieuTT: (axios, data) => axios.delete(`/web-qlvt/api/thanh-toan-don-hang/xoa-chung-tu-phieu-thanh-toan/?phieutt-id=${data.phieutt_id}&ctdh-id=${data.ctdh_id}`),
    TaoDonHang: (axios, data) => axios.put(`/web-qlvt/api/thanh-toan-don-hang/xu-ly-don-hang?type=${data.type}`,data.params),
    CapNhatDonHang: (axios, data) => axios.put(`/web-qlvt/api/thanh-toan-don-hang/xu-ly-don-hang?type=${data.type}`,data.params),
    CapNhatBackUpDonHangTT: (axios, data) => axios.put(`/web-qlvt/api/thanh-toan-don-hang/xu-li-backup-don-hang-thanh-toan?type=${data.type}`,data.params),
  }