export default{
  get_danhsach_doituong_hoso: async (axios, data) => axios.post('/web-quantri/danhmuc/danhsach_doituong_hoso', data),
  danhsach_node_thietbi_con: async (axios, data) => axios.post('/web-quantri/danhmuc/danhsach_node_thietbi_con', data),
  get_danhsach_hopdong_theo_matb: async (axios, data) => axios.post('/web-quantri/danhmuc/danhsach_hopdong_theo_matb', data),
  get_danhsach_hopdong_theo_makh: async (axios, data) => axios.post('/web-thicong/hoinghi_truyenhinh/lay_ds_hd_theo_makh', data),
  get_danhsach_hoso_icon: async (axios, data) => axios.post('/web-quantri/danhmuc/danhsach_hoso_icon', data),
  get_danhsach_lichsu_baohong_theo_matb: async (axios, data) => axios.post('/web-quantri/danhmuc/danhsach_lichsu_baohong_theo_matb', data),
  get_danhsach_nhom_file_hoso: async (axios, data) => axios.post('/web-quantri/danhmuc/danhsach_nhom_file_hoso', data),
  get_danhsach_loai_file_hoso: async (axios, data) => axios.post('/web-quantri/danhmuc/danhsach_loai_file_hoso', data),
  get_danhsach_kieu_file_hoso: async (axios, data) => axios.post('/web-hopdong/lapdatmoi/lay_ds_dl_nghiepvu', data),
  get_db_theo_matb: async (axios, data) => axios.post('/web-quantri/doiiptruynhap/sp_lay_db_theo_matb_1', data),
  get_danhsach_thuebao_theo_makh: async (axios, data) => axios.post('/web-quantri/danhmuc/danhsach_thuebao_theo_makh', data),
  get_chitiet_file_hs: async (axios, data) => axios.post('/web-quantri/danhmuc/lay_chitiet_file_hs', data),
  get_ds_file_hs: async (axios, data) => axios.post('/web-quantri/danhmuc/lay_ds_file_hs', data),
  get_ds_file_hs_ct: async (axios, data) => axios.post('/web-quantri/danhmuc/lay_chitiet_file_hs', data),
  get_ds_hd_tb_theo_hdkh_id: async (axios, data) => axios.post('/web-quantri/danhmuc/lay_ds_hd_tb_theo_hdkh_id', data),
  get_ds_hd_tb_theo_ma_tb: async (axios, data) => axios.post('/web-quantri/danhmuc/lay_ds_hd_theo_ma_tb', data),
  tracuu_makh: async (axios, data) => axios.post('/web-quantri/danhmuc/tracuu_makh', data),
  cap_nhat_file_hoso: async (axios, data) => axios.post('/web-quantri/quantri/cap_nhat_file_hoso', data),
  gan_thuebao_file_hoso: async (axios, data) => axios.post('/web-quantri/quantri/gan_thuebao_file_hoso', data),
  them_moi_file_hoso: async (axios, data) => axios.post('/web-quantri/quantri/them_moi_file_hoso', data),
  xoa_file_hoso: async (axios, data) => axios.post('/web-quantri/quantri/xoa_file_hoso', data),
  upload_file_hoso: async (axios, data,header) => axios.post('/web-quantri/upload', data,header),
  link_view_file: async (axios, data,header) => axios.post('/web-quantri/upload/link_view_file', data,header),
  kiemtra_loaifile_duoc_up: async (axios, data,header) => axios.post('/web-quantri/quantri/kiemtra_loaifile_duoc_up', data,header),
}
