export default {
  ur_29002_001_ds_quyen_nguoidung: async (axios, data, header) => axios.get('/web-quantri/quyen/ds_quyen_nguoidung', data, header),
  ur_29002_002_kieu_giao_hoso: async (axios, data, header) => axios.get('/web-tracuu/danhmuc/kieu_giao_hoso', data, header),
  ur_29002_004_donvi_giao_hoso: async (axios, data, header) => axios.get('/web-tracuu/danhmuc/donvi_giao_hoso', data, header),
  ur_29002_005_trangthai_ph: async (axios, data, header) => axios.get('/web-tracuu/danhmuc/trangthai_ph', data, header),
  ur_29002_007_layds_bohoso_chuagiao_theo_makh_magd: async (axios, data) => axios.post('/web-quantri/hoso/layds_bohoso_chuagiao_theo_makh_magd', data),
  ur_29002_008_layds_file_trong_hoso: async (axios, data) => axios.post('/web-quantri/hoso/layds_file_trong_hoso', data),
  ur_29002_010_nhom_file: async (axios, data, header) => axios.get('/web-quantri/danhmuc/hoso/nhom_file', data, header),
  ur_29002_011_loai_file: async (axios, data, header) => axios.get('/web-quantri/danhmuc/hoso/loai_file', data, header),
  ur_29002_012_lay_ds_hd_tb_theo_hdkh_id: async (axios, data) => axios.post('/web-hopdong/hopdong/lay_ds_hd_tb_theo_hdkh_id', data),
  ur_29002_014_giaophieu_donvi_tieptheo: async (axios, data) => axios.post('/web-quantri/hoso/giaophieu_donvi_tieptheo', data),
  ur_29002_015_traphieu_bohoso: async (axios, data) => axios.post('/web-quantri/hoso/traphieu_bohoso', data),
  ur_29002_017_xacnhan_bohoso: async (axios, data) => axios.post('/web-quantri/hoso/xacnhan_bohoso', data),
  ur_29002_019_capnhat_file_hoso: async (axios, data) => axios.post('/web-hopdong/hopdong/capnhat_file_hoso', data),
  
  ur_29003_000_sp_lay_ds_huonggiao_theo_quytrinh: async (axios, data) => axios.post('/web-ccdv/giao_cho_hths/sp_lay_ds_huonggiao_theo_quytrinh', data),
  ur_29003_000_sp_lay_ds_thaotac: async (axios, data) => axios.post('/web-baohong/giao_cho_hths/sp_lay_ds_thaotac', data),
  ur_29003_001_lay_ds_lobhs: async (axios, data) => axios.post('/web-ccdv/giao_cho_hths/lay_ds_lobhs', data),
  ur_29003_002_lay_ds_bo_hs_ganlo: async (axios, data) => axios.post('/web-ccdv/giao_cho_hths/lay_ds_bo_hs_ganlo', data),
  ur_29003_004_capnhat_lobhs: async (axios, data) => axios.post('/web-ccdv/giao_cho_hths/capnhat_lobhs', data),
  ur_29003_006_sp_lay_ds_bhs_theo_id: async (axios, data) => axios.post('/web-ccdv/giao_cho_hths/sp_lay_ds_bhs_theo_id', data),
  ur_29003_006_sp_lay_ds_chitiet_lo_hs: async (axios, data) => axios.post('/web-ccdv/giao_cho_hths/sp_lay_ds_chitiet_lo_hs', data),
  ur_29003_006_sp_them_ds_chitiet_lo_hs: async (axios, data) => axios.post('/web-ccdv/giao_cho_hths/sp_them_ds_chitiet_lo_hs', data),
  ur_29003_007_sp_xoa_ds_chitiet_lo_hs: async (axios, data) => axios.post('/web-ccdv/giao_cho_hths/sp_xoa_ds_chitiet_lo_hs', data),

  ur_29004_001_sp_tt_tuyenthu: async (axios, data) => axios.post('/web-hopdong/laydulieu/sp_tt_tuyenthu', data),
  ur_29004_002_sp_lay_ds_donvi_theo_tuyenthu: async (axios, data) => axios.post('/web-hopdong/giao_cho_qlk/sp_lay_ds_donvi_theo_tuyenthu', data),
  ur_29004_003_ds_nhanvien_donvi: async (axios, data, header) => axios.get(`/web-quantri/danhmuc/ds_nhanvien_donvi/${data.dvtt_id}`, data, header),
  ur_29004_006_sp_capnhat_tuyenthu_bhs: async (axios, data) => axios.post('/web-hopdong/giao_cho_qlk/sp_capnhat_tuyenthu_bhs', data),
  ur_29004_008_fn_lay_soluong_phieu_bohs: async (axios, data) => axios.post('/web-hopdong/giao_cho_qlk/fn_lay_soluong_phieu_bohs', data),
  ur_29004_008_fn_capnhat_file_hs: async (axios, data) => axios.post('/web-hopdong/giao_cho_qlk/fn_capnhat_file_hs', data),
  ur_29004_008_sp_capnhat_file_hs_ghichu_tt: async (axios, data) => axios.post('/web-hopdong/giao_cho_qlk/sp_capnhat_file_hs_ghichu_tt', data),
  
  xoa_file: (axios, data) => axios.post('/web-quantri/upload/xoa_file', data),
  fn_capnhat_file_hstb: (axios, data) => axios.post('/web-hopdong/hopdong/fn_capnhat_file_hstb', data),
}
