export default {
  getThongTinDangNhapALT: (axios) => axios.get('web-thicong/tientrinh_thicong/lay_tt_dangnhap_alt'),
  getDanhSachLoaiNhom: (axios) => axios.post('web-thicong/tienhtrinh_tcbh/lay_loainhom_capnhat_hen'),
  getDanhSachCayDonVi: (axios) => axios.get('web-thicong/tientrinh_thicong/lay_ds_cay_donvi'),
  getDanhSachDichVuVienThong: (axios) => axios.get('web-quantri/danhmuc-chung/CSS_DICHVU_VT'),
  getDanhSachThamSoMacDinh: (axios) => axios.get('web-thicong/tientrinh_thicong/lay_ds_thamso_md'),
  getDanhSachLoaiHDPL: (axios) => axios.post('web-hopdong/traphieuthicong/ht_loai_hd_combobox_tp'),
  getDanhSachLoaiHDByLoaiNhom: (axios, loaiNhomId) => axios.get(`web-tracuu/phattrien/ds_loai_hd/${loaiNhomId}`),
  taoCTDLTienTrinh: (axios) => axios.get('web-thicong/tientrinh_thicong/tao_ctdl_tientrinh'),
  getDanhSachTienTrinhTCBH: (axios, body) => axios.post('web-thicong/tientrinh_thicong/lay_ds_tientrinh_tc_bh', body),
  getSoAoVaLoaiKHLon: (axios, body) => axios.post('web-thicong/tientrinh_thicong/lay_soao_loainhom_tc', body),
  getDanhSachTienTrinhXuLy: (axios, hdtbId) => axios.get(`web-thicong/tientrinh_thicong/lay_ds_tientrinh_xuly?hdtbId=${hdtbId}`),
  getDanhSachBaoTon: (axios, phieuId) => axios.get(`web-thicong/tientrinh_thicong/lay_ds_tientrinh_baoton?phieuId=${phieuId}`),
  getPortStatus: (axios, body) => axios.post('tichhop/bnm/getPortStatus', body),
  xoaTienTrinhXuLy: (axios, body) => axios.post('web-thicong/tientrinh_thicong/xoa_tientrinh_tc', body),
  ghiLaiTienTrinh: (axios, body) => axios.post('web-thicong/hoinghi_truyenhinh/fn_ghilai_noidung_tientrinh_thicong', body),
  getDanhSachTienTrinhTC: (axios, body) => axios.post('web-thicong/tientrinh_thicong/lay_ds_phieu_tientrinh_tc', body),
  getSoDienThoaiGuiSMS: (axios, body) => axios.post('web-ccdv/tien_trinh_bao_hong/sp_sdt_tientrinh_sms', body),
  getDanhSachDanhBa: (axios, body) => axios.post('web-ccdv/tien_trinh_bao_hong/sp_ds_danhba_tientrinh_sms', body),
  getDanhSachDanhBaBaoHong: (axios, { baoHongId, loaiTN }) => axios.get(`web-ccdv/tien_trinh_bao_hong/lay_ds_nhanvien_nhan_tinnhan/${baoHongId}/${loaiTN}`),
  getDanhSachTinNhanDaGui: (axios, body) => axios.post('web-ccdv/tien_trinh_bao_hong/lay_ds_tientrinh_sms_theo_tientrinh_id', body),
  sendSMS: (axios, body) => axios.post('web-ccdv/tien_trinh_bao_hong/fn_guisms_tientrinh_sms', body),
  getUrlFileTT: (axios, hdtbId) => axios.get(`web-hopdong/hopdong/lay_ds_file_hdtb/${hdtbId}`),
  uploadFile: (axios, body, header) => axios.post('web-quantri/upload', body, header),
  capNhatFileTT: (axios, body) => axios.post('web-ccdv/tien_trinh_bao_hong/capnhat_file_tientrinh_lm', body),
  getFileByPath: (axios, body) => axios.post('/web-quantri/upload/link_view_file', body),
  getThongTinHdtb: (axios, body) => axios.post('web-tratruoc/thongtin_tratruoc_dn/fn_tt_hd_thuebao', body),
  getThongTinDbCon: (axios, body) => axios.post('web-tratruoc/thongtin_tratruoc_dn/fn_tt_db_con', body),
  getThongTinLoaiKhl: (axios, body) => axios.post('web-tratruoc/thongtin_tratruoc_dn/fn_tt_loai_khl', body),
  getThongTinTienTrinhSMS: (axios, body) => axios.post('web-tratruoc/thongtin_tratruoc_dn/fn_tt_tientrinhsms', body)
}
