export default {
    lay_tienkhoanmuc_loaihd: (axios, data) => axios.post('web-thicong/danhmuc/lay_tienkhoanmuc_loaihd', data),
    sp_lay_donvi_quanly_ldv: (axios, data) => axios.post('web-ccdv/tien_trinh_bao_hong/sp_lay_donvi_quanly_ldv', data),
    
    lay_thongtin_ds_tocdo_adsl: (axios, data) => axios.get('web-hopdong/hopdong/lay_thongtin_ds_tocdo_adsl', data),
    lay_thongtin_ds_muccuoc: (axios, data) => axios.get('web-hopdong/hopdong/lay_thongtin_ds_muccuoc', data),
    lay_thongtin_ds_hdtb_loaiip: (axios, data) => axios.get(`web-hopdong/hopdong/lay_thongtin_ds_hdtb_loaiip?hdtb_id=${data.hdtb_id}`, data),
    lay_thongtin_ds_hdtb_kieu_nt: (axios, data) => axios.get(`web-hopdong/hopdong/lay_thongtin_ds_hdtb_kieu_nt?hdKhId=${data.hdtb_id}`, data),
    lay_thongtin_ds_thietbi_ims: (axios, data) => axios.get('web-hopdong/hopdong/lay_thongtin_ds_thietbi_ims', data),
    lay_thongtin_ds_trangbi: (axios, data) => axios.get('web-hopdong/hopdong/lay_thongtin_ds_trangbi', data),
    lay_thongtin_ds_goicuoc_dd: (axios, data) => axios.get(`web-hopdong/hopdong/lay_thongtin_ds_goicuoc_dd?loaitb_id=${data.loaitb_id}`, data),
    lay_thongtin_kieuld: (axios, data) => axios.get(`web-hopdong/hopdong/lay_thongtin_kieuld?loaihd_id=${data.loaihd_id}`, data),
    lay_thongtin_ds_dichvu_khac: (axios, data) => axios.get(`web-hopdong/hopdong/lay_thongtin_ds_dichvu_khac?dvkhac_id=${data.dvkhac_id}`, data),
    lay_thongtin_ds_loai_kh: (axios, data) => axios.get(`web-hopdong/hopdong/lay_thongtin_ds_loai_kh?loaikh_id=${data.loaikh_id}`, data),
    lay_thongtin_ds_phanloai_kh: (axios, data) => axios.get(`web-hopdong/hopdong/lay_thongtin_ds_phanloai_kh?hienthi_md=${data.hienthi_md}`, data),
    lay_thongtin_tinh_tc: (axios, data) => axios.get(`web-hopdong/hopdong/lay_thongtin_tinh_tc?tinh_id=${data.tinh_id}`, data),
    lay_thongtin_ds_muccuoc_tb: (axios, data) => axios.get(`web-hopdong/hopdong/lay_thongtin_ds_muccuoc_tb?mucuoctb_id=${data.mucuoctb_id}`, data),

    lay_ds_thuebao_dichvu_bc: (axios, data) => axios.post('web-hopdong/hopdong/lay_ds_thuebao_dichvu_bc', data),
    lay_ds_thuebao_dichvu: (axios, data) => axios.post('web-hopdong/hopdong/lay_ds_thuebao_dichvu', data),
    lay_ds_thamso_md_mats: async (axios, data,header) => axios.post('/web-ccdv/khaibaotsl/lay_ds_thamso_md_mats', data, header),
    sp_tt_thamso_md: (axios, data) => axios.post('web-hopdong/laydulieu/sp_tt_thamso_md', data),

    fn_tt_nganhang: (axios, data) => axios.post('/web-tratruoc/thongtin_tratruoc_dn/fn_tt_nganhang', data),
    fn_tt_hd_mig: (axios, data) => axios.post('/web-tratruoc/thongtin_tratruoc_dn/fn_tt_hd_mig', data),
    fn_tt_nhanvien: (axios, data) => axios.post('/web-tratruoc/thongtin_tratruoc_dn/fn_tt_nhanvien', data),
    fn_tt_hd_khachhang: (axios, data) => axios.post('/web-tratruoc/thongtin_tratruoc_dn/fn_tt_hd_khachhang', data),
    fn_tt_db_khachhang: (axios, data) => axios.post('/web-tratruoc/thongtin_tratruoc_dn/fn_tt_db_khachhang', data),
    fn_tt_loaihinh_tb: (axios, data) => axios.post('/web-tratruoc/thongtin_tratruoc_dn/fn_tt_loaihinh_tb', data),
    fn_tt_tuyenthu: (axios, data) => axios.post('/web-tratruoc/thongtin_tratruoc_dn/fn_tt_tuyenthu', data),
    fn_tt_muccuoc_tb: (axios, data) => axios.post('/web-tratruoc/thongtin_tratruoc_dn/fn_tt_muccuoc_tb', data),

    HT_nvtc_theodc_v2: (axios, data) => axios.post('web-hopdong/fn_lay_load_hths_datmoi/HT_nvtc_theodc_v2', data),
    ht_nvtc_theodc: (axios, data) => axios.post('web-hopdong/lapdatmoi/ht_nvtc_theodc', data),
    lay_ds_hopdong_tt_theo_hdtt_id: (axios, data) => axios.post('web-hopdong/lapdatmoi/lay_ds_hopdong_tt_theo_hdtt_id', data),
    lay_ds_diachi_theo_hdtt: (axios, data) => axios.get(`web-hopdong/hopdong/lay_ds_diachi_theo_hdtt?hdttId=${data.hdttId}`, data),
    ht_combo_ma_daidien: (axios, data) => axios.post('web-hopdong/hopdong/ht_combo_ma_daidien', data),
    lay_nhanvien_ql: (axios, data) => axios.post('web-hopdong/hopdong/lay_nhanvien_ql', data),
    lay_ds_donviql_v2: (axios, data) => axios.post('web-hopdong/xac_nhan_giahan_datcoc_tt/lay_ds_donviql_v2', data),
    lay_ds_donviql: (axios, data) => axios.post('web-ccdv/tiepnhan_yc_ks_lapdat/lay_ds_donviql', data),
    lay_ds_nhanvien_ql_am_v2: (axios, data) => axios.post('web-hopdong/lapdatmoi/lay_ds_nhanvien_ql_am_v2', data),
    lay_ds_nhanvien_ql_am_1: (axios, data) => axios.post('web-hopdong/tachnhapthuebao/lay_ds_nhanvien_ql_am_1', data),
    lay_somay_truynhap_theo_matb: (axios, data) => axios.get(`web-hopdong/hopdong/lay_somay_truynhap_theo_matb?maTb=${data.maTb}`, data),
    lay_ds_diachi_theo_hdkh: (axios, data) => axios.get(`web-hopdong/hopdong/lay_ds_diachi_theo_hdkh?hdKhId=${data.hdKhId}`, data),
    lay_ds_hdtt_theo_hdkh_id_1: (axios, data) => axios.post('web-ccdv/hoanthien-hs-muativi/lay_ds_hdtt_theo_hdkh_id_1', data),
    lay_ds_hopdong_thuebao_theo_hdkh: (axios, data) => axios.get(`web-hopdong/hopdong/lay_ds_hopdong_thuebao_theo_hdkh?hdKhId=${data.hdKhId}`, data),
    lay_ds_hopdong_thanhtoan_theo_hdkh: (axios, data) => axios.get(`web-hopdong/hopdong/lay_ds_hopdong_thanhtoan_theo_hdkh?hdKhId=${data.hdKhId}`, data),
    lay_tinh_theo_thuebaoid: (axios, data) => axios.get(`web-hopdong/thanhly-thuebao-bancheo/lay_tinh_theo_thuebaoid?thuebao_id=${data.thuebao_id}`, data),
    lay_thuebaoid_thicong: (axios, data) => axios.post('web-hopdong/chuyendoi-codinh-sang-ims-bancheo/lay_thuebaoid_thicong', data),
    lay_ds_diachi_theo_hdtb: (axios, data) => axios.get(`web-hopdong/hopdong/lay_ds_diachi_theo_hdtb?hdtbId=${data.hdtbId}`, data),
    lay_ds_dbtb_theo_tbid: (axios, data) => axios.post('web-hopdong/thong-tin-kenh-trang/lay_ds_dbtb_theo_tbid', data),
    lay_biendong_thongtin_thuebao: (axios, data) => axios.get(`web-hopdong/hopdong/lay_biendong_thongtin_thuebao?hdtbId=${data.hdtbId}`, data),
    lay_tien_hopdong: (axios, data) => axios.get(`web-hopdong/hopdong/lay_tien_hopdong?hdtbId=${data.hdtbId}`, data),

    lay_ds_hopdong_thuebao_codinh: (axios, data) => axios.get(`web-hopdong/hopdong/lay_ds_hopdong_thuebao_codinh?hdtbId=${data.hdtbId}`, data),
    lay_ds_hdtb_dd_theo_hdtb_id: (axios, data) => axios.post('web-hopdong/hopdong/lay_ds_hdtb_dd_theo_hdtb_id', data),
    lay_ds_hopdong_thuebao_adsl: (axios, data) => axios.get(`web-hopdong/hopdong/lay_ds_hopdong_thuebao_adsl?hdtbId=${data.hdtbId}`, data),
    lay_ds_hopdong_thuebao_mgwan: (axios, data) => axios.get(`web-hopdong/hopdong/lay_ds_hopdong_thuebao_mgwan?hdtbId=${data.hdtbId}`, data),
    lay_ds_hopdong_thuebao_tls: (axios, data) => axios.get(`web-hopdong/hopdong/lay_ds_hopdong_thuebao_tls?hdtbId=${data.hdtbId}`, data),
    lay_ds_hopdong_thuebao_gp: (axios, data) => axios.get(`web-hopdong/hopdong/lay_ds_hopdong_thuebao_gp?hdtbId=${data.hdtbId}`, data),
    lay_ds_hopdong_thuebao_ims: (axios, data) => axios.get(`web-hopdong/hopdong/lay_ds_hopdong_thuebao_ims?hdtbId=${data.hdtbId}`, data),
    lay_ds_hopdong_thuebao_cntt: (axios, data) => axios.get(`web-hopdong/hopdong/lay_ds_hopdong_thuebao_cntt?hdtbId=${data.hdtbId}`, data),

    lay_danhba_theo_matb: (axios, data) => axios.post('web-hopdong/hopdong/lay_danhba_theo_matb', data),
    lay_ds_chitiet_khuyenmai: (axios, data) => axios.get(`web-hopdong/hopdong/lay_ds_chitiet_khuyenmai?thueBaoId=${data.thueBaoId}&kieu=${data.kieu}`, data),
    kiemtra_thuebao_lap_hopdong_khac: (axios, data) => axios.post('web-hopdong/hopdong/kiemtra_thuebao_lap_hopdong_khac', data),
    lay_ds_diachi_theo_khachhang: (axios, data) => axios.get(`web-hopdong/hopdong/lay_ds_diachi_theo_khachhang?khachHangId=${data.khachHangId}`, data),
    kiemtra_hopdong_thuebao: (axios, data) => axios.get(`web-hopdong/hopdong/kiemtra_hopdong_thuebao?thueBaoId=${data.thueBaoId}&maGd=${data.maGd}`, data),

    bancheo_lay_ds_diachi_theo_dbtbid: (axios, data) => axios.post('web-bancheo/tracuu/lay_ds_diachi_theo_dbtbid', data),
    bancheo_lay_ds_db_thuebao_theo_tbid: (axios, data) => axios.post('web-bancheo/tracuu/lay_ds_db_thuebao_theo_tbid', data),
    bancheo_lay_ds_danhba_codinh: (axios, data) => axios.post('web-bancheo/tracuu/lay_ds_db_cd_theo_tbid', data),   
    bancheo_lay_ds_danhba_ims: (axios, data) => axios.post('web-bancheo/tracuu/lay_ds_db_ims_theo_tbid', data),
    bancheo_lay_ds_danhba_adsl: (axios, data) => axios.post('web-bancheo/tracuu/lay_ds_db_adsl_theo_tbid', data),
    bancheo_lay_ds_danhba_tsl: (axios, data) => axios.post('web-bancheo/tracuu/lay_ds_db_tsl_theo_tbid', data),
    bancheo_lay_thongso_thuebao_thuebaoid: (axios, data) => axios.post('web-bancheo/tracuu/lay_thongso_thuebao_thuebaoid', data),

    lay_ds_danhba_codinh: (axios, data) => axios.get(`web-hopdong/hopdong/lay_ds_danhba_codinh?thueBaoId=${data.thueBaoId}`, data),
    lay_ds_danhba_ims: (axios, data) => axios.get(`web-hopdong/hopdong/lay_ds_danhba_ims?thueBaoId=${data.thueBaoId}`, data),
    lay_ds_danhba_adsl: (axios, data) => axios.get(`web-hopdong/hopdong/lay_ds_danhba_adsl?thueBaoId=${data.thueBaoId}`, data),
    lay_ds_danhba_tsl: (axios, data) => axios.get(`web-hopdong/hopdong/lay_ds_danhba_tsl?thueBaoId=${data.thueBaoId}`, data),
    lay_ds_danhba_dd: (axios, data) => axios.get(`web-hopdong/hopdong/lay_ds_danhba_dd?thueBaoId=${data.thueBaoId}`, data),
    lay_ds_danhba_megawan: (axios, data) => axios.get(`web-hopdong/hopdong/lay_ds_danhba_megawan?thueBaoId=${data.thueBaoId}`, data),
    lay_ds_danhba_gp: (axios, data) => axios.get(`web-hopdong/hopdong/lay_ds_danhba_gp?thueBaoId=${data.thueBaoId}`, data),
    lay_ds_danhba_megaeys: (axios, data) => axios.get(`web-hopdong/hopdong/lay_ds_danhba_megaeys?thueBaoId=${data.thueBaoId}`, data),
    lay_ds_danhba_cntt: (axios, data) => axios.get(`web-hopdong/hopdong/lay_ds_danhba_cntt?thueBaoId=${data.thueBaoId}`, data),
    lay_thongso_thuebao_thuebaoid: (axios, data) => axios.get(`web-hopdong/hopdong/lay_thongso_thuebao_thuebaoid?thueBaoId=${data.thueBaoId}`, data),

    lay_ds_hopdong_theo_ma_gd: (axios, data) => axios.post('web-hopdong/hopdong/lay_ds_hopdong_theo_ma_gd', data),
    lay_db_theo_matb: (axios, data) => axios.post('web-hopdong/lapdatmoi/lay_db_theo_matb', data),
    lay_khachhangid_thicong: (axios, data) => axios.post('web-bancheo/tracuu/lay_khachhangid_thicong', data),
    lay_ds_diachi_theo_dbttid: (axios, data) => axios.get(`web-hopdong/thaydoithongtinkhuyenmai/lay_ds_diachi_theo_dbttid?dbttid=${data.dbttid}`, data),

    lay_dbtt_theo_matt_khid: (axios, data) => axios.post('web-hopdong/lapdatmoi/lay_dbtt_theo_matt_khid', data),

    lay_ds_hopdong_tb_theo_hdtb_id: (axios, data) => axios.post('web-hopdong/thaydoiloaihinhtb/lay_ds_hopdong_tb_theo_hdtb_id', data),
    lay_thongso_thuebao_bancheo_hdtbid: (axios, data) => axios.get(`web-hopdong/hopdong/lay_thongso_thuebao_bancheo_hdtbid?hdtbId=${data.hdtbId}`, data),

    kiemtra_thanhtoan_lh: (axios, data) => axios.get(`web-hopdong/hopdong/kiemtra_thanhtoan_lh?hdkhId=${data.hdkhId}`, data),

    kiemtra_hdtb_theo_hdtt: (axios, data) => axios.get(`web-hopdong/hopdong/kiemtra_hdtb_theo_hdtt?hdttId=${data.hdttId}`, data),

    xoa_hopdong_thanhtoan: (axios, data) => axios.post(`web-hopdong/hopdong/xoa_hopdong_thanhtoan?hdttId=${data.hdttId}`, data),

    kiemtra_makh_matt_magd: (axios, data) => axios.post('web-hopdong/hopdong/kiemtra_makh_matt_magd', data),
    lay_ds_makh_theo_mst: (axios, data) => axios.post('web-hopdong/hopdong/lay_ds_makh_theo_mst', data),
    get_keys: (axios, data) => axios.post('web-quantri/donvitinh/get_keys', data),
    sinh_matt: (axios, data) => axios.get(`web-hopdong/chuyendich/sinh_matt?donvi_id=${data.donvi_id}&quan_id=${data.quan_id}`, data),
    sp_lap_hopdong_chuyenquyen: (axios, data) => axios.post('web-hopdong/hopdong/khac/sp_lap_hopdong_chuyenquyen', data),

    xoa_hdkh_v2: (axios, data) => axios.post('web-hopdong/hopdong/xoa_hdkh_v2', data),

    xoa_hopdong_thuebao: (axios, data) => axios.post(`web-hopdong/hopdong/xoa_hopdong_thuebao?hdtbId=${data.hdtbId}`, data),

    kiemtra_thaydoi: (axios, data) => axios.get(`web-hopdong/hopdong/kiemtra_thaydoi?thueBaoId=${data.thueBaoId}&loaiHdId=${data.loaiHdId}`, data),

    lay_ds_kieu_ld: (axios, data) => axios.post('web-hopdong/thaydoimytv/lay_ds_kieu_ld', data),

}