export default {
	ts_vcc_ds_thuebao: async (axios) => axios.get('/ccbs/executor/ts_vcc_ds_thuebao'),
	ts_vcc_ds_loaivcc: async (axios) => axios.get('/ccbs/executor/ts_vcc_ds_loaivcc'),
	ts_vcc_ds_muc_giamgia: async (axios, data) => axios.post('/ccbs/executor/ts_vcc_ds_muc_giamgia', data),
	ts_dichvu_pt_thanhtoan: async (axios) => axios.get('/ccbs/executor/ts_dichvu_pt_thanhtoan'),
	ts_dichvu_kieu_baocuoc: async (axios) => axios.get('/ccbs/executor/ts_dichvu_kieu_baocuoc'),
	ts_dm_nganhang_ds: async (axios) => axios.get('/ccbs/executor/ts_dm_nganhang_ds'),
	ts_ds_loaikh: async (axios) => axios.get('/ccbs/executor/ts_ds_loaikh'),	
	ts_vcc_ds_dichvubs: async (axios) => axios.get('/ccbs/executor/ts_vcc_ds_dichvubs'),
	ts_vcc_lay_tttb: async (axios, data) => axios.post('/ccbs/executor/ts_vcc_lay_tttb', data),
	lay_danhba_theo_matb: async (axios, data) => axios.post('/web-quantri/dangky-dichvu-vcc/lay_danhba_theo_matb', data),
	kiemtra_ma_tb_lap_hopdong_khac: async (axios, data) => axios.post('/web-quantri/dangky-dichvu-vcc/kiemtra_ma_tb_lap_hopdong_khac', data),
	fn_frmdangky_dv_vcc_ttqt_dangky: async (axios, data) => axios.post('/web-quantri/dangky-dichvu-vcc/fn_frmdangky_dv_vcc_ttqt_dangky', data),
	post_sinh_magd: async (axios, data) => axios.post('/web-hopdong/khoiphucthanhly/sinh_magd',data),

	siptrungking_dichvu_nguoi_gt: async (axios, data) => axios.post('/ccbs/executor/siptrungking_dichvu_nguoi_gt', data),
	ts_vcc_ds_goicuoc: async (axios, data) => axios.post('/ccbs/executor/ts_vcc_ds_goicuoc', data),
	ts_vcc_ds_goi_tb: async (axios, data) => axios.post('/ccbs/executor/ts_vcc_ds_goi_tb', data),
	ts_vcc_ds_tb_dichvubs: async (axios, data) => axios.post('/ccbs/executor/ts_vcc_ds_tb_dichvubs', data),
	ts_vcc_dangky_dichvu: async (axios, data) => axios.post('/ccbs/executor/vcc/ts_dangky_dichvu', data),
	ts_vcc_huy_dichvu: async (axios, data) => axios.post('/ccbs/executor/vcc/ts_huy_dichvu', data),
	ts_vcc_tamngung_dichvu: async (axios, data) => axios.post('/ccbs/executor/vcc/ts_tamngung_dichvu', data),
	ts_vcc_kichhoat_dichvu: async (axios, data) => axios.post('/ccbs/executor/vcc/ts_kichhoat_dichvu', data),
	ts_vcc_capnhat_goi: async (axios, data) => axios.post('/ccbs/executor/ts_vcc_capnhat_goi', data),
	ts_vcc_huy_goi: async (axios, data) => axios.post('/ccbs/executor/ts_vcc_huy_goi', data),
	ts_vcc_dichvubs_dangky: async (axios, data) => axios.post('/ccbs/vcc/ts_dangky_dvbosung', data),
	ts_vcc_dichvubs_huy: async (axios, data) => axios.post('/ccbs/vcc/ts_huy_dvbosung', data),
	ts_vcc_dichvubs_capnhat: async (axios, data) => axios.post('/ccbs/vcc/ts_capnhat_dvbosung', data),
}
