export default {
  PHIEU_DANGKY_NHUCAU: 1,
  PHIEU_DENGHI_NHAPKHO_TT: 2,
  PHIEU_DENGHI_MUALE: 3,
  PHIEU_NHAPKHO: 4,
  PHIEU_DENGHI_CHUYENKHO: 5,
  PHIEU_CHUYENKHO: 6,
  PHIEU_DENGHI_XUATKHO: 7,
  PHIEU_XUATKHO: 8,
  PHIEU_DENGHI_QUYETTOAN: 9,
  PHIEU_DENGHI_THUHOI_TB: 10,
  PHIEU_DENGHI_THUHOI_CT: 11
}
