export default {
  KHO_THUHOI: 15,
  KHO_BAOHANH: 6,
  KHO_TOTRUONG: 14,
  KHO_GUI_BAOHANH: 16,
  KHO_TRA_BAOHANH: 17,
  KHO_NHA_CC: 2,
  KHO_NV: 5,
  KHO_VATTU_SUACHUA: 530,
  KHO_VATTU_BAOHANH: 540
}
