const GRID_COLUMS = {
  1: [
    { fieldName: '_CHECK', visible: false, allowEditing: false },
    { fieldName: 'MA_TT', headerText: 'Mã TT', allowFiltering: true, allowSorting: false, allowEditing: false, isPrimaryKey: true },
    { fieldName: 'MA_TUYEN', headerText: 'Tuyến thu', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'TIEN_HD', headerText: 'Tiền hóa đơn', allowFiltering: true, allowSorting: false, type: 'number', format: 'N0', allowEditing: false },
    { fieldName: 'MATB_DD', headerText: 'Mã TBĐD', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'TIEN', headerText: 'Tiền nợ', allowFiltering: true, allowSorting: false, type: 'number', format: 'N0', allowEditing: false },
    { fieldName: 'TIENNO_QL', headerText: 'Tiền nợ QL', allowFiltering: true, allowSorting: false, type: 'number', format: 'N0', allowEditing: false },
    { fieldName: 'SO_SERI', headerText: 'Số Seri', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'TEN_TT', headerText: 'Tên TT', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'DIACHI_TT', headerText: 'Địa chỉ TT', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'HINHTHUC_TT', headerText: 'HTTT', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'SO_THUNG', headerText: 'Số thùng', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'SERI', headerText: 'Seri', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'THUTU_IN', headerText: 'Thứ tự in', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'NGAYHEN', headerText: 'Ngày hẹn', allowFiltering: true, allowSorting: false },
    { fieldName: 'NGAYNHAN_HD', headerText: 'Ngày nhận', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'LYDOTRA_ID', headerText: 'Lý do', allowFiltering: true, allowSorting: false, allowEditing: true},
    { fieldName: 'GHICHU', headerText: 'Ghi chú', allowFiltering: true, allowSorting: false, allowEditing: true },
    { fieldName: 'GHICHU_GDV', headerText: 'Ghi chú GDV', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'MAIN_GHEP', headerText: 'Mã in ghép', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'THUNO', headerText: 'Thu nợ', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'MANV_TC', headerText: 'Mã NV/HTTT', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'GIAOPHIEU_ID', headerText: 'Lượt giao', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'TEN_LKHL', headerText: 'Loại KHL', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'TENHT_GIAO', headerText: 'HT giao', allowFiltering: true, allowSorting: false, allowEditing: false },
	{ fieldName: 'TEN_PLKH', headerText: 'Phân loại KH', allowFiltering: true, allowSorting: false, allowEditing: false },
	{ fieldName: 'CNRR', headerText: 'CNRR', allowFiltering: true, allowSorting: false, allowEditing: false }
  ],
  2: [
    { fieldName: '_CHECK', visible: false },
    { fieldName: 'MA_TT', headerText: 'Mã TT', allowFiltering: true, allowSorting: false, allowEditing: false, isPrimaryKey: true },
    { fieldName: 'MA_TUYEN', headerText: 'Tuyến thu', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'TIEN_HD', headerText: 'Tiền hóa đơn', allowFiltering: true, allowSorting: false, type: 'number', format: 'N0', allowEditing: false },
    { fieldName: 'MATB_DD', headerText: 'Mã TBĐD', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'TIEN', headerText: 'Tiền nợ', allowFiltering: true, allowSorting: false, type: 'number', format: 'N0', allowEditing: false },
    { fieldName: 'TIENNO_QL', headerText: 'Tiền nợ QL', allowFiltering: true, allowSorting: false, type: 'number', format: 'N0', allowEditing: false },
    { fieldName: 'SO_SERI', headerText: 'Số Seri', allowFiltering: true, allowSorting: false, allowEditing: false },    
    { fieldName: 'TEN_TT', headerText: 'Tên TT', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'DIACHI_TT', headerText: 'Địa chỉ TT', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'HINHTHUC_TT', headerText: 'HTTT', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'SO_THUNG', headerText: 'Số thùng', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'SERI', headerText: 'Seri', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'THUTU_IN', headerText: 'Thứ tự in', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'NGAYHEN', headerText: 'Ngày hẹn', allowFiltering: true, allowSorting: false },
    { fieldName: 'NGAYNHAN_HD', headerText: 'Ngày nhận', allowFiltering: true, allowSorting: false },
    { fieldName: 'LYDOTRA_ID', headerText: 'Lý do', allowFiltering: true, allowSorting: false, allowEditing: true},
    { fieldName: 'ND_THUCHIEN', headerText: 'NVQLTC xử lý', allowFiltering: true, allowSorting: false, allowEditing: true },
    { fieldName: 'GHICHU', headerText: 'Ghi chú', allowFiltering: true, allowSorting: false, allowEditing: true },
    { fieldName: 'GHICHU_GDV', headerText: 'Ghi chú GDV', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'MAIN_GHEP', headerText: 'Mã in ghép', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'THUNO', headerText: 'Thu nợ', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'MANV_TC', headerText: 'Mã NV/HTTT', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'GIAOPHIEU_ID', headerText: 'Lượt giao', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'TEN_LKHL', headerText: 'Loại KHL', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'TENHT_GIAO', headerText: 'HT giao', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'TEN_PLKH', headerText: 'Phân loại KH', allowFiltering: true, allowSorting: false, allowEditing: false },
	{ fieldName: 'CNRR', headerText: 'CNRR', allowFiltering: true, allowSorting: false, allowEditing: false }
  ],
	3: [
    { fieldName: '_CHECK', visible: false },
    { fieldName: 'MA_TT', headerText: 'Mã TT', allowFiltering: true, allowSorting: false, allowEditing: false, isPrimaryKey: true },
    { fieldName: 'MA_TUYEN', headerText: 'Tuyến thu', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'TIEN_HD', headerText: 'Tiền hóa đơn', allowFiltering: true, allowSorting: false, type: 'number', format: 'N0', allowEditing: false },
    { fieldName: 'MATB_DD', headerText: 'Mã TBĐD', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'TIEN', headerText: 'Tiền nợ', allowFiltering: true, allowSorting: false, type: 'number', format: 'N0', allowEditing: false },
    { fieldName: 'TIENNO_QL', headerText: 'Tiền nợ QL', allowFiltering: true, allowSorting: false, type: 'number', format: 'N0', allowEditing: false },
    { fieldName: 'SO_SERI', headerText: 'Số Seri', allowFiltering: true, allowSorting: false, allowEditing: false },    
    { fieldName: 'TEN_TT', headerText: 'Tên TT', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'DIACHI_TT', headerText: 'Địa chỉ TT', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'HINHTHUC_TT', headerText: 'HTTT', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'SO_THUNG', headerText: 'Số thùng', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'SERI', headerText: 'Seri', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'THUTU_IN', headerText: 'Thứ tự in', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'NGAYHEN', headerText: 'Ngày hẹn', allowFiltering: true, allowSorting: false },
    { fieldName: 'NGAYNHAN_HD', headerText: 'Ngày nhận', allowFiltering: true, allowSorting: false },
    { fieldName: 'LYDOTRA_ID', headerText: 'Lý do', allowFiltering: true, allowSorting: false, allowEditing: true},
    { fieldName: 'ND_THUCHIEN', headerText: 'NVQLTC xử lý', allowFiltering: true, allowSorting: false, allowEditing: true },
    { fieldName: 'GHICHU', headerText: 'Ghi chú', allowFiltering: true, allowSorting: false, allowEditing: true },
    { fieldName: 'GHICHU_GDV', headerText: 'Ghi chú GDV', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'MAIN_GHEP', headerText: 'Mã in ghép', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'THUNO', headerText: 'Thu nợ', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'MANV_TC', headerText: 'Mã NV/HTTT', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'GIAOPHIEU_ID', headerText: 'Lượt giao', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'TEN_LKHL', headerText: 'Loại KHL', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'TENHT_GIAO', headerText: 'HT giao', allowFiltering: true, allowSorting: false, allowEditing: false },
    { fieldName: 'TEN_PLKH', headerText: 'Phân loại KH', allowFiltering: true, allowSorting: false, allowEditing: false },
	{ fieldName: 'CNRR', headerText: 'CNRR', allowFiltering: true, allowSorting: false, allowEditing: false }
	],
	4: [
    { fieldName: '_CHECK', visible: false },
		{fieldName: 'MA_TT', headerText: 'Mã TT', allowFiltering: true, allowSorting:false},
		{fieldName: 'MA_TUYEN', headerText: 'Tuyến thu', allowFiltering: true, allowSorting:false},
		{fieldName: 'TIEN_HD', headerText: 'Tiền hóa đơn', allowFiltering: true, allowSorting:false,type:'number',format:'N0'},
		{fieldName: 'MATB_DD', headerText: 'Mã TBĐD', allowFiltering: true, allowSorting:false},
		{fieldName: 'TIEN', headerText: 'Tiền nợ', allowFiltering: true, allowSorting:false,type:'number',format:'N0'},
		{fieldName: 'TIENNO_QL', headerText: 'Tiền nợ QL', allowFiltering: true, allowSorting:false,type:'number',format:'N0'},
		{fieldName: 'SO_SERI', headerText: 'Số Seri', allowFiltering: true, allowSorting:false},
		{fieldName: 'TEN_TT', headerText: 'Tên TT', allowFiltering: true, allowSorting:false},
		{fieldName: 'DIACHI_TT', headerText: 'Địa chỉ TT', allowFiltering: true, allowSorting:false},		
		{fieldName: 'SO_THUNG', headerText: 'Số thùng', allowFiltering: true, allowSorting:false},
		{fieldName: 'SERI', headerText: 'Seri', allowFiltering: true, allowSorting:false},
		{fieldName: 'THUTU_IN', headerText: 'Thứ tự in', allowFiltering: true, allowSorting:false},
		{fieldName: 'NGAYHEN', headerText: 'Ngày hẹn', allowFiltering: true, allowSorting:false,type: 'string'},
		{fieldName: 'NGAYNHAN_HD', headerText: 'Ngày nhận', allowFiltering: true, allowSorting:false},
		{fieldName: 'LYDOTRA_ID_HTML', headerText: 'Lý do', allowFiltering: true, allowSorting:false, allowHtml:true},
		{fieldName: 'ND_THUCHIEN', headerText: 'NVQLTC xử lý', allowFiltering: true, allowSorting:false, allowHtml:true},
		{fieldName: 'GHICHU_HTML', headerText: 'Ghi chú', allowFiltering: true, allowSorting:false, allowHtml:true},
		{fieldName: 'GHICHU_GDV', headerText: 'Ghi chú GDV', allowFiltering: true, allowSorting:false},
		{fieldName: 'MAIN_GHEP', headerText: 'Mã in ghép', allowFiltering: true, allowSorting:false},
		{fieldName: 'GIAOPHIEU_ID', headerText: 'Lượt giao', allowFiltering: true, allowSorting:false},
		{fieldName: 'THUNO', headerText: 'Thu nợ', allowFiltering: true, allowSorting:false},
		{fieldName: 'MANV_TC', headerText: 'Mã NV/HTTT', allowFiltering: true, allowSorting:false},
		{fieldName: 'TEN_LKHL', headerText: 'Loại KHL', allowFiltering: true, allowSorting:false},
		{fieldName: 'TENHT_GIAO', headerText: 'HT giao', allowFiltering: true, allowSorting:false},
		{fieldName: 'TEN_PLKH', headerText: 'Phân loại KH', allowFiltering: true, allowSorting:false},
		{ fieldName: 'CNRR', headerText: 'CNRR', allowFiltering: true, allowSorting: false, allowEditing: false }
	],
	5: [
    { fieldName: '_CHECK', visible: false },
		{fieldName: 'MA_TT', headerText: 'Mã TT', allowFiltering: true, allowSorting:false},
		{fieldName: 'MA_TUYEN', headerText: 'Tuyến thu', allowFiltering: true, allowSorting:false},
		{fieldName: 'TIEN_HD', headerText: 'Tiền hóa đơn', allowFiltering: true, allowSorting:false,type:'number',format:'N0'},
		{fieldName: 'MATB_DD', headerText: 'Mã TBĐD', allowFiltering: true, allowSorting:false},
		{fieldName: 'TIEN', headerText: 'Tiền nợ', allowFiltering: true, allowSorting:false,type:'number',format:'N0'},
		{fieldName: 'TIENNO_QL', headerText: 'Tiền nợ QL', allowFiltering: true, allowSorting:false,type:'number',format:'N0'},
		{fieldName: 'SO_SERI', headerText: 'Số Seri', allowFiltering: true, allowSorting:false},
		{fieldName: 'TEN_TT', headerText: 'Tên TT', allowFiltering: true, allowSorting:false},
		{fieldName: 'DIACHI_TT', headerText: 'Địa chỉ TT', allowFiltering: true, allowSorting:false},
		{fieldName: 'HINHTHUC_TT', headerText: 'HTTT', allowFiltering: true, allowSorting:false},
		{fieldName: 'SO_THUNG', headerText: 'Số thùng', allowFiltering: true, allowSorting:false},
		{fieldName: 'SERI', headerText: 'Seri', allowFiltering: true, allowSorting:false},
		{fieldName: 'THUTU_IN', headerText: 'Thứ tự in', allowFiltering: true, allowSorting:false},
		{fieldName: 'NGAYHEN', headerText: 'Ngày hẹn', allowFiltering: true, allowSorting:false},
		{fieldName: 'NGAYNHAN_HD', headerText: 'Ngày nhận', allowFiltering: true, allowSorting:false},
		{fieldName: 'LYDOTRA_ID_HTML', headerText: 'Lý do', allowFiltering: true, allowSorting:false, allowHtml:true},
		{fieldName: 'ND_THUCHIEN', headerText: 'NVQLTC xử lý', allowFiltering: true, allowSorting:false, allowHtml:true},
		{fieldName: 'GHICHU_HTML', headerText: 'Ghi chú', allowFiltering: true, allowSorting:false, allowHtml:true},
		{fieldName: 'GHICHU_GDV', headerText: 'Ghi chú GDV', allowFiltering: true, allowSorting:false},
		{fieldName: 'MAIN_GHEP', headerText: 'Mã in ghép', allowFiltering: true, allowSorting:false},
		{fieldName: 'THUNO', headerText: 'Thu nợ', allowFiltering: true, allowSorting:false},
		{fieldName: 'MANV_TC', headerText: 'Mã NV/HTTT', allowFiltering: true, allowSorting:false},
		{fieldName: 'GIAOPHIEU_ID', headerText: 'Lượt giao', allowFiltering: true, allowSorting:false},
		{fieldName: 'TEN_LKHL', headerText: 'Loại KHL', allowFiltering: true, allowSorting:false},
		{fieldName: 'TENHT_GIAO', headerText: 'HT giao', allowFiltering: true, allowSorting:false},
		{fieldName: 'TEN_PLKH', headerText: 'Phân loại KH', allowFiltering: true, allowSorting: false },
		{fieldName: 'CNRR', headerText: 'CNRR', allowFiltering: true, allowSorting: false, allowEditing: false }
	],
	6:[
    { fieldName: '_CHECK', visible: false },
		{fieldName: 'STT', headerText: 'STT', allowFiltering: true, allowSorting:false},
		{fieldName: 'NGAY_TT', headerText: 'Ngày trả', allowFiltering: true, allowSorting:false},		
    {fieldName: 'SOPHIEU', headerText: 'Số phiếu', allowFiltering: true, allowSorting:false},
    {fieldName: 'MA_TT', headerText: 'Mã Thanh toán', allowFiltering: true, allowSorting:false},
		{fieldName: 'TIENTRA', headerText: 'Tiền trả', allowFiltering: true, allowSorting:false,type:'number',format:'N0'},
		{fieldName: 'MATB_DD', headerText: 'Mã TBĐD', allowFiltering: true, allowSorting:false},		
		{fieldName: 'TEN_TT', headerText: 'Tên TT', allowFiltering: true, allowSorting:false},
		{fieldName: 'LANTRA', headerText: 'Lần trả', allowFiltering: true, allowSorting:false},
		{fieldName: 'DIACHI_TT', headerText: 'Địa chỉ TT', allowFiltering: true, allowSorting:false},		
		{fieldName: 'SOHOADON', headerText: 'Số hóa đơn', allowFiltering: true, allowSorting:false},
		{fieldName: 'NGUOIGACH', headerText: 'Người gạch', allowFiltering: true, allowSorting:false},
		{fieldName: 'CHUNGTU', headerText: 'Số chứng từ', allowFiltering: true, allowSorting:false},
		{fieldName: 'GHICHU', headerText: 'Ghi chú', allowFiltering: true, allowSorting:false},
		{fieldName: 'GHICHU_GDV', headerText: 'Ghi chú GDV', allowFiltering: true, allowSorting:false},
		{fieldName: 'MA_TN', headerText: 'Thu ngân', allowFiltering: true, allowSorting:false},
		{fieldName: 'DTCC', headerText: 'ĐTCC', allowFiltering: true, allowSorting:false},
		{fieldName: 'NGAY_CN', headerText: 'Ngày cập nhật', allowFiltering: true, allowSorting:false},
		{fieldName: 'GIAOPHIEU_ID', headerText: 'Lượt giao', allowFiltering: true, allowSorting:false},
		{fieldName: 'MANV_TC', headerText: 'Mã NV/HTTT', allowFiltering: true, allowSorting:false},
		{fieldName: 'TEN_LKHL', headerText: 'Loại KHL', allowFiltering: true, allowSorting:false},
		{fieldName: 'TENHT_GIAO', headerText: 'HT giao', allowFiltering: true, allowSorting:false},
		{ fieldName: 'TEN_PLKH', headerText: 'Phân loại KH', allowFiltering: true, allowSorting: false },
		{ fieldName: 'CNRR', headerText: 'CNRR', allowFiltering: true, allowSorting: false, allowEditing: false }
	],
	7:[
    { fieldName: '_CHECK', visible: false },
		{fieldName: 'MA_TT', headerText: 'Mã TT', allowFiltering: true, allowSorting:false},
		{fieldName: 'MA_TUYEN', headerText: 'Tuyến thu', allowFiltering: true, allowSorting:false},
		{fieldName: 'TIEN', headerText: 'Tiền nợ', allowFiltering: true, allowSorting:false,type:'number',format:'N0'},
		{fieldName: 'MATB_DD', headerText: 'Mã TBĐD', allowFiltering: true, allowSorting:false},
		{fieldName: 'TIEN_HD', headerText: 'Tiền hóa đơn', allowFiltering: true, allowSorting:false,type:'number', format:'N0'},
		{fieldName: 'TEN_TT', headerText: 'Tên TT', allowFiltering: true, allowSorting:false},
		{fieldName: 'SODT_LH', headerText: 'ĐT LH', allowFiltering: true, allowSorting:false},
		{fieldName: 'DIACHI_TT', headerText: 'Địa chỉ TT', allowFiltering: true, allowSorting:false},
		{fieldName: 'SO_SERI', headerText: 'Số Seri', allowFiltering: true, allowSorting:false},
		{fieldName: 'NO_PS', headerText: 'Nợ PS', allowFiltering: true, allowSorting:false},
		{fieldName: 'NO_PS_2', headerText: 'Nợ n-2', allowFiltering: true, allowSorting:false},
		{fieldName: 'NO_PS_3', headerText: 'Nợ n-3', allowFiltering: true, allowSorting:false},
		{fieldName: 'NO_PS_4', headerText: 'Nợ n-4', allowFiltering: true, allowSorting:false},
		{fieldName: 'NO_DK', headerText: 'Nợ ĐK', allowFiltering: true, allowSorting:false},
		{fieldName: 'TIENNO_QL', headerText: 'Tiền nợ QL', allowFiltering: true, allowSorting:false},
		{fieldName: 'SO_THUNG', headerText: 'Số thùng', allowFiltering: true, allowSorting:false},
		{fieldName: 'HINHTHUC_TT', headerText: 'HTTT', allowFiltering: true, allowSorting:false},
		{fieldName: 'HINHTHUC_TT_2', headerText: 'HTTT n-2', allowFiltering: true, allowSorting:false},
		{fieldName: 'THANHTOAN_2', headerText: 'Thanh toán n-2', allowFiltering: true, allowSorting:false},
		{fieldName: 'HINHTHUC_TT_3', headerText: 'HTTT n-3', allowFiltering: true, allowSorting:false},
		{fieldName: 'HINHTHUC_TT_3', headerText: 'Thanh toán n-2', allowFiltering: true, allowSorting:false},
		{fieldName: 'HINHTHUC_TT_4', headerText: 'HTTT n-4', allowFiltering: true, allowSorting:false},
		{fieldName: 'HINHTHUC_TT_4', headerText: 'Thanh toán n-4', allowFiltering: true, allowSorting:false},
		{fieldName: 'TRANGTHAI_TB', headerText: 'Trạng thái TB', allowFiltering: true, allowSorting:false},
		{fieldName: 'NGAY_CM', headerText: 'Ngày chêm/mở', allowFiltering: true, allowSorting:false},
		{fieldName: 'MA_KHL', headerText: 'Mã KHL', allowFiltering: true, allowSorting:false},
		{fieldName: 'TEN_DVVT', headerText: 'Dịch vụ', allowFiltering: true, allowSorting:false},
		{fieldName: 'MST', headerText: 'MST', allowFiltering: true, allowSorting:false},
		{fieldName: 'DONVI_BHKV', headerText: 'Phòng BHKV', allowFiltering: true, allowSorting:false},
		{fieldName: 'TEN_DLTC', headerText: 'Tên ĐLTC', allowFiltering: true, allowSorting:false},
		{fieldName: 'SDT_DLTC', headerText: 'Số ĐT ĐLTC', allowFiltering: true, allowSorting:false},
		{fieldName: 'TO_KD', headerText: 'Tổ KD', allowFiltering: true, allowSorting:false},
		{fieldName: 'TEN_QLDB', headerText: 'Tên QLĐB', allowFiltering: true, allowSorting:false},
		{fieldName: 'SDT_QLDB', headerText: 'SĐT QLĐB', allowFiltering: true, allowSorting:false},
		{fieldName: 'TO_KT', headerText: 'Đơn vị VT', allowFiltering: true, allowSorting:false},
		{fieldName: 'TEN_NVVT', headerText: 'Tên NVVT', allowFiltering: true, allowSorting:false},
		{fieldName: 'SDT_CNVT', headerText: 'SĐT CNVT', allowFiltering: true, allowSorting:false},
		{fieldName: 'SERI', headerText: 'Seri', allowFiltering: true, allowSorting:false},
		{fieldName: 'THUTU_IN', headerText: 'Thứ tự in', allowFiltering: true, allowSorting:false},
		{fieldName: 'NGAYHEN', headerText: 'Ngày hẹn', allowFiltering: true, allowSorting:false},
		{fieldName: 'NGAYNHAN_HD', headerText: 'Ngày nhận', allowFiltering: true, allowSorting:false},
		{fieldName: 'LYDOTRA_ID_HTML', headerText: 'Lý do', allowFiltering: true, allowSorting:false, allowHtml:true},
		{fieldName: 'GHICHU_HTML', headerText: 'Ghi chú', allowFiltering: true, allowSorting:false, allowHtml:true},
		{fieldName: 'GHICHU_GDV', headerText: 'Ghi chú GDV', allowFiltering: true, allowSorting:false},
		{fieldName: 'ND_THUCHIEN', headerText: 'NVQLTC xử lý', allowFiltering: true, allowSorting:false, allowHtml:true},
		{fieldName: 'SMS', headerText: 'SMS', allowFiltering: true, allowSorting:false},
		{fieldName: 'POPUP', headerText: 'Popup', allowFiltering: true, allowSorting:false},
		{fieldName: 'OUTBOUND', headerText: 'Outbound', allowFiltering: true, allowSorting:false},
		{fieldName: 'SOLAN_NN', headerText: 'Số lần NN', allowFiltering: true, allowSorting:false},
		{fieldName: 'KQ_TTVT', headerText: 'KQ nhắc TTVT', allowFiltering: true, allowSorting:false},
		{fieldName: 'KQ_TTKD', headerText: 'KQ nhắc GDV', allowFiltering: true, allowSorting:false},
		{fieldName: 'MAIN_GHEP', headerText: 'Mã in ghép', allowFiltering: true, allowSorting:false},
		{fieldName: 'GIAOPHIEU_ID', headerText: 'Lượt giao', allowFiltering: true, allowSorting:false},
		{fieldName: 'THUNO', headerText: 'Thu nợ', allowFiltering: true, allowSorting:false},
		{fieldName: 'MANV_TC', headerText: 'Mã NV/HTTT', allowFiltering: true, allowSorting:false},
		{fieldName: 'TEN_LKHL', headerText: 'Loại KHL', allowFiltering: true, allowSorting:false},
		{fieldName: 'TENHT_GIAO', headerText: 'HT giao', allowFiltering: true, allowSorting:false},
		{ fieldName: 'TEN_PLKH', headerText: 'Phân loại KH', allowFiltering: true, allowSorting: false },
		{ fieldName: 'CNRR', headerText: 'CNRR', allowFiltering: true, allowSorting: false, allowEditing: false }
	]
};

export default GRID_COLUMS;
