loaihinh_thuebao = select loaitb_id, ma_lhtb, loaihinh_tb, ghichu, dichvuvt_id from css.loaihinh_tb
loaihinh_thuebao_theo_dichvu = select loaitb_id,ma_lhtb,loaihinh_tb,ghichu,dichvuvt_id from css.loaihinh_tb where dichvuvt_id=${dichvuvt_id}
loaihinh_thuebao_upd_ghichu = update css.loaihinh_tb set ghichu ='$ghichu' where loaitb_id = '$loaitb_id'
loaihinh_thuebao_del = delete from css.loaihinh_tb where loaitb_id = '$loaitb_id'
loaihinh_thuebao_add = insert into css.loaihinh_tb(loaitb_id,ma_lhtb,loaihinh_tb,dichvuvt_id,GIACUOC_NH) values ('$loaitb_id','$ma_lhtb','$loaihinh_tb','$dichvuvt_id','$giacuoc')

sp_layds_loaihinh_tb = { call css.pkg_category.SP_LAYDS_LOAIHINH_TB('$dvvt_id', ?) }
sp_layds_loaihinh_tb.type = procedure-cur
sp_udp_loaihinh_tb = { call css.pkg_category.SP_UDP_LOAIHINH_TB('$dvvt_id', '$loaitb_id', '$ghichu') }
fn_udp_loaihinh_tb = { ? = call css.pkg_category.FN_UDP_LOAIHINH_TB('$dvvt_id', '$loaitb_id', '$ghichu') }
fn_get_rs_sel = { ? = call css.pkg_category.FN_GET_RS_SEL('$lenh') }
fn_get_rs_sel.type = function-cur