 # Unique ID for this project
sonar.projectKey=VNPT-IT.OneBSS.cskh
sonar.projectName=VNPT-IT.OneBSS.api_app_cskh
sonar.projectVersion=1.0
sonar.sources=src/.
sonar.java.source=src/main/java
sonar.java.binaries=src/main/java/vn/vnptit/sapi/oneapp
#sonar.java.binaries=**/target/classes
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/*.sh
sonar.login=6a6bb2f6a3e8a1a2ea625b7dc2a576ef99794034
#sonar.nodejs.executable=/usr/bin/nodejs
# sonar.css.node=/usr/bin/node
#sonar.skippedModules=ShellCheck
