import axios from 'axios'
export default {
  CSS_DICHVU_VT: async (axios, data) => axios.get('/web-quantri/danhmuc-chung/CSS_DICHVU_VT', data),
  get_loai_hinh_tb_by_dichvuvt_id: async (axios, data) => axios.get(`/web-quantri/danhmuc-chung/get_loai_hinh_tb_by_dichvuvt_id/${data.dichvuvt_id}`),
  sp_ht_tatca_vetinh_combobox1: async (axios, data) => axios.post('/web-hopdong/khaibaotsl/sp_ht_tatca_vetinh_combobox1', data),
  sp_lay_ds_thamso_md: async (axios, data) => axios.post('/web-hopdong/khaibaotsl/sp_lay_ds_thamso_md', data),
  lay_danhmuc_thicong_internet: async (axios, data) => axios.post('/web-thicong/thicong-internet/lay_danhmuc_thicong_internet', data),
  sp_khdn_lay_phieu_vip: async (axios, data) => axios.post('/web-thicong/giaoviec-vip/sp_khdn_lay_phieu_vip', data),
  fn_loaihinhtb_hienthi_nut_traphieutinh: async (axios, data) => axios.get(`/web-thicong/giaoviec-vip/fn_loaihinhtb_hienthi_nut_traphieutinh?vphanvung_id=${data.vphanvung_id}&vhuonggiao_id=${data.vhuonggiao_id}&vloaitb_id=${data.vloaitb_id}`, data),
  sp_khdn_lay_ds_tientrinh_tc: async (axios, data) => axios.post(`web-thicong/giaoviec-vip/sp_khdn_lay_ds_tientrinh_tc`, data),
  sp_lay_tt_kh_bc: async (axios, data) => axios.get(`/web-thicong/giaoviec-vip/sp_lay_tt_kh_bc?vphanvung_id=${data.vphanvung_id}&vtinh_id=${data.vtinh_id}&vhdtb_id=${data.vhdtb_id}`, data),
  lay_ds_nhanvien_theo_phieu_id: async (axios, data) => axios.post('/web-thicong/giaoviec-vip/lay_ds_nhanvien_theo_phieu_id', data),
  lay_ds_nhanvien_cung_th_theo_phieu_id: async (axios, data) => axios.get(`/web-thicong/giaoviec-vip/lay_ds_nhanvien_cung_th_theo_phieu_id?vphanvung_id=${data.vphanvung_id}&vphieu_id=${data.vphieu_id}`, data),
  bancheo_lay_ds_thongtin_kythuat_v2: async (axios, data) => axios.get(`/web-thicong/giaoviec-vip/bancheo_lay_ds_thongtin_kythuat_v2?vphanvung_id=${data.vphanvung_id}&vtinh_id=${data.vtinh_id}&vhdtb_id=${data.vhdtb_id}`, data),
  lay_ds_nvql_tb_theo_hdtb_bc_v2: async (axios, data) => axios.get(`/web-thicong/giaoviec-vip/lay_ds_nvql_tb_theo_hdtb_bc_v2?vphanvung_id=${data.vphanvung_id}&vtinh_id=${data.vtinh_id}&vhdtb_id=${data.vhdtb_id}`, data),
  lay_ds_dangky_dvgt: async (axios, data) => axios.get(`/web-thicong/giaoviec-vip/lay_ds_dangky_dvgt?vphanvung_id=${data.vphanvung_id}&vhdtb_id=${data.vhdtb_id}`, data),
  lay_ds_tbi_hdtb: async (axios, data) => axios.get(`/web-thicong/giaoviec-vip/lay_ds_tbi_hdtb?vphanvung_id=${data.vphanvung_id}&vhdtb_id=${data.vhdtb_id}`, data),
  sp_chuyen_vip_giamsat: async (axios, data) => axios.post('/web-thicong/giaoviec-vip/sp_chuyen_vip_giamsat', data),
  fn_bancheo_hienthi_hoso_khdn: async (axios, data) => axios.get(`/web-thicong/giaoviec-vip/fn_bancheo_hienthi_hoso_khdn?vphanvung_id=${data.vphanvung_id}&vtinh_id=${data.vtinh_id}&vhdtb_id=${data.vhdtb_id}`, data),
  sp_bancheo_capnhat_bbnt_dv_onebusiness: async (axios, data) => axios.post('/web-thicong/giaoviec-vip/sp_bancheo_capnhat_bbnt_dv_onebusiness', data),
  hoanthanh: async (axios, data) => axios.post('/web-thicong/giaoviec-vip/hoanthanh', data),
  lay_thoigian_sla_theo_hdtbid: async (data) => axios.post('/web-thicong/dvcntt/lay_thoigian_sla_theo_hdtbid', data),
  sp_bancheo_update_nd_thuchien: async (axios, data) => axios.post('/web-thicong/giaoviec-vip/sp_bancheo_update_nd_thuchien', data),
  kiemtra_thoaitra_hoanthanh_net: async (axios, data) => axios.get(`/web-thicong/khaibao_dichvu_net_mgw/kiemtra_thoaitra_hoanthanh_net?vphanvung_id=${data.vphanvung_id}&vhdtb_id=${data.vhdtb_id}&vphieu_tinh_id=${data.vphieu_tinh_id}&vloai_check=${data.vloai_check}`, data),
  // lay api form net khac
  bancheo_lay_thongtin_hd_thicong: async (axios, data) => axios.post('/web-ccdv/completion/bancheo_lay_thongtin_hd_thicong', data),
  sp_lay_tinh_tc_theo_tinh_id: async (axios, data) => axios.post('/web-hopdong/lapdatmoi/sp_lay_tinh_tc_theo_tinh_id', data),
  update_nd_thuchien: async (axios, data) => axios.post('/web-hopdong/thaydoi_thongso_megawan/update_nd_thuchien', data),
  // Lay_danhsach_thuoctinh_v2: async (axios, request) => axios.post('/web-bancheo/tracuu/Lay_danhsach_thuoctinh_v2', request),
  upload_file: async (axios, data, header) => axios.post('/web-quantri/upload', data, header),
  lay_luong_thaotac_cntt_v2: async (axios, data, header) => axios.post('/web-thicong/dvcntt/lay_luong_thaotac_cntt_v2', data, header),

  sp_lay_tt_hd_thuebao_ct_dynamic: async (axios, data, header) => axios.post('/web-thicong/capnhatthongtin/sp_lay_tt_hd_thuebao_ct_dynamic', data, header),
}
