 # Unique ID for this project
sonar.projectKey=VNPT-IT.OneBSS.api_web_suco
sonar.projectName=VNPT-IT.OneBSS.api_web_suco
sonar.projectVersion=1.0
sonar.sources=src/.
sonar.java.source=src/main/java
sonar.java.binaries=src/main/java/vn/vnpt
#sonar.java.binaries=**/target/classes
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/*.sh
sonar.login=cd3cd7b83b233a50fe99d38e0952385adb9410f7
#sonar.nodejs.executable=/usr/bin/nodejs
# sonar.css.node=/usr/bin/node
#sonar.skippedModules=ShellCheck
