import { DETAIL_SERVICE_NEW_AUDITION_TYPE_OPTIONS } from '@/utils/enums/funeral/reservation-mngt.enums';

export const mappingNewAdditionService = {
  monite: DETAIL_SERVICE_NEW_AUDITION_TYPE_OPTIONS.HOUSING_ENSHRINEMENT,
  home: DETAIL_SERVICE_NEW_AUDITION_TYPE_OPTIONS.HOUSING_HOME,
  emotional: DETAIL_SERVICE_NEW_AUDITION_TYPE_OPTIONS.PRECIOUSNESS_MEMORY_WARMTH,
  sophisticated: DETAIL_SERVICE_NEW_AUDITION_TYPE_OPTIONS.ETERNITY_ELEGANCE,
  frame: DETAIL_SERVICE_NEW_AUDITION_TYPE_OPTIONS.FRAME,
  columbarium: DETAIL_SERVICE_NEW_AUDITION_TYPE_OPTIONS.COLUMBARIUM,
};
