import { BRANCH_ENUMS } from '@/utils/enums/common.enums';
import { DETAIL_SERVICE_NEW_AUDITION_TYPE_OPTIONS } from '@/utils/enums/funeral/reservation-mngt.enums';

export const STOCK_ORDER_CATEGORIES = {
  [BRANCH_ENUMS.GYEONGGI_GWANGJU]: [
    DETAIL_SERVICE_NEW_AUDITION_TYPE_OPTIONS.COLUMBARIUM,
    DETAIL_SERVICE_NEW_AUDITION_TYPE_OPTIONS.HOUSING_HOME,
    DETAIL_SERVICE_NEW_AUDITION_TYPE_OPTIONS.PRECIOUSNESS_MEMORY_WARMTH,
    DETAIL_SERVICE_NEW_AUDITION_TYPE_OPTIONS.ETERNITY_ELEGANCE,
    DETAIL_SERVICE_NEW_AUDITION_TYPE_OPTIONS.FRAME,
  ],
  [BRANCH_ENUMS.GIMPO]: [
    DETAIL_SERVICE_NEW_AUDITION_TYPE_OPTIONS.COLUMBARIUM,
    DETAIL_SERVICE_NEW_AUDITION_TYPE_OPTIONS.HOUSING_HOME,
    DETAIL_SERVICE_NEW_AUDITION_TYPE_OPTIONS.PRECIOUSNESS_MEMORY_WARMTH,
    DETAIL_SERVICE_NEW_AUDITION_TYPE_OPTIONS.ETERNITY_ELEGANCE,
    DETAIL_SERVICE_NEW_AUDITION_TYPE_OPTIONS.FRAME,
  ],
  [BRANCH_ENUMS.NAMYANGJU]: [
    DETAIL_SERVICE_NEW_AUDITION_TYPE_OPTIONS.HOUSING_HOME,
    DETAIL_SERVICE_NEW_AUDITION_TYPE_OPTIONS.PRECIOUSNESS_MEMORY_WARMTH,
    DETAIL_SERVICE_NEW_AUDITION_TYPE_OPTIONS.ETERNITY_ELEGANCE,
    DETAIL_SERVICE_NEW_AUDITION_TYPE_OPTIONS.MONITE,
  ],
};
