export default {
  getDichVuVT: (axios) => axios.get('/web-quantri/danhmuc-chung/CSS_DICHVU_VT'),
  getLoaiHD: (axios) => axios.post('/web-hopdong/traphieuthicong/ht_loai_hd_combobox_tp'),
  getQuyTrinh: (axios, data) => axios.post('/web-ccdv/dongbo_tb_codinh_lentongdai/sp_ht_quytrinh_gdv_kh', data),
  getLoaiHinhTB: (axios) => axios.get('/web-quantri/danhmuc-chung/CSS_LOAIHINH_TB'),
  getKieuYeuCau: (axios, data) => axios.post('/web-ccdv/ds_yeucau_khaosat/lay_ds_kieu_ld', data),
  LAY_DS_HDTB_GD_KICHHOAT_CD: (axios, data) => axios.post('/web-ccdv/dongbo_tb_codinh_lentongdai/lay_ds_hdtb_gd_kichhoat_cd', data),
  getDsDVGT: (axios, data) => axios.post('/web-thicong/hoinghi_truyenhinh/lay_ds_dangky_dvgt', data),
  getDsHuy: (axios, data) => axios.post('/web-thicong/thanhly-thuebao/sp_lay_ds_lydohuy_hdtb', data),
  dgvThueBao_Selection: (axios, data) => axios.post('/web-ccdv/dongbo_tb_codinh_lentongdai/lay_ds_hdtb_dv_loaidv', data),
  lay_huonggiao_theo_quytrinh: (axios, data) => axios.post('web-thicong/hoinghi_truyenhinh/sp_lay_huonggiao_theo_quytrinh', data),
  lay_luong_thaotac: (axios, data) => axios.post('/web-thicong/hoinghi_truyenhinh/lay_luong_thaotac', data),
  lay_control: (axios, data) => axios.post('/web-thicong/hths-thaydoi-tocdo/sp_lay_dulieu_thaotac_control_theo_thaotac_id', data),
  LAY_DS_SUDUNG_DVGT: (axios, data) => axios.post('/web-ccdv/dongbo_tb_codinh_lentongdai/lay_ds_sudung_dvgt', data),
  SP_DONG_BO_TONGDAI_CD: (axios, data) => axios.post('/web-ccdv/dongbo_tb_codinh_lentongdai/sp_dong_bo_tongdai_cd', data),
  KT_TaoDB_Thang: (axios, data) => axios.post('/web-ccdv/dongbo_tb_codinh_lentongdai/kt_taodb_thang', data),
  KT_DBThang_DaChot: (axios, data) => axios.post('/web-ccdv/dongbo_tb_codinh_lentongdai/kt_dbthang_dachot', data),
  SP_UPDATE_DANGKY_DVGT: (axios, data) => axios.post('/web-ccdv/dongbo_tb_codinh_lentongdai/sp_update_dangky_dvgt', data),
  map_id: (axios, data) => axios.post('/web-tratruoc/thongtin_tratruoc_dn/fn_tt_hd_thuebao', data),

  Lay_DonVi_GiaoPhieu: (axios, data) => axios.post('/web-ccdv/dongbo_tb_codinh_lentongdai/lay_donvi_giaophieu', data),
  CAPNHAT_NGAYHT: (axios, data) => axios.post('/web-ccdv/dongbo_tb_codinh_lentongdai/fn_capnhat_ngayht', data),
  HOANTHANH_HOANCONG: (axios, data) => axios.post('/web-ccdv/dongbo_tb_codinh_lentongdai/hoanthanh_hoancong', data),
  GIAOPHIEU_TD_KHI_HC: (axios, data) => axios.post('/web-ccdv/dongbo_tb_codinh_lentongdai/giaophieu_td_khi_hc', data),
  HOANTHIEN_HS_THAYDOI_DV: (axios, data) => axios.post('/web-ccdv/dongbo_tb_codinh_lentongdai/hoanthien_hs_thaydoi_dv', data),
  GIAOPHIEU_TD_HOST_THUHOI_1: (axios, data) => axios.post('/web-ccdv/dongbo_tb_codinh_lentongdai/giaophieu_td_host_thuhoi_1', data),
  CapNhat_TT_Phieu_HTHS: (axios, data) => axios.post('/web-ccdv/dongbo_tb_codinh_lentongdai/sp_capnhat_tt_phieu_hths', data),
  SP_CAPNHAT_NGAYKH: (axios, data) => axios.post('/web-ccdv/dongbo_tb_codinh_lentongdai/sp_capnhat_ngaykh', data),
  CAPNHAT_NGAYKH_STATUS: (axios, data) => axios.post('/web-ccdv/dongbo_tb_codinh_lentongdai/capnhat_ngaykh_status', data),
  CAPNHAT_TT_PHIEU_HC: (axios, data) => axios.post('/web-ccdv/dongbo_tb_codinh_lentongdai/capnhat_tt_phieu_hc', data),
  HOANTHIEN_HS_CHAMDUT_SD: (axios, data) => axios.post('/web-ccdv/dongbo_tb_codinh_lentongdai/hoanthien_hs_chamdut_sd', data),
}
