export enum COLLABORATING_PARTNER_HOSPITAL_DETAIL_TABS {
  HOSPITAL_INFO = 'HOSPITAL_INFO',
  SETTLEMENT_DETAIL = 'SETTLEMENT_DETAIL',
  SALE_ACTIVITY = 'SALE_ACTIVITY',
  PROMOTE_MATERIAL_DELIVERY = 'PROMOTE_MATERIAL_DELIVERY',
}
