const collumns = {
    collumnsHD: [
        {
            fieldName: "ma_chung",
            headerText: "Mã GD",
            allowFiltering: true,
            width: "150",
            autoFit: "true",
            cellCssClass: 'text-left',
        },
        {
            fieldName: "ngay_yc",
            headerText: "Ngày YC",
            allowFiltering: true,
            width: "100",
            textAlign: 'right',
            autoFit: "true",
            cellCssClass: 'text-left',
        },
        {
            fieldName: "ten_loaihd",
            headerText: "Loại HĐ",
            allowFiltering: true,
            width: "150",
            autoFit: "true",
            cellCssClass: 'text-left',
        },
        {
            fieldName: "ten_dv",
            headerText: "Đơn vị lắp HĐ/PL",
            allowFiltering: true,
            width: "180",
            autoFit: "true",
            cellCssClass: 'text-left',
        },
        {
            fieldName: "ma_tb",
            headerText: "Mã TB",
            allowFiltering: true,
            width: "150",
            autoFit: "true",
            cellCssClass: 'text-left',
        },
        {
            fieldName: "trangthai",
            headerText: "Trạng thái",
            allowFiltering: true,
            width: "150",
            autoFit: "true",
            cellCssClass: 'text-left',
        },
    ],
    collumnsBH: [
        {
            fieldName: "ma_chung",
            headerText: "Mã LT/Acc",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            cellCssClass: 'text-left',
        },
        {
            fieldName: "ngay_yc",
            headerText: "Ngày BH",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            cellCssClass: 'text-left',
        },
        {
            fieldName: "ten_loaihd",
            headerText: "Loại HĐ",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            cellCssClass: 'text-left',
        },
        {
            fieldName: "ten_dv",
            headerText: "Trạm VL",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            cellCssClass: 'text-left',
        },
        {
            fieldName: "ma_tb",
            headerText: "Mã TB",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            cellCssClass: 'text-left',
        },
        {
            fieldName: "trangthai",
            headerText: "Trạng thái",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            cellCssClass: 'text-left',
        },
    ],
    collumnsPhieu: [
        {
            fieldName: "ma_tb",
            headerText: "Số máy/ACC",
            allowSorting: false,
            allowFiltering: true,
            width: "50",
            textAlign: 'center',
            autoFit: "true",
        },
        {
            fieldName: "ten_tb",
            headerText: "Tên thuê bao",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            textAlign: 'left',
        },
        {
            fieldName: "diachi_tb",
            headerText: "Địa chỉ thuê bao",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            textAlign: 'left',
        },
        {
            fieldName: "diachi_ld",
            headerText: "Địa chỉ lắp đặt",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            textAlign: 'left',
        },
        {
            fieldName: "ghichu",
            headerText: "Ghi chú",
            allowFiltering: true,
            width: "100",
            autoFit: "false",
            textAlign: 'left',
        },
    ],
}

export default collumns
