const DS_KHONG_XULY = Object.freeze({
  THUEBAO_KHONGCHE: 0,
  THUEBAO_KHONG_KHOA: 1,
  THUEBAO_KHONG_NHACNO: 2,
  THUEBAO_KHONG_HUY: 3,
  THUEBAO_KHONG_NHANHONG: 5,
  THUEBAO_KHONG_OB_LM: 6,
  THUEBAO_KHONG_OB_BH: 7,
  THONGBAO_SUCO_TTVT: 12,
  THUEBAO_KHONG_SMS_TBC: 15,
  THUEBAO_KHONG_SMS_EMAIL: 16,
  THUEBAO_KHONG_NHACNO_TBC: 17,
  THUEBAO_KHONG_KHOAMAY_TUDONG: 18,
  THUEBAO_KHONG_XNTT_SMS: 20
});
export default DS_KHONG_XULY;
