const HuongGiao = Object.freeze(
  {
    DUYET_TH : 3006, //HoangPKN :
    DUYET_CAP : 3004, //HoangPKN :

    TRAMVT_THUHOICONG : 3000, //HoangPKN :
    HOST_THUHOICONG : 3001,   //HoangPKN :
    TONV_GQKN : 2260,
    CHAMDUT_SD_ADSL : 16,
    TIEPNHAN_YEUCAU_BAOHONG : 90,
    HOANTHIEN_BAOHONG : 100,
    DAIKV_XULY_SUCO_THOAI : 91,
    TRAMVT_XULY_SUCO_THOAI : 101,
    // TIEPNHAN_YEUCAU_BAOHONG : 90,
    DAIKV_XULY_SUCO_INTERNET : 92,
    TRAMVT_XULY_SUCO_INTERNET : 102,
    DAIKV_XULY_MGW : 93,
    DAIKV_XULY_TSL : 94,
    TRAMVT_XULY_MGW : 103,
    TRAMVT_XULY_TSL : 104,
    TIEPNHAN_KHIEUNAI : 2251 //tunghpg
  }
)
export default HuongGiao
