const KHOANMUCTT_NO = Object.freeze(
  {
    CUOC_SUDUNG : 2,
    KHOAN_MUC_KHONGTHUE : 207,
    KHOAN_MUC_GCDADV : 425,
    KHOAN_MUC_DAT_COC_CSD : 521,
    KHOAN_MUC_TT : 98,
    KHOAN_MUC_KM1 : 96,
    KHOAN_MUC_KM2 : 97,
    KHOAN_MUC_KM3 : 411,
    KHOAN_MUC_KMFTTH : 414,
    KHOAN_MUC_TRUY_THU : 196,
    KHOAN_MUC_TAM_UNG : 198,
  }
)
export default KHOANMUCTT_NO
