
const KTRA_MATT = Object.freeze(
  {
    DIACHI_CT: 1,
    MST: 2,
    SDT: 3,
    EMAIL: 4,
    TAO_XLN_TT: 5,
    TAO_XLN_KH: 6,
    THUEBAO_DB_THANG: 7,
    THUEBAO_CHEM: 8,
    THUEBAO_KHONGKHOA: 9,
    TAODS_KHL_KH: 10,
    GAN_KHL_DONVI: 11,
    GAN_KHL_NHANVIEN: 12,
    LAY_DS_NO: 13,
    LAY_DS_NO_TT: 14,
    LAY_DS_NO_VNP: 26,
    GAN_DBTB_KV: 15,
    DAILY_NOP_NH: 16,
    XOA_THUEBAO_DB_THANG: 20,
    XOA_THUEBAO_KHONG_KHOA: 21,
    XOA_THUEBAO_KHONG_MO: 22,
    GAN_PHANLOAI_KH: 23,
    THONGTIN_LIENHE: 24,
    GAN_TRAMHC_TB: 40,
    CAPNHAT_NHATKY_TN: 41,
    CAPNHAT_TTLH_TT: 42,
    CAPNHAT_TEN_TT_FILE: 50
  })
export default KTRA_MATT
