const THUNO_KEY = Object.freeze({
  KEY_SOQUYEN: 'KEY_SOQUYEN',
  KEY_SERI: 'KEY_SERI',
  KEY_SOSERI: 'KEY_SOSERI',
  KEY_KYCUOC_HT: 'KEY_KYCUOC_HT',
  KEY_CHUKY_HT: 'KEY_CHUKY_HT',
  KEY_TONGTIEN: 'KEY_TONGTIEN',
  KEY_TONGPHIEU: 'KEY_TONGPHIEU'
}
)
export default THUNO_KEY
