export const KIEULAPDAT = {
  THAYDOI_TT_THANHTOAN: 18,
  THAYDOI_TT_KHUYENMAI: 312,
  THAYDOI_MUCCUOC_TB: 692,
  THAYDOI_TT_DV_CNTT: 863,
  THAYDOI_TT_DICHVU_KHAC: 17,
  THAYDOI_TT_KHACHHANG: 21,
  THAYDOI_TT_THUEBAO: 75,
  GIAHAN_DV_CNTT: 13131,
  THAYDOI_TT_LIENHE: 586
}

export const DICHVUVIENTHONG = {
    TATCA: -1,
    CO_DINH: 1,
    DI_DONG: 2,
    ADSL: 4,
    DD_TRATRUOC: 5,
    EMAIL: 6,
    METRONET: 7,
    MEGAWAN: 8,
    TSL: 9,
    GPHONE: 10,
    IMS: 11,
    MEGA_EYES: 12,
    HOINGHI_TRUYENHINH: 13,
    ANTOAN_BAOMAT_TT: 14,
    DICHVU_CNTT: 15,
    TRUNGTAM_DULIEU: 16,
    HATANG_VIENTHONG: 19,
    IMS_DOITAC: 21,
    BRCD_DOITAC: 22,
    MGW_DOITAC: 23,
    TSL_DOITAC: 24,
    NOIBO_2DIEM: 25,
    NOIBO_DADIEM: 26
}

export const LOAIHINHTB = {
  MAIL_SMD: 9,
  INTERNET_1260: 10,
  INTERNET_ADSL: 11,
  HOINGHI_TRUYENHINH: 13,
  ANTOAN_BAOMAT_TT: 14,
  DICHVU_CNTT: 15,
  TRUNGTAM_DULIEU: 16,
  HTVC_FIBERVNN_ANALOG: 18,
  HTVC_FIBERVNN_DIGITAL: 19,
  DIDONGTRATRUOC: 21,
  INTERNET_FTTH: 58,
  INTERNET_MYTV: 61,
  WIFI_FIBER: 79,
  IMS_POTS: 62,
  IMS_SIP: 63,
  INTERNET_MYTV_B2B: 171,
  DIDONGTRASAU: 20
}

export const HINHTHUCTHANHTOAN ={
  THU_TAI_QUAY: 1,
  THU_TAI_NHA: 2,
  UYNHIEM_THU: 3,
  UYNHIEM_CHI: 4,
  GACHNO_POS: 133
}


