export default {
  ds_quyen_nd: async (axios, data) => axios.get(`/web-qlvt/api/tra-cuu-ton-kho-user/ds-quyen-nd/${data.nguoidung_id}`),
  ds_tham_so_mac_dinh: async (axios, data) => axios.post(`/web-qlvt/api/test-port-v2/tham-so-mac-dinh`, data),
  tham_so_mac_dinh: (axios, data) => axios.get(`/web-qlvt/api/tiep-nhan-thiet-bi-bao-hanh/tham-so-mac-dinh/${data.kieu_id}`),
  sp_lay_ds_makhotd: async (axios, data) => axios.get(`/web-hopdong/nhap_xuat_vt/sp_lay_ds_makhotd`, data),
  ds_loai_kho_td: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-loai-kho-td/${data.mucdich_id}`, data),
  danh_sach_vat_tu_ccdc_chat_luong: async (axios, data) => axios.get(`/web-qlvt/api/danh-sach-vat-tu-ccdc/chat-luong`, data),
  danh_muc_loai_chung_tu: async (axios, data) => axios.get(`/web-qlvt/api/chon-chung-tu-ccdc/danh-muc-loai-chung-tu`),
  ds_kho_nhap_xuat: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-kho-nhap-xuat/${data.nhanvien_id}`),
  ds_muc_dich_nhap_xuat: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-muc-dich-nhap-xuat/${data.nhommd_id}`),
  ds_cong_trinh: async (axios, data) => axios.post(`/web-qlvt/api/dang-ky-cap-phat/ds-cong-trinh`, data),
  tinh_trang_thiet_bi: async (axios, data) => axios.get(`/web-qlvt/api/cap-phat-ccdc/tinh-trang-thiet-bi`),
  chat_luong: async (axios, data) => axios.get(`/web-qlvt/api/danh-sach-vat-tu-ccdc/chat-luong`),
  ds_nghiep_vu: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-nghiep-vu`, data),
  ds_don_vi_su_dung: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-don-vi-su-dung/${data.kieu}`),
  kho_vat_tu_le: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-vt/kho-vat-tu-le?nhan-vien-id=${data.nhanvien_id}&don-vi-id=${data.donvi_id}`),
  lay_ds_kieu_phieu: async (axios, data) => axios.get(`/web-qlvt/api/tra-cuu-chung-tu/lay-ds-kieu-phieu/${data.loaict_id}`),
  ds_tinh: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-tinh`, data),
  ds_chung_tu_theo_loai: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-chung-tu-theo-loai`, data),
  lay_ds_vattu_chungtu: async (axios, data) => axios.get(`/web-qlvt/api/tra-cuu-chung-tu/lay-ds-vattu-chungtu/${data.chungtu_id}`),
  ds_vat_tu_chung_tu_hcm: async (axios, data) => axios.get(`/web-qlvt/api/chung-tu-thue-bao/ds-vat-tu-chung-tu-hcm?chung-tu-id=${data.chungtu_id}`),
  ds_ma_muc_dich_theo_muc_dich: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-ma-muc-dich-theo-muc-dich/${data.mucdich_id}`),
  ds_vattu_chung_tu_serial: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-vattu-chung-tu-serial/${data.chungtu_id}`),
  lay_ds_thietbi_chungtu: async (axios, data) => axios.get(`/web-qlvt/api/tra-cuu-chung-tu/lay-ds-thietbi-chungtu/${data.chungtu_id}`),
  ds_ten_tat_theo_muc_dich: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-ten-tat-theo-muc-dich/${data.mucdich_id}`),
  ds_vat_tu_nhap_xuat: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-vat-tu-nhap-xuat/${data.chungtu_id}`),
  cap_nhat_chung_tu_nhap: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/cap-nhat-chung-tu-nhap`, data),
  cap_nhat_chung_tu_v2: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/cap-nhat-chung-tu-v2`, data),
  thong_tin_ngay_don_hang: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/thong-tin-ngay-don-hang/${data.chungtu_id}`),
  thong_tin_ngay_chung_tu: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/thong-tin-ngay-chung-tu/${data.chungtu_id}`),
  loai_chung_tu_theo_muc_dich: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/loai-chung-tu-theo-muc-dich/${data.mucdich_id}`),
  ds_vat_tu_chung_tu_v1: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-vat-tu-chung-tu-v1/${data.chungtu_id}`),
  kiem_tra_chung_tu_cha: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-chung-tu-cha/${data.chungtu_id}`),
  ds_kieu_chung_tu: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-kieu-chung-tu/${data.chungtu_id}`),
  ds_van_ban_ct: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-van-ban-ct/${data.chungtu_id}`),
  kiem_tra_chi_tiet_vat_tu: async (axios, data) => axios.get(`/web-qlvt/api/gan-seri/kiem-tra-chi-tiet-vat-tu?chungtu-id=${data.chungtu_id}`),
  cap_nhat_dang_ky: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/cap-nhat-dang-ky?chung-tu-id=${data.chungtu_id}&dang-ky-id=${data.dangky_id}`),
  cap_nhat_vat_tu_dang_ky: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/cap-nhat-vat-tu-dang-ky`, data),
  trang_thai_phieu_tu_chung_tu_id: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-vt/trang-thai-phieu-tu-chung-tu-id?chung-tu-id=${data.chungtu_id}`),
  kiem_tra_xoa_phieu_hoan_thanh: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-xoa-phieu-hoan-thanh/${data.chungtu_id}`),
  xoa_phieu_da_hoan_thanh: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/xoa-phieu-da-hoan-thanh`, data),
  xoa_tat_ca_chi_tiet_chung_tu: async (axios, data) => axios.post(`/web-qlvt/api/duyet-dang-ky-cap-phat/xoa-tat-ca-chi-tiet-chung-tu?chung-tu-id=${data.chungtu_id}`),
  xoa_thong_tin_ct: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/xoa-thong-tin-ct/${data.chungtu_id}`),
  giao_phieu_hoan_tra: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/giao-phieu-hoan-tra`, data),
  get_key: async (axios, data) => axios.post(`/web-qlvt/api/cap-phat-ccdc/get-key`, data),
  sinh_so_phieu_vt_v5: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/sinh-so-phieu-vt-v5`, data),
  kiem_tra_ct_dieu_chinh: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-ct-dieu-chinh`, data),
  ds_chung_tu_cha_theo_chung_tu: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-chung-tu-cha-theo-chung-tu/${data.chungtu_id}`),
  ds_chung_tu_theo_so_phieu: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-chung-tu-theo-so-phieu?soPhieu=${data.so_phieu}`),
  cap_nhat_ct_theo_kieu: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/cap-nhat-ct-theo-kieu`, data),
  xoa_chung_tu_bao_hanh: async (axios, data) => axios.post(`/web-qlvt/api/duyet-dang-ky-cap-phat/xoa-chung-tu-bao-hanh`, data),
  send_sms_chung_tu: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/send-sms-chung-tu`, data),
  kiem_tra_xac_nhan_ct: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-xac-nhan-ct`, data),
  ngay_gui_tt: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/ngay-gui-tt/${data.chungtu_id}`),
  kiem_tra_han_chung_tu: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-han-chung-tu`, data),
  kiem_tra_han_chung_tu_v2: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-han-chung-tu-v2`, data),
  kiem_tra_chi_tiet_vt: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-chi-tiet-vt`, data),
  ds_phieu_kt_theo_ct: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-phieu-kt-theo-ct/${data.chungtu_id}`),
  cap_nhat_ngay_nhan_ct: async (axios, data) => axios.put(`/web-qlvt/api/nhap-xuat-chuyen-vt/cap-nhat-ngay-nhan-ct`, data),
  kiem_tra_quyen_xn: async (axios, data) => axios.get(`/web-qlvt/api/duyet-dang-ky-cap-phat/kiem-tra-quyen-xn/${data.nhanvien_id}/${data.kho_id}`),
  kiem_tra_sua_thu_hoi: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-sua-thu-hoi/${data.chungtu_id}`),
  kiem_tra_cap_nhat_chung_tu: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-cap-nhat-chung-tu/${data.chungtu_id}`),
  kiem_tra_thay_doi: async (axios, data) => axios.get(`/web-qlvt/api/duyet-dang-ky-cap-phat/kiem-tra-thay-doi/${data.chungtu_id}`),
  kiem_tra_thay_doi_ctct: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-thay-doi-ctct/${data.chungtu_id}/${data.them_moi}`),
  ds_chung_tu_theo_so_phieu_gop: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-chung-tu-theo-so-phieu-gop?soPhieuGop=${data.so_phieu_gop}`),
  ds_chung_tu_theo_chung_tu_cha: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-chung-tu-theo-chung-tu-cha/${data.chungtucha_id}`),
  ds_nhom_nd_theo_ma: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-nhom-nd-theo-ma?maNd=${data.ma_nd}`),
  kiem_tra_kho_den_ton_kho: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-kho-den-ton-kho/${data.kho_id}`),
  lay_ds_ton_kho: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/lay-ds-ton-kho/${data.kho_id}`),
  so_phieu_theo_chung_tu_id: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-vt/so-phieu-theo-chung-tu-id?chung-tu-id=${data.chungtu_id}`),
  kiem_tra_xoa_chung_tu: async (axios, data) => axios.get(`/web-qlvt/api/duyet-dang-ky-cap-phat/kiem-tra-xoa-chung-tu/${data.chungtu_id}/${data.ma_nd}`),
  kiem_tra_ct_xuat_nhap_hoan_tra: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-ct-xuat-nhap-hoan-tra?soPhieuGop=${data.so_phieu_gop}`),
  kiem_tra_ct_xuat_hoan_tra_theo_ct_cha: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-ct-xuat-hoan-tra-theo-ct-cha/${data.chungtucha_id}`),
  kiem_tra_xoa_dong_bo: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-xoa-dong-bo`, data),
  kiem_tra_xoa_ims: async (axios, chungTuId) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-xoa-ims/${chungtu_id}`),
  kiem_tra_loai_ma_kho: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-loai-ma-kho`, data),
  ds_prefix_lo_hang: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-prefix-lo-hang/${data.lo_hang}`),
  ds_hop_dong_mua_sam: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-hop-dong-mua-sam`),
  ds_du_an: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-du-an/${data.chkDuAn}`),
  cap_nhat_loai_kho_td: async (axios, data) => axios.put(`/web-qlvt/api/nhap-xuat-chuyen-vt/cap-nhat-loai-kho-td?loaiKhoTdId=${data.loaikhotd_id}&ctctId=${data.ctct_id}`),
  cap_nhat_kho_td: async (axios, data) => axios.put(`/web-qlvt/api/nhap-xuat-chuyen-vt/cap-nhat-kho-td?khoTdId=${data.khotd_id}&ctctId=${data.ctct_id}`),
  ds_so_phieu_theo_ct_cha: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-so-phieu-theo-ct-cha/${data.chungtu_id}`),
  kiem_tra_hoan_thien_chung_tu: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-vt/kiem-tra-hoan-thien-chung-tu?chung-tu-id=${data.chungtu_id}`),
  kiem_tra_hoan_thien_chung_tu_v1: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-vt/kiem-tra-hoan-thien-chung-tu-v1?chung-tu-id=${data.chungtu_id}`),
  hoan_thien_ct_hcm: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/hoan-thien-ct-hcm`, data),
  ds_ngay_nhan_thanhtoan_chungtu: async (axios, data) => axios.get(`/web-qlvt/api/duyet-dang-ky-cap-phat/ds-ngay-nhan-thanhtoan-chungtu/${data.chungtu_id}`),
  kiem_tra_chi_tiet_qlts: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-chi-tiet-qlts/${data.chungtu_id}`),
  kiem_tra_xuat_hoan_tra: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-xuat-hoan-tra/${data.chungTuId}`),
  kiem_tra_trang_thai_ims: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-trang-thai-ims`, data),
  deleteFile: async (axios, data) => axios.post(`/web-qlvt/api/storage/deleteFile`, data),
  cap_nhat_bbbg_ims: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/cap-nhat-bbbg-ims`, data),
  xoa_chung_tu_gop_ham: async (axios, data) => axios.post(`/web-qlvt/api/xoa-chung-tu/xoa`, data),
  xoa_phieu_de_nghi: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/xoa-phieu-de-nghi`, data),
  xu_ly_cap_nhat_ngay_ky: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/xu-ly-cap-nhat-ngay-ky?chungTuId=${data.chungtu_id}&ngayKy=${data.ngay_ky}`),
  cap_nhat_de_nghi_ct: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/cap-nhat-de-nghi-ct`, data),
  trang_thai_phieu_v2: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/trang-thai-phieu-v2/${data.chungtu_id}`),
  cap_nhat_so_phieu_in: async (axios, data) => axios.put(`/web-qlvt/api/nhap-xuat-chuyen-vt/cap-nhat-so-phieu-in?chungTuId=${data.chungtu_id}&soPhieuIn=${data.so_phieu_in}`),
  cap_nhat_ngay_chuyen: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/cap-nhat-ngay-chuyen?chungTuId=${data.chungtu_id}&ngayChuyen=${ngay_chuyen}`),
  xu_ly_cap_nhat_ngay_chung_tu: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/xu-ly-cap-nhat-ngay-chung-tu?chungTuId=${data.chungtu_id}&ngayCt=${data.ngay_ct}`),
  ds_loai_kho_theo_kho: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-loai-kho-theo-kho/${data.kho_id}`),
  huong_giao_tiep_theo_id: async (axios, data) => axios.get(`/web-qlvt/api/nhap-de-nghi-vt/huong-giao-tiep-theo-id/${data.huonggiao_id}`),
  ds_cong_trinh_theo_chung_tu: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-cong-trinh-theo-chung-tu/${data.chungtu_id}`),
  sinh_dieu_chuyen_qlt: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/sinh-dieu-chuyen-qlts`, data),
  kiem_tra_loc_csht: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-loc-csht`, data),
  kiem_tra_ton_kho_den_kho: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-ton-kho-den-kho/${data.kho_id}/${data.kieu}`),
  kiem_tra_chung_tu_dong_bo: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-chung-tu-dong-bo/${data.chungtu_id}`),
  kiem_tra_dong_bo_ims: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-dong-bo-ims/${data.chungtu_id}`),
  xu_ly_dong_bo_ims: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/xu-ly-dong-bo-ims`, data),
  xoa_chi_tiet_chung_tu: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/xoa-chi-tiet-chung-tu?ctct-id=${data.ctct_id}`),
  cap_nhat_so_lan_in_ct: async (axios, data) => axios.put(`/web-qlvt/api/nhap-xuat-chuyen-vt/cap-nhat-so-lan-in-ct?chungTuId=${data.chungtu_id}&maNd=${data.ma_nd}`),
  bao_cao_nhap_kho: async (axios, data) => axios.post(`/web-qlvt/api/bao-cao/bao-cao-nhap-kho?extend=pdf`, data),
  copy_chung_tu_v2: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-vt/copy-chung-tu-v2?chung-tu-id=${data.chungtu_id}&kieu=${data.kieu}`),
  kiem_tra_vt_doc_file: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-vt-doc-file`, data),
  kiem_tra_don_gia_ims: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-don-gia-ims`, data),
  ds_vat_tu_ton_kho: async (axios, data) => axios.post(`/web-qlvt/api/duyet-dang-ky-cap-phat/ds-vat-tu-ton-kho`, data),
  cap_nhat_so_lan_in: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/cap-nhat-so-lan-in?chungTuId=${data.chungtu_id}`),
  lay_ds_serial_null_ims: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/lay-ds-serial-null-ims`, data),
  // getThongTinNgayNhanCT: (axios, data) => axios.get(`/web-qlvt/api/duyet-dang-ky-cap-phat/ds-ngay-nhan-thanhtoan-chungtu/${data.chungTuId}`),
  noi_dung_giao_ct: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/noi-dung-giao-ct/${data.chungTuId}`),
  kiem_tra_sua_thu_hoi: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-sua-thu-hoi/${data.chungtu_id}`),
  cap_nhat_serial_v2: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/cap-nhat-serial`, data),
  xoa_tat_ca_chung_tu_thiet_bi: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-vt/xoa-tat-ca-chung-tu-thiet-bi?chung-tu-id=${data.chungtu_id}`),
  lay_ds_serial_null_ims: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/lay-ds-serial-null-ims`, data),
  cap_nhat_thong_tin_ctct: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-vt/cap-nhat-thong-tin-ctct`, data),
  sinh_qr_code: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/sinh-qr-code`, data),
  kiem_tra_huy_gan_ma_duan: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-huy-gan-ma-duan/?soHieuCt=${data.soHieuCt}`),
  xoa_thong_tin_du_an: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-vt/xoa-thong-tin-du-an`, data),
  cap_nhat_serial_ims: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/cap-nhat-serial-ims`, data),
  fn_kiemtra_xuathoantra: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/fn_kiemtra_xuathoantra`, data),
  sinh_ct_qlts: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/sinh-ct-qlts`, data),
  sinh_ct_ims_bbg: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/sinh-ct-ims-bbg`, data),
  ma_co_so_ha_tang: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/ma-co-so-ha-tang/${data.kho_id}`),
  contract_info_by_project_code: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/contract-info-by-project-code?maDuan=${data.maDuan}&maCsht=${data.maCsht}`),
  ds_assset_by_project: async (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-assset-by-project?maDuan=${data.ma_duan}`),
  ds_vat_tu_theo_nvu: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-vat-tu-theo-nvu`, data),
  kiem_tra_ton_kho: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-vt/kiem-tra-ton-kho`, data),
  update_asset_scan_info: async (axios, data) => axios.post(`/tichhop/qlts/update_asset_scan_info`, data),
  uploadFile: async (axios, data) => axios.post(`/web-qlvt/api/storage/uploadFile`, data),
  cap_nhat_ct_van_ban: async (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/cap-nhat-ct-van-ban`, data),
  checkFileExist: async (axios, data) => axios.post(`/web-qlvt/api/storage/checkExistsFile`, data),
  deleteFile: async (axios, data) => axios.post(`/web-qlvt/api/storage/deleteFile`, data),
  downloadFile: async (axios, linkFile) => axios.get(`/web-qlvt/api/storage/downloadFile?fileSource=${linkFile}`),
  cap_nhat_chung_tu_vb: (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/cap-nhat-chung-tu-vb`,data),
  xoa_chung_tu_theo_ctct_va_tbi_id: (axios, data) => axios.delete(`/web-qlvt/api/nhap-xuat-vt/xoa-chung-tu-theo-ctct-va-tbi-id?ctct-id=${data.ctct_id}&thiet-bi-id=${data.thietbi_id}`),
  xoa_thiet_bi_chi_tiet: (axios, data) => axios.delete(`/web-qlvt/api/nhap-xuat-chuyen-vt/xoa-thiet-bi-chi-tiet/${data.thietbi_id}`),
  cap_nhat_so_luong_chi_tiet_vat_tu: (axios, data) => axios.post(`/web-qlvt/api/gan-seri/cap-nhat-so-luong-chi-tiet-vat-tu`,data),
  cap_nhat_ghi_chu_chung_tu_thiet_bi: (axios, data) => axios.put(`/web-qlvt/api/nhap-xuat-vt/cap-nhat-ghi-chu-chung-tu-thiet-bi`,data),
  kiem_tra_ton_tai_serial: (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/kiem-tra-ton-tai-serial?serial=${data.serial}`),
  kiem_tra_serial_dang_cap: (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-vt/kiem-tra-serial-dang-cap?serial=${data.serial}`),
  getPresignedUrl: (axios, data) => axios.post(`/web-qlvt/api/storage/getPresignedUrl`, data),
  cap_nhat_chung_tu_thiet_bi_v2: (axios, data) => axios.post(`/web-qlvt/api/nhap-xuat-chuyen-vt/cap-nhat-chung-tu-thiet-bi-v2`,data),
  kiem_tra_lo_hang_serial: (axios, data) => axios.get(`/web-qlvt/api/nhap-xuat-vt/kiem-tra-lo-hang-serial?serial=${data.serial}&chung-tu-id=${data.chungtu_id}`),
  ds_phieu_nv: (axios, mucDichId) => axios.get(`/web-qlvt/api/nhap-xuat-chuyen-vt/ds-phieu-nv/${mucdich_id}`),
  report_run: async (axios, request) => axios.post('/web-report/report/bi/run', request),
  get_report_params: async (axios, data) => axios.get(`/web-report/report/bi/parameters?report=${data.path}`),
  //myapi
  sp_lay_ds_makhotd: async (axios, data) => axios.get(`/web-qlvt/api/nhapxuatvt_v2/sp_lay_ds_makhotd`, data),
  fn_kiemtra_ngaygui_tt: async (axios, data) => axios.post(`/web-qlvt/api/nhapxuatvt_v2/fn_kiemtra_ngaygui_tt`, data),
  sp_capnhat_ngaytt_theokieu: async (axios, data) => axios.post(`/web-qlvt/api/nhapxuatvt_v2/sp_capnhat_ngaytt_theokieu`, data),
  sp_lay_phieu_kt_id: async (axios, data) => axios.post(`/web-qlvt/api/nhapxuatvt_v2/sp_lay_phieu_kt_id`, data),
  sp_chitiet_nhieu: async (axios, data) => axios.post(`/web-qlvt/api/nhapxuatvt_v2/sp_chitiet_nhieu`, data),
  fn_kiemtra_loaidv_kho: async (axios, data) => axios.post(`/web-qlvt/api/nhapxuatvt_v2/fn_kiemtra_loaidv_kho`, data),
  fn_kt_thaotac_chungtu_psis: async (axios, data) => axios.post(`/web-qlvt/api/nhapxuatvt_v2/fn_kt_thaotac_chungtu_psis`, data),
  sp_lay_quyen_xn: async (axios, data) => axios.post(`/web-qlvt/api/nhapxuatvt_v2/sp_lay_quyen_xn`, data),
  fn_capnhat_chungtu: async (axios, data) => axios.post(`/web-qlvt/api/nhapxuatvt_v2/fn_capnhat_chungtu`, data),
  ktdb_fmis_taikhoan: async (axios, data) => axios.post(`/web-qlvt/api/nhapxuatvt_v2/ktdb_fmis_taikhoan`, data),
  xoa_thietbi_nhapxuatv2: async (axios, data) => axios.post(`/web-qlvt/api/nhapxuatvt_v2/xoa_thietbi_nhapxuatv2`, data),
  capnhat_quetserial: async (axios, data) => axios.post(`/web-qlvt/api/nhapxuatvt_v2/capnhat_quetserial`, data),
  capnhat_gridviewthietbi: async (axios, data) => axios.post(`/web-qlvt/api/nhapxuatvt_v2/capnhat_gridviewthietbi`, data),
  fn_update_tien_ngoaite: async (axios, data) => axios.post(`/web-qlvt/api/nhapxuatvt_v2/fn_update_tien_ngoaite`, data),
  sp_lay_baocao_qlvt_bip: async (axios, data) => axios.post(`/web-qlvt/api/nhapxuatvt_v2/sp_lay_baocao_qlvt_bip`, data),
  xoa_het_chitiet_nhapxuatv2: async (axios, data) => axios.post(`/web-qlvt/api/nhapxuatvt_v2/xoa_het_chitiet_nhapxuatv2`, data),
  //hconganh api
  ds_tbi_giao_nhan_ct: (axios, data) => axios.post(`/web-qlvt/api/nhap-tbi-bao-hanh/ds-tbi-giao-nhan-ct`, data),
  capnhat_ngay_gui: async (axios, data) => axios.post(`/web-qlvt/api/nhapxuatvt_v2/capnhat_ngay_gui`, data),
  capnhat_ngay_nhan: async (axios, data) => axios.post(`/web-qlvt/api/nhapxuatvt_v2/capnhat_ngay_nhan`, data),
  xoa_chungtu_nhapxuatv2: async (axios, data) => axios.post(`/web-qlvt/api/nhapxuatvt_v2/xoa_chungtu_nhapxuatv2`, data),
  fn_sinh_ma_denghi: async (axios, data) => axios.post(`/web-qlvt/api/nhapxuatvt_v2/fn_sinh_ma_denghi`, data),
  lay_quytrinh_huonggiao_theo_denghi_id: async (axios, data) => axios.get(`/web-tracuu/tracuu-thuebao/lay_quytrinh_huonggiao_theo_denghi_id?denghi_id=${data.denghi_id}`, data),
  sp_lay_huonggiao_tieptheo: async (axios, data) => axios.get(`/web-tracuu/tracuu-thuebao/sp_lay_huonggiao_tieptheo?huonggiao_id=${data.huonggiao_id}`, data),
  hoanthien_chungtu_frmnhapxuatv2: async (axios, data) => axios.post(`/web-qlvt/api/nhapxuatvt_v2/hoanthien_chungtu_frmnhapxuatv2`, data),
  xacnhan_tt_xuat_ims: async (axios, data) => axios.post(`/web-qlvt/api/nhapxuatvt_v2/xacnhan_tt_xuat_ims`, data)
}
