import axios from 'axios'
export default {
  getList: (axios) => axios.get('/web-quantri/danhmuc-chung/CSS_LINHVUC'),
  create: (name) => axios.get(`/web-quantri/danhmuc-chung/CSS_LINHVUC_NHAP?linhVucId=0&linhVuc=${name}`),
  update: (id, name) => axios.get(`/web-quantri/danhmuc-chung/CSS_LINHVUC_NHAP?linhVucId=${id}&linhVuc=${name}`),
  delete: (data) => axios.post(`/web-quantri/khuyenmai/sp_khuyenmai_delete`, data),
  getListTelecomService: () => axios.get(`web-thicong/danhmuc/lay_danhsach_dichvu_vienthong`),
  getListPromotionType: () => axios.get(`web-quantri/danhmuc-chung/CSS_KIEU_KM`),
  getListParticipationPromotion: (data) => axios.post(`web-quantri/khuyenmai/lay_ds_thamso_md`, data),
  getListAccompanyingPromotion: (data) => axios.post('web-quantri/khuyenmai/lay_ds_thamso_md', data),
  getListContractType: (data) => axios.get(`web-thicong/danhmuc/lay_ds_loai_hd?loaiHdId=${data}`),
  getListPromotion: (data) => axios.post(`web-quantri/khuyenmai/sp_khuyenmai_layds_dvvt_cvan`, data),
  getDataContractType: (data) => axios.post(`web-quantri/khuyenmai/sp_khuyenmai_layds_kieuld`, data),
  getListSoCongVan_TimKiem: (data) => axios.post(`web-quantri/khuyenmai/sp_bangts_layds_socongvan_cokm`, data),
  getDanhSachTrangBi: (data) => axios.post(`web-quantri/khuyenmai/sp_khuyenmai_layds_trangbi`, data),
  getChiTietKhuyenMai: (data) => axios.post(`web-quantri/khuyenmai/lay_ds_chitiet_km`, data),
  getDanhSachDoiTuongTB: (data) => axios.post(`web-quantri/khuyenmai/sp_khuyenmai_layds_doituongtb`, data),
  khuyenmaiInsertOUupdate: (data) => axios.post(`web-quantri/khuyenmai/sp_khuyenmai_insert_or_update`, data),
  getDanhSachGoiThamGia: (data) => axios.post(`web-quantri/khuyenmai/sp_khuyenmai_layds_goi_dadv`, data),
  getDanhSachDichVuKem: (data) => axios.post(`web-quantri/khuyenmai/sp_khuyenmai_layds_dichvukem`, data),
  getDanhSachTocDoTheoTB: (data) => axios.post(`web-quantri/khuyenmai/lay_ds_td_km`, data),
  getDanhSachKhuVuc: (data) => axios.post(`web-quantri/khuyenmai/sp_khuyenmai_layds_khuvuc`, data),
  getDanhSachMaGhep: (data) => axios.post(`web-hopdong/laydulieu/sp_tt_ma_ghep`, data),
  xuatCTKM: (data) => axios.post(`web-quantri/khuyenmai/lay_ctkm_theo_congvan`, data),
  copyKhuyenMai: (data) => axios.post(`web-quantri/khuyenmai/copy_khuyenmai`, data),
  //  api  mở popup chi tiết KM
  getNhomKM: (data) => axios.post(`web-hopdong/laydulieu/sp_tt_thamso_md`, data),
  getNguonKM: (data) => axios.post(`web-quantri/khuyenmai/sp_khuyenmai_ctiet_layds_nguonkm`, data),
  getDanhSachChiTiet: (data) => axios.post(`web-hopdong/laydulieu/sp_tt_ct_khuyenmai`, data),
  //getDanhSachChiTiet: (data) => axios.post(`/web-quantri/khuyenmai/lay_ds_chitiet_km`, data),
  getDanhSachNhomDatCoc: (data) => axios.post(`web-quantri/lay-dulieu/sp_tt_nhom_datcoc`, data),
  getDanhSachNhomTB: (data) => axios.get(`/web-quantri/danhmuc-chung/CSS_NHOM_TBI`),
  getDanhSachLoaiHinhTB: (data) => axios.post(`/web-quantri/khuyenmai/lay_ds_td_km`, data),
  getDanhSachToaNha: (data) => axios.post(`/web-ccdv/hopdong/sp_lay_ds_toanha_theo_ctkm`, data),
  getDanhSachGoiThamGiaChiTiet: (data) => axios.post(`/web-quantri/khuyenmai/sp_khuyenmai_ctiet_layds_goi_dadv`, data),
  getDanhSachTraGopThietBi: (data) => axios.post(`/web-quantri/khuyenmai/sp_khuyenmai_ctiet_layds_tragoptbi`, data),
  getDanhSachKMTB: (data) => axios.post(`web-quantri/khuyenmai/sp_khuyenmai_ctiet_layds_km_loai_tbi`, data),
  getDanhSachDichVuGT: (data) => axios.post(`web-quantri/khuyenmai/sp_khuyenmai_ctiet_layds_dvgt`, data),
  insertOrUpdateDetail: (data) => axios.post(`web-quantri/khuyenmai/sp_khuyenmai_ctiet_insert_or_update`, data),
  insertOrUpdateDetail_v2: (data) => axios.post(`web-quantri/khuyenmai/sp_khuyenmai_ctiet_insert_or_update_v2`, data),
  getNgayHieuLuc: (data) => axios.post(`/web-hopdong/laydulieu/sp_tt_km_ngayhl`, data),
  insertDate: (data) => axios.post(`web-quantri/khuyenmai/sp_khuyenmai_ngayhl_insert`, data),
  deleteDate: (data) => axios.post(`web-quantri/khuyenmai/sp_khuyenmai_ngayhl_delete`, data),
  getDanhSachNguonDaGan: (data) => axios.post(`/web-hopdong/laydulieu/sp_tt_ctkm_nguon_kmld`, data),
  copyChiTietKhuyenMai: (data) => axios.post(`web-quantri/khuyenmai/copy_ct_khuyenmai`, data),
  deleteChiTietKhuyenMai: (data) => axios.post(`web-quantri/khuyenmai/sp_khuyenmai_ctiet_delete`, data),
  //getQuotaByIDDetailPromotion: (data) => axios.post(`web-quantri/khuyenmai/lay_ds_thamso_md`, data),
  updateQuotaByIDDetailPromotion: (data) => axios.post(`web-quantri/khuyenmai/khuyenmai_ctiet_update_dinhmuc`, data),
  deleteQuotaByIDDetailPromotion: (data) => axios.post(`web-quantri/khuyenmai/khuyenmai_ctiet_dinhmuc_delete`, data),
  lay_ds_lhtb_km: async (axios, data,header) => axios.post(`web-quantri/khuyenmai/lay_ds_lhtb_km`, data, header),
  sp_tt_socongvan: (data) => axios.post(`/web-hopdong/laydulieu/sp_tt_socongvan`, data),
  sp_tt_khuyenmai: (data) => axios.post(`/web-hopdong/laydulieu/sp_tt_khuyenmai`, data),
  sp_tt_ctkm_dinhmuc: (data) => axios.post(`/web-hopdong/laydulieu/sp_tt_ctkm_dinhmuc`, data),
  sp_tt_dongia_tps: (data) => axios.post(`/web-hopdong/laydulieu/sp_tt_dongia_tps`, data),
  getDanhSachLoainha: (data) => axios.post(`/web-thicong/capnhatthongtin/sp_khuyenmai_layds_loainha`, data),
  sp_khuyenmai_ctiet_layds_trangbi: (data) => axios.post(`/web-quantri/khuyenmai/sp_khuyenmai_ctiet_layds_trangbi`, data),
  sp_khuyenmai_ctiet_layds_khuyenmai: (data) => axios.post(`/web-thicong/capnhatthongtin/sp_khuyenmai_ctiet_layds_khuyenmai`, data),
  sp_khuyenmai_ctiet_layds_loainha: (data) => axios.post(`/web-thicong/capnhatthongtin/sp_khuyenmai_ctiet_layds_loainha`, data),
} 