
function newThongSoThueBao(){
    return {
        tocdo_id: 0,
        tocdothuc_id: 0,
        tocdo_pir_id: 0,
        tocdo_nix: 0,
        tocdo_isp: 0,

        chuquan_id: 0,
        chuquanld_id: 0,
        congnghe_id: 0,
        muccuoc_id: 0,
        kieutra_id: 0,
        doituong_id: 0,
        muccuoctb_id: 0,
        trangbi_id: 0,
        kieuld_id: 0,
        thietbidc_id: 0,
        loaimd_id: 0,
        loaikenh_id: 0,
        thietbidc_id_cuoi: 0,
        thoihan_id: 0,
        ma_tn: '',
        ma_doicap: '',

        chuquanld_id_cuoi: 0,
        phanloai_id: 0,
        phantach_id: 0,

        mhkn_id: 0,
        gdkn_id: 0,
        yc_baove: 0,
        tocdo_pop: 0,
        gdkn_pop_id: 0,
        gdkn_kh_id: 0,
        cauhinh_dt_id: 0,
        kieu_duplex_id: 0,
        kieukn_id: 0,

        mtu_size: '',
        auto_nego: '',
        sncp: '',
        cap_chinh: '', 
        cap_duphong: '',
        diem_pop: '',
        wan_ip: '',
        lan_ip: '',
        ce_ip: '',
        tt_ip: '',
        sl_ip: '',
        ten_trunk_nni: '', 
        so_as: '',
        hqos: '',
        cos: '',
        svlan: '', 
        cvlan: '',
        vlan_transparent: '',
        tt_port: '',

        loai_ip:null,
        kieu_nghiemthu:null,

        nhomloaikenh_id: '',
        hatang_vnpt: ''
                // public DataTable loai_ip: 
        // public DataTable kieu_nghiemthu: 

        // public ITEM_TYPE[] thongso_cntt: 
    }
}
function createObjectHDKH(object){
    return {
        PHANVUNG_ID:object.hasOwnProperty('PHANVUNG_ID')?object.PHANVUNG_ID:null, 
        HDKH_ID:0,
        MA_GD:object.hasOwnProperty('MA_GD')?object.MA_GD:null,
        MA_HD:object.hasOwnProperty('MA_HD')?object.MA_HD:null,
        MA_KH:object.hasOwnProperty('MA_KH')?object.MA_KH:null,
        KHACHHANG_ID:object.hasOwnProperty('KHACHHANG_ID')?object.KHACHHANG_ID:null,
        TEN_KH:object.hasOwnProperty('TEN_KH')?object.TEN_KH:null,
        DIACHI_KH:object.hasOwnProperty('DIACHI_KH')?object.DIACHI_KH:null,
        NGUOI_DD:object.hasOwnProperty('NGUOI_DD')?object.NGUOI_DD:null,
        CHUCDANH_DD:object.hasOwnProperty('CHUCDANH_DD')?object.CHUCDANH_DD:null,
        SO_DT:object.hasOwnProperty('SO_DT')?object.SO_DT:null,
        SO_FAX:object.hasOwnProperty('SO_FAX')?object.SO_FAX:null,
        WEBSITE:object.hasOwnProperty('WEBSITE')?object.WEBSITE:null,
        NGAY_SN:object.hasOwnProperty('MA_GD')?object.NGAY_SN:null,
        NGAYLAP_HD:object.hasOwnProperty('NGAYLAP_HD')?object.NGAYLAP_HD:null,
        SO_GT:object.hasOwnProperty('SO_GT')?object.SO_GT:null,
        NGAYCAP:object.hasOwnProperty('NGAYCAP')?object.NGAYCAP:null,
        NOICAP:object.hasOwnProperty('NOICAP')?object.NOICAP:null,
        GHICHU:object.hasOwnProperty('GHICHU')?object.GHICHU:null,
        DONVI_ID:object.hasOwnProperty('DONVI_ID')?object.DONVI_ID:null,
        LOAIGT_ID:object.hasOwnProperty('LOAIGT_ID')?object.LOAIGT_ID:null,
        NHANVIEN_ID:object.hasOwnProperty('NHANVIEN_ID')?object.NHANVIEN_ID:null,
        KHLON_ID:object.hasOwnProperty('KHLON_ID')?object.KHLON_ID:null,
        LOAIHD_ID:object.hasOwnProperty('LOAIHD_ID')?object.LOAIHD_ID:null,
        BOSUNGTB_ID:object.hasOwnProperty('BOSUNGTB_ID')?object.BOSUNGTB_ID:null,
        MAY_CN:object.hasOwnProperty('MAY_CN')?object.MAY_CN:null,
        NGAY_CN:object.hasOwnProperty('NGAY_CN')?object.NGAY_CN:null,
        NGUOI_CN:object.hasOwnProperty('NGUOI_CN')?object.NGUOI_CN:null,
        IP_CN:object.hasOwnProperty('IP_CN')?object.IP_CN:null,
        KH_KT3:object.hasOwnProperty('KH_KT3')?object.KH_KT3:null,
        MST_KH:object.hasOwnProperty('MST_KH')?object.MST_KH:null,
        HOKHAU:object.hasOwnProperty('HOKHAU')?object.HOKHAU:null,
        LOAIKH_ID:object.hasOwnProperty('LOAIKH_ID')?object.LOAIKH_ID:null,
        NOICAP_HK:object.hasOwnProperty('NOICAP_HK')?object.NOICAP_HK:null,
        NGAY_HK:object.hasOwnProperty('NGAY_HK')?object.NGAY_HK:null,
        NGAY_YC:object.hasOwnProperty('NGAY_YC')?object.NGAY_YC:null,
        GIOITINH:object.hasOwnProperty('GIOITINH')?object.GIOITINH:null,
        DANTOC_ID:object.hasOwnProperty('DANTOC_ID')?object.DANTOC_ID:null,
        QUOCTICH_ID:object.hasOwnProperty('QUOCTICH_ID')?object.QUOCTICH_ID:null,
        NGANHNGHE_ID:object.hasOwnProperty('NGANHNGHE_ID')?object.NGANHNGHE_ID:null,
        DIACHI_NDD:object.hasOwnProperty('DIACHI_NDD')?object.DIACHI_NDD:null,
        NGAYHETHAN_GT:object.hasOwnProperty('NGAYHETHAN_GT')?object.NGAYHETHAN_GT:null,
        MST:object.hasOwnProperty('MST')?object.MST:null,
        STK:object.hasOwnProperty('STK')?object.STK:null,
        NGANHANG_ID:object.hasOwnProperty('NGANHANG_ID')?object.NGANHANG_ID:null,
        CTV_ID:object.hasOwnProperty('CTV_ID')?object.CTV_ID:null,
        TNC1_ID:object.hasOwnProperty('TNC1_ID')?object.TNC1_ID:null,
        TNC2_ID:object.hasOwnProperty('TNC2_ID')?object.TNC2_ID:null,
        TNC3_ID:object.hasOwnProperty('TNC3_ID')?object.TNC3_ID:null,
        DACTRUNG:object.hasOwnProperty('DACTRUNG')?object.DACTRUNG:null,
        KIEUHD_ID:object.hasOwnProperty('KIEUHD_ID')?object.KIEUHD_ID:null,
        HTTTHI_ID:object.hasOwnProperty('HTTTHI_ID')?object.HTTTHI_ID:null,
        HDKH_CHA_ID:object.hasOwnProperty('HDKH_CHA_ID')?object.HDKH_CHA_ID:null,
        PHANLOAIKH_ID:object.hasOwnProperty('PHANLOAIKH_ID')?object.PHANLOAIKH_ID:null,
        NHANVIENGT_ID:object.hasOwnProperty('NHANVIENGT_ID')?object.NHANVIENGT_ID:null,
        KENHTN_ID:object.hasOwnProperty('KENHTN_ID')?object.KENHTN_ID:null,
        MA_DUAN:object.hasOwnProperty('MA_DUAN')?object.MA_DUAN:null,
        EMAIL:object.hasOwnProperty('EMAIL')?object.EMAIL:null,
        PHIEUCSKH_ID:object.hasOwnProperty('PHIEUCSKH_ID')?object.PHIEUCSKH_ID:null,
        TNC4_ID:object.hasOwnProperty('TNC4_ID')?object.TNC4_ID:null
    }
    
}
//HD_THUEBAO_DATA.xds
function createObjectHDTB(){
    return {
        HDTB_ID:0,
        THUEBAO_ID:null,
        MA_TB:null,
        TEN_TB:null,
        DIACHI_TB:null,
        GHICHU:null,
        HDTB_CHA_ID:null,
        HDKH_ID:null,
        HDTT_ID:null,
        KIEULD_ID:null,
        TTHD_ID:null,
        LOAITB_ID:null,
        DOITUONG_ID:null,
        DICHVUVT_ID:null,
        DONVI_ID:null,
        NGAY_HT:null,
        MAY_CN:null,
        NGAY_CN:null,
        NGUOI_CN:null,
        IP_CN:null,
        SOLUONG:null,
        TBHD_PL:null,
        DIACHI_LD:null,
        NGAY_SN:null,
        KIEU_TB:null,
        STATUS:null,
        DONVI_DAU_ID:null,
        DONVI_CUOI_ID:null,
        MUCUOCTB_ID:null,
        MUCUOC_TB:null,
        THUEBAO_CHA_ID:null,
        QUYTRINH_ID:null,
        CHUYENMANG:null,
        TG_THUE_TU:null,
        TG_THUE_DEN:null,
        GOIKT_ID:null,
        SOTHANG_CK:null,
        NGAY_HH_TD:null,
        NHACC_CU_ID:null,
        DOITUONG_CT_ID:null,
        HTCM_ID:null,
        TRANGTHAIYC_ID:null
    }
}
function createObjectHDTB_CD(object){
    return {
        PHANVUNG_ID:object.hasOwnProperty('PHANVUNG_ID')?object.PHANVUNG_ID:null,
        HDTB_ID: 0,
        NE:object.hasOwnProperty('NE')?object.NE:null,
        CULY:object.hasOwnProperty('CULY')?object.CULY:null,
        GHICHU:object.hasOwnProperty('GHICHU')?object.GHICHU:null,
        NE_CU:object.hasOwnProperty('NE_CU')?object.NE_CU:null,
        MC_TBCD_ID:object.hasOwnProperty('MC_TBCD_ID')?object.MC_TBCD_ID:null,
        CAIDAT_DV:object.hasOwnProperty('CAIDAT_DV')?object.CAIDAT_DV:null,
        TT_TC_DM:object.hasOwnProperty('TT_TC_DM')?object.TT_TC_DM:null,
        NHANVIEN_HC_ID:object.hasOwnProperty('NHANVIEN_HC_ID')?object.NHANVIEN_HC_ID:null,
        NHANVIEN_DAIVT_ID:object.hasOwnProperty('NHANVIEN_DAIVT_ID')?object.NHANVIEN_DAIVT_ID:null,
        NGAYCN_HC:object.hasOwnProperty('NGAYCN_HC')?object.NGAYCN_HC:null,
        NGAYCD_DV:object.hasOwnProperty('NGAYCD_DV')?object.NGAYCD_DV:null,
        MIENCUOC_TB:object.hasOwnProperty('MIENCUOC_TB')?object.MIENCUOC_TB:null,
        MATB_TN:object.hasOwnProperty('MATB_TN')?object.MATB_TN:null,
        MADOICAP:object.hasOwnProperty('MADOICAP')?object.MADOICAP:null,
        MA_LT: object.hasOwnProperty('MA_LT')?object.MA_LT:null,
        TRANGBI_ID:object.hasOwnProperty('TRANGBI_ID')?object.TRANGBI_ID:null,
        NE_ID: object.hasOwnProperty('NE_ID')?object.NE_ID:null,
        TRAMTB_ID: object.hasOwnProperty('TRAMTB_ID')?object.TRAMTB_ID:null,
        TUYENCAP:object.hasOwnProperty('TUYENCAP')?object.TUYENCAP:null,
        LIENTU:object.hasOwnProperty('LIENTU')?object.LIENTU:null,
        DOICAP_P:object.hasOwnProperty('DOICAP_P')?object.DOICAP_P:null,
        HOPCAP_P:object.hasOwnProperty('HOPCAP_P')?object.HOPCAP_P:null,
        TUCAP_P:object.hasOwnProperty('TUCAP_P')?object.TUCAP_P:null,
        LOAICAP_ID:object.hasOwnProperty('LOAICAP_ID')?object.LOAICAP_ID:null,
        CAP_GOC:object.hasOwnProperty('CAP_GOC')?object.CAP_GOC:null,
        CAP_P:object.hasOwnProperty('CAP_P')?object.CAP_P:null,
        DOICAP_GOC:object.hasOwnProperty('DOICAP_GOC')?object.DOICAP_GOC:null,
        TG_THUESO:object.hasOwnProperty('TG_THUESO')?object.TG_THUESO:null,
        TG_THUESO:object.hasOwnProperty('TG_THUESO')?object.TG_THUESO:null,
        SOTRUOT:object.hasOwnProperty('SOTRUOT')?object.SOTRUOT:null,
        NOIDUNG_TB:object.hasOwnProperty('NOIDUNG_TB')?object.NOIDUNG_TB:null,
        CHUQUAN_ID:object.hasOwnProperty('CHUQUAN_ID')?object.CHUQUAN_ID:null,
        KETCUOI_ID:object.hasOwnProperty('KETCUOI_ID')?object.KETCUOI_ID:null,
        CONGNGHE_ID:object.hasOwnProperty('CONGNGHE_ID')?object.CONGNGHE_ID:null,
        THOIHAN_ID:object.hasOwnProperty('THOIHAN_ID')?object.THOIHAN_ID:null,
        SO_TAT:object.hasOwnProperty('SO_TAT')?object.SO_TAT:null,
        DOITAC_ID:object.hasOwnProperty('DOITAC_ID')?object.DOITAC_ID:null,
        CUOC_DOITAC:object.hasOwnProperty('CUOC_DOITAC')?object.CUOC_DOITAC:null,
        CHUQUANLD_ID:object.hasOwnProperty('CHUQUANLD_ID')?object.CHUQUANLD_ID:null,
        TINHKHAC:object.hasOwnProperty('TINHKHAC')?object.TINHKHAC:null,
        MA_VNPT:object.hasOwnProperty('MA_VNPT')?object.MA_VNPT:null
    }
}
function createObjectHDTB_IMS(object){
    return {
        PHANVUNG_ID:object.hasOwnProperty('PHANVUNG_ID')?object.PHANVUNG_ID:null,
        HDTB_ID: 0,
        CULY:object.hasOwnProperty('CULY')?object.CULY:null,
        GHICHU:object.hasOwnProperty('GHICHU')?object.GHICHU:null,
        BRAS_ID:object.hasOwnProperty('BRAS_ID')?object.BRAS_ID:null,
        DSLAM_ID:object.hasOwnProperty('DSLAM_ID')?object.DSLAM_ID:null,
        MADOICAP:object.hasOwnProperty('MADOICAP')?object.MADOICAP:null,
        MA_LT:object.hasOwnProperty('MA_LT')?object.MA_LT:null,
        TRANGBI_ID:object.hasOwnProperty('TRANGBI_ID')?object.TRANGBI_ID:null,
        PORT_ID:object.hasOwnProperty('PORT_ID')?object.PORT_ID:null,
        VCI_VPI_ID:object.hasOwnProperty('VCI_VPI_ID')?object.VCI_VPI_ID:null,

        USERNAME:object.hasOwnProperty('USERNAME')?object.USERNAME:null,
        PASSWORD:object.hasOwnProperty('PASSWORD')?object.PASSWORD:null,
        THIETBI_ID:object.hasOwnProperty('THIETBI_ID')?object.THIETBI_ID:null,
        TRAMTB_ID:object.hasOwnProperty('TRAMTB_ID')?object.TRAMTB_ID:null,
        TUYENCAP:object.hasOwnProperty('TUYENCAP')?object.TUYENCAP:null,
        LIENTU:object.hasOwnProperty('LIENTU')?object.LIENTU:null,
        DOICAP_P:object.hasOwnProperty('DOICAP_P')?object.DOICAP_P:null,
        HOPCAP_P:object.hasOwnProperty('HOPCAP_P')?object.HOPCAP_P:null,
        TUCAP_P:object.hasOwnProperty('TUCAP_P')?object.TUCAP_P:null,
        LOAICAP_ID:object.hasOwnProperty('LOAICAP_ID')?object.LOAICAP_ID:null,

        CAP_GOC:object.hasOwnProperty('CAP_GOC')?object.CAP_GOC:null,
        CAP_P:object.hasOwnProperty('CAP_P')?object.CAP_P:null,
        DOICAP_GOC:object.hasOwnProperty('DOICAP_GOC')?object.DOICAP_GOC:null,
        TUCAP_GOC:object.hasOwnProperty('TUCAP_GOC')?object.TUCAP_GOC:null,
        MATB_TN:object.hasOwnProperty('MATB_TN')?object.MATB_TN:null,
        CHUQUAN_ID:object.hasOwnProperty('CHUQUAN_ID')?object.CHUQUAN_ID:null,
        SL_CUOCGOI:object.hasOwnProperty('SL_CUOCGOI')?object.SL_CUOCGOI:null,
        KETCUOI_ID:object.hasOwnProperty('KETCUOI_ID')?object.KETCUOI_ID:null,
        CONGNGHE_ID:object.hasOwnProperty('CONGNGHE_ID')?object.CONGNGHE_ID:null,
        THOIHAN_ID:object.hasOwnProperty('THOIHAN_ID')?object.THOIHAN_ID:null,

        IP:object.hasOwnProperty('IP')?object.IP:null,
        CTDV_ID:object.hasOwnProperty('CTDV_ID')?object.CTDV_ID:null,
        CHUQUANLD_ID:object.hasOwnProperty('CHUQUANLD_ID')?object.CHUQUANLD_ID:null,
        TINHKHAC:object.hasOwnProperty('TINHKHAC')?object.TINHKHAC:null,
        DOITAC_ID:object.hasOwnProperty('DOITAC_ID')?object.DOITAC_ID:null,
        CUOC_DOITAC:object.hasOwnProperty('CUOC_DOITAC')?object.CUOC_DOITAC:null,
        MA_VNPT:object.hasOwnProperty('MA_VNPT')?object.MA_VNPT:null,
        TRUNKID:object.hasOwnProperty('TRUNKID')?object.TRUNKID:null,
        HTTC_ID:object.hasOwnProperty('HTTC_ID')?object.HTTC_ID:null,
    }
}
function createObjectHDTB_ADSL(){
    return {
        PHANVUNG_ID:null,
        HDTB_ID:0,
        EMAIL:null,
        KH_CD:null,
        MUCCUOC_ID:null,
        TOCDO_ID:null,
        CULY:null,
        SO_DT:null,
        MATB_MGWAN:null,
        THIETBIDC_ID:null,
        GHICHU:null,
        PASSWORD:null,
        BRAS_ID:null,
        DSLAM_ID:null,
        IP:null,
        TUCTHI:null,
        HANDATCHO:null,
        MATB_TN:null,
        MADOICAP:null,
        MA_LT:null,
        KIEUTRA_ID:null,
        THANG_ID:null,
        TRANGBI_ID:null,
        TYLE_GC:null,
        NGAY_GC:null,
        TG_GIAM:null,
        IP_MP:null,
        THONGTIN_TC:null,
        PORT_ID:null,
        VCI_VPI_ID:null,
        NGAYTRA:null,
        TRAMTB_ID:null,
        TUYENCAP:null,
        LIENTU:null,
        DOICAP_P:null,
        HOPCAP_P:null,
        TUCAP_P:null,
        LOAICAP_ID:null,
        CAP_GOC:null,
        CAP_P:null,
        DOICAP_GOC:null,
        TUCAP_GOC:null,
        STATUS_IP:null,
        CHUQUAN_ID:null,
        VMP:null,
        TOCDOTHUC_ID:null,
        SLTV_HTVC:null,
        PROFILEDSL_ID:null,
        CUOC_TN:null,
        CUOC_SODEP:null,
        CUOC_QL:null,
        TL_GIAMCUOC_QL:null,
        CUOC_SD:null,
        CUOC_TBI:null,
        KETCUOI_ID:null,
        HANG_SX:null,
        HARDWARE_VERSION:null,
        FIRMWARE_VERSION:null,
        CONGNGHE_ID:null,
        THOIHAN_ID:null,
        DOITAC_ID:null,
        LOAI_CSHT_ID:null,
        SERIAL_STB:null,
        CUOC_DOITAC:null,
        CHUQUANLD_ID:null,
        TINHKHAC:null,
        IPV4_WAN:null,
        IPV6_LAN:null,
        MA_VNPT:null,
        USERNAME:null,
        SLID:null,
        SERI_MD:null
    }
}
function createObjectHDTB_MGWAN(){
    return {
        PHANVUNG_ID:null,
        HDTB_ID:0,
        MA_VPN:null,
        CULY:null,
        THIETBIDC_ID:null,
        GHICHU:null,
        TOCDO_ID:null,
        LOAIMD_ID:null,
        LOAIKENH_ID:null,
        TRANGBI_ID:null,
        CHUQUAN_ID:null,
        THOIHAN_ID:null,
        HUONG_KN:null,
        PORT_ID:null,
        TEN_TBI:null,
        MATB_TN:null,
        MADOICAP:null,
        MA_LT:null,
        WAN_IP:null,
        LAN_IP:null,
        CUOC_TC:null,
        CUOC_TK:null,
        PE_ID:null,
        PORT_PE:null,
        SLOT_PE:null,
        VCI_VPI_ID:null,
        TUYENCAP:null,
        LIENTU:null,
        DOICAP_P:null,
        HOPCAP_P:null,
        TUCAP_P:null,
        LOAICAP_ID:null,
        CAP_GOC:null,
        CAP_P:null,
        DOICAP_GOC:null,
        TUCAP_GOC:null,
        DSLAM:null,
        VRF:null,
        LINK:null,
        SERIAL:null,
        ROUTE:null,
        DOITAC_ID:null,
        CUOC_HT:null,
        CUOC_TBI:null,
        SVLAN:null,
        CVLAN:null,
        CUOC_TKDT:null,
        CUOC_TCDT:null,
        MAHD_DT:null,
        TOCDO_PIR_ID:null,
        MA_PL:null,
        SITE_ID:null,
        GIUKENH:null,
        LOAINODE_ID:null,
        DIACHI_KN:null,
        KP_AO:null,
        MA_CV:null,
        NGAY_CV:null,
        NGAY_YCHT:null,
        MA_CRM:null,
        ID_ERP:null,
        MAKENH_VTN:null,
        KETCUOI_ID:null,
        TINH_KN_ID:null,
        SL_IP:null,
        CUOC_IP:null,
        TOCDO_NIX:null,
        CUOC_NIX:null,
        TOCDO_ISP:null,
        CUOC_ISP:null,
        CONGNGHE_ID:null,
        CHUQUANLD_ID:null,
        TINHKHAC:null,
        MA_VNPT:null,
        KENH_TONG:null,
        DIACHI_POP:null,
        QUOCGIA_POP:null,
        HUONGLUONG_UUTIEN:null,
        CAPNGOAI_VNPT:null,
        PHANLOAI_ID:null,
        PHANTACH_TD:null,
        MA_BSS:null,
        TINHCUOC:null,
        TOCDO_POP:null,
        DIEM_POP:null,
        MHKN_ID:null,
        GDKN_POP_ID:null,
        GDKN_KH_ID:null,
        TEN_TRUNK_NNI:null,
        CE_IP:null,
        SO_AS:null,
        CAUHINH_DT_ID:null,
        KIEU_DUPLEX_ID:null,
        MTU_SIZE:null,
        HQOS:null,
        COS:null,
        KIEUKN_ID:null,
        VLAN_TRANSPARENT:null,
        PORT_POP:null,
        IP_POP:null,
        SD_TBI_NET:null
    }
}
function createObjectHDTB_TSL(object){
    return {
        PHANVUNG_ID:object.hasOwnProperty('PHANVUNG_ID')?object.PHANVUNG_ID:null,
        HDTB_ID:object.hasOwnProperty('HDTB_ID')?object.HDTB_ID:0,
        DAUCUOI_ID:object.hasOwnProperty('DAUCUOI_ID')?object.DAUCUOI_ID:null,

        MA_TB_SUB:object.hasOwnProperty('MA_TB_SUB')?object.MA_TB_SUB:null,
        DIACHI:object.hasOwnProperty('DIACHI')?object.DIACHI:null,
        LOAIKENH_ID:object.hasOwnProperty('LOAIKENH_ID')?object.LOAIKENH_ID:null,
        TOCDO_ID:object.hasOwnProperty('TOCDO_ID')?object.TOCDO_ID:null,
        CHUQUAN_ID:object.hasOwnProperty('CHUQUAN_ID')?object.CHUQUAN_ID:null,
        LOAIMD_ID:object.hasOwnProperty('LOAIMD_ID')?object.LOAIMD_ID:null,
        THOIHAN_ID:object.hasOwnProperty('THOIHAN_ID')?object.THOIHAN_ID:null,
        TRANGBI_ID:object.hasOwnProperty('TRANGBI_ID')?object.TRANGBI_ID:null,
        GHICHU:object.hasOwnProperty('GHICHU')?object.GHICHU:null,
        DIACHI_ID:object.hasOwnProperty('DIACHI_ID')?object.DIACHI_ID:null,
        THIETBIDC_ID:object.hasOwnProperty('THIETBIDC_ID')?object.THIETBIDC_ID:null,
        CULY:object.hasOwnProperty('CULY')?object.CULY:null,
        SLOT:object.hasOwnProperty('SLOT')?object.SLOT:null,
        PORT:object.hasOwnProperty('PORT')?object.PORT:null,
        TIMESLOT:object.hasOwnProperty('TIMESLOT')?object.TIMESLOT:null,
        TEN_TBI:object.hasOwnProperty('TEN_TBI')?object.TEN_TBI:null,

        SLOT_CN:object.hasOwnProperty('SLOT_CN')?object.SLOT_CN:null,
        PORT_CN:object.hasOwnProperty('PORT_CN')?object.PORT_CN:null,
        TIMESLOT_CN:object.hasOwnProperty('TIMESLOT_CN')?object.TIMESLOT_CN:null,
        MAPPING_CN:object.hasOwnProperty('MAPPING_CN')?object.MAPPING_CN:null,
        MA_LT:object.hasOwnProperty('MA_LT')?object.MA_LT:null,
        LIENTU:object.hasOwnProperty('LIENTU')?object.LIENTU:null,
        DOICAP_P:object.hasOwnProperty('DOICAP_P')?object.DOICAP_P:null,
        HOPCAP_P:object.hasOwnProperty('HOPCAP_P')?object.HOPCAP_P:null,
        TUCAP_P:object.hasOwnProperty('TUCAP_P')?object.TUCAP_P:null,
        LOAICAP_ID:object.hasOwnProperty('LOAICAP_ID')?object.LOAICAP_ID:null,
        CAP_GOC:object.hasOwnProperty('CAP_GOC')?object.CAP_GOC:null,
        CAP_P:object.hasOwnProperty('CAP_P')?object.CAP_P:null,
        DOICAP_GOC:object.hasOwnProperty('DOICAP_GOC')?object.DOICAP_GOC:null,
        TUCAP_GOC:object.hasOwnProperty('TUCAP_GOC')?object.TUCAP_GOC:null,
        TUYENCAP:object.hasOwnProperty('TUYENCAP')?object.TUYENCAP:null,

        LINK:object.hasOwnProperty('LINK')?object.LINK:null,
        SERIAL:object.hasOwnProperty('SERIAL')?object.SERIAL:null,
        DOITAC_ID:object.hasOwnProperty('DOITAC_ID')?object.DOITAC_ID:null,
        SO_DT:object.hasOwnProperty('SO_DT')?object.SO_DT:null,
        CUOC_TK:object.hasOwnProperty('CUOC_TK')?object.CUOC_TK:null,
        CUOC_HT:object.hasOwnProperty('CUOC_HT')?object.CUOC_HT:null,
        CUOC_TC:object.hasOwnProperty('CUOC_TC')?object.CUOC_TC:null,
        CUOC_TBI:object.hasOwnProperty('CUOC_TBI')?object.CUOC_TBI:null,
        CUOC_TKDT:object.hasOwnProperty('CUOC_TKDT')?object.CUOC_TKDT:null,
        CUOC_TCDT:object.hasOwnProperty('CUOC_TCDT')?object.CUOC_TCDT:null,
        MAHD_DT:object.hasOwnProperty('MAHD_DT')?object.MAHD_DT:null,
        MA_PL:object.hasOwnProperty('MA_PL')?object.MA_PL:null,
        DC_DAUCUOI:object.hasOwnProperty('DC_DAUCUOI')?object.DC_DAUCUOI:null,
        TRAMTB_ID:object.hasOwnProperty('TRAMTB_ID')?object.TRAMTB_ID:null,
        BRAS_ID:object.hasOwnProperty('BRAS_ID')?object.BRAS_ID:null,
        DSLAM_ID:object.hasOwnProperty('DSLAM_ID')?object.DSLAM_ID:null,
        PORT_ID:object.hasOwnProperty('PORT_ID')?object.PORT_ID:null,
        VCI_VPI_ID:object.hasOwnProperty('VCI_VPI_ID')?object.VCI_VPI_ID:null,
        IP_WAN:object.hasOwnProperty('IP_WAN')?object.IP_WAN:null,
        VRF:object.hasOwnProperty('VRF')?object.VRF:null,
        MA_CV:object.hasOwnProperty('MA_CV')?object.MA_CV:null,
        NGAY_CV:object.hasOwnProperty('NGAY_CV')?object.NGAY_CV:null,
        NGAY_YCHT:object.hasOwnProperty('NGAY_YCHT')?object.NGAY_YCHT:null,
        MA_CRM:object.hasOwnProperty('MA_CRM')?object.MA_CRM:null,

        ID_ERP:object.hasOwnProperty('ID_ERP')?object.ID_ERP:null,
        MAKENH_VTN:object.hasOwnProperty('MAKENH_VTN')?object.MAKENH_VTN:null,
        KETCUOI_ID:object.hasOwnProperty('KETCUOI_ID')?object.KETCUOI_ID:null,
        KINHDO_LD:object.hasOwnProperty('KINHDO_LD')?object.KINHDO_LD:null,
        VIDO_LD:object.hasOwnProperty('VIDO_LD')?object.VIDO_LD:null,
        SITE_ID:object.hasOwnProperty('SITE_ID')?object.SITE_ID:null,
        CONGNGHE_ID:object.hasOwnProperty('CONGNGHE_ID')?object.CONGNGHE_ID:null,
        SL_SOIQUANG:object.hasOwnProperty('SL_SOIQUANG')?object.SL_SOIQUANG:null,
        CHUQUANLD_ID:object.hasOwnProperty('CHUQUANLD_ID')?object.CHUQUANLD_ID:null,
        MA_VNPT:object.hasOwnProperty('MA_VNPT')?object.MA_VNPT:null,
        TINH_ID:object.hasOwnProperty('TINH_ID')?object.TINH_ID:null,
        TINH_DC_ID:object.hasOwnProperty('TINH_DC_ID')?object.TINH_DC_ID:null,
        MA_BSS:object.hasOwnProperty('MA_BSS')?object.MA_BSS:null
    }
}

//HD_BANCHEO_DATA.xsd
function createObjectHD_BANCHEO(){
    return {
        TINH_BAN: null,
        TINH_THICONG: null,
        HDTB_BAN: null,
        HDTB_THICONG: null,
        THUEBAO_ID_BAN: null,
        THUEBAO_ID_THICONG: null,
        TRANG_THAI: null,
        LOAIHD_BANCHEO: null,
        MANV_DIEUHUONG: null,
        NGAY_CN: null,
        NGUOI_CN: null,
        MAY_CN: null,
        KHACHHANG_ID_BAN: null,
        KHACHHANG_ID_TC: null,
        THANHTOAN_ID_BAN: null,
        THANHTOAN_ID_TC: null,
        NGAY_HOANCONG: null,
        NGAY_HOANTHIEN: null,
        URL: null,
        VANBAN: null,
        ND_CHUYENTHICONG: null,
        ND_THOAITRA: null,
        DAUCUOI_ID: null
    }
}
//HDTB_BANCHEO_DATA.xsd
function createObjectHDTB_BANCHEO(object){
    return {
        HDTB_ID:object.hasOwnProperty('HDTB_ID')?object.HDTB_ID:null,
        THUEBAO_ID:object.hasOwnProperty('THUEBAO_ID')?object.THUEBAO_ID:null,
        MA_TB:object.hasOwnProperty('MA_TB')?object.MA_TB:null,
        TEN_TB:object.hasOwnProperty('TEN_TB')?object.TEN_TB:null,
        DIACHI_TB:object.hasOwnProperty('DIACHI_TB')?object.DIACHI_TB:null,
        GHICHU:object.hasOwnProperty('GHICHU')?object.GHICHU:null,
        HDTB_CHA_ID:object.hasOwnProperty('HDTB_CHA_ID')?object.HDTB_CHA_ID:null,
        HDKH_ID:object.hasOwnProperty('HDKH_ID')?object.HDKH_ID:null,
        HDTT_ID:object.hasOwnProperty('HDTT_ID')?object.HDTT_ID:null,
        KIEULD_ID:object.hasOwnProperty('KIEULD_ID')?object.KIEULD_ID:null,
        TTHD_ID:object.hasOwnProperty('TTHD_ID')?object.TTHD_ID:null,
        LOAITB_ID:object.hasOwnProperty('LOAITB_ID')?object.LOAITB_ID:null,
        DOITUONG_ID:object.hasOwnProperty('DOITUONG_ID')?object.DOITUONG_ID:null,
        DICHVUVT_ID:object.hasOwnProperty('DICHVUVT_ID')?object.DICHVUVT_ID:null,
        DONVI_ID:object.hasOwnProperty('DONVI_ID')?object.DONVI_ID:null,
        NGAY_HT:object.hasOwnProperty('NGAY_HT')?object.NGAY_HT:null,
        MAY_CN:object.hasOwnProperty('MAY_CN')?object.MAY_CN:null,
        NGAY_CN:object.hasOwnProperty('NGAY_CN')?object.NGAY_CN:null,
        NGUOI_CN:object.hasOwnProperty('NGUOI_CN')?object.NGUOI_CN:null,
        IP_CN:object.hasOwnProperty('IP_CN')?object.IP_CN:null,
        SOLUONG:object.hasOwnProperty('SOLUONG')?object.SOLUONG:null,
        TBHD_PL:object.hasOwnProperty('TBHD_PL')?object.TBHD_PL:null,
        DIACHI_LD:object.hasOwnProperty('DIACHI_LD')?object.DIACHI_LD:null,
        NGAY_SN:object.hasOwnProperty('NGAY_SN')?object.NGAY_SN:null,
        KIEU_TB:object.hasOwnProperty('KIEU_TB')?object.KIEU_TB:null,
        STATUS:object.hasOwnProperty('STATUS')?object.STATUS:null,
        DONVI_DAU_ID:object.hasOwnProperty('DONVI_DAU_ID')?object.DONVI_DAU_ID:null,
        DONVI_CUOI_ID:object.hasOwnProperty('DONVI_CUOI_ID')?object.DONVI_CUOI_ID:null,
        MUCUOCTB_ID:object.hasOwnProperty('MUCUOCTB_ID')?object.MUCUOCTB_ID:null,
        MUCUOC_TB:object.hasOwnProperty('MUCUOC_TB')?object.MUCUOC_TB:null,
        THUEBAO_CHA_ID:object.hasOwnProperty('THUEBAO_CHA_ID')?object.THUEBAO_CHA_ID:null,
        CHUYENMANG:object.hasOwnProperty('CHUYENMANG')?object.CHUYENMANG:null,
        TG_THUE_TU:object.hasOwnProperty('TG_THUE_TU')?object.TG_THUE_TU:null,
        TG_THUE_DEN:object.hasOwnProperty('TG_THUE_DEN')?object.TG_THUE_DEN:null,
        GOIKT_ID:object.hasOwnProperty('GOIKT_ID')?object.GOIKT_ID:null,
        SOTHANG_CK:object.hasOwnProperty('SOTHANG_CK')?object.SOTHANG_CK:null,
        NHACC_CU_ID:object.hasOwnProperty('NHACC_CU_ID')?object.NHACC_CU_ID:null,
        DOITUONG_CT_ID:object.hasOwnProperty('DOITUONG_CT_ID')?object.DOITUONG_CT_ID:null,
        HTCM_ID:object.hasOwnProperty('HTCM_ID')?object.HTCM_ID:null,
        TRANGTHAIYC_ID:object.hasOwnProperty('TRANGTHAIYC_ID')?object.TRANGTHAIYC_ID:null,
        QUAN_ID:object.hasOwnProperty('QUAN_ID')?object.QUAN_ID:null,
        PHUONG_ID:object.hasOwnProperty('PHUONG_ID')?object.PHUONG_ID:null,
        PHO_ID:object.hasOwnProperty('PHO_ID')?object.PHO_ID:null,
        AP_ID:object.hasOwnProperty('AP_ID')?object.AP_ID:null,
        KHU_ID:object.hasOwnProperty('KHU_ID')?object.KHU_ID:null,
        DACDIEM_ID:object.hasOwnProperty('DACDIEM_ID')?object.DACDIEM_ID:null,
        HUONGGIAO_TN_ID:object.hasOwnProperty('HUONGGIAO_TN_ID')?object.HUONGGIAO_TN_ID:null,
        NGAY_HH_TD:object.hasOwnProperty('NGAY_HH_TD')?object.NGAY_HH_TD:null,
        TINH_ID:object.hasOwnProperty('TINH_ID')?object.TINH_ID:null,
        TINH_DC_ID:object.hasOwnProperty('TINH_DC_ID')?object.TINH_DC_ID:null,
        DAUCUOI_ID:object.hasOwnProperty('DAUCUOI_ID')?object.DAUCUOI_ID:null
    }
}
//HDBC_CD_DATA.xsd
function createObjectHDTBBC_CD(object){
    return {
        HDTB_ID:object.hasOwnProperty('HDTB_ID')?object.HDTB_ID:null,
        NE:object.hasOwnProperty('NE')?object.NE:null,
        CULY:object.hasOwnProperty('CULY')?object.CULY:null,
        GHICHU:object.hasOwnProperty('GHICHU')?object.GHICHU:null,
        NE_CU:object.hasOwnProperty('NE_CU')?object.NE_CU:null,
        MC_TBCD_ID:object.hasOwnProperty('MC_TBCD_ID')?object.MC_TBCD_ID:null,
        CAIDAT_DV:object.hasOwnProperty('CAIDAT_DV')?object.CAIDAT_DV:null,
        TT_TC_DM:object.hasOwnProperty('TT_TC_DM')?object.TT_TC_DM:null,
        NHANVIEN_HC_ID:object.hasOwnProperty('NHANVIEN_HC_ID')?object.NHANVIEN_HC_ID:null,
        NHANVIEN_DAIVT_ID:object.hasOwnProperty('NHANVIEN_DAIVT_ID')?object.NHANVIEN_DAIVT_ID:null,
        NGAYCN_HC:object.hasOwnProperty('NGAYCN_HC')?object.NGAYCN_HC:null,
        NGAYCD_DV:object.hasOwnProperty('NGAYCD_DV')?object.NGAYCD_DV:null,
        MIENCUOC_TB:object.hasOwnProperty('MIENCUOC_TB')?object.MIENCUOC_TB:null,
        MATB_TN:object.hasOwnProperty('MATB_TN')?object.MATB_TN:null,
        MADOICAP:object.hasOwnProperty('MADOICAP')?object.MADOICAP:null,
        MA_LT:object.hasOwnProperty('MA_LT')?object.MA_LT:null,
        TRANGBI_ID:object.hasOwnProperty('TRANGBI_ID')?object.TRANGBI_ID:null,
        NE_ID:object.hasOwnProperty('NE_ID')?object.NE_ID:null,
        TRAMTB_ID:object.hasOwnProperty('TRAMTB_ID')?object.TRAMTB_ID:null,
        TUYENCAP:object.hasOwnProperty('TUYENCAP')?object.TUYENCAP:null,
        LIENTU:object.hasOwnProperty('LIENTU')?object.LIENTU:null,
        DOICAP_P:object.hasOwnProperty('DOICAP_P')?object.DOICAP_P:null,
        HOPCAP_P:object.hasOwnProperty('HOPCAP_P')?object.HOPCAP_P:null,
        TUCAP_P:object.hasOwnProperty('TUCAP_P')?object.TUCAP_P:null,
        LOAICAP_ID:object.hasOwnProperty('LOAICAP_ID')?object.LOAICAP_ID:null,
        CAP_GOC:object.hasOwnProperty('CAP_GOC')?object.CAP_GOC:null,
        CAP_P:object.hasOwnProperty('CAP_P')?object.CAP_P:null,
        DOICAP_GOC:object.hasOwnProperty('DOICAP_GOC')?object.DOICAP_GOC:null,
        TUCAP_GOC:object.hasOwnProperty('TUCAP_GOC')?object.TUCAP_GOC:null,
        TG_THUESO:object.hasOwnProperty('TG_THUESO')?object.TG_THUESO:null,
        SOTRUOT:object.hasOwnProperty('SOTRUOT')?object.SOTRUOT:null,
        NOIDUNG_TB:object.hasOwnProperty('NOIDUNG_TB')?object.NOIDUNG_TB:null,
        CHUQUAN_ID:object.hasOwnProperty('CHUQUAN_ID')?object.CHUQUAN_ID:null,
        KETCUOI_ID:object.hasOwnProperty('KETCUOI_ID')?object.KETCUOI_ID:null,
        CONGNGHE_ID:object.hasOwnProperty('CONGNGHE_ID')?object.CONGNGHE_ID:null,
        THOIHAN_ID:object.hasOwnProperty('THOIHAN_ID')?object.THOIHAN_ID:null,
        CHUQUANLD_ID:object.hasOwnProperty('CHUQUANLD_ID')?object.CHUQUANLD_ID:null,
        MA_VNPT:object.hasOwnProperty('MA_VNPT')?object.MA_VNPT:null
    }
}
function createObjectHDTBBC_IMS(object){
    return {
        HDTB_ID:object.hasOwnProperty('HDTB_ID')?object.HDTB_ID:null,
        CULY:object.hasOwnProperty('CULY')?object.CULY:null,
        GHICHU:object.hasOwnProperty('GHICHU')?object.GHICHU:null,
        BRAS_ID:object.hasOwnProperty('BRAS_ID')?object.BRAS_ID:null,
        DSLAM_ID:object.hasOwnProperty('DSLAM_ID')?object.DSLAM_ID:null,
        MADOICAP:object.hasOwnProperty('MADOICAP')?object.MADOICAP:null,
        MA_LT:object.hasOwnProperty('MA_LT')?object.MA_LT:null,
        TRANGBI_ID:object.hasOwnProperty('TRANGBI_ID')?object.TRANGBI_ID:null,
        PORT_ID:object.hasOwnProperty('PORT_ID')?object.PORT_ID:null,
        VCI_VPI_ID:object.hasOwnProperty('VCI_VPI_ID')?object.VCI_VPI_ID:null,
        USERNAME:object.hasOwnProperty('USERNAME')?object.USERNAME:null,
        PASSWORD:object.hasOwnProperty('PASSWORD')?object.PASSWORD:null,
        THIETBI_ID:object.hasOwnProperty('THIETBI_ID')?object.THIETBI_ID:null,
        TRAMTB_ID:object.hasOwnProperty('TRAMTB_ID')?object.TRAMTB_ID:null,
        TUYENCAP:object.hasOwnProperty('TUYENCAP')?object.TUYENCAP:null,
        LIENTU:object.hasOwnProperty('LIENTU')?object.LIENTU:null,
        DOICAP_P:object.hasOwnProperty('DOICAP_P')?object.DOICAP_P:null,
        HOPCAP_P:object.hasOwnProperty('HOPCAP_P')?object.HOPCAP_P:null,
        TUCAP_P:object.hasOwnProperty('TUCAP_P')?object.TUCAP_P:null,
        LOAICAP_ID:object.hasOwnProperty('LOAICAP_ID')?object.LOAICAP_ID:null,
        CAP_GOC:object.hasOwnProperty('CAP_GOC')?object.CAP_GOC:null,
        CAP_P:object.hasOwnProperty('CAP_P')?object.CAP_P:null,
        DOICAP_GOC:object.hasOwnProperty('DOICAP_GOC')?object.DOICAP_GOC:null,

        TUCAP_GOC:object.hasOwnProperty('TUCAP_GOC')?object.TUCAP_GOC:null,
        MATB_TN:object.hasOwnProperty('MATB_TN')?object.MATB_TN:null,
        CHUQUAN_ID:object.hasOwnProperty('CHUQUAN_ID')?object.CHUQUAN_ID:null,
        SL_CUOCGOI:object.hasOwnProperty('SL_CUOCGOI')?object.SL_CUOCGOI:null,
        KETCUOI_ID:object.hasOwnProperty('KETCUOI_ID')?object.KETCUOI_ID:null,
        CONGNGHE_ID:object.hasOwnProperty('CONGNGHE_ID')?object.CONGNGHE_ID:null,
        THOIHAN_ID:object.hasOwnProperty('THOIHAN_ID')?object.THOIHAN_ID:null,
        IP:object.hasOwnProperty('IP')?object.IP:null,
        CTDV_ID:object.hasOwnProperty('CTDV_ID')?object.CTDV_ID:null,
        CHUQUANLD_ID:object.hasOwnProperty('CHUQUANLD_ID')?object.CHUQUANLD_ID:null,
        TINHKHAC:object.hasOwnProperty('TINHKHAC')?object.TINHKHAC:null,
        DOITAC_ID:object.hasOwnProperty('DOITAC_ID')?object.DOITAC_ID:null,
        CUOC_DOITAC:object.hasOwnProperty('CUOC_DOITAC')?object.CUOC_DOITAC:null,
        MA_VNPT:object.hasOwnProperty('MA_VNPT')?object.MA_VNPT:null,
        TRUNKID:object.hasOwnProperty('TRUNKID')?object.TRUNKID:null,
        HTTC_ID:object.hasOwnProperty('HTTC_ID')?object.HTTC_ID:null,
        TONGDAI_ID:object.hasOwnProperty('TONGDAI_ID')?object.TONGDAI_ID:null,
        ENDPOINT_ID:object.hasOwnProperty('ENDPOINT_ID')?object.ENDPOINT_ID:null,
        PROFILE:object.hasOwnProperty('PROFILE')?object.PROFILE:null,
        PROFILE_INFO:object.hasOwnProperty('PROFILE_INFO')?object.PROFILE_INFO:null,
        NGUONG_CSD:object.hasOwnProperty('NGUONG_CSD')?object.NGUONG_CSD:null
    }
}
//HDBC_ADSL_DATA.xsd
function createObjectHDTBBC_ADSL(object){
    return {
        HDTB_ID:object.hasOwnProperty('HDTB_ID')?object.HDTB_ID:null,
        EMAIL:object.hasOwnProperty('EMAIL')?object.EMAIL:null,
        KH_CD:object.hasOwnProperty('KH_CD')?object.KH_CD:null,
        MUCCUOC_ID:object.hasOwnProperty('MUCCUOC_ID')?object.MUCCUOC_ID:null,
        TOCDO_ID:object.hasOwnProperty('TOCDO_ID')?object.TOCDO_ID:null,
        CULY:object.hasOwnProperty('CULY')?object.CULY:null,
        SO_DT:object.hasOwnProperty('SO_DT')?object.SO_DT:null,
        MATB_MGWAN:object.hasOwnProperty('MATB_MGWAN')?object.MATB_MGWAN:null,
        THIETBIDC_ID:object.hasOwnProperty('THIETBIDC_ID')?object.THIETBIDC_ID:null,
        GHICHU:object.hasOwnProperty('GHICHU')?object.GHICHU:null,
        PASSWORD:object.hasOwnProperty('PASSWORD')?object.PASSWORD:null,
        BRAS_ID:object.hasOwnProperty('BRAS_ID')?object.BRAS_ID:null,
        DSLAM_ID:object.hasOwnProperty('DSLAM_ID')?object.DSLAM_ID:null,
        IP:object.hasOwnProperty('IP')?object.IP:null,
        TUCTHI:object.hasOwnProperty('TUCTHI')?object.TUCTHI:null,
        HANDATCHO:object.hasOwnProperty('HANDATCHO')?object.HANDATCHO:null,
        MATB_TN:object.hasOwnProperty('MATB_TN')?object.MATB_TN:null,
        MADOICAP:object.hasOwnProperty('MADOICAP')?object.MADOICAP:null,

        MA_LT:object.hasOwnProperty('MA_LT')?object.MA_LT:null,
        KIEUTRA_ID:object.hasOwnProperty('KIEUTRA_ID')?object.KIEUTRA_ID:null,
        THANG_ID:object.hasOwnProperty('THANG_ID')?object.THANG_ID:null,
        TRANGBI_ID:object.hasOwnProperty('TRANGBI_ID')?object.TRANGBI_ID:null,
        TYLE_GC:object.hasOwnProperty('TYLE_GC')?object.TYLE_GC:null,
        NGAY_GC:object.hasOwnProperty('NGAY_GC')?object.NGAY_GC:null,
        TG_GIAM:object.hasOwnProperty('TG_GIAM')?object.TG_GIAM:null,
        IP_MP:object.hasOwnProperty('IP_MP')?object.IP_MP:null,
        THONGTIN_TC:object.hasOwnProperty('THONGTIN_TC')?object.THONGTIN_TC:null,
        PORT_ID:object.hasOwnProperty('PORT_ID')?object.PORT_ID:null,
        VCI_VPI_ID:object.hasOwnProperty('VCI_VPI_ID')?object.VCI_VPI_ID:null,
        NGAYTRA:object.hasOwnProperty('NGAYTRA')?object.NGAYTRA:null,
        TRAMTB_ID:object.hasOwnProperty('TRAMTB_ID')?object.TRAMTB_ID:null,
        TUYENCAP:object.hasOwnProperty('TUYENCAP')?object.TUYENCAP:null,
        LIENTU:object.hasOwnProperty('LIENTU')?object.LIENTU:null,
        DOICAP_P:object.hasOwnProperty('DOICAP_P')?object.DOICAP_P:null,
        HOPCAP_P:object.hasOwnProperty('HOPCAP_P')?object.HOPCAP_P:null,
        TUCAP_P:object.hasOwnProperty('TUCAP_P')?object.TUCAP_P:null,
        LOAICAP_ID:object.hasOwnProperty('LOAICAP_ID')?object.LOAICAP_ID:null,
        CAP_GOC:object.hasOwnProperty('CAP_GOC')?object.CAP_GOC:null,
        CAP_P:object.hasOwnProperty('CAP_P')?object.CAP_P:null,
        DOICAP_GOC:object.hasOwnProperty('DOICAP_GOC')?object.DOICAP_GOC:null,

        TUCAP_GOC:object.hasOwnProperty('TUCAP_GOC')?object.TUCAP_GOC:null,
        STATUS_IP:object.hasOwnProperty('STATUS_IP')?object.STATUS_IP:null,
        CHUQUAN_ID:object.hasOwnProperty('CHUQUAN_ID')?object.CHUQUAN_ID:null,
        VMP:object.hasOwnProperty('VMP')?object.VMP:null,
        TOCDOTHUC_ID:object.hasOwnProperty('TOCDOTHUC_ID')?object.TOCDOTHUC_ID:null,
        SLTV_HTVC:object.hasOwnProperty('SLTV_HTVC')?object.SLTV_HTVC:null,
        PROFILEDSL_ID:object.hasOwnProperty('PROFILEDSL_ID')?object.PROFILEDSL_ID:null,
        CUOC_TN:object.hasOwnProperty('CUOC_TN')?object.CUOC_TN:null,
        CUOC_SODEP:object.hasOwnProperty('CUOC_SODEP')?object.CUOC_SODEP:null,
        CUOC_QL:object.hasOwnProperty('CUOC_QL')?object.CUOC_QL:null,
        TL_GIAMCUOC_QL:object.hasOwnProperty('TL_GIAMCUOC_QL')?object.TL_GIAMCUOC_QL:null,
        CUOC_SD:object.hasOwnProperty('CUOC_SD')?object.CUOC_SD:null,
        CUOC_TBI:object.hasOwnProperty('CUOC_TBI')?object.CUOC_TBI:null,
        KETCUOI_ID:object.hasOwnProperty('KETCUOI_ID')?object.KETCUOI_ID:null,
        HANG_SX:object.hasOwnProperty('HANG_SX')?object.HANG_SX:null,
        HARDWARE_VERSION:object.hasOwnProperty('HARDWARE_VERSION')?object.HARDWARE_VERSION:null,
        FIRMWARE_VERSION:object.hasOwnProperty('FIRMWARE_VERSION')?object.FIRMWARE_VERSION:null,
        CONGNGHE_ID:object.hasOwnProperty('CONGNGHE_ID')?object.CONGNGHE_ID:null,
        THOIHAN_ID:object.hasOwnProperty('THOIHAN_ID')?object.THOIHAN_ID:null,
        DOITAC_ID:object.hasOwnProperty('DOITAC_ID')?object.DOITAC_ID:null,
        LOAI_CSHT_ID:object.hasOwnProperty('LOAI_CSHT_ID')?object.LOAI_CSHT_ID:null,
        CHUQUANLD_ID:object.hasOwnProperty('CHUQUANLD_ID')?object.CHUQUANLD_ID:null,
        MA_VNPT:object.hasOwnProperty('MA_VNPT')?object.MA_VNPT:null,
        USERNAME:object.hasOwnProperty('USERNAME')?object.USERNAME:null
    }
}
function createObjectHDTBBC_MGWAN(object){
    return {
        HDTB_ID:object.hasOwnProperty('HDTB_ID')?object.HDTB_ID:null,
        CULY:object.hasOwnProperty('CULY')?object.CULY:null,
        THIETBIDC_ID:object.hasOwnProperty('THIETBIDC_ID')?object.THIETBIDC_ID:null,
        GHICHU:object.hasOwnProperty('GHICHU')?object.GHICHU:null,
        TOCDO_ID:object.hasOwnProperty('TOCDO_ID')?object.TOCDO_ID:null,
        LOAIMD_ID:object.hasOwnProperty('LOAIMD_ID')?object.LOAIMD_ID:null,
        LOAIKENH_ID:object.hasOwnProperty('LOAIKENH_ID')?object.LOAIKENH_ID:null,
        TRANGBI_ID:object.hasOwnProperty('TRANGBI_ID')?object.TRANGBI_ID:null,
        CHUQUAN_ID:object.hasOwnProperty('CHUQUAN_ID')?object.CHUQUAN_ID:null,
        THOIHAN_ID:object.hasOwnProperty('THOIHAN_ID')?object.THOIHAN_ID:null,
        HUONG_KN:object.hasOwnProperty('HUONG_KN')?object.HUONG_KN:null,
        PORT_ID:object.hasOwnProperty('PORT_ID')?object.PORT_ID:null,
        TEN_TBI:object.hasOwnProperty('TEN_TBI')?object.TEN_TBI:null,
        MATB_TN:object.hasOwnProperty('MATB_TN')?object.MATB_TN:null,
        MADOICAP:object.hasOwnProperty('MADOICAP')?object.MADOICAP:null,
        MA_LT:object.hasOwnProperty('MA_LT')?object.MA_LT:null,
        WAN_IP:object.hasOwnProperty('WAN_IP')?object.WAN_IP:null,
        LAN_IP:object.hasOwnProperty('LAN_IP')?object.LAN_IP:null,
        CUOC_TC:object.hasOwnProperty('CUOC_TC')?object.CUOC_TC:null,

        CUOC_TK:object.hasOwnProperty('CUOC_TK')?object.CUOC_TK:null,
        PE_ID:object.hasOwnProperty('PE_ID')?object.PE_ID:null,
        PORT_PE:object.hasOwnProperty('PORT_PE')?object.PORT_PE:null,
        SLOT_PE:object.hasOwnProperty('SLOT_PE')?object.SLOT_PE:null,
        VCI_VPI_ID:object.hasOwnProperty('VCI_VPI_ID')?object.VCI_VPI_ID:null,
        TUYENCAP:object.hasOwnProperty('TUYENCAP')?object.TUYENCAP:null,
        LIENTU:object.hasOwnProperty('LIENTU')?object.LIENTU:null,
        DOICAP_P:object.hasOwnProperty('DOICAP_P')?object.DOICAP_P:null,
        HOPCAP_P:object.hasOwnProperty('HOPCAP_P')?object.HOPCAP_P:null,
        TUCAP_P:object.hasOwnProperty('TUCAP_P')?object.TUCAP_P:null,
        LOAICAP_ID:object.hasOwnProperty('LOAICAP_ID')?object.LOAICAP_ID:null,
        CAP_P:object.hasOwnProperty('CAP_P')?object.CAP_P:null,
        DOICAP_GOC:object.hasOwnProperty('DOICAP_GOC')?object.DOICAP_GOC:null,

        TUCAP_GOC:object.hasOwnProperty('TUCAP_GOC')?object.TUCAP_GOC:null,
        DSLAM:object.hasOwnProperty('DSLAM')?object.DSLAM:null,
        VRF:object.hasOwnProperty('VRF')?object.VRF:null,
        LINK:object.hasOwnProperty('LINK')?object.LINK:null,
        ROUTE:object.hasOwnProperty('ROUTE')?object.ROUTE:null,
        DOITAC_ID:object.hasOwnProperty('DOITAC_ID')?object.DOITAC_ID:null,
        CUOC_HT:object.hasOwnProperty('CUOC_HT')?object.CUOC_HT:null,
        CUOC_TBI:object.hasOwnProperty('CUOC_TBI')?object.CUOC_TBI:null,
        SVLAN:object.hasOwnProperty('SVLAN')?object.SVLAN:null,
        CVLAN:object.hasOwnProperty('CVLAN')?object.CVLAN:null,
        CUOC_TKDT:object.hasOwnProperty('CUOC_TKDT')?object.CUOC_TKDT:null,
        CUOC_TCDT:object.hasOwnProperty('CUOC_TCDT')?object.CUOC_TCDT:null,
        MAHD_DT:object.hasOwnProperty('MAHD_DT')?object.MAHD_DT:null,
        TOCDO_PIR_ID:object.hasOwnProperty('TOCDO_PIR_ID')?object.TOCDO_PIR_ID:null,
        MA_PL:object.hasOwnProperty('MA_PL')?object.MA_PL:null,
        SITE_ID:object.hasOwnProperty('SITE_ID')?object.SITE_ID:null,
        GIUKENH:object.hasOwnProperty('GIUKENH')?object.GIUKENH:null,
        LOAINODE_ID:object.hasOwnProperty('LOAINODE_ID')?object.LOAINODE_ID:null,
        DIACHI_KN:object.hasOwnProperty('DIACHI_KN')?object.DIACHI_KN:null,
        KP_AO:object.hasOwnProperty('KP_AO')?object.KP_AO:null,
        MA_CV:object.hasOwnProperty('MA_CV')?object.MA_CV:null,
        NGAY_CV:object.hasOwnProperty('NGAY_CV')?object.NGAY_CV:null,
        NGAY_YCHT:object.hasOwnProperty('NGAY_YCHT')?object.NGAY_YCHT:null,
        MA_CRM:object.hasOwnProperty('MA_CRM')?object.MA_CRM:null,

        ID_ERP:object.hasOwnProperty('ID_ERP')?object.ID_ERP:null,
        MAKENH_VTN:object.hasOwnProperty('MAKENH_VTN')?object.MAKENH_VTN:null,
        KETCUOI_ID:object.hasOwnProperty('KETCUOI_ID')?object.KETCUOI_ID:null,
        TINH_KN_ID:object.hasOwnProperty('TINH_KN_ID')?object.TINH_KN_ID:null,
        SL_IP:object.hasOwnProperty('SL_IP')?object.SL_IP:null,
        CUOC_IP:object.hasOwnProperty('CUOC_IP')?object.CUOC_IP:null,
        TOCDO_NIX:object.hasOwnProperty('TOCDO_NIX')?object.TOCDO_NIX:null,
        CUOC_NIX:object.hasOwnProperty('CUOC_NIX')?object.CUOC_NIX:null,
        TOCDO_ISP:object.hasOwnProperty('TOCDO_ISP')?object.TOCDO_ISP:null,
        CUOC_ISP:object.hasOwnProperty('CUOC_ISP')?object.CUOC_ISP:null,
        CONGNGHE_ID:object.hasOwnProperty('CONGNGHE_ID')?object.CONGNGHE_ID:null,
        CHUQUANLD_ID:object.hasOwnProperty('CHUQUANLD_ID')?object.CHUQUANLD_ID:null,
        MA_VNPT:object.hasOwnProperty('MA_VNPT')?object.MA_VNPT:null,
        PHANLOAI_ID:object.hasOwnProperty('PHANLOAI_ID')?object.PHANLOAI_ID:null,
        PHANTACH_TD:object.hasOwnProperty('PHANTACH_TD')?object.PHANTACH_TD:null,
        TINHCUOC:object.hasOwnProperty('TINHCUOC')?object.TINHCUOC:null,

        TOCDO_POP:object.hasOwnProperty('TOCDO_POP')?object.TOCDO_POP:null,
        DIEM_POP:object.hasOwnProperty('DIEM_POP')?object.DIEM_POP:null,
        MHKN_ID:object.hasOwnProperty('MHKN_ID')?object.MHKN_ID:null,
        GDKN_POP_ID:object.hasOwnProperty('GDKN_POP_ID')?object.GDKN_POP_ID:null,
        GDKN_KH_ID:object.hasOwnProperty('GDKN_KH_ID')?object.GDKN_KH_ID:null,
        TEN_TRUNK_NNI:object.hasOwnProperty('TEN_TRUNK_NNI')?object.TEN_TRUNK_NNI:null,
        CE_IP:object.hasOwnProperty('CE_IP')?object.CE_IP:null,
        SO_AS:object.hasOwnProperty('SO_AS')?object.SO_AS:null,
        CAUHINH_DT_ID:object.hasOwnProperty('CAUHINH_DT_ID')?object.CAUHINH_DT_ID:null,
        KIEU_DUPLEX_ID:object.hasOwnProperty('KIEU_DUPLEX_ID')?object.KIEU_DUPLEX_ID:null,
        MTU_SIZE:object.hasOwnProperty('MTU_SIZE')?object.MTU_SIZE:null,
        HQOS:object.hasOwnProperty('HQOS')?object.HQOS:null,
        COS:object.hasOwnProperty('COS')?object.COS:null,
        KIEUKN_ID:object.hasOwnProperty('KIEUKN_ID')?object.KIEUKN_ID:null,
        VLAN_TRANSPARENT:object.hasOwnProperty('VLAN_TRANSPARENT')?object.VLAN_TRANSPARENT:null,
        PORT_POP:object.hasOwnProperty('PORT_POP')?object.PORT_POP:null,
        IP_POP:object.hasOwnProperty('IP_POP')?object.IP_POP:null,
        SD_TBI_NET:object.hasOwnProperty('SD_TBI_NET')?object.SD_TBI_NET:null
    }
}
//HDBC_TSL_DATA.xsd
function createObjectHDTBBC_TSL(object){
    return {
        HDTB_ID:object.hasOwnProperty('HDTB_ID')?object.HDTB_ID:null,
        DAUCUOI_ID:object.hasOwnProperty('DAUCUOI_ID')?object.DAUCUOI_ID:null,
        MA_TB_SUB:object.hasOwnProperty('MA_TB_SUB')?object.MA_TB_SUB:null,
        DIACHI:object.hasOwnProperty('DIACHI')?object.DIACHI:null,
        LOAIKENH_ID:object.hasOwnProperty('LOAIKENH_ID')?object.LOAIKENH_ID:null,
        TOCDO_ID:object.hasOwnProperty('TOCDO_ID')?object.TOCDO_ID:null,
        CHUQUAN_ID:object.hasOwnProperty('CHUQUAN_ID')?object.CHUQUAN_ID:null,
        LOAIMD_ID:object.hasOwnProperty('LOAIMD_ID')?object.LOAIMD_ID:null,

        THOIHAN_ID:object.hasOwnProperty('THOIHAN_ID')?object.THOIHAN_ID:null,
        TRANGBI_ID:object.hasOwnProperty('TRANGBI_ID')?object.TRANGBI_ID:null,
        GHICHU:object.hasOwnProperty('GHICHU')?object.GHICHU:null,
        DIACHI_ID:object.hasOwnProperty('DIACHI_ID')?object.DIACHI_ID:null,
        THIETBIDC_ID:object.hasOwnProperty('THIETBIDC_ID')?object.THIETBIDC_ID:null,
        CULY:object.hasOwnProperty('CULY')?object.CULY:null,
        SLOT:object.hasOwnProperty('SLOT')?object.SLOT:null,
        PORT:object.hasOwnProperty('PORT')?object.PORT:null,
        TIMESLOT:object.hasOwnProperty('TIMESLOT')?object.TIMESLOT:null,
        TEN_TBI:object.hasOwnProperty('TEN_TBI')?object.TEN_TBI:null,
        SLOT_CN:object.hasOwnProperty('SLOT_CN')?object.SLOT_CN:null,
        PORT_CN:object.hasOwnProperty('PORT_CN')?object.PORT_CN:null,
        TIMESLOT_CN:object.hasOwnProperty('TIMESLOT_CN')?object.TIMESLOT_CN:null,
        MAPPING_CN:object.hasOwnProperty('MAPPING_CN')?object.MAPPING_CN:null,
        MA_LT:object.hasOwnProperty('MA_LT')?object.MA_LT:null,
        LIENTU:object.hasOwnProperty('LIENTU')?object.LIENTU:null,
        DOICAP_P:object.hasOwnProperty('DOICAP_P')?object.DOICAP_P:null,
        HOPCAP_P:object.hasOwnProperty('HOPCAP_P')?object.HOPCAP_P:null,
        TUCAP_P:object.hasOwnProperty('TUCAP_P')?object.TUCAP_P:null,
        LOAICAP_ID:object.hasOwnProperty('LOAICAP_ID')?object.LOAICAP_ID:null,

        CAP_GOC:object.hasOwnProperty('CAP_GOC')?object.CAP_GOC:null,
        CAP_P:object.hasOwnProperty('CAP_P')?object.CAP_P:null,
        DOICAP_GOC:object.hasOwnProperty('DOICAP_GOC')?object.DOICAP_GOC:null,
        TUCAP_GOC:object.hasOwnProperty('TUCAP_GOC')?object.TUCAP_GOC:null,
        TUYENCAP:object.hasOwnProperty('TUYENCAP')?object.TUYENCAP:null,
        LINK:object.hasOwnProperty('LINK')?object.LINK:null,
        SERIAL:object.hasOwnProperty('SERIAL')?object.SERIAL:null,
        DOITAC_ID:object.hasOwnProperty('DOITAC_ID')?object.DOITAC_ID:null,
        SO_DT:object.hasOwnProperty('SO_DT')?object.SO_DT:null,
        CUOC_TK:object.hasOwnProperty('CUOC_TK')?object.CUOC_TK:null,
        CUOC_HT:object.hasOwnProperty('CUOC_HT')?object.CUOC_HT:null,
        CUOC_TC:object.hasOwnProperty('CUOC_TC')?object.CUOC_TC:null,
        CUOC_TBI:object.hasOwnProperty('CUOC_TBI')?object.CUOC_TBI:null,
        CUOC_TKDT:object.hasOwnProperty('CUOC_TKDT')?object.CUOC_TKDT:null,
        CUOC_TCDT:object.hasOwnProperty('CUOC_TCDT')?object.CUOC_TCDT:null,
        MAHD_DT:object.hasOwnProperty('MAHD_DT')?object.MAHD_DT:null,
        MA_PL:object.hasOwnProperty('MA_PL')?object.MA_PL:null,
        DC_DAUCUOI:object.hasOwnProperty('DC_DAUCUOI')?object.DC_DAUCUOI:null,
        TRAMTB_ID:object.hasOwnProperty('TRAMTB_ID')?object.TRAMTB_ID:null,
        BRAS_ID:object.hasOwnProperty('BRAS_ID')?object.BRAS_ID:null,
        DSLAM_ID:object.hasOwnProperty('DSLAM_ID')?object.DSLAM_ID:null,
        PORT_ID:object.hasOwnProperty('PORT_ID')?object.PORT_ID:null,
        VCI_VPI_ID:object.hasOwnProperty('VCI_VPI_ID')?object.VCI_VPI_ID:null,
        IP_WAN:object.hasOwnProperty('IP_WAN')?object.IP_WAN:null,
        VRF:object.hasOwnProperty('VRF')?object.VRF:null,
        MA_CV:object.hasOwnProperty('MA_CV')?object.MA_CV:null,
        NGAY_CV:object.hasOwnProperty('NGAY_CV')?object.NGAY_CV:null,
        NGAY_YCHT:object.hasOwnProperty('NGAY_YCHT')?object.NGAY_YCHT:null,
        MA_CRM:object.hasOwnProperty('MA_CRM')?object.MA_CRM:null,
        ID_ERP:object.hasOwnProperty('ID_ERP')?object.ID_ERP:null,
        MAKENH_VTN:object.hasOwnProperty('MAKENH_VTN')?object.MAKENH_VTN:null,
        KETCUOI_ID:object.hasOwnProperty('KETCUOI_ID')?object.KETCUOI_ID:null,

        KINHDO_LD:object.hasOwnProperty('KINHDO_LD')?object.KINHDO_LD:null,
        VIDO_LD:object.hasOwnProperty('VIDO_LD')?object.VIDO_LD:null,
        SITE_ID:object.hasOwnProperty('SITE_ID')?object.SITE_ID:null,
        CONGNGHE_ID:object.hasOwnProperty('CONGNGHE_ID')?object.CONGNGHE_ID:null,
        SL_SOIQUANG:object.hasOwnProperty('SL_SOIQUANG')?object.SL_SOIQUANG:null,
        CHUQUANLD_ID:object.hasOwnProperty('CHUQUANLD_ID')?object.CHUQUANLD_ID:null,
        MA_VNPT:object.hasOwnProperty('MA_VNPT')?object.MA_VNPT:null,
        TINH_ID:object.hasOwnProperty('TINH_ID')?object.TINH_ID:null,
        TINH_DC_ID:object.hasOwnProperty('TINH_DC_ID')?object.TINH_DC_ID:null,
        MA_BSS:object.hasOwnProperty('MA_BSS')?object.MA_BSS:null
    }
}
export {
    newThongSoThueBao,
    createObjectHDKH,
    createObjectHDTB,
    createObjectHDTB_CD,
    createObjectHDTB_IMS,
    createObjectHDTB_ADSL,
    createObjectHDTB_MGWAN,
    createObjectHDTB_TSL,
    createObjectHD_BANCHEO,
    createObjectHDTB_BANCHEO,
    createObjectHDTBBC_CD,
    createObjectHDTBBC_IMS,
    createObjectHDTBBC_ADSL,
    createObjectHDTBBC_MGWAN,
    createObjectHDTBBC_TSL
}

 
