export default [
    {
        CHON: "s0",
        LANTAO_ID: "523421",
        NGUOITAO: "admin",
        XULYNO_ID: "994",
        MA_XLN: "HPG-05-249116",
        MATB_DD: "3594104",
        TEN_TT: "Trần Thị Nhuần",
        DIACHI_TT: "Thôn 1 - Ngô Hùng - Xã An Hồng - Huyện An Dương",
        NVTC_ID: "",
        MANV_TC: "-",
        MST: "",
        SO_CV: "1",
        NOGOC: "",
        THUE: "",
        HOAHONG: "",
        TONGNO: "0",
        NODK: "0",
        NOPS: "0",
        THANGNO: "0",
        BUOCXLN_ID_NEXT: "5",
        NGAYCHUYEN: "",
        NGUOICHUYEN: "",
        NHANVIEN_ID_NEXT: "",
        NGAYHAN: "",
        NHANVIEN_PL_ID: "",
        MA_TT: "",
        MA_KH: "HPG-000685142",
        BUOCCHUYEN: "Quy trình xử lý nợ",
        NO_GIAO: 44000,
        NO_LECH: 44000
    },
    {
        CHON: "s0",
        LANTAO_ID: "523421",
        NGUOITAO: "admin",
        XULYNO_ID: "995",
        MA_XLN: "HPG-05-299533",
        MATB_DD: "3594208",
        TEN_TT: "Nguyễn Thị Vân",
        DIACHI_TT: "Tất Sứng - Xã An Hồng - Huyện An Dương",
        NVTC_ID: "",
        MANV_TC: "-",
        MST: "",
        SO_CV: "2",
        NOGOC: "",
        THUE: "",
        HOAHONG: "",
        TONGNO: "0",
        NODK: "0",
        NOPS: "0",
        THANGNO: "0",
        BUOCXLN_ID_NEXT: "5",
        NGAYCHUYEN: "",
        NGUOICHUYEN: "",
        NHANVIEN_ID_NEXT: "",
        NGAYHAN: "",
        NHANVIEN_PL_ID: "",
        MA_TT: "",
        MA_KH: "HPG-000716226",
        BUOCCHUYEN: "Quy trình xử lý nợ",
        NO_GIAO: 44000,
        NO_LECH: 44000
    },
    {
        CHON: "s0",
        LANTAO_ID: "523421",
        NGUOITAO: "admin",
        XULYNO_ID: "996",
        MA_XLN: "HPG-05-261773",
        MATB_DD: "3594331",
        TEN_TT: "Đồng Đức Hiệu",
        DIACHI_TT: "Lê Lác 1 - Xã An Hồng - Huyện An Dương",
        NVTC_ID: "",
        MANV_TC: "-",
        MST: "",
        SO_CV: "3",
        NOGOC: "",
        THUE: "",
        HOAHONG: "",
        TONGNO: "0",
        NODK: "0",
        NOPS: "0",
        THANGNO: "0",
        BUOCXLN_ID_NEXT: "5",
        NGAYCHUYEN: "",
        NGUOICHUYEN: "",
        NHANVIEN_ID_NEXT: "",
        NGAYHAN: "",
        NHANVIEN_PL_ID: "",
        MA_TT: "",
        MA_KH: "HPG-000692612",
        BUOCCHUYEN: "Quy trình xử lý nợ",
        NO_GIAO: 44000,
        NO_LECH: 44000
    },
    {
        CHON: "s0",
        LANTAO_ID: "523421",
        NGUOITAO: "admin",
        XULYNO_ID: "997",
        MA_XLN: "HPG-05-356060",
        MATB_DD: "3594547",
        TEN_TT: "Nguyễn Hữu Mạnh",
        DIACHI_TT: "Lê Sáng - Xã An Hồng - Huyện An Dương",
        NVTC_ID: "",
        MANV_TC: "-",
        MST: "",
        SO_CV: "4",
        NOGOC: "",
        THUE: "",
        HOAHONG: "",
        TONGNO: "0",
        NODK: "0",
        NOPS: "0",
        THANGNO: "0",
        BUOCXLN_ID_NEXT: "5",
        NGAYCHUYEN: "",
        NGUOICHUYEN: "",
        NHANVIEN_ID_NEXT: "",
        NGAYHAN: "",
        NHANVIEN_PL_ID: "",
        MA_TT: "",
        MA_KH: "HPG-000737058",
        BUOCCHUYEN: "Quy trình xử lý nợ",
        NO_GIAO: 44000,
        NO_LECH: 44000
    },
    {
        CHON: "s0",
        LANTAO_ID: "523421",
        NGUOITAO: "admin",
        XULYNO_ID: "998",
        MA_XLN: "HPG-05-296329",
        MATB_DD: "3594705",
        TEN_TT: "Chu Đức Khanh",
        DIACHI_TT: "Lê Sáng - Xã An Hồng - Huyện An Dương",
        NVTC_ID: "",
        MANV_TC: "-",
        MST: "",
        SO_CV: "5",
        NOGOC: "",
        THUE: "",
        HOAHONG: "",
        TONGNO: "0",
        NODK: "0",
        NOPS: "0",
        THANGNO: "0",
        BUOCXLN_ID_NEXT: "5",
        NGAYCHUYEN: "",
        NGUOICHUYEN: "",
        NHANVIEN_ID_NEXT: "",
        NGAYHAN: "",
        NHANVIEN_PL_ID: "",
        MA_TT: "",
        MA_KH: "HPG-000714296",
        BUOCCHUYEN: "Quy trình xử lý nợ",
        NO_GIAO: 44000,
        NO_LECH: 44000
    },
    {
        CHON: "s0",
        LANTAO_ID: "523421",
        NGUOITAO: "admin",
        XULYNO_ID: "999",
        MA_XLN: "HPG-05-302354",
        MATB_DD: "3594758",
        TEN_TT: "Trần Thị Trước",
        DIACHI_TT: "Lê Lác 2 - Xã An Hồng - Huyện An Dương",
        NVTC_ID: "",
        MANV_TC: "-",
        MST: "",
        SO_CV: "6",
        NOGOC: "",
        THUE: "",
        HOAHONG: "",
        TONGNO: "0",
        NODK: "0",
        NOPS: "0",
        THANGNO: "0",
        BUOCXLN_ID_NEXT: "5",
        NGAYCHUYEN: "",
        NGUOICHUYEN: "",
        NHANVIEN_ID_NEXT: "",
        NGAYHAN: "",
        NHANVIEN_PL_ID: "",
        MA_TT: "",
        MA_KH: "HPG-000720461",
        BUOCCHUYEN: "Quy trình xử lý nợ",
        NO_GIAO: 44000,
        NO_LECH: 44000
    },
    {
        CHON: "s0",
        LANTAO_ID: "523421",
        NGUOITAO: "admin",
        XULYNO_ID: "1000",
        MA_XLN: "HPG-05-265266",
        MATB_DD: "3594901",
        TEN_TT: "Lê Văn Việt",
        DIACHI_TT: "Ngô Hùng - Xã An Hồng - Huyện An Dương",
        NVTC_ID: "",
        MANV_TC: "-",
        MST: "",
        SO_CV: "7",
        NOGOC: "",
        THUE: "",
        HOAHONG: "",
        TONGNO: "0",
        NODK: "0",
        NOPS: "0",
        THANGNO: "0",
        BUOCXLN_ID_NEXT: "5",
        NGAYCHUYEN: "",
        NGUOICHUYEN: "",
        NHANVIEN_ID_NEXT: "",
        NGAYHAN: "",
        NHANVIEN_PL_ID: "",
        MA_TT: "",
        MA_KH: "HPG-000696375",
        BUOCCHUYEN: "Quy trình xử lý nợ",
        NO_GIAO: 44000,
        NO_LECH: 44000
    },
    {
        CHON: "s0",
        LANTAO_ID: "523421",
        NGUOITAO: "admin",
        XULYNO_ID: "1001",
        MA_XLN: "HPG-05-268730",
        MATB_DD: "3594928",
        TEN_TT: "Nguyễn Thị Hà",
        DIACHI_TT: "Khánh Thịnh - Xã An Hồng - Huyện An Dương",
        NVTC_ID: "",
        MANV_TC: "-",
        MST: "",
        SO_CV: "8",
        NOGOC: "",
        THUE: "",
        HOAHONG: "",
        TONGNO: "0",
        NODK: "0",
        NOPS: "0",
        THANGNO: "0",
        BUOCXLN_ID_NEXT: "5",
        NGAYCHUYEN: "",
        NGUOICHUYEN: "",
        NHANVIEN_ID_NEXT: "",
        NGAYHAN: "",
        NHANVIEN_PL_ID: "",
        MA_TT: "",
        MA_KH: "HPG-000696382",
        BUOCCHUYEN: "Quy trình xử lý nợ",
        NO_GIAO: 44000,
        NO_LECH: 44000
    },
    {
        CHON: "s0",
        LANTAO_ID: "523421",
        NGUOITAO: "admin",
        XULYNO_ID: "1002",
        MA_XLN: "HPG-05-269567",
        MATB_DD: "3594937",
        TEN_TT: "Phạm Văn Động",
        DIACHI_TT: "Tất Sứng - Xã An Hồng - Huyện An Dương",
        NVTC_ID: "",
        MANV_TC: "-",
        MST: "",
        SO_CV: "9",
        NOGOC: "",
        THUE: "",
        HOAHONG: "",
        TONGNO: "0",
        NODK: "0",
        NOPS: "0",
        THANGNO: "0",
        BUOCXLN_ID_NEXT: "5",
        NGAYCHUYEN: "",
        NGUOICHUYEN: "",
        NHANVIEN_ID_NEXT: "",
        NGAYHAN: "",
        NHANVIEN_PL_ID: "",
        MA_TT: "",
        MA_KH: "HPG-000698182",
        BUOCCHUYEN: "Quy trình xử lý nợ",
        NO_GIAO: 44000,
        NO_LECH: 44000
    },
    {
        CHON: "s0",
        LANTAO_ID: "523421",
        NGUOITAO: "admin",
        XULYNO_ID: "1003",
        MA_XLN: "HPG-05-245157",
        MATB_DD: "3618157",
        TEN_TT: "Cty Cp Đầu Tư Xây Lắp Điện Hp",
        DIACHI_TT: "trong uỷ ban xã Lê Sáng - Xã An Hồng - Huyện An Dương",
        NVTC_ID: "",
        MANV_TC: "-",
        MST: "",
        SO_CV: "10",
        NOGOC: "",
        THUE: "",
        HOAHONG: "",
        TONGNO: "0",
        NODK: "0",
        NOPS: "0",
        THANGNO: "0",
        BUOCXLN_ID_NEXT: "5",
        NGAYCHUYEN: "",
        NGUOICHUYEN: "",
        NHANVIEN_ID_NEXT: "",
        NGAYHAN: "",
        NHANVIEN_PL_ID: "",
        MA_TT: "",
        MA_KH: "HPG-000682281",
        BUOCCHUYEN: "Quy trình xử lý nợ",
        NO_GIAO: 44000,
        NO_LECH: 44000
    },
    {
        CHON: "s0",
        LANTAO_ID: "523421",
        NGUOITAO: "admin",
        XULYNO_ID: "1004",
        MA_XLN: "HPG-05-729016",
        MATB_DD: "3618344",
        TEN_TT: "Bùi Văn Xoan",
        DIACHI_TT: "Đội 3 - Xóm Chùa - Xã An Hồng - Huyện An Dương",
        NVTC_ID: "",
        MANV_TC: "-",
        MST: "",
        SO_CV: "11",
        NOGOC: "",
        THUE: "",
        HOAHONG: "",
        TONGNO: "0",
        NODK: "0",
        NOPS: "0",
        THANGNO: "0",
        BUOCXLN_ID_NEXT: "5",
        NGAYCHUYEN: "",
        NGUOICHUYEN: "",
        NHANVIEN_ID_NEXT: "",
        NGAYHAN: "",
        NHANVIEN_PL_ID: "",
        MA_TT: "",
        MA_KH: "HPG-000632260",
        BUOCCHUYEN: "Quy trình xử lý nợ",
        NO_GIAO: 44550,
        NO_LECH: 44550
    },
    {
        CHON: "s0",
        LANTAO_ID: "523421",
        NGUOITAO: "admin",
        XULYNO_ID: "1005",
        MA_XLN: "HPG-05-256501",
        MATB_DD: "3618879",
        TEN_TT: "Trương Văn Dòn",
        DIACHI_TT: "Lê Lác 2 - Xã An Hồng - Huyện An Dương",
        NVTC_ID: "",
        MANV_TC: "-",
        MST: "",
        SO_CV: "12",
        NOGOC: "",
        THUE: "",
        HOAHONG: "",
        TONGNO: "0",
        NODK: "0",
        NOPS: "0",
        THANGNO: "0",
        BUOCXLN_ID_NEXT: "5",
        NGAYCHUYEN: "",
        NGUOICHUYEN: "",
        NHANVIEN_ID_NEXT: "",
        NGAYHAN: "",
        NHANVIEN_PL_ID: "",
        MA_TT: "",
        MA_KH: "HPG-000690464",
        BUOCCHUYEN: "Quy trình xử lý nợ",
        NO_GIAO: 64000,
        NO_LECH: 64000
    },
    {
        CHON: "s0",
        LANTAO_ID: "523421",
        NGUOITAO: "admin",
        XULYNO_ID: "1006",
        MA_XLN: "HPG-05-387358",
        MATB_DD: "3924381",
        TEN_TT: "Trương Văn Hiền",
        DIACHI_TT: "Lê Lác 2 - Xã An Hồng - Huyện An Dương",
        NVTC_ID: "",
        MANV_TC: "-",
        MST: "",
        SO_CV: "13",
        NOGOC: "",
        THUE: "",
        HOAHONG: "",
        TONGNO: "0",
        NODK: "0",
        NOPS: "0",
        THANGNO: "0",
        BUOCXLN_ID_NEXT: "5",
        NGAYCHUYEN: "",
        NGUOICHUYEN: "",
        NHANVIEN_ID_NEXT: "",
        NGAYHAN: "",
        NHANVIEN_PL_ID: "",
        MA_TT: "",
        MA_KH: "HPG-000751183",
        BUOCCHUYEN: "Quy trình xử lý nợ",
        NO_GIAO: 44000,
        NO_LECH: 44000
    },
    {
        CHON: "s0",
        LANTAO_ID: "523421",
        NGUOITAO: "admin",
        XULYNO_ID: "1007",
        MA_XLN: "HPG-05-264697",
        MATB_DD: "3971713",
        TEN_TT: "Nguyễn Thị Dưỡng",
        DIACHI_TT: "Song Mai - Xã An Hồng - Huyện An Dương",
        NVTC_ID: "",
        MANV_TC: "-",
        MST: "",
        SO_CV: "14",
        NOGOC: "",
        THUE: "",
        HOAHONG: "",
        TONGNO: "0",
        NODK: "0",
        NOPS: "0",
        THANGNO: "0",
        BUOCXLN_ID_NEXT: "5",
        NGAYCHUYEN: "",
        NGUOICHUYEN: "",
        NHANVIEN_ID_NEXT: "",
        NGAYHAN: "",
        NHANVIEN_PL_ID: "",
        MA_TT: "",
        MA_KH: "HPG-000696272",
        BUOCCHUYEN: "Quy trình xử lý nợ",
        NO_GIAO: 44000,
        NO_LECH: 44000
    }
];
