export default {
  cols: [
    {
      fieldName: "ma_sc",
      headerText: "Mã sự cố",
      allowFiltering: true,
      allowSorting: false,
      freeze: 'left',
      width: 120
    },
    {
      fieldName: "he_thong",
      headerText: "Hệ thống, dịch vụ bị sự cố",
      allowFiltering: true,
      allowSorting: false,
      textAlign: 'right',
      width: 120,
      freeze: 'left',
    },
    {
      fieldName: "noidung_sc",
      headerText: "Nội dung chi tiết sự cố",
      allowFiltering: true,
      allowSorting: false,
      width: 120,
    },
    {
      fieldName: "tg_batdau",
      headerText: "Thời gian xảy ra",
      allowFiltering: true,
      allowSorting: false,
      width: 120,
    },
    {
      fieldName: "tg_ketthuc",
      headerText: "Thời gian kết thúc",
      allowFiltering: true,
      allowSorting: false,
      width: 120,
    },
    {
      fieldName: "tg_xuly",
      headerText: "Thời gian xử lý (h)",
      allowFiltering: true,
      allowSorting: false,
      width: 100,
    },
    {
      fieldName: "tg_dukien",
      headerText: "Thời gian dự kiến xử lý",
      allowFiltering: true,
      allowSorting: false,
      width: 120,
    },
    {
      fieldName: "mucdo_sc",
      headerText: "Mức độ sự cố",
      allowFiltering: true,
      allowSorting: false,
      width: 100,
    },
    {
      fieldName: "donvi_chutri",
      headerText: "ĐV chủ trì xử lý",
      allowFiltering: true,
      allowSorting: false,
      width: 120,
    },
    {
      fieldName: "nguyen_nhan",
      headerText: "Nguyên nhân",
      allowFiltering: true,
      allowSorting: false,
      width: 100,
    },
    {
      fieldName: "tuan",
      headerText: "Tuần",
      allowFiltering: true,
      allowSorting: false,
      width: 70,
    },
    {
      fieldName: "thang",
      headerText: "Tháng",
      allowFiltering: true,
      allowSorting: false,
      width: 70,
    },
    {
      fieldName: "phamvi_ah",
      headerText: "Phạm vi ảnh hưởng",
      allowFiltering: true,
      allowSorting: false,
      width: 100,
    },
    {
      fieldName: "slg_thuebao",
      headerText: "Số lượng TB ảnh hưởng",
      allowFiltering: true,
      allowSorting: false,
      width: 100,
    },
    {
      fieldName: "donvi_nhap",
      headerText: "Đơn vị nhập SC",
      allowFiltering: true,
      allowSorting: false,
      width: 120,
    },
    {
      fieldName: "lienhe",
      headerText: "Đầu mối liên hệ",
      allowFiltering: true,
      allowSorting: false,
      width: 100,
    },
    {
      fieldName: "tiendo_xuly",
      headerText: "Tiến độ xử lý",
      allowFiltering: true,
      allowSorting: false,
      width: 100,
    }
  ],
}
