const collumns = {
    collumnsVNP: [
        {
            fieldName: "",
            headerText: "Ngày thực hiện",
            allowSorting: false,
            allowFiltering: true,
            width: "100",
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "name",
            headerText: "Mã dịch vụ",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            textAlign: 'left',
        },
        {
            fieldName: "name",
            headerText: "Thao tác",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            textAlign: 'left',
        },
        {
            fieldName: "name",
            headerText: "Ghi chú",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            textAlign: 'left',
        },
        {
            fieldName: "name",
            headerText: "Người dùng",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            textAlign: 'left',
        },
        {
            fieldName: "name",
            headerText: "MSIN cũ",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            textAlign: 'left',
        },
        {
            fieldName: "name",
            headerText: "MSIN mới",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            textAlign: 'left',
        },
        {
            fieldName: "name",
            headerText: "Tỉnh cũ",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            textAlign: 'left',
        },
        {
            fieldName: "name",
            headerText: "Tỉnh mới",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            textAlign: 'left',
        },
    ],
    collumnsCauhoi: [
        {
            fieldName: "cauhoi_id",
            headerText: "T",
            allowFiltering: true,
            width: "50",
            autoFit: "true",
            textAlign: 'center',
        },
        {
            fieldName: "mangthi",
            headerText: "Mảng thi",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            textAlign: 'left',
        },
        {
            fieldName: "chude",
            headerText: "Chủ đề",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            textAlign: 'left',
        },
        {
            fieldName: "noidung",
            headerText: "Câu hỏi",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            textAlign: 'left',
        },
        {
            fieldName: "hienthi",
            headerText: "Hiển thị",
            type:"checkBox",
            headerTemplate:"<th class='w60'>Hiển thị</th>",
            allowSorting: false,
            allowFiltering: true,
            filterTemplate:"<th class='w60'>Hiển thị</th>",
            textAlign: 'center',
            width: "50",
            autoFit: "true",
        },
    ],
    collumnsDapan: [
        {
            fieldName: "dapan_id",
            headerText: "Số thứ tự",
            allowFiltering: true,
            width: "50",
            autoFit: "true",
            textAlign: 'center',
        },
        {
            fieldName: "noidung",
            headerText: "Nội dung",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            textAlign: 'left',
        },
        {
            fieldName: "ketqua",
            headerText: "Kết quả",
            allowFiltering: true,
            headerTemplate:"<th class='w60'>Kết quả</th>",
            type:"checkBox",
            width: "40",
            autoFit: "true",
            textAlign: 'center',
        }
    ],
    collumnsDSChude: [
        {
            fieldName: "chude_id",
            headerText: "ID",
            allowFiltering: true,
            width: "50",
            autoFit: "true",
            textAlign: 'center',
        },
        {
            fieldName: "chude",
            headerText: "Chủ đề",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            textAlign: 'left',
        }
    ],
    collumnsDSMangthi: [
        {
            fieldName: "mangthi_id",
            headerText: "ID",
            allowFiltering: true,
            width: "50",
            autoFit: "true",
            textAlign: 'center',
        },
        {
            fieldName: "mangthi",
            headerText: "Mảng thi",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            textAlign: 'left',
        }
    ],
}

export default collumns
