export const POST_CATEGORIES = {
  ANNOUNCEMENT: 'ANNOUNCEMENT',
  PRESS_REPORT: 'PRESS_REPORT',
  FREQUENTLY_ASKED: {
    FREQUENTLY_ASKED_BASIC_TRAINING: 'FREQUENTLY_ASKED_BASIC_TRAINING',
    FREQUENTLY_ASKED_ETC: 'FREQUENTLY_ASKED_ETC',
    FREQUENTLY_ASKED_LUCETTE: 'FREQUENTLY_ASKED_LUCETTE',
    FREQUENTLY_ASKED_FUNERAL_SERVICE: 'FREQUENTLY_ASKED_FUNERAL_SERVICE',
    FREQUENTLY_ASKED_FUNERAL_MATERIAL: 'FREQUENTLY_ASKED_FUNERAL_MATERIAL',
  },
  JOURNAL: {
    JOURNAL_HEALTH: 'JOURNAL_HEALTH',
    JOURNAL_EDUCATION: 'JOURNAL_EDUCATION',
    JOURNAL_ETC: 'JOURNAL_ETC',
    JOURNAL_CULTURAL: 'JOURNAL_CULTURAL',
    // JOURNAL_LAW: 'JOURNAL_LAW',
    JOURNAL_FUNERAL: 'JOURNAL_FUNERAL',
    JOURNAL_PETRO: 'JOURNAL_PETRO',
  },
};
