import moment from "moment"
export default {
    gridbox: {
        bohoso: {
            list: [],
            header: [],
            value: {},
        },
        filehoso: {
            list: [],
            header: [],
            value: {},
        },
        hdthuebao: {
            list: [],
            header: [],
            value: {},
        },
    },
    dateconfig: {
        altFormat: "d/m/Y H:i:S",
        altInput: true,
        dateFormat: "d/m/Y H:i:S",
        allowInput: true,
        enableTime: true,
    },
    // phieu_id: 0,
    // baohong_id: 0,
    // hdtb_id:  0,
    vdvtram_id: 0,
    _check: 0,
    // vtthd_id: -1,
    ttbh_id: 0,
    IS_USING_LACHUONG_BH: 1,
    Tag:"",
    tag_hdbh: -1,//1 la hd 2 la boahong
    txtMaTB:'',
    btnLayTTMoi:{
        Visible:true
    },
    layout_DSLacHuong:{
        Visibility:true
    },
    layoutCT_DHXL:{
        Text:"Thông tin phiếu yêu cầu",
        Visibility:true,
    },
    cbx_donviql:[],
    cbx_donvi:[],
    cbx_dichvu:[],
    DanhSachLH_Select:[],
    formTT: {
        ma_tb: "",
        ngay_bh: "",
        dichvuvt_id: 0,
        loaihinh_tb: "",
        ten_tb: "",
        diachi_ld: "",
        ghichu: "",
        nguoigiao: "",
        noinhan: "", 
        trangthai_bh: "",
        donvi_ql_id:0,
        donvi_nhan_id:0,
        noidung:"",
    },
    gvDanhSach: {
        tableCollumns: [
            { fieldName: 'MA_TB', headerText: 'Số máy/Acc', allowFiltering: true, allowSorting: true,freeze:"left" },
            { fieldName: 'MA_LT', headerText: 'Số ảo', allowFiltering: true, allowSorting: true ,freeze:"left"},
            { fieldName: 'LOAIHINH_TB', headerText: 'Loại hình', allowFiltering: true, allowSorting: true,freeze:"left" },
            { fieldName: 'TEN_TB', headerText: 'Tên thuê bao', allowFiltering: true, allowSorting: true ,freeze:"left"},
            { fieldName: 'DIACHI_LD', headerText: 'Địa chỉ LĐ', allowFiltering: true, allowSorting: true ,freeze:"left"},
            { fieldName: 'DONVINHAN', headerText: 'Đơn vị nhận', allowFiltering: true, allowSorting: true },
            { fieldName: 'DIACHI_DAU', headerText: 'Địa chỉ LĐ (Điểm đầu)', allowFiltering: true, allowSorting: true },
            { fieldName: 'DIACHI_CUOI', headerText: 'Địa chỉ LĐ (Điểm cuối)', allowFiltering: true, allowSorting: true },
            { fieldName: 'NGAY_BH', headerText: 'Ngày BH', format: {type: 'date', format: 'dd/MM/yyyy HH:mm:ss'},type: 'date',allowFiltering: true, allowSorting: true,textAlign:'Right' },
            { fieldName: 'GOI_KT', headerText: 'Gói KT', allowFiltering: true, allowSorting: true },
            { fieldName: 'KENH_TN', headerText: 'Kênh tiếp nhận', allowFiltering: true, allowSorting: true },
            { fieldName: 'CHITIEU_TG', headerText: 'Chỉ tiêu TG', allowFiltering: true, allowSorting: true ,textAlign:'Right'},
            { fieldName: 'TGXL', headerText: 'Giờ XL', allowFiltering: true, allowSorting: true,textAlign:'Right' },
            { fieldName: 'GIO_CK', headerText: 'Giờ CK', allowFiltering: true, allowSorting: true,textAlign:'Right' },
            { fieldName: 'GIO_CONLAI', headerText: 'Giờ còn lại', allowFiltering: true, allowSorting: true,textAlign:'Right' },
            { fieldName: 'MUCDO', headerText: 'Mức độ', allowFiltering: true, allowSorting: true },
            { fieldName: 'DS_NHANVIEN_TH', headerText: 'Nhân viên TH', allowFiltering: true, allowSorting: true },
            { fieldName: 'TINHTRANG', headerText: 'Tình trạng', allowFiltering: true, allowSorting: true },
            { fieldName: 'TEN_PLKH', headerText: 'Phân loại KH', allowFiltering: true, allowSorting: true },
            { fieldName: 'DIENTHOAI_LH', headerText: 'Số liên hệ', allowFiltering: true, allowSorting: true },
            { fieldName: 'LUOT_BH', headerText: 'Lượt BH', allowFiltering: true, allowSorting: true,textAlign:'Right' },
            { fieldName: 'LAN_PA', headerText: 'KH gọi', allowFiltering: true, allowSorting: true },
            { fieldName: 'NGUYENNHAN', headerText: 'Nguyên nhân', allowFiltering: true, allowSorting: true },
            { fieldName: 'NGAYGIAO', headerText: 'Ngày giao', allowFiltering: true, allowSorting: true,format: {type: 'date', format: 'dd/MM/yyyy HH:mm:ss'},type: 'date',textAlign:'Right' },
            { fieldName: 'ND_GIAO', headerText: 'Nội dung giao', allowFiltering: true, allowSorting: true },
            { fieldName: 'LAN_KS', headerText: 'Lần KS', allowFiltering: true, allowSorting: true ,textAlign:'Right'},
            { fieldName: 'NGAY_SD', headerText: 'Ngày SD', format: {type: 'date', format: 'dd/MM/yyyy HH:mm:ss'},type: 'date',allowFiltering: true, allowSorting: true },
            { fieldName: 'GHICHU_HONG', headerText: 'Ghi chú hỏng', allowFiltering: true, allowSorting: true },
            { fieldName: 'GHICHU_TH', headerText: 'Ghi chú TH', allowFiltering: true, allowSorting: true },
            { fieldName: 'LYDOTON', headerText: 'Lý do tồn', allowFiltering: true, allowSorting: true },
            { fieldName: 'GHICHUTON', headerText: 'Ghi chú tồn', allowFiltering: true, allowSorting: true },
            { fieldName: 'TEN_DV', headerText: 'Đơn vị giao', allowFiltering: true, allowSorting: true },
            { fieldName: 'NHANVIENQL', headerText: 'Nhân viên QL', allowFiltering: true, allowSorting: true },
            { fieldName: 'TEN_DV', headerText: 'ĐV giao', allowFiltering: true, allowSorting: true },
            { fieldName: 'TEN_CAP', headerText: 'Cáp gốc', allowFiltering: true, allowSorting: true },
            { fieldName: 'DOI_CAP', headerText: 'Đôi số', allowFiltering: true, allowSorting: true },
            { fieldName: 'TEN_KC', headerText: 'Kết cuối', allowFiltering: true, allowSorting: true },
            { fieldName: 'VITRI', headerText: 'Vị trí', allowFiltering: true, allowSorting: true },
            { fieldName: 'TIENTRINH', headerText: 'Tiến trình', allowFiltering: true, allowSorting: true },
            { fieldName: 'HENSUATU', headerText: 'Hẹn sửa từ', format: {type: 'date', format: 'dd/MM/yyyy HH:mm:ss'},type: 'date',allowFiltering: true, allowSorting: true ,textAlign:'Right'},
            { fieldName: 'HENSUADEN', headerText: 'Hẹn sửa đến', format: {type: 'date', format: 'dd/MM/yyyy HH:mm:ss'},type: 'date',allowFiltering: true, allowSorting: true,textAlign:'Right' },
            { fieldName: 'TEN_KV', headerText: 'Khu vực', allowFiltering: true, allowSorting: true },
            { fieldName: 'NVKT_DB', headerText: 'Nhân viên kỹ thuật ', allowFiltering: true, allowSorting: true },
            { fieldName: 'NVKD_DB', headerText: 'Nhân viên kinh doanh', allowFiltering: true, allowSorting: true },
            { fieldName: 'ND_TRA_CON', headerText: 'Nội dung trả', allowFiltering: true, allowSorting: true },
            { fieldName: 'NGAYTRA_CON', headerText: 'Ngày trả', allowFiltering: true, allowSorting: true },
            { fieldName: 'CHUYENMANG', headerText: 'NCC khác', allowFiltering: true, allowSorting: true },
                                    
        ],
        tableData:[],
    },
    gvChitiet: {
        tableCollumns: [
            { fieldName: 'HUONGGIAO', headerText: 'Đơn vị giao', allowFiltering: true, allowSorting: true, isGroupedColumn: true, },
            { fieldName: 'DVG', headerText: 'Đơn vị giao', allowFiltering: true, allowSorting: true },
            { fieldName: 'NV_GIAO', headerText: 'Nhân viên giao', allowFiltering: true, allowSorting: true },
            { fieldName: 'NGAY_GIAO', headerText: 'Ngày giao', allowFiltering: true, allowSorting: true },
            { fieldName: 'ND_GIAO', headerText: 'Nội dung giao', allowFiltering: true, allowSorting: true },
            { fieldName: 'DVN', headerText: 'Đơn vị nhận', allowFiltering: true, allowSorting: true },
            { fieldName: 'NGAY_TRA', headerText: 'Ngày trả', allowFiltering: true, allowSorting: true },
            { fieldName: 'ND_TRA', headerText: 'Nội dung trả', allowFiltering: true, allowSorting: true },
            { fieldName: 'TRANGTHAI_PH', headerText: 'Trạng thái phiếu', allowFiltering: true, allowSorting: true },
            { fieldName: 'NV_TH', headerText: 'Nhân viên TH', allowFiltering: true, allowSorting: true },
            { fieldName: 'NGAY_TH', headerText: 'Ngày TH', format: {type: 'date', format: 'dd/MM/yyyy HH:mm:ss'},type: 'date',allowFiltering: true, allowSorting: true,textAlign:'Right' },
            { fieldName: 'GHICHU_TH', headerText: 'Nội dung TH', allowFiltering: true, allowSorting: true },              
        ],
        tableData:[],
    },
    
}