export enum POST_VISIBILITY {
  RELEASE = 'RELEASE',
  PRIVATE = 'PRIVATE',
}

export enum POST_CATEGORIES {
  ANNOUNCEMENT = 'ANNOUNCEMENT',
  FREQUENTLY_ASKED = 'FREQUENTLY_ASKED',
  FREQUENTLY_ASKED_BASIC_TRAINING = 'FREQUENTLY_ASKED_BASIC_TRAINING',
  FREQUENTLY_ASKED_ETC = 'FREQUENTLY_ASKED_ETC',
  FREQUENTLY_ASKED_LUCETTE = 'FREQUENTLY_ASKED_LUCETTE',
  FREQUENTLY_ASKED_FUNERAL_SERVICE = 'FREQUENTLY_ASKED_FUNERAL_SERVICE',
  FREQUENTLY_ASKED_FUNERAL_MATERIAL = 'FREQUENTLY_ASKED_FUNERAL_MATERIAL',
  JOURNAL = 'JOURNAL',
  // JOURNAL_LAW = 'JOURNAL_LAW',
  JOURNAL_CULTURAL = 'JOURNAL_CULTURAL',
  JOURNAL_EDUCATION = 'JOURNAL_EDUCATION',
  JOURNAL_FUNERAL = 'JOURNAL_FUNERAL',
  JOURNAL_HEALTH = 'JOURNAL_HEALTH',
  JOURNAL_PETRO = 'JOURNAL_PETRO',
  JOURNAL_ETC = 'JOURNAL_ETC',
  PRESS_REPORT = 'PRESS_REPORT',
}

export enum POST_EXPOSURE {
  EXPOSED = 'EXPOSED',
  UNEXPOSED = 'UNEXPOSED',
}
