export enum ROOM_TYPE {
  NONE = 'NONE',
  MEMORIAL_HALL_1 = 'MEMORIAL_HALL_1',
  MEMORIAL_HALL_2 = 'MEMORIAL_HALL_2',
  MEMORIAL_HALL_3 = 'MEMORIAL_HALL_3',
  CREMATORIUM_1 = 'CREMATORIUM_1',
  CREMATORIUM_2 = 'CREMATORIUM_2',
  CREMATORIUM_3 = 'CREMATORIUM_3',
  CREMATORIUM_4 = 'CREMATORIUM_4',
}
