export default {
     
    contextMenuItems: [
      {text: 'Đánh dấu hoàn thành', id: 'dstn_danhauhoanthanh', target: '.e-content', },
      {text: 'Không nhận khách hàng', id: 'dstn_khongnhanKH', target: '.e-content',
      items: 
      [
       { text: 'Không chuyển tỉnh khác',id: '0' },
       { text: 'Chuyển An Giang' ,id: '1'},
       { text: 'Chuyển Bà Rịa Vũng Tàu',id: '2' },
       { text: 'Chuyển Bắc Giang' ,id: '3'},
       { text: 'Chuyển Bắc Cạn' ,id: '4'},
       { text: 'Chuyển Bắc Ninh' ,id: '5'},
       { text: 'Chuyển Bình Định ' ,id: '6'},
       { text: 'Chuyển Bến Tre' ,id: '7'},
       { text: 'Chuyển Bình Dương' ,id: '8'},
       { text: 'Chuyển Bình Phước' ,id: '9'},
       { text: 'Chuyển Bình Thuận' ,id: '10'},
       { text: 'Chuyển Bạc Liêu' ,id: '11'},
       { text: 'Chuyển Cao Bằng' ,id: '12'},
       { text: 'Chuyển Cần Thơ' ,id: '13'},
       { text: 'Chuyển Cà Mau ' ,id: '14'},
       { text: 'Chuyển Tp.Đà Nẵng' ,id: '15'},
       { text: 'Chuyển Đắc Lắc' ,id: '16'},
       { text: 'Chuyển Đồng Nai' ,id: '17'},
       { text: 'Chuyển Đồng Tháp' ,id: '18'},
       { text: 'Chuyển Gia Lai' ,id: '19'},
       { text: 'Chuyển Hà Giang' ,id: '20'},
       { text: 'Chuyển Hà Nội' ,id: '21'},
       { text: 'Chuyển Điện Biên' ,id: '22'},
       { text: 'Chuyển Hà Tĩnh' ,id: '23'},
       { text: 'Chuyển Hưng Yên ' ,id: '24'},
       { text: 'Chuyển Hà Nam' ,id: '25'},
       { text: 'Chuyển Hải Phòng' ,id: '26'},
       { text: 'Chuyển Hải Dương ' ,id: '27'},
       { text: 'Chuyển Tp Hồ Chí Minh' ,id: '28'},
       { text: 'Chuyển Khánh Hoà' ,id: '29'},
       { text: 'Chuyển Kiên Giang' ,id: '30'},
       { text: 'Chuyển Kon Tum' ,id: '31'},
       { text: 'Chuyển Lai Châu' ,id: '32'},
       { text: 'Chuyển Lạng Sơn' ,id: '33'},
       { text: 'Chuyển Lào Cai' ,id: '34'},
       { text: 'Chuyển Lâm Đồng' ,id: '35'},
       { text: 'Chuyển Long An' ,id: '36'},
       { text: 'Chuyển Nam Định' ,id: '37'},
       { text: 'Chuyển Nghệ An' ,id: '38'},
       { text: 'Chuyển Ninh Bình ' ,id: '40'},
       { text: 'Chuyển Ninh Thuận' ,id: '41'},
       { text: 'Chuyển Phú Yên' ,id: '42'},
       { text: 'Chuyển Quảng Bình' ,id: '43'},
       { text: 'Chuyển Quảng Nam' ,id: '44'},
       { text: 'Chuyển Quảng Ngãi' ,id: '45'},
       { text: 'Chuyển Quảng Ninh' ,id: '46'},
       { text: 'Chuyển Quảng Trị' ,id: '47'},
       { text: 'Chuyển Sóc Trăng' ,id: '48'},
       { text: 'Chuyển Sơn La ' ,id: '49'},
       { text: 'Chuyển Tây Ninh' ,id: '50'},
       { text: 'Chuyển Thái Bình' ,id: '51'},
       { text: 'Chuyển Thanh Hoá' ,id: '52'},
       { text: 'Chuyển Huế' ,id: '53'},
       { text: 'Chuyển Tiền Giang' ,id: '54'},
       { text: 'Chuyển Trà Vinh' ,id: '55'},
       { text: 'Chuyển Tuyên Quang' ,id: '56'},
       { text: 'Chuyển Vĩnh Long' ,id: '57'},
       { text: 'Chuyển Vĩnh Phúc' ,id: '58'},
       { text: 'Chuyển Phú Thọ' ,id: '59'},
       { text: 'Chuyển Yên Bái' ,id: '60'},
       { text: 'Chuyển Thái Nguyên' ,id: '61'},
       { text: 'Chuyển Đắc Nông' ,id: '62'},
       { text: 'Chuyển Hòa Bình' ,id: '63'},
       { text: 'Chuyển Hậu Giang ' ,id: '64'},
       { text: 'Chuyển Khách hàng doanh nghiệp' ,id: '65'},
       { text: 'Đài CSKH Tập trung' ,id: '66'},
       { text: 'Chuyển tất cả các tỉnh' ,id: '67'},
        
      ],
    
    },
    ]
  }
  