export default {
  cboDichVuVT: [],
  cboLoaihinhTB: [],
  gridDanhsachBaohong: [],
  gridDanhsachlapkem: [],
  position: { X: 'center', Y: 'top' },
  form: {
    dichvuvt_id: 4,
    loaitb_id: null,
    ma_tb: null,
    ten_tb: null,
    thuebao_id: 8008505
  },
  dsGiaTriHD: [],
  columnsTBLK: [{
    fieldName: "ma_tb",
    headerText: "Số máy/Acc",
    allowSorting: false,
    width: "100",
    textAlign: 'center',
    autoFit: "true",
  },
  {
    fieldName: "ten_tb",
    headerText: "Tên thuê bao",
    allowSorting: false,
    width: "100",
    textAlign: 'center',
    autoFit: "true",
  },
  {
    fieldName: "ma_tl",
    headerText: "Số ảo",
    allowSorting: false,
    width: "100",
    textAlign: 'center',
    autoFit: "true",
  }
  ],
  DichVuVienThong: {
    TATCA: -1,
    CO_DINH: 1,
    DI_DONG: 2,
    ADSL: 4,
    DD_TRATRUOC: 5,
    EMAIL: 6,
    METRONET: 7,
    MEGAWAN: 8,
    TSL: 9,
    GPHONE: 10,
    IMS: 11,
    MEGA_EYES: 12,
    HOINGHI_TRUYENHINH: 13,
    ANTOAN_BAOMAT_TT: 14,
    DICHVU_CNTT: 15,
    TRUNGTAM_DULIEU: 16,
    HATANG_VIENTHONG: 19,

    IMS_DOITAC: 21,
    BRCD_DOITAC: 22,
    MGW_DOITAC: 23,
    TSL_DOITAC: 24
  },
  columnsDsThuebao: [
    {
      fieldName: "ma_tb",
      headerText: "Account",
      allowSorting: false,
      textAlign: 'center',
      autoFit: "true",
    },
    {
      fieldName: "loaihinh_tb",
      headerText: "Loại hình",
      allowSorting: false,
      textAlign: 'center',
      autoFit: "true",
    },
    {
      fieldName: "ten_tb",
      headerText: "Tên thuê bao",
      allowSorting: false,
      textAlign: 'center',
      autoFit: "true",
    },
    {
      fieldName: "diachi_ld",
      headerText: "Địa chỉ lắp đặt",
      allowSorting: false,
      textAlign: 'center',
      autoFit: "true",
    },
    {
      fieldName: "trangthai_tb",
      headerText: "Trạng thái",
      allowSorting: false,
      textAlign: 'center',
      autoFit: "true",
    },
  ],
  columnsGiando: [{
    fieldName: "kh_cv",
    headerText: "Cáp vào",
    allowSorting: false,
    width: "100",
    textAlign: 'center',
    autoFit: "true",
  },
  {
    fieldName: "jumper_vao",
    headerText: "Vị trí vào",
    allowSorting: false,
    width: "100",
    textAlign: 'center',
    autoFit: "true",
  },
  {
    fieldName: "kh_kc",
    headerText: "Kết cuối",
    allowSorting: false,
    width: "100",
    textAlign: 'center',
    autoFit: "true",
  },
  {
    fieldName: "jumper_ra",
    headerText: "Vị trí ra",
    allowSorting: false,
    width: "100",
    textAlign: 'center',
    autoFit: "true",
  },
  {
    fieldName: "kh_cr",
    headerText: "Cáp ra",
    allowSorting: false,
    width: "100",
    textAlign: 'center',
    autoFit: "true",
  },
  {
    fieldName: "diachi_kc",
    headerText: "Địa chỉ KC",
    allowSorting: false,
    width: "100",
    textAlign: 'center',
    autoFit: "true",
  },
  {
    fieldName: "dodai_cr",
    headerText: "Độ dài",
    allowSorting: false,
    width: "100",
    textAlign: 'center',
    autoFit: "true",
  },
  {
    fieldName: "soicap",
    headerText: "Sợi",
    allowSorting: false,
    width: "100",
    textAlign: 'center',
    autoFit: "true",
  },
  ],
  collums: [{
    fieldName: "ma_tb",
    headerText: "Số máy/Acc",
    allowSorting: false,
    width: "100",
    textAlign: 'center',
    autoFit: "true",
  },
  {
    fieldName: "ma_tl",
    headerText: "Số ảo",
    allowSorting: false,
    width: "100",
    textAlign: 'center',
    autoFit: "true",
  },
  {
    fieldName: "ten_tb",
    headerText: "Tên thuê bao",
    allowSorting: false,
    width: "100",
    textAlign: 'center',
    autoFit: "true",
  },
  {
    fieldName: "diachi_ld",
    headerText: "Địa chỉ lắp đặt",
    allowSorting: false,
    width: "100",
    textAlign: 'center',
    autoFit: "true",
  },
  {
    fieldName: "nguoi_bh",
    headerText: "Người báo hỏng",
    allowSorting: false,
    width: "100",
    textAlign: 'center',
    autoFit: "true",
  },
  {
    fieldName: "ngay_bh",
    headerText: "Ngày báo hỏng",
    allowSorting: false,
    width: "100",
    textAlign: 'center',
    autoFit: "true",
  },
  {
    fieldName: "dienthoai_lh",
    headerText: "Điện thoại liên hệ",
    allowSorting: false,
    width: "100",
    textAlign: 'center',
    autoFit: "true",
  },
  {
    fieldName: "ten_dvvt",
    headerText: "Dịch vụ",
    allowSorting: false,
    width: "100",
    textAlign: 'center',
    autoFit: "true",
  },
  {
    fieldName: "loaihinh_tb",
    headerText: "Loại hình",
    allowSorting: false,
    width: "100",
    textAlign: 'center',
    autoFit: "true",
  },
  {
    fieldName: "trangthai_bh",
    headerText: "Trạng thái",
    allowSorting: false,
    width: "100",
    textAlign: 'center',
    autoFit: "true",
  },
  {
    fieldName: "luot_bh",
    headerText: "Lần BH",
    allowSorting: false,
    width: "100",
    textAlign: 'center',
    autoFit: "true",
  }
  ],
  thongso: [],
  gridGiando: []
}
