/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.25).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.model.dto;

import io.swagger.model.response.BaseResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.annotation.Generated;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2021-03-16T07:34:18.357Z[GMT]")
@Validated
@RequestMapping(value = "/ttkh")
public interface TTKhachHangApi {
    @Operation(summary = "Lấy thêm thông tin thuê bao", tags = {"Thu thập thông tin khách hàng"})
    @RequestMapping(value = "/thongTinTB", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<ThueBaoKH>> thongTinTB(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Mã thuê bao", required = true, schema = @Schema()) @Valid @RequestParam(value = "maTb", required = true) String maTb);

    @Operation(summary = "Lấy danh sách liên hệ, dùng chung cho cả 3 tab, Kiểu: 1: khách hàng, 2: thanh toán, 3: thuê bao", tags = {"Thu thập thông tin khách hàng"})
    @RequestMapping(value = "/dsLienHe", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<LienHeKH>>> dsLienHe(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Kiểu", required = true, schema = @Schema()) @Valid @RequestParam(value = "kieu", required = true) Long kieu,
                                                          @NotNull @Parameter(in = ParameterIn.QUERY, description = "ID tương ứng", required = true, schema = @Schema()) @Valid @RequestParam(value = "id", required = true) Long id,
                                                          @NotNull @Parameter(in = ParameterIn.QUERY, description = "Chọn tất cả truyền 1, không chọn truyền 0", required = true, schema = @Schema()) @Valid @RequestParam(value = "all", required = true) Long all);

    @Operation(summary = "Hủy gán thông tin liên hệ", tags = {"Thu thập thông tin khách hàng"})
    @RequestMapping(value = "/huyGanLienHe", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<Void>> huyGanLienHe(@NotNull @Parameter(in = ParameterIn.QUERY, description = "ID khách hàng", required = true, schema = @Schema()) @Valid @RequestParam(value = "khacHangId", required = true) Long khacHangId,
                                                    @NotNull @Parameter(in = ParameterIn.QUERY, description = "ID thông tin liên hệ", required = true, schema = @Schema()) @Valid @RequestParam(value = "ttlhId", required = true) Long ttlhId,
                                                    @NotNull @Parameter(in = ParameterIn.QUERY, description = "Kiểu (1: )", required = true, schema = @Schema()) @Valid @RequestParam(value = "kieu", required = true) Long kieu);

    @Operation(summary = "Xóa thông tin liên hệ", tags = {"Thu thập thông tin khách hàng"})
    @RequestMapping(value = "/xoaLienHe", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<Void>> xoaLienHe(@NotNull @Parameter(in = ParameterIn.QUERY, description = "ID thông tin liên hệ", required = true, schema = @Schema()) @Valid @RequestParam(value = "ttlhId", required = true) String ttlhId);

    @Operation(summary = "Danh sách vai trò", tags = {"Thu thập thông tin khách hàng"})
    @RequestMapping(value = "/dsChung", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsChung(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Kiểu", required = true, schema = @Schema()) @Valid @RequestParam(value = "kieu", required = true) Long kieu,
                                                        @NotNull @Parameter(in = ParameterIn.QUERY, description = "ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "id", required = true) Long id);

    @Operation(summary = "Danh mục chung", tags = {"Thu thập thông tin khách hàng"})
    @RequestMapping(value = "/danhMuc", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> danhMuc(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Kiểu", required = true, schema = @Schema()) @Valid @RequestParam(value = "kieu", required = true) Long kieu);

    @Operation(summary = "Cập nhật liên hệ", tags = {"Thu thập thông tin khách hàng"})
    @RequestMapping(value = "/capNhatLienHe", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> capNhatLienHe(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody LienHeKHChiTiet requestBody);

    @Operation(summary = "Lấy thông tin chi tiết liên hệ khách hàng", tags = {"Thu thập thông tin khách hàng"})
    @RequestMapping(value = "/ctLienHe", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<LienHeKHChiTiet>> ctLienHe(@NotNull @Parameter(in = ParameterIn.QUERY, description = "ID thông tin liên hệ", required = true, schema = @Schema()) @Valid @RequestParam(value = "ttlhId", required = true) String ttlhId);

}

