export default {
    getTTDanhBa_MaTB:async (axios, data) => axios.post('/web-hopdong/hopdong/lay_danhba_theo_matb', data),
    Lay_ds_hopdong_theo_ma_gd: (axios, data) => axios.post('/web-hopdong/khoiphucthanhly/lay_ds_hopdong_theo_ma_gd', data),
    Lay_ds_hopdong_theo_ma_tb: (axios, data) => axios.post('/web-hopdong/khoiphucthanhly/lay_ds_hopdong_theo_ma_tb', data),
    getDSDichVu: async (axios) => axios.get('/web-quantri/danhmuc-chung/CSS_DICHVU_VT'),
    getLoaiHinhTB: async (axios,id) =>axios.get('/web-thicong/danhmuc/lay_ds_loaihinh_thuebao_dichvu?dichVuVtId='+id),
    getDmKieuYC: async (axios, data) => axios.get(`web-hopdong/danhmuc/ds_kieu_ld/${data.loaihd_id}/${data.loaitb_id}`, data),
    Lay_ds_diachi: (axios, data) => axios.post('/web-hopdong/khoiphucthanhly/lay_ds_diachi_theo_dbtbid', data),
    Lay_ds_diachi_khid: async (axios, data) => axios.get(`/web-thicong/tiepnhan-yc-tongdai/lay_ds_diachi_theo_dbkhid?p_phanvung_id=${data.phanvung_id}&in_khachhang_id=${data.khachhang_id}`, data),
    lay_db_theo_matb: (axios, data) => axios.post('/web-thicong/tiepnhan-yc-tongdai/lay_db_theo_matb', data),
    Lay_DonVi_ThiCong: (axios, data) => axios.post('/web-hopdong/khoiphucthanhly/sp_lay_ds_donvi_thicong', data),
    LAY_DONVI_THEO_LOAIDV_DIACHI_LD: (axios, data) => axios.post('/web-thicong/tiepnhan-yc-tongdai/lay_donvi_theo_loaidv_diachi_ld', data),
    lay_ds_nhanvien_khuvuc_lnv_v2: (axios, data) => axios.post('/web-ccdv/tiepnhan_yc_ks_lapdat/lay_ds_nhanvien_khuvuc_lnv_v2', data),
    lay_ct_khuvuc_thuebao: (axios, data) => axios.get(`/web-thicong/tiepnhan-yc-tongdai/lay_ct_khuvuc_thuebao?p_thuebao_id=${data.thuebao_id}`, data),
    lay_ds_nhanvien_khuvuc_lnv: (axios, data) => axios.post('/web-thicong/tiepnhan-yc-tongdai/lay_ds_nhanvien_khuvuc_lnv', data),
    lay_ds_donviql: (axios, data) => axios.post('/web-ccdv/tiepnhan_yc_ks_lapdat/lay_ds_donviql', data),
    lay_ds_khuvuc_theo_hd_db: (axios, data) => axios.post('/web-thicong/tiepnhan-yc-tongdai/lay_ds_khuvuc_theo_hd_db', data),
    thu_lay_khuvuc_theo_diadanh: (axios, data) => axios.post('/web-thicong/tiepnhan-yc-tongdai/thu_lay_khuvuc_theo_diadanh', data),
    Tiepnhanyc_18001166_load: (axios, data) => axios.post('/web-thicong/tiepnhan-yc-tongdai/tiepnhanyc_18001166_load', data),
    lay_ds_hdtb_tiepnhan_ks: (axios, data) => axios.post('/web-thicong/tiepnhan-yc-tongdai/lay_ds_hdtb_tiepnhan_ks', data),
    xoa_hdkh_v2: (axios, data) => axios.post('/web-thicong/tiepnhan-yc-tongdai/xoa_hdkh_v2', data),
    kiemtra_makh_mtt: (axios, data) => axios.post('/web-thicong/tiepnhan-yc-tongdai/kiemtra_makh_mtt', data),
    sp_lay_nhanvien_kv_theo_thuebao_id_v2: async (axios, data) => axios.get(`/web-thicong/tiepnhan-yc-tongdai/sp_lay_nhanvien_kv_theo_thuebao_id_v2?p_phanvung_id=${data.p_phanvung_id}&p_thuebao_id=${data.p_thuebao_id}`, data),
    lay_ds_nhanvien_khuvuc_lnv_v3: (axios, data) => axios.post('/web-thicong/tiepnhan-yc-tongdai/lay_ds_nhanvien_khuvuc_lnv_v3', data),
    kiemtrakhachhanguc3: async (axios, data) => axios.get(`/web-thicong/tiepnhan-yc-tongdai/kiemtrakhachhanguc3?vphanvung_id=${data.phanvung_id}&vma_kh=${data.ma_kh}`, data),
    lay_ds_diachi_theo_hdkh_id: async (axios, data) => axios.get(`/web-thicong/tiepnhan-yc-tongdai/lay_ds_diachi_theo_hdkh_id?in_hdkh_id=${data.hdkh_id}&p_phanvung_id=${data.p_phanvung_id}`, data),
    sp_lay_ds_donvi_ldv: (axios, data) => axios.post('/web-ccdv/tiepnhan_yc_ks_lapdat/sp_lay_ds_donvi_ldv', data),
    fn_tt_giaophieu: (axios, data) => axios.post('/web-thicong/tiepnhan-yc-tongdai/fn_tt_giaophieu', data),
    laynhanvienxulydonhanghcm: (axios, data) => axios.post('/web-thicong/tiepnhan-yc-tongdai/laynhanvienxulydonhanghcm', data),
    //get_keys: (axios, data) => axios.post('/web-hopdong/khoiphucthanhly/get_keys', data), 
    sinh_magd_v1: (axios, data) => axios.post('/web-hopdong/khoiphucthanhly/sinh_magd', data),
    sinh_magd: (axios, data) => axios.post('/web-thicong/tiepnhan-yc-tongdai/sinh_magd', data),
    get_keys: (axios, data) => axios.post('/web-bancheo/tracuu/get_key', data),
    layhuonggiao_tiepnhan_v2: (axios, data) => axios.post('/web-hopdong/khoiphucthanhly/layhuonggiao_tiepnhan_v2', data),
    sp_tiepnhanyc_themmoi_hopdong: (axios, data) => axios.post('/web-thicong/tiepnhan-yc-tongdai/sp_tiepnhanyc_themmoi_hopdong', data),
    sp_tiepnhanyc_capnhat_hopdong: (axios, data) => axios.post('/web-thicong/tiepnhan-yc-tongdai/sp_tiepnhanyc_capnhat_hopdong', data),
    hoanthiendonhang_18001166: (axios, data) => axios.post('/web-thicong/tiepnhan-yc-tongdai/hoanthiendonhang_18001166', data),
    lay_ds_tiepnhan_yc: (axios, data) => axios.get('/web-tracuu/tracuutonghop/lay_ds_tiepnhan_yc', data),
    lay_ds_tinh: async (axios, data) => axios.get('/web-quantri/danhmuc-chung/CSS_TINH', data),


}

   
