import moment from "moment"
export default {    
      actions: [
        {
          id: 'naplai',
          name: 'Nạp lại',
          active: true,
          icon_class: 'one-reload1',
          visible: true
        },
        {
          id: 'nhapmoi',
          name: 'Nhập mới',
          active: true,
          icon_class: 'one-file-attach ',
          visible: true
        },
        {
          id: 'ghilai',
          name: 'Ghi lại',
          active: true,
          icon_class: 'one-file-edit2',
          visible: true
        },
        {
            id: 'xoahd',
            name: 'Xóa HĐ',
            active: true,
            icon_class: 'one-file-arrow-up',
            visible: true
        },
        
      ], 
      giaophieu_active:false,  
      is_enable_nhapmoi:false,  
    searchDate: {        
        ngay_lap: moment(new Date()).format('DD/MM/yyyy hh:mm a'),        
        ngay_cap: moment(new Date()).format('DD/MM/yyyy'), 
        dateconfig: {altFormat: "d/m/Y",altInput: true,dateFormat: "d/m/Y",allowInput: true,},
        dateconfig_ngaylap: {altFormat: "d/m/Y H:i K",altInput: true,dateFormat: "d/m/Y H:i K",allowInput: true,},
    },    
    options:{
        cbo_dichvu:[],
        cbo_loaihinh: [],
        cbo_kieuld:[],
        cbo_loaicsht:[],
        cbo_loaigt:[],
        cbo_donvinhan:[],
    },
    may_cn:"",
    ip_cn:"",
    dataPopupNVDB:[],    
    dsHDKH:[],
    dsHDTT:[],
    dsHDTB:[],
    dsHDTB_ADSL:[],
    dsHDTBDV:[],
    dsHDTB_KV:[],
    dsDiaChi:[],
    dsDiaChiHDKH:[],
    dsDiaChiHDTT:[],
    dsDiaChiHDTB:[],
    //hdkh_id:0,
    khachhang_id:0,
    huonggiaotn_id:0,
    quytrinh_id:0,
    isReadonlyFields:false,
    formTTHD:{
        ma_hd:"",
        dichvuvt_id:0,
        ma_gd:"",
        loaitb_id:0,
        ngaylap_hd:"",
        nguoilap_hd:"",
        kieuld_id:"",
        ma_csht:"",
        ma_tb:"",
        loai_csht_id:0,
        ghichu:"",
        hdkh_id:0,
        hdtt_id:0,
        hdtb_id:0,
        khachhang_id:0,
    },
    showModalGanNV: false,
    ganKhuVucModel: { hdtb_id: null },
    CurrentDiaBan:{
        ten_kv:"",
        khuvuc_id:0,
    },
    formViewTTKH: {
        khachhang_id:0,
        ma_kh:"",
        ten_kh:"",
        ten_gd:"",
        nguoi_dd:"",
        chucdanh_dd:"",        
        so_dt:"",
        so_fax:"",
        stk:"",
        mst:"",
        loaigt_id:0,
        so_gt:"",
        ngaycap: "",
        noicap: "",        
        diachi_kh:{
            diachi_id:0,
            diachi:"",
            tinh_id:0,
            quan_id:0,
            phuong_id:0,
            pho_id:0,
            khu_id:0,
            so_nha:"",
            dac_diem_id:0,
            sonha:"",
            dacdiem_id:0,
        },
        diachi_tt:{
            diachi_id:0,
            diachi:"",
            tinh_id:0,
            quan_id:0,
            phuong_id:0,
            pho_id:0,
            khu_id:0,            
            sonha:"",
            dacdiem_id:0,
        },
        diachi_tb:{
            diachi_id:0,
            diachi:"",
            tinh_id:0,
            quan_id:0,
            phuong_id:0,
            pho_id:0,
            khu_id:0,            
            sonha:"",
            dacdiem_id:0,
        },
        diachi_ld:{
            diachi_id:0,
            diachi:"",
            tinh_id:0,
            quan_id:0,
            phuong_id:0,
            pho_id:0,
            khu_id:0,            
            sonha:"",
            dacdiem_id:0,
        },
    },

    formGiaoPhieu: {
        donvinhan_id:0,
        ghichu_gp:""
    },    
    gvDanhSachHD: {
        tableCollumns: [
            {
                fieldName: "stt",
                headerText: "STT",
                allowFiltering: true,
                allowSorting: false,
                width: 70,
                textAlign:'Center',
            },
            {
                fieldName: "ma_gd",
                headerText: "Mã GD",
                allowFiltering: true,
                allowSorting: false,
                width: 100,
            },
            {
                fieldName: "ma_tb",
                headerText: "Mã CSHT",
                allowFiltering: true,
                allowSorting: false,
                width: 100,
            },
            {
                fieldName: "ma_hd",
                headerText: "Số HĐ gốc",
                allowFiltering: true,
                allowSorting: false,
                width: 100,
                textAlign:'Left',
            },
            {
                fieldName: "ten_kh",
                headerText: "Tên khách hàng",
                allowFiltering: true,
                allowSorting: false,
                width: 100,
                textAlign:'Left',
            },
            {
                fieldName: "diachi_kh",
                headerText: "Địa chỉ",
                allowFiltering: true,
                allowSorting: false,
                width: 100,
            },
            {
                fieldName: "so_dt",
                headerText: "SĐT",
                allowFiltering: true,
                allowSorting: false,
                width: 100,
                textAlign:'Left',
            },
            {
                fieldName: "so_fax",
                headerText: "Fax",
                allowFiltering: true,
                allowSorting: false,
                width: 100,
                textAlign:'Left',
            },
            {
                fieldName: "ngay_yc",
                headerText: "Ngày lập HĐ",
                allowFiltering: true,
                allowSorting: false,
                width: 100,
                textAlign:'Right',
                format: {type: 'date', format: 'dd/MM/yyyy HH:mm:ss'},
                type: 'date',
            },
            {
                fieldName: "nguoi_laphd",
                headerText: "Người lập HĐ",
                allowFiltering: true,
                allowSorting: false,
                width: 100,
            },
        ],
        tableData:[],
    },
    
}