export default {
  DS_TTTHUEBAO: [],
  DS_DICHVU_VT: [],
  DS_LOAIHINH_TB: [],
  DS_LOAI_KH: [],
  DS_DOITUONG: [],
  DS_HINHTHUC_KN: [],
  DS_LOAI_KN: [],
  DS_KETQUA_KN: [],
  DS_CHUDEKN: [],
  DS_KHIEUNAI_HT: [],
  DS_TB_KHIEUNAI: [],
  DS_TB_KHIEUNAI_DAGIAO: [],
  DS_TB_KHIEUNAI_DAKHOA: [],
  DS_NHANVIEN: [],
  DS_TIENGC: [],
  DS_KQ_LOI_KN: [],
  DS_CHITIETNO_THEO_KHOANMUC: [],
  DS_HUONGGIAO_LDV: [],
  DSThangGC: [],
  DSThangApDung: [],
  DsGC: [],
  DS_PAXL: [],
  DS_MD_HAILONG: [],
  DS_HINHTHUC_TL: []
};
