export default {
    lay_thongtin_tinh: async (axios) => axios.get('/web-cabman/bando_tuyencot/lay_thongtin_tinh'),
    lay_ds_quan_huyen: async (axios, tinhId) => axios.get(`/web-cabman/bando_tuyencot/lay_ds_quan_huyen/${tinhId}`),
    lay_ds_phuong_xa: async (axios, huyenId) => axios.get(`/web-cabman/bando_tuyencot/lay_ds_phuong_xa/${huyenId}`),
    lay_ds_pho_ap_khu: async (axios, phuongId) => axios.get(`/web-cabman/bando_tuyencot/lay_ds_pho_ap_khu/${phuongId}`),
    lay_ds_thanhvienkenh: async (axios, data,header) => axios.post('/web-quantri/vnp08/dm_thanh_vien_kenh/sp_lay_ds_tv_kenh',data,header),
    lay_ds_hangkenh: async (axios, data,header) => axios.get('/web-quantri/vnp08/dm_hang_kenh/sp_lay_ds_hang_kenh', data,header),
    lay_ds_kenhban: async (axios, data,header) => axios.post('/web-quantri/vnp08/danhSachKenhBan', data,header),
    getKey_Kenhban: async (axios, data,header) => axios.post('/web-quantri/vnp08/sinhMaKenhBan', data,header),
    Themmoi_Kenhban: async (axios, data,header) => axios.post('/web-quantri/vnp08/themMoiKenhBan', data,header),
    Capnhat_Kenhban: async (axios, data,header) => axios.post('/web-quantri/vnp08/capNhatMoiKenhBan', data,header),
    getDsSanphamDagan: async (axios, data,header) => axios.post('/web-quantri/vnp08/danhSachSPDaGan', data,header),
    getDsSanphamChuagan: async (axios, data,header) => axios.post('/web-quantri/vnp08/danhSachSPChuaGan', data,header),
    ganSanpham: async (axios, data,header) => axios.post('/web-quantri/vnp08/ganSP', data,header),
    upload_file: async (axios, data,header) => axios.post('/web-quantri/upload', data,header),
    view_file: async (axios, data,header) => axios.post('/web-quantri/upload/link_view_file', data,header),
    lay_ds_loai_hop_dong: async (axios) => axios.get('/web-quantri/vnp08/dm_loai_hop_dong/sp_lay_ds_loai_hop_dong'),
    lay_ds_nhanvienQL: async (axios, data, header) => axios.post('/web-khdn/kenhban/dsNVQL', data,header),
    lay_ds_loaiGT: async (axios, data, header) => axios.post('/web-khdn/kenhban/dsLoaiGT', data,header),
    lay_dsFile_Kenhban: async (axios, data, header) => axios.post('/web-khdn/kenhban/dsFileKB', data,header),
    capNhatFileKB: async (axios, data, header) => axios.post('/web-khdn/kenhban/capNhatFileKB', data,header),
    dsLoaiFile: async (axios, data, header) => axios.post('/web-khdn/kenhban/dsLoaiFile', data,header),
    lay_dsHTHD: async (axios, data, header) => axios.post('/web-khdn/kenhban/dsHTHD', data,header),
    lay_dsTTKenhBan: async (axios, data, header) => axios.post('/web-khdn/kenhban/dsTTKenhBan', data,header),
}
