export default {
  getDSKenhThu: (axios, data) => axios.get('/web-quantri/danhmuc-chung/CSS_KENHTHU'),
  getDSKieuHD: (axios, data) => axios.get('/web-quantri/danhmuc-chung/CSS_KIEU_HD'),
  getDSLoaiHD: (axios, data) => axios.get('/web-quantri/danhmuc-chung/CSS_LOAI_HD'),
  getDSDoiTac: (axios, data) => axios.post('/web-hopdong/khaibaotsl/sp_lay_ds_doitac', data),
  getTocDoKenh: (axios, data) => axios.post('/web-thicong/hoinghi_truyenhinh/ht_tocdo_kenh_combobox',data),
  getDSLoaiHinh : (axios, data) => axios.get('/web-quantri/danhmuc-chung/CSS_LOAIHINH_TB'),
  getDSNguoiGV: (axios, data) => axios.post('/web-hopdong/khaibaotsl/sp_lay_ds_nhanvien_thuchien_theo_dv',data),
  // getDSThueBao: (axios, data) => axios.post('/web-hopdong/khaibaotsl/lay_ds_phieu_giaoden_tsl',data),
  getDSChuQuan: (axios, data) => axios.get('/web-quantri/danhmuc-chung/CSS_CHUQUAN'),
  getDgvDanhSachThueBao: (axios, data) => axios.post('/web-hopdong/khaibaotsl/sp_lay_ds_phieu_giaoden_net_tsl',data),
  getThongTinKyThuat: (axios, data) => axios.post('/web-thicong/khaibao_dichvu_net_mgw/bancheo_lay_ds_thongtin_kythuat_2',data),
  getThongTinTB: (axios, data) => axios.get(`/web-hopdong/hopdong/lay_ds_hopdong_thuebao_tls?hdtbId=${data}`),
  getThongTinDiemDau: (axios, data) => axios.post('/web-hopdong/DiemChiaTrungGianTSL/lay_hdtb_tsl_diemdau',data),
  getDiaChiLD: (axios, data) => axios.post('/web-hopdong/khaibaotsl/sp_lay_diachi_ld',data),
  getDSQuyTrinh: (axios, data) => axios.post('/web-hopdong/khaibaotsl/sp_lay_ds_quytrinh_v2',data),
  getDSNhanVienTheoPhieuID: (axios, data) => axios.post('/web-hopdong/khaibaotsl/lay_ds_nhanvien_theo_phieu_id',data),
  getThongTinNV: (axios, data) => axios.get(`/web-hopdong//danhmuc/lay_thongtin_nhanvien/${data}`),
  getThongTinPhieuTra: (axios, data) => axios.post('/web-hopdong/khaibaotsl/sp_ht_phieu_tra_tsl',data), 
  getThongTinHen: (axios, data) => axios.post('/web-hopdong/khaibaotsl/sp_kiemtra_hen_hdtb',data),
  getDSChiTietDHTC: (axios, data) => axios.post('/web-thicong/hoinghi_truyenhinh/lay_danhsach_phieu_net_con',data),
  getDSTienTinhDHTC: (axios, data) => axios.post('/web-hopdong/khaibaotsl/sp_tt_tientrinh_tc',data),
  getLuongTheoQuyTrinh: (axios, data) => axios.get(`/web-hopdong/danhmuc/ds_huonggiao/${data.quytrinh_id}/${data.tthd_id}`),
  getLuongThaoTac: (axios, data) => axios.post(`/web-hopdong/khaibaoims/sp_lay_luong_thaotac`,data),
  getDuLieuThaoTac: (axios, data) => axios.post(`/web-hopdong/hths-thaydoi-tocdo/sp_lay_dulieu_thaotac_control_theo_thaotac_id`,data),
  updateNoiDungTH: (axios, data) => axios.post(`/web-hopdong/DiemChiaTrungGianTSL/capnhat_noidung_th`,data),
  updateTTPhieuGiao: (axios, data) => axios.post(`/web-hopdong/khaibaotsl/capnhat_tt_phieugiao`,data), 
  getHuonggiaoTheoLuongID: (axios, data) => axios.post(`/web-hopdong/khaibaotsl/lay_huonggiao_theo_luong_id`,data),
  getDSHopDongTBTheoHDTBID: (axios, data) => axios.get(`/web-hopdong/hopdong/lay_ds_hdtb_tsl_theo_hdtb_id?hdtbId=${data.hdtb_id}`),
  hoanThanhHoanCong: (axios, data) => axios.post(`/web-hopdong/khaibaotsl/fn_hoanthanh_hoancongtsl_net`,data),
  downloadFileNT: (axios, data) => axios.post(`/web-ccdv/completion/lay_ds_file_hs_bc`,data),
  kiemtraDL: (axios, data) => axios.post(`/web-thicong/khaibao-truyensolieu/fn_kiemtra_giaophieu_vattu`,data),
  capnhatPhieuGiao: (axios, data) => axios.post(`/web-hopdong/khaibaotsl/fn_capnhat_hoancongtsl_net`,data),
  getKey: (axios, data) => axios.post(`/web-quantri/donvitinh/get_keys`,data),
  uploadFile: (axios, data) => axios.post('/web-quantri/upload',data, {headers: {'Content-Type': 'multipart/form-data'}}),
  uploadFileNT: (axios, data) => axios.post('/web-hopdong/khaibaotsl/sp_insert_filehs_net',data),
  link_view_file: async (axios, data) => axios.post('/web-quantri/upload/link_view_file', data),
  // downloadFileNT: (axios, data) => axios.post('/web-hopdong/completion/sp_tt_hd_bancheo',data),
}