export enum FUNERAL_RESERVATION_TABS {
  LIST = 'LIST',
  PHOTOS = 'PHOTOS',
}

export enum FUNERAL_RESERVATION_CONTENT {
  RESERVATION = 'RESERVATION',
  DELETE_LIST = 'DELETE_LIST',
  PNT_SETTING = 'PNT_SETTING',
}

export enum ROOM_TYPE {
  NONE = 'NONE',
  MEMORIAL_HALL_1 = 'MEMORIAL_HALL_1',
  MEMORIAL_HALL_2 = 'MEMORIAL_HALL_2',
  MEMORIAL_HALL_3 = 'MEMORIAL_HALL_3',
  CREMATORIUM_1 = 'CREMATORIUM_1',
  CREMATORIUM_2 = 'CREMATORIUM_2',
  CREMATORIUM_3 = 'CREMATORIUM_3',
  CREMATORIUM_4 = 'CREMATORIUM_4',
}
