export enum LUCETTE_CATEGORY {
  ON_THE_DAY = 'ON_THE_DAY',
  SCHEDULE_PENDING = 'SCHEDULE_PENDING',
  PROCESS_PENDING = 'PROCESS_PENDING',
  EXCLUSIVE = 'EXCLUSIVE',
}

export enum FUNERAL_LUCETTE_TABS {
  LIST = 'LIST',
  SCHEDULE = 'SCHEDULE',
}
