export default {
  getDanhSachDonVi: (axios, data) => axios.get('/web-thuno/api/thu-no/common/don-vi/loai-don-vi?loaiDVId=2', data),
  getDanhSachDonVi2: (axios, data) => axios.get('/web-thuno/api/thu-no/common/don-vi/loai-don-vi', { params: data }),
  getDanhSachDonViQuanLy: (axios, data) => axios.get('/web-thuno/api/thu-no/lay-danh-sach-don-vi-quan-ly', { params: data }),
  getChuKyNoTheoKyCuoc: async (axios, data) => axios.get('/web-thuno/api/thu-no/common/chu-ky-no/ky-cuoc/' + data),
  getThongTinChuKyNo: async (axios, data) => axios.get('/web-thuno/api/thu-no/common/chu-ky-no/' + data),
  getDanhSachNganHang: async (axios) => axios.get('/web-thuno/api/thu-no/common/ngan-hang'),
  getDSNganHangGachNo: async (axios) => axios.get('/web-thuno/api/thu-no/common/ngan-hang-gach-no'),
  getDanhSachHinhThucThanhToan: async (axios, data) => axios.get('/web-thuno/api/thu-no/common/hinh-thuc-thanh-toan', { params: data }),
  getDanhSachNhanVienThuCuoc: async (axios) => axios.get('web-thuno/api/thu-no/common/nhan-vien-thu-cuoc/nguoi-dung/don-vi'),
  getDanhSachDichVuVienThong: async (axios) => axios.get('web-thuno/api/thu-no/common/dich-vu-vien-thong'),
  getDanhSachDichVuVienThongDangKy: async (axios) => axios.get('web-thuno/api/thu-no/common/dich-vu-vien-thong-dang-ky'),
  getDanhSachLoaiHinhThueBao: async (axios, id) => axios.get('web-thuno/api/thu-no/common/loai-hinh-thue-bao/dich-vu-vien-thong/' + id),
  getDanhMucQuanHuyen: async (axios) => axios.get('web-thuno/api/thu-no/common/quan-huyen'),
  getDanhMucPhuongTheoQuan: async (axios, data) => axios.get('web-thuno/api/thu-no/danh-muc/lay-danh-sach-phuong-theo-quan', { params: data}),
  getDanhMucPhoApKhuTheoPhuong: async (axios, data) => axios.get('web-thuno/api/thu-no/danh-muc/lay-danh-sach-pho-ap-khu-theo-phuong', { params: data}),
  getDanhMucDacDiem: async (axios, data) => axios.get('web-thuno/api/thu-no/thong-tin-khach-hang/lay-danh-muc-dac-diem', { params: data}),  
  getDanhSachNguoiGiaoViec: async (axios, id) => axios.get('web-thuno/api/thu-no/common/ds-nguoi-giao-viec/don-vi/' + id),
  getDanhSachLoaiHinhTBTheoQuyTrinh: async (axios, id) => axios.get('web-thuno/api/thu-no/common/loai-hinh-thue-bao/quy-trinh/' + id),
  getDanhSachKHLon: async (axios) => axios.get('web-thuno/api/thu-no/common/khach-hang-lon'),
  getDanhSachLoaiKhachHang: async (axios, id = -1) => axios.get('web-thuno/api/thu-no/common/loai-khach-hang/nhom-kh/' + id),
  getDanhSachNhanVienTheoDonVi: async (axios, id) => axios.get('web-thuno/api/thu-no/common/ds-nhan-vien/don-vi/' + id),
  getTocDoTheoLoaiThueBao: async (axios, id) => axios.get('web-thuno/api/thu-no/common/toc-do/loai-thue-bao/' + id),
  getDanhSachLoaiPhieu: async (axios) => axios.get('web-thuno/api/thu-no/common/danh-muc/loai-phieu'),
  getDanhSachNhanVienThuNgan: async (axios) => axios.get('web-thuno/api/thu-no/common/nhan-vien-thu-ngan/nguoi-dung-hien-tai'),
  getNhomHinhThucThanhToan: async (axios) => axios.get('web-thuno/api/thu-no/common/nhom-hinh-thuc-thanh-toan'),
  getHinhThucThanhToan: async (axios) => axios.get('web-thuno/api/thu-no/common/hinh-thuc-thanh-toan'),
  getDanhBaTheoMaThueBao: async (axios, data) => axios.get('web-thuno/api/thu-no/tra-cuu-danh-ba/ma-thue-bao', { params: data }),
  getDanhBaTheoMaThanhToan: async (axios, data) => axios.get('web-thuno/api/thu-no/tra-cuu-danh-ba/ma-thanh-toan', { params: data }),
  getDanhSachLanTaoCongNo: (axios) => axios.get("/web-thuno/api/thu-no/cong-no/ds-lan-tao-cong-no"),
  getDanhSachLyDoKhoa: async (axios) => axios.get('web-thuno/api/thu-no/nguyen-nhan-no/lay-danh-sach-ly-do-tra'),
  getDanhSachPhanLoaiKhachHang: async (axios, id) => axios.get('web-thuno/api/thu-no/common/phan-loai-khach-hang/nhom-kh/' + id),
  getDanhSachNhanVienQuanLyTheoDonVi: async (axios, id) => axios.get('web-thuno/api/thu-no/common/nhan-vien-quan-ly/don-vi/' + id),
  getDanhSachNhanVienThuCuocTheoQuanLy: async (axios, id) => axios.get('web-thuno/api/thu-no/common/nhan-vien-thu-cuoc/quan-ly/' + id),
  // getDanhSachNhanVienThuCuocTheoNguoiDung: async (axios, id) => axios.get('web-thuno/api/thu-no/common/nhan-vien-thu-cuoc/quan-ly/' + id),
  getDanhSachLyDoXacNhan: async (axios) => axios.get('web-thuno/api/thu-no/common/ds-ly-do-xac-nhan'),
  getDanhSachNguyenNhanXacNhan: async (axios) => axios.get('web-thuno/api/thu-no/common/ds-nguyen-nhan-xac-nhan'),
  getDanhSachNganHangGachNo: async (axios) => axios.get('/web-thuno/api/thu-no/common/ngan-hang-gach-no'),
  getHTTTNganHang: (axios) => axios.get('/web-thuno/api/thu-no/common/lay-httt-ngan-hang/chuyen-khoan-file'),
  getDSTimKiem: (axios, id) => axios.get('/web-thuno/api/thu-no/common/ds-tim-kiem/' + id),
  getDanhSachKhoanMucGachNo: (axios) => axios.get('/web-thuno/api/thu-no/quan-ly-thu-no/gach-no-tien-mat/danh-sach-khoan-muc-gach-no'),
  getDSQuyenGachNoL: (axios) => axios.get('/web-thuno/api/thu-no/common/ds-quyen-gach-no-nguoi-dung'),
  getUserNeo: (axios) => axios.get('/web-thuno/api/thu-no/common/user-neo'),
  getDSNguoiDung: (axios) => axios.get('/web-thuno/api/thu-no/common/ds-nguoi-dung-theo-phan-vung'),
  getDSNhomCTV: (axios, data) => axios.get('/web-thuno/api/thu-no/common/lay-ds-nhom-nhan-vien/' + data),
  getDSNganHangCcbs: (axios) => axios.get('/web-thuno/api/thu-no/common/ds-ngan-hang-ccbs'),
  getDSThaoTacTheoLuong: (axios, id) => axios.get('/web-thuno/api/thu-no/common/thao-tac/luong/' + id),
  getKyCuocHienHanh: (axios) => axios.get('/web-thuno/api/thu-no/common/ky-cuoc-hien-hanh'),
  // getDanhSachLoaiKhachHang: async (axios) => axios.get('web-thuno/api/thu-no/common/phan-loai-khach-hang'),
  getDanhSachNhanVienTheoLoai: (axios, loaiId) => axios.get('/web-thuno/api/thu-no/common/nhan-vien/loai-nhan-vien/' + loaiId),
  getDanhSachDonViTheoLoai: (axios, data) => axios.get('/web-thuno/api/thu-no/common/don-vi/loai-don-vi?loaiDVId=' + data),
  getDanhSachNhanVienQLTheoDaiLy: async (axios, id) => axios.get('/web-thuno/api/thu-no/common/nhan-vien-quan-ly/dai-ly/' + id),
  getNhanVienQLTheoNguoiDung: async (axios, id) => axios.get('/web-thuno/api/thu-no/tra-cuu/nguoi-dung/nhan-vien-quan-ly/' + id),
  getDanhSachDonViQL: (axios, data) => axios.get('/web-thuno/api/thu-no/gach-no/ds-don-vi-quan-ly-dia-chi-thanh-toan'),
  getDanhSachNVTCTheoDonVi: async (axios, data) => axios.get('web-thuno/api/thu-no/common/nhan-vien-thu-cuoc/nguoi-dung/don-vi/' + data),
  getDSChuKyNo: async (axios, data) => axios.get('/web-thuno/api/thu-no/common/chu-ky-no'),
  getDSHTTTNganHang: async (axios, data) => axios.get('/web-thuno/api/thu-no/common/hinh-thuc-thanh-toan-ngan-hang'),
  getDSThamSoMacDinh: async (axios, data) => axios.get('/web-thuno/api/thu-no/common/ds-tham-so-mac-dinh/' + data),
  getDSThamSoMacDinhAdmin: async (axios, data) => axios.get('/web-thuno/api/thu-no/common/tham-so-admin/' + data),
  getMapID: async (axios, data) => axios.post('/web-thuno/api/thu-no/common/map-id', data),
  // tham số mặc định
  getThamSoMacDinh: async (axios, data) => axios.get('/web-thuno/api/thu-no/mo-may-theo-danh-sach/lay-danh-sach-tham-so-md-mats', {params: data}),
  //
  getTongNoKHTheoTB: async (axios, data) => axios.get('/web-thuno/api/thu-no/xu-ly-thue-bao/khoa-may-theo-so-may-va-tai-khoan/lay-tong-no-thue-bao', {params: data}),
  getIDTheoMa: async (axios, data) => axios.post('/web-thuno/api/thu-no/common/lay-id-theo-ma', data),
  getDanhBaTheoMaTT: async (axios, data) => axios.get('web-thuno/api/thu-no/tra-cuu-danh-ba/ma-thanh-toan', { params: data }),
  getDanhBaTheoMaTT2: async (axios, data) => axios.get('web-thuno/api/thu-no/tra-cuu-danh-ba/thue-bao-theo-ma-thanh-toan', { params: data })
}
