export default {
  getDanhSachHoaDon: (axios, data) => axios.post('/app-com/hoadon_dientu/listInvByCus', data),
  huyBoHoaDon: (axios, data) => axios.post('/app-com/hoadon_dientu/cancelInv', data),
  getDsPattern:(axios, data) => axios.get('/web-thuno/api/thu-no/in-hoa-don/ds-mau-hoa-don'),
  getDsSerial:(axios, data) => axios.get('/web-thuno/api/thu-no/in-hoa-don/ds-ser-hoa-don/pattern/' + data),
  getChiTietHoaDon:(axios, data) => axios.post('/app-com/hoadon_dientu/downloadInvNoPay', data),
  fetchReplaceInv:(axios, data) => axios.post('/app-com/hoadon_dientu/replaceInv', data),
  fetchReplaceInvAction:(axios, data) => axios.post('/app-com/hoadon_dientu/ReplaceInvoiceAction', data),
  fetchAdjustInv:(axios, data) => axios.post('/app-com/hoadon_dientu/adjustInvAction', data),
  getDanhSachHoaDonByFkey: (axios, data) => axios.post('/app-com/hoadon_dientu/listInvByCusFkey', data),
  postConfirmPaymentFkey: (axios, data) => axios.post('/app-com/hoadon_dientu/confirmPaymentFkey', data),
  postUnConfirmPaymentFkey: (axios, data) => axios.post('/app-com/hoadon_dientu/UnconfirmPaymentFkey', data),
  postDownloadInvFkeyNoPayXml: (axios, data) => axios.post('/app-com/hoadon_dientu/downloadInvFkeyNoPayXml', data),
  postDownloadInvPDFFkeyNoPay: (axios, data) => axios.post('/app-com/hoadon_dientu/downloadInvPDFFkeyNoPay', data),
  getInvViewNoPay: (axios, data) => axios.post('/app-com/hoadon_dientu/getInvViewNoPay', data),

  getId: (axios, data) => axios.post('/web-thuno/api/thu-no/common/lay-id-theo-ma', data),
  listInvByCus: (axios, data) => axios.post('/tichhop/vnptinvoice/listInvByCus', data),
  listInvByCusFkey: (axios, data) => axios.post('/tichhop/vnptinvoice/listInvByCusFkey', data),
  confirmPaymentFkey: (axios, data) => axios.post('/tichhop/vnptinvoice/confirmPaymentFkey', data),
  unConfirmPaymentFkey: (axios, data) => axios.post('/tichhop/vnptinvoice/unConfirmPaymentFkey', data),
  downloadInvFkeyNoPay: (axios, data) => axios.post('/tichhop/vnptinvoice/downloadInvFkeyNoPay', data),
  downloadInvPDFFkeyNoPay: (axios, data) => axios.post('/tichhop/vnptinvoice/downloadInvPDFFkeyNoPay', data),
  getInvView: (axios, data) => axios.post('/tichhop/vnptinvoice/getInvView', data),
  replaceInvoiceAction:(axios, data) => axios.post('tichhop/vnptinvoice/replaceInvoiceAction', data),
  adjustInvoiceAction:(axios, data) => axios.post('tichhop/vnptinvoice/adjustInvoiceAction', data),
  POST_GET_KEYS: async (axios, data) => axios.post('/web-quantri/donvitinh/get_keys', data),
  CapNhat: (axios, data) => axios.post('/web-hopdong/hopdong/fn_xuat_hddt_file_capnhat_biendong', data),
  lay_ds_thamso_md_ds_mats: (axios, data) => axios.get('/web-thuno/api/thu-no/common/tham-so-admin/' + data),
}
