const columns = {
    columnsPYC: [
        { fieldName: "ma_tb", headerText: "Số máy/Acc", textAlign: "left", width: "150px" },
        { fieldName: "ma_lt", headerText: "Số ảo", textAlign: "left", autoFit: "true" },
        { fieldName: "tram_vt", headerText: "Tổ thi công", textAlign: "left", autoFit: "true" },
        { fieldName: "ma_bh", headerText: "Mã BH", textAlign: "left", autoFit: "true" },
        { fieldName: "ngay_yc", headerText: "Ngày BH", textAlign: "center", autoFit: "true" },
        { fieldName: "goi_kt", headerText: "Gói KT", textAlign: "left", autoFit: "true" },
        { fieldName: "ngaygiao_td", headerText: "Ngày giao TĐ", textAlign: "center", autoFit: "true" },
        { fieldName: "thoigian_ck", headerText: "Thời gian CK", textAlign: "center", autoFit: "true" },
        { fieldName: "gio_conlai", headerText: "Giờ còn lại", textAlign: "left", autoFit: "true" },
        { fieldName: "ten_tb", headerText: "Tên thuê bao", textAlign: "left", autoFit: "true" },
        { fieldName: "diachi_ld", headerText: "Địa chỉ lắp đặt", textAlign: "left", autoFit: "true" },
        { fieldName: "loaihinh_tb", headerText: "Loại hình", textAlign: "left", autoFit: "true" },
        { fieldName: "mucdo", headerText: "Mức độ", textAlign: "left", autoFit: "true" },
        { fieldName: "chitieu_tg", headerText: "Chỉ tiêu thời gian", textAlign: "left", autoFit: "true" },
        { fieldName: "nguoi_dh", headerText: "Người ĐH", textAlign: "left", autoFit: "true" },
        { fieldName: "thongtin_dh", headerText: "Thông tin ĐH", textAlign: "left", autoFit: "true" },
        { fieldName: "ten_kv", headerText: "Khu vực", textAlign: "left", autoFit: "true" },
        { fieldName: "nhanvien_tc", headerText: "Nhân viên TC", textAlign: "left", autoFit: "true" },
        { fieldName: "so_dt", headerText: "Điện thoại KH", textAlign: "left", autoFit: "true" },
        { fieldName: "luot_bh", headerText: "Lượt BH", textAlign: "left", autoFit: "true" },
        { fieldName: "lan_pa", headerText: "KH gọi", textAlign: "left", autoFit: "true" },
        { fieldName: "lan_ks", headerText: "Lần KS", textAlign: "left", autoFit: "true" },
        { fieldName: "trangthai_hd", headerText: "Trạng thái HĐ", textAlign: "left", autoFit: "true" },
        { fieldName: "trangthai_tb", headerText: "Trạng thái TB", textAlign: "left", autoFit: "true" },
        { fieldName: "ngay_ht", headerText: "Ngày hoàn thành", textAlign: "center", autoFit: "true" },
        { fieldName: "nhanvien_tn", headerText: "NV tiếp nhận", textAlign: "left", autoFit: "true" },
        { fieldName: "donvi_tn", headerText: "Đvị tiếp nhận", textAlign: "left", autoFit: "true" },
        { fieldName: "donvi_qlld", headerText: "Đơn vị LĐ", textAlign: "left", autoFit: "true" },
        { fieldName: "ghichu_tb", headerText: "Ghi chú TB", textAlign: "left", autoFit: "true" },
        { fieldName: "tinhtrang", headerText: "Trạng thái", textAlign: "left", autoFit: "true" },
        { fieldName: "lydoton", headerText: "Lý do tồn", textAlign: "left", autoFit: "true" },
        { fieldName: "ghichu_ton", headerText: "Ghi chú tồn", textAlign: "left", autoFit: "true" },
        { fieldName: "ngay_bt", headerText: "Ngày báo tồn", textAlign: "center", autoFit: "true" },
        { fieldName: "nhomton", headerText: "Nhóm tồn", textAlign: "left", autoFit: "true", visible: true },
        { fieldName: "nguoi_cn", headerText: "Người CN", textAlign: "left", autoFit: "true" },
        { fieldName: "ngay_cn", headerText: "Ngày CN", textAlign: "left", autoFit: "true" },
        { fieldName: "ten_dt", headerText: "Đối tượng", textAlign: "left", autoFit: "true" },
        { fieldName: "ten_kieuld", headerText: "Kiểu yêu cầu", textAlign: "left", autoFit: "true" },
        { fieldName: "tt_port", headerText: "TT Port", textAlign: "center", autoFit: "true" },
        { fieldName: "ten_cap", headerText: "Cáp gốc", textAlign: "left", autoFit: "true" },
        { fieldName: "doi_cap", headerText: "Đôi số", textAlign: "left", autoFit: "true" },
        { fieldName: "ten_kc", headerText: "Kết cuối", textAlign: "left", autoFit: "true" },
        { fieldName: "vitri", headerText: "Vị trí", textAlign: "left", autoFit: "true" },
        { fieldName: "giohen_dau", headerText: "Giờ hẹn đầu", textAlign: "left", autoFit: "true" },
        { fieldName: "giohen_cuoi", headerText: "Giờ hẹn cuối", textAlign: "left", autoFit: "true" },
        { fieldName: "nhanvien_hen", headerText: "Người hẹn", textAlign: "left", autoFit: "true" },
        { fieldName: "thoidiem_hen", headerText: "Thời điểm hẹn", textAlign: "left", autoFit: "true" },
        { fieldName: "url_file_tt", headerText: "File TT", textAlign: "left", autoFit: "true", visible: true },
    ]
}

export default columns