export default {
  getTienKhoanMucLoaiHD: (axios, body) => axios.post('web-thicong/danhmuc/lay_tienkhoanmuc_loaihd', body),
  getDanhSachDichVuVT: (axios) => axios.get('web-quantri/danhmuc-chung/CSS_DICHVU_VT'),
  getDanhSachThamSoMacDinh: (axios, kieu) => axios.get(`web-quantri/danhmuc/ds_thamso_md/${kieu}`),
  getDanhSachVeTinh: (axios, body) => axios.post('web-hopdong/thanhly/sp_lay_ds_tatca_vetinh', body),
  getDanhSachTrangBi: (axios) => axios.post('web-hopdong/thaydoitocdoadsl/sp_lay_ds_trangbi_theo_dieukien'),
  getDanhSachHopDongByMaGD: (axios, body) => axios.post('web-hopdong/thaydoi-account/lay_ds_hopdong_theo_ma_gd', body),
  getDanhSachHopDongByMaTB: (axios, body) => axios.post('web-hopdong/hopdong/lay_ds_hopdong_theo_matb', body),
  getDanhSachDiaChiByThueBaoId: (axios, body) => axios.post('web-hopdong/khoiphucthanhly/lay_ds_diachi_theo_dbtbid', body),
  getDanhSachIDSN: (axios, thueBaoId, kieuLDId) => axios.get(`web-hopdong/thaydoi-account/sp_lay_ds_chitiet_doithu_canhtranh?thuebao_id=${thueBaoId}&kieuld_id=${kieuLDId}`),
  getDanhSachHopDongTBADSL: (axios, hdtbId) => axios.get(`web-hopdong/hopdong/lay_ds_hopdong_thuebao_adsl?hdtbId=${hdtbId}`),
  getDanhSachHopDongTBIMS: (axios, hdtbId) => axios.get(`web-hopdong/hopdong/lay_ds_hopdong_thuebao_ims?hdtbId=${hdtbId}`),
  getDanhSachHopDongTBCD: (axios, hdtbId) => axios.get(`web-hopdong/hopdong/lay_ds_hopdong_thuebao_codinh?hdtbId=${hdtbId}`),
  getDanhSachThueBaoByMaTB: (axios, maTB, dichVuVTId) => axios.get(`web-hopdong/hopdong/lay_ds_thuebao_matb?maTb=${maTB}&dvvtId=${dichVuVTId}`),
  getThongTinTBByMaTB: (axios, maTB) => axios.get(`web-hopdong/thaydoi-account/sp_lay_tt_tb_lap_hd_doiso_theo_thuebao_id?thuebao_id=${maTB}`),
  getDanhSachDanhBaADSL: (axios, thueBaoId) => axios.get(`web-hopdong/chuyendich-adsl/lay_ds_db_adsl_theo_tbid?thuebao_id=${thueBaoId}`),
  getDanhSachDanhBaIMS: (axios, thueBaoId) => axios.get(`web-hopdong/hopdong/lay_ds_danhba_ims?thueBaoId=${thueBaoId}`),
  getDanhSachDanhBaCD: (axios, thueBaoId) => axios.get(`web-hopdong/chuyendich-codinh/lay_ds_db_cd_theo_tbid?thuebao_id=${thueBaoId}`),
  getDanhSachDanhBaGPhone: (axios, thueBaoId) => axios.get(`web-hopdong/hopdong/lay_ds_danhba_gp?thueBaoId=${thueBaoId}`),
  getThongTinCN: (axios) => axios.get('web-quantri/nguoidung/thongtin'),
  xoaHopDong: (axios, body) => axios.post('web-hopdong/hopdong/khoa_mo_thuebao_no_cuoc/xoa_hopdong', body),
  xoaThueBao: (axios, body) => axios.post('web-hopdong/khoiphucthanhly/xoa_hdtb', body),
  getDanhSachBienDongByHdtbId: (axios, hdtbId) => axios.get(`web-hopdong/hopdong/lay_biendong_thongtin_thuebao?hdtbId=${hdtbId}`),
  getDanhSachHDTBByKhidAndMaGD: (axios, body) => axios.post('web-ccdv/tien_trinh_bao_hong/lay_ds_db_hdtb_theo_khid_magd', body),
  getDanhSachLoaiHinhTB: (axios) => axios.get('web-quantri/danhmuc-chung/CSS_LOAIHINH_TB'),
  getDanhSachKieuLD: (axios, body) => axios.post('web-thicong/danhmuc/lay_ds_kieu_ld_by_loaitb_loaihd', body),
  lapHopDongDoiSo: (axios, body) => axios.post('web-hopdong/thaydoi-account/sp_lap_hopdong_doiso', body),
  getDanhSachTienKhoanMuc: (axios, thueBaoId, kieuLdId) => axios.get(`web-hopdong/thaydoi-account/sp_lay_tien_khoanmuc_ld_doiso?thuebao_id=${thueBaoId}&kieuld_id=${kieuLdId}`),
  getThongTinNguoiDung2: (axios) => axios.post('quantri/user/thongtin_nguoidung2', {}),
  getDanhSachSoISDN: (axios, thueBaoId, kieuLdId) => axios.get(`web-hopdong/thaydoi-account/sp_kiemtra_lay_ds_so_isdn?thuebao_id=${thueBaoId}&kieuld_id=${kieuLdId}`),
  kiemTraMaTB: (axios, body) => axios.post('web-hopdong/hopdong/kiemtra_matb', body),
  kiemTraAccountVisa: (axios, body) => axios.post('tichhop/visa-app/lookupRASAccount', body)
}
