package vn.vnptit.sapi.oneapp.service.tts

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonProperty
import groovy.transform.Canonical
import groovy.transform.ToString

@Canonical
@ToString(includeFields = true, includeNames = true)
@JsonIgnoreProperties(ignoreUnknown = true)
class SyncViaGwOssRequestDTO {
    @JsonProperty String id_tts = ""
    @JsonProperty String id_css = ""
    @JsonProperty String loaiphieu_id = ""
    @JsonProperty String parent_id = ""
    @JsonProperty String ma_tinh = ""
    @JsonProperty String mo_ta = ""
    @JsonProperty String tg_batdau = ""
    @JsonProperty String tg_dukien_xyly = ""
    @JsonProperty String tg_ketthuc = ""
    @JsonProperty String tg_chuyenphieu = ""
    @JsonProperty String anhhuong_dvu = ""
    @JsonProperty String chitiet_anhhuong = ""
    @JsonProperty String donvi_chuquan = ""
    @JsonProperty String dai_vt = ""
    @JsonProperty String mucdo_id = ""
    @JsonProperty String loai_suco = ""
    @JsonProperty String hethong = ""
    @JsonProperty String thietbi_id = ""
    @JsonProperty String ma_thietbi = ""
    @JsonProperty String nguon_sc = ""
    @JsonProperty String thongtin_chitiet = ""
    @JsonProperty String nguyen_nhan = ""
    @JsonProperty String giai_phap = ""
    @JsonProperty String bienphap_phongngua = ""
    @JsonProperty String thamso_thaydoi = ""
    @JsonProperty String trangthai_xly = ""
    @JsonProperty String ma_quytrinh = ""
    @JsonProperty String ma_buoc_hien_tai = ""
    @JsonProperty String ma_buoc_tiep_theo = ""
    @JsonProperty String ma_nhanvien_xuly = ""
    @JsonProperty String donvi_xuly_id = ""
    @JsonProperty String ma_donvi_xuly_hrm = ""
    @JsonProperty String donvi_nhan_id = ""
    @JsonProperty String ma_donvi_nhan_id = ""
    @JsonProperty String donvi_giao_id = ""
    @JsonProperty String ma_donvi_giao_hrm = ""
    @JsonProperty String css_parent_id = ""
    @JsonProperty String css_id = ""
    @JsonProperty String loaidoituong = ""
    @JsonProperty String id_hethong = ""
    @JsonProperty String diachine = ""
    @JsonProperty String tenhang = ""
    @JsonProperty String phanloaitram = ""
    @JsonProperty String ma_csht = ""
    @JsonProperty String loaicanhbao = ""
    @JsonProperty String muc_donvi_nhan = ""
    @JsonProperty String ten_donvi_giao = ""
    @JsonProperty String ten_donvi_nhan = ""
    @JsonProperty String ma_donvi_nhan_hrm = ""
    @JsonProperty String id_fms = ""
    @JsonProperty String nhomnn_id = ""
    @JsonProperty String nhom_nn = ""
    @JsonProperty String nguyennhan_id = ""
    @JsonProperty String Ma_quytrinh_cha = ""
    @JsonProperty String qos = ""
    @JsonProperty String qoe = ""
    @JsonProperty String voice = ""
    @JsonProperty String cei = ""
    @JsonProperty String ma_nguyen_nhan_fms = ""
    @JsonProperty String VSAT = ""
    @JsonProperty String MAY_NO = ""
    @JsonProperty String KV_BIENBAO = ""
    @JsonProperty String MA_NHOM_TTP = ""
    @JsonProperty String sla_date = ""
    @JsonProperty String sla_process_time = ""
    @JsonProperty String sla = ""
    @JsonProperty String quahan_taibuoc = ""
    @JsonProperty String quahan_toantrinh = ""
    @JsonProperty List<Map<String, Object>> phuongan_dexuat = []
}
