@base = https://api-onebss-dev.vnptit3.vn
@contentType = application/json
@createdAt = {{$datetime iso8601}}

#IT00752
@usr1 = TEST_APP1.HPG
@pwd1 = dhdbtt2017
#IT00753
@usr2 = TEST_APP2.HPG
@pwd2 = dhdbtt2017
#CTV045272
@usr3 = TEST_APP3.HPG
@pwd3 = dhdbtt2017

@usr = admin
@pwd = dhdbtt2017
### Login

POST {{base}}/quantri/user/login HTTP/1.1
Content-Type: {{contentType}}

{
	"username": "{{usr}}",
	"password": "{{pwd}}"
}

### Get token
## lay secretCode ở Login
## otp fix 159874 cho dev


POST {{base}}/quantri/oauth/token  HTTP/1.1
Content-Type: {{contentType}}

{
	"grant_type": "password",
    "client_id": "clientapp",
    "client_secret": "password",
    "otp": "159874",
	"secretCode": "37:313000030501210383345800026543:543::2::0:"
}

### Resend OTP

POST {{base}}/quantri/user/resendotp HTTP/1.1
Content-Type: {{contentType}}

{
	"secretCode": "37:313016200133400090235865298302520:02520:097:2::888888:"
}


@TokenID = 97388db0-6ce9-11ea-bc55-0242ac130003
@BearerToken = Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9uaGFudmllbl9kaHN4IjoiNDUyIiwiaWRlbnRpZnkiOiI2Mj82NDY1NTU1NjUwNTQ3NDU2PTY2MTA9NTU1NzMwMTY_MDE2Pz83Pz81PyIsIm1hX3RpbmgiOiJIUEciLCJ1c2VyX25hbWUiOiJhZG1pbiIsImdyb3VwSWQiOiIwIiwiaXNzIjoiaHR0cDovL3F1YW50cmkvb2F1dGgvdG9rZW5fa2V5IiwiYXV0aG9yaXRpZXMiOlsiUFJFX0FVVEgiXSwiaWRfZG9udmkiOiI5MDAiLCJjbGllbnRfaWQiOiJjbGllbnRhcHAiLCJhdWQiOlsicmVzdHNlcnZpY2UiXSwic2NvcGUiOlsicmVhZCIsIndyaXRlIl0sIm1hX25oYW52aWVuX2NjYnMiOiJhZG1pbl9ocGciLCJzZWxsaW5nRGVwYXJ0bWVudElkIjoiMCIsImNzc19zY2giOiJDU1NfSFBHLiIsImV4cCI6MTYzNzkzODI0MSwibWFfbnYiOiJJVDAwMTIyIiwiaWRfdGluaHRoYW5oIjoiMjYiLCJuZ3VvaWR1bmdfaWQiOiIxIn0.ab7kLGei9l_RHK75DWsbosoJCDPYyfVmRjeYYe45_KN2QYxmBWe7LvPWepqXzVCeKHI7m-ncpRw46DdB74jcgP8HQ0tfRWYoRpWqEbJpSyrtH6Fu0lKU28MGqY-YKpC1BULHyrQEOdURlwyTv6TiUuFf3tz6gxRHef670GjbW-KgCdJb0yzVWAmuDB2Q854PhXlzyKiEt99BXhcPv_8szIFmBreqwkYIaQQBrKT9CzorUkIGLHFXE7eRG9D6gcvdOdvMXITlpLuuko-4mDjY6wqNir5VClBW6LDjuTIQVLtJWyOeE-w3d_RkQKzIwRNQoUAyevzh7yiB0_m5cIcjBA
@AppSecret = ewogICJkZXZpY2VfaWQiOiAiMTI0IiwKICAiZGV2aWNlX2lwIjogIjEuMS4xLjEiLAogICJkZXZpY2VfbmFtZSI6ICJJT1MxMzEiLAogICJtYWNfYWRkcmVzcyI6ICI2NC01RC04Ni1EQy04QS0xNSIsCiAgIm1vYmlsZV9pZCI6ICIxMTI0IiwKICAiYXBwX2lkIjogIjEiLAogICJhcHBfdmVyc2lvbiI6ICJJT1MuMS4wLjEiLAogICJvc192ZXJzaW9uIjogIjExIgp9



POST  {{base}}/web-thicong/thanhly-thuebao/sp_ht_dichvuvt_combobox HTTP/1.1
Content-Type: {{contentType}}
Token-id: {{TokenID}}
Mac-address: WEB
App-secret: {{AppSecret}}
Authorization: {{BearerToken}}

{
	"dichvu_vt_id": "5,8,4"
}


POST  {{base}}/web-thicong/hths-thaydoi-tocdo/sp_lay_dulieu_bang_theo_dieukien HTTP/1.1
Content-Type: {{contentType}}
Token-id: {{TokenID}}
Mac-address: WEB
App-secret: {{AppSecret}}
Authorization: {{BearerToken}}

{
    "schema": "CSS",
    "table_name": "TOCDO_ADSL",
    "list_of_cols": "TOCDO_ID,THUONGHIEU",
    "where": "",
    "order": "TOCDO_ID"
}

POST  {{base}}/web-thicong/hths-thaydoi-tocdo/sp_lay_ds_nhanvien_thuchien_theo_dv HTTP/1.1
Content-Type: {{contentType}}
Token-id: {{TokenID}}
Mac-address: WEB
App-secret: {{AppSecret}}
Authorization: {{BearerToken}}
 
{
    "donvi_id": 100
}
