export default {
	capnhat_hd_cntt_v9: async (axios, data) => axios.post(`/web-hopdong/dichvu-cntt-gtgt/capnhat_hd_cntt_v9`, data),
	capnhat_hd_thuebao_ct_common: async (axios, data) => axios.post(`/web-hopdong/dichvu-cntt-gtgt/capnhat_hd_thuebao_ct_common`, data),
	KIEM_TRA_MUA_TBI_TRONGOI_HDKH: async (axios, data) => axios.post(`/web-hopdong/dichvu-cntt-gtgt/kiem_tra_mua_tbi_trongoi_hdkh`, data),
	kt_goccuoc_giahan_ca: async (axios, data) => axios.post(`/web-hopdong/dichvu-cntt-gtgt/kt_goccuoc_giahan_ca`, data),
	NAP_DS_COMBO: async (axios, data) => axios.post(`/web-hopdong/dichvu-cntt-gtgt/fn_lay_tt_nap_ds_combo_giahancntt`, data),
	layds_kieuld_theo_lhtb: async (axios, data) => axios.post(`/web-hopdong/dichvu-cntt-gtgt/layds_kieuld_theo_lhtb`, data),
	loaihinhtb_loaidv: async (axios, data) => axios.post('/web-hopdong/thuebao_datcoc_thunghiem/sp_ds_loaihinhtb_loaidv', data),
	ds_hopdong_theo_ma_gd: async (axios, data) => axios.post('/web-hopdong/dichvu-ca/lay_ds_hopdong_theo_ma_gd', data),
	lay_ds_hopdong_tb_theo_hdkh_id: async (axios, data) => axios.post('/web-hopdong/khuyenmai_tocdo_internet/lay_ds_hopdong_tb_theo_hdkh_id', data),
	lay_ds_hopdong_theo_ma_tb: async (axios, data) => axios.post('/web-hopdong/thuebao_datcoc_thunghiem/lay_ds_hopdong_theo_ma_tb', data),
	LAY_DANHBA_THEO_MATB: async (axios, data) => axios.post('/web-tracuu/tracu-danhba/LAY_DANHBA_THEO_MATB', data),
	hienthittdanhbakh: async (axios, data) => axios.post('/web-hopdong/dichvu-cntt-gtgt/fn_lay_tt_hienthittdanhbakh_giahancntt', data),
	hienthi_tt_hopdong: async (axios, data) => axios.post('/web-hopdong/dichvu-cntt-gtgt/fn_lay_tt_hienthitthopdongtb_giahancntt', data),
	lay_ds_thuoctinh_giahan_cntt: async (axios, data) => axios.post('/web-hopdong/dichvu-cntt-gtgt/sp_lay_danhsach_thuoctinh_giahan_cntt', data),
	fn_init_properties_cntt: async (axios, data) => axios.post('/web-hopdong/lapdatmoi/fn_init_properties_cntt', data),
	ttdb_morong_giahancntt: async (axios, data) => axios.post('/web-hopdong/dichvu-cntt-gtgt/fn_lay_tt_hienthi_tt_db_morong_giahancntt', data),
	ht_giaodien_donvi: async (axios, data) => axios.post('/web-hopdong/dichvu-cntt-gtgt/sp_ht_giaodien_donvi_giahancntt', data),
	getDS_DONVI_TRAMTC_BANTHIETBI: async (axios, data) => axios.post('/web-hopdong/dichvu-ca/sp_lay_ds_donvi_tramtc_banthietbi', data),
	getDS_DONVI_THEO_LOAIDV_BANTHIETBI: async (axios, data) => axios.post('/web-hopdong/dichvu-ca/sp_lay_ds_donvi_theo_loaidv_banthietbi', data),
	load_hdtbdv: async (axios, data) => axios.post('/web-hopdong/dichvu-cntt-gtgt/sp_load_hdtbdv_giahancntt', data),
	lay_kenhban_caidat_dv: async (axios, data) => axios.post('/web-hopdong/dichvu-cntt-gtgt/lay_kenhban_caidat_dv', data),
	lay_pbh_caidat_dv: async (axios, data) => axios.post('/web-hopdong/dichvu-cntt-gtgt/lay_pbh_caidat_dv', data),
	timkiem_matb: async (axios, data) => axios.post('/web-hopdong/dichvu-cntt-gtgt/fn_lay_tt_timkiem_matb_giahancntt', data),
	LayHuongGiao_TiepNhan: async (axios, data) => axios.post('/web-hopdong/hopdong/lay_huonggiao_tiepnhan', data),
	kt_va_lay_tt_capnhat: async (axios, data) => axios.post('/web-hopdong/dichvu-cntt-gtgt/fn_kt_va_lay_tt_capnhat_frmgiahandvcntt', data),
	get_kiemTraThoiHanKM: async (axios, data) => axios.post('/web-hopdong/thaydoithongtinkhuyenmai/kiemtra_thoihan_khuyenmai', data),
	get_lay_ngaykt_km: async (axios, data) => axios.post('/web-hopdong/lapdatmoi/lay_ngaykt_km', data),
	kiemtra_hienthi_thietbi: async (axios, data) => axios.post('/web-hopdong/dichvu-cntt-gtgt/fn_kiemtra_hienthi_thietbi_theo_loaitb', data),
	ttct_thietbi: async (axios, data) => axios.post('/web-ccdv/ban-thiet-bi/sp_ht_ttct_thietbi_loaitbi', data),
	lay_chitiet_km_theo_hdtb_id: async (axios, data) => axios.get(`/web-ccdv/HoanCongThuTienPhatSinh/lay_chitiet_km_theo_hdtb_id?vhdtb_id=${data.vhdtb_id}&vloai_km=${data.vloai_km}`),
	nap_ds_kmtt: async (axios, data) => axios.post('/web-hopdong/dichvu-cntt-gtgt/sp_lay_tt_nap_ds_kmtt_giahancntt', data),
	getds_trangthaihd: async (axios, nhanvien_id) => axios.get(`/web-tracuu/danhmuc/trangthai_hd`),
	txttocdo_id_changed: async (axios, data) => axios.post('/web-hopdong/dichvu-cntt-gtgt/fn_lay_tt_txttocdo_id_changed_giahancntt', data),
	DB_CNTT: async (axios, thuebao_id) => axios.get(`/web-hopdong/hopdong/lay_ds_danhba_cntt?thueBaoId=${thuebao_id}`),
	fn_xoahd_kh_giahancntt: async (axios, data) => axios.post('/web-hopdong/dichvu-cntt-gtgt/fn_xoahd_kh_giahancntt', data),
	Lay_HuongGiao_QuyTrinh: async (axios, data) => axios.post('/web-thicong/hoinghi_truyenhinh/sp_lay_huonggiao_theo_quytrinh', data),
	lay_tt_tsbtnthanhtoan: async (axios, data) => axios.post('/web-hopdong/dichvu-cntt-gtgt/fn_lay_tt_tsbtnthanhtoan_click_giahancntt', data),
	getKey: async (axios, data) => axios.post('/web-hopdong/khoiphucthanhly/get_keys', data),
	kieuld_tscn: async (axios, data) => axios.post('/web-hopdong/dichvu-cntt-gtgt/kieuld_tscn', data),
	getNhanvien_nvID: async (axios, nhanvien_id) => axios.get(`/web-hopdong/danhmuc/lay_thongtin_nhanvien/${nhanvien_id}`),
	// frmHDTB_SUB_V2
	lay_thongtin_loaigt: async (axios) => axios.get(`/web-ccdv/tram-thicong-dv-cntt/lay_thongtin_loaigt`),
	lay_thongtin_loaitb_id: async (axios, hdtb_id) => axios.get(`/web-ccdv/tram-thicong-dv-cntt/lay_thongtin_loaitb_id?hdtb_id=${hdtb_id}`),
	lay_tt_thuebao_bosung_ca: async (axios, hdtb_id) => axios.get(`/web-ccdv/tram-thicong-dv-cntt/lay_tt_thuebao_bosung_ca?hdtb_id=${hdtb_id}`),
	ivan_khoa_form_thongtin_bosung: async (axios, kieuld_id) => axios.get(`/web-ccdv/tram-thicong-dv-cntt/ivan_khoa_form_thongtin_bosung?kieuld_id=${kieuld_id}`),
	ca_khoa_form_thongtin_bosung: async (axios, kieuld_id) => axios.get(`/web-ccdv/tram-thicong-dv-cntt/ca_khoa_form_thongtin_bosung?kieuld_id=${kieuld_id}`),
	capnhat_hdtb_sub_ra_ca: async (axios, data) => axios.post('/web-ccdv/tram-thicong-dv-cntt/capnhat_hdtb_sub_ra_ca', data),
	// frmHDTB_SUB_V3
	lay_tt_thuebao_bosung: async (axios, data) => axios.post('/web-thicong/hoinghi_truyenhinh/lay_tt_thuebao_bosung', data),
	fn_capnhat_hdtb_sub: async (axios, data) => axios.post('/web-ccdv/tram-thicong-dv-cntt/fn_capnhat_hdtb_sub', data),
	// frmDangKyThietBiIDC
	lay_ds_thietbi_idc_dangky: async (axios, hdtb_id) => axios.get(`/web-ccdv/tram-thicong-dv-cntt/lay_ds_thietbi_idc_dangky?hdtb_id=${hdtb_id}`),
	lay_ds_thietbi_idc_sudung: async (axios, thuebao_id) => axios.get(`/web-ccdv/tram-thicong-dv-cntt/lay_ds_thietbi_idc_sudung?thuebao_id=${thuebao_id}`),
	capnhat_thietbi_dk_biendong_idc: async (axios, data) => axios.post('/web-ccdv/tram-thicong-dv-cntt/capnhat_thietbi_dk_biendong_idc', data),
	// frmChuanHoaHDDT
	LayTTKhachHangHDDT: async (axios, _mst) => axios.get(`/tichhop/hddt/LayThongTinKHHDDT?taxcode=${_mst}`),
	LaySoLuongHDDTDaDK: async (axios, cus_id, _mst) => axios.get(`/tichhop/hddt/LaySoLuongHDDTDaDK?cus_id=${cus_id}&taxcode=${_mst}`),
	LayDSMauHoaDonDaDangKy: async (axios, data) => axios.post(`/tichhop/hddt/LayDSMauHoaDonDaDangKy`,data),
	dongbo_dulieu_hddt: async (axios, data) => axios.post(`/web-hopdong/hopdong/dongbo_dulieu_hddt`,data),
	LayChiTietMauHoaDon: async (axios, id) => axios.get(`/tichhop/hddt/LayChiTietMauHoaDon?inv_id=${id}`),

	SP_LAY_DS_DL_NGHIEPVU: async (axios, data) => axios.post(`/web-hopdong/quanly_khdn_mnp/sp_lay_ds_dl_nghiepvu`,data),
  	GIAHAN_HANGLOAT_CA_V2: async (axios, data) => axios.post('/web-hopdong/hopdong/giahan_hangloat_ca_v2', data),
  	Get_Data_TraCuu: async (axios, data) => axios.post(`/tichhop/vnEduEnrollment/tracuu`,data),
	Check_Data_Edu: async (axios, data) => axios.post('/web-thicong/edu/check_data_edu', data),
	cntt_dynamic_api: (axios, data) => axios.post(`web-thicong/cnttdynamic/api`, data),
	sp_lay_ds_nghiepvu_cntt_common : async(axios, data) => axios.post('/web-thicong/dvcntt/lay_ds_nghiepvu_cntt_common',data),
  	fn_thongbao_kichhoat_dvcntt_common : async(axios, data) => axios.post('/web-thicong/dvcntt/fn_thongbao_kichhoat_dvcntt_common', data),

}
