export default{
    getDsChiTietDvIMS: (axios, data) => axios.post('/web-ccdv/khaibaoims/sp_lay_ds_chitietdv_ims', data),
    getDsThamSoMD: (axios, data) => axios.post('/web-ccdv/khaibaotsl/sp_lay_ds_thamso_md', data),
    getDsThietBiIMS: (axios, data) => axios.post('/web-hopdong/giao_cho_qlk/sp_lay_dulieu_theo_dieukien', data),
    getDsDichVuVT: (axios, data) => axios.post('/web-ccdv/hths-thaydoi-tocdo/sp_ht_dichvuvt_combobox', data),
    getDsKieuLD: (axios, data) => axios.post('/web-ccdv/ds_yeucau_khaosat/lay_ds_kieu_ld', data),
    getDsLoaiTB: (axios) => axios.get('/web-quantri/danhmuc-chung/CSS_LOAIHINH_TB'),
    getDsHopDongTheoMaTB: (axios, data) => axios.post('/web-ccdv/thaythe_vattu_wifi/lay_ds_hopdong_theo_ma_tb', data),
    getDsHDTB_TDTS_IMS: (axios, data) => axios.get('/web-hopdong/thay_doi_thong_so_ims/lay_ds_hopdong_tb_tdts_ims/' + data),
    getDanhBaTheoMaTB: (axios, data) => axios.post('/web-tracuu/tracu-danhba/LAY_DANHBA_THEO_MATB', data),
    ktraTB_LapHDKhac: (axios, data) => axios.post('/web-hopdong/hopdong/kiemtra_thuebao_lap_hopdong_khac', data),
    //getDBIMSTheoTBId: (axios, data) => axios.post('/web-hopdong/thaydoiloaihinhtbcodinhims/lay_ds_db_ims_theo_tbid', data),
    layDsDanhBaIMS: (axios, data) => axios.get("/web-hopdong/hopdong/lay_ds_danhba_ims?thueBaoId=" + data.thuebao_id),
    getDsHopDongTheoMaGD: (axios, data) => axios.post('/web-hopdong/dichvu-ca/lay_ds_hopdong_theo_ma_gd', data),
    getTienKhoanMucLD: (axios, data) => axios.post('/web-hopdong/khoiphucthanhly/lay_tien_khoanmuc_ld', data),
    ktraMaKH_MaTT_MaGD: (axios, data) => axios.post('/web-hopdong/hopdong/kiemtra_makh_matt_magd', data),
    fnInsUpdateTDTS_IMS: (axios, data) => axios.post('/web-hopdong/thay_doi_thong_so_ims/fn_ins_update_thaydoi_ts_ims', data),
    getHuongGiaoTiepNhan: (axios, data) => axios.post('/web-hopdong/dichvu-ca/layhuonggiao_tiepnhan', data),
    getDsDBTB_DV: (axios, data) => axios.post('/web-hopdong/dichvu-ca/sp_lay_ds_dbtb_dv', data),
    getKey: (axios, data) => axios.post('/web-hopdong/khoiphucthanhly/get_keys', data),
    getMaGDv2: (axios, data) => axios.post('/web-hopdong/khoiphucthanhly/sinh_magd_v2', data),
    getMaGD: (axios, data) => axios.post('/web-hopdong/khoiphucthanhly/sinh_magd', data),
    fnInsUpdateTDTS_IMS_ThemTB: (axios, data) => axios.post('/web-hopdong/thay_doi_thong_so_ims/fn_ins_update_thaydoi_ts_ims_them_tb', data),
    getBienDongTheoHDTBId: (axios, data) => axios.post('/web-hopdong/khoiphucthanhly/lay_biendong_theo_hdtb_id', data),
    getDB_HDTBTheoKHId_MaGD: (axios, data) => axios.post('/web-ccdv/tien_trinh_bao_hong/lay_ds_db_hdtb_theo_khid_magd', data),
    delHDTB: (axios, data) => axios.post('/web-hopdong/thuebao_datcoc_thunghiem/xoa_hdtb', data),
    //delHDKH: (axios, data) => axios.post('/web-hopdong/khoiphucthanhly/xoa_hdkh_v2', data),
    delHDKH: (axios, data) => axios.post('/web-baohong/TiepNhanBaoHong/xoa_hdkh_version_nd', data), // Sửa theo comment 10h44 ngày 18/7 của anh Nguyễn Việt Dũng trong https://cntt.vnpt.vn/browse/BSS-67708
    getHDKHTheoMaGD: (axios, data) => axios.post('/web-hopdong/thay_doi_thong_so_ims/lay_hopdong_kh_theo_magd', data),

    // Bán chéo - minhtri.hcm: 06/12/2023
    lay_ds_kieu_ld_bc: (axios, data) => axios.post('/web-hopdong/thaydoitocdoadsl/lay_ds_kieu_ld_bc', { "vloaihd_id": data.vloaihd_id, "vkieu": data.vkieu, "vloaitb_id": data.vloaitb_id }), 
    lay_tinhthicong_theo_matb: (axios, matb) => axios.get(`/web-bancheo/tracuu/lay_tinhthicong_theo_matb?matb=${matb}`), 
    lay_ds_hopdong_theo_ma_tb_TraCuu: (axios, data) => axios.post('/web-bancheo/thaydoimegawan/lay_ds_hopdong_theo_ma_tb', { 
        "tinhthicong_id": data.tinhthicong_id ? data.tinhthicong_id : 0, 
        "in_ma_tb": data.in_ma_tb ? data.in_ma_tb : '', 
        "in_loaihd_id": data.in_loaihd_id ? data.in_loaihd_id : 0, 
        "in_donvi_id": data.in_donvi_id ? data.in_donvi_id : 0, 
        "in_tthd_id": data.in_tthd_id ? data.in_tthd_id : 0, 
        "in_nhanvien_id": data.in_nhanvien_id ? data.in_nhanvien_id : 0, 
        "in_donvi_dl_id": data.in_donvi_dl_id ? data.in_donvi_dl_id : 0, 
        "in_dichvuvt_id": data.in_dichvuvt_id ? data.in_dichvuvt_id : 0, 
        "in_loaitb_id": data.in_loaitb_id ? data.in_loaitb_id : 0, 
    }), 
    lay_danhba_theo_thuebaoid: (axios, data) => axios.post('/web-bancheo/tracuu/lay_danhba_theo_thuebaoid', { 
        "tinhthicong_id": data.tinhthicong_id ? data.tinhthicong_id : 0, 
        "thuebao_id": data.thuebao_id ? data.thuebao_id : 0, 
        "dichvuvt_id": data.dichvuvt_id ? data.dichvuvt_id : 0, 
        "donvi_id": data.donvi_id ? data.donvi_id : 0, 
        "loaihdbc": data.loaihdbc ? data.loaihdbc : 0, 
    }), 
    kiemtra_hd_bancheo_tc: (axios, data) => axios.post('/web-hopdong/thaydoidichvu/kiemtra_hd_bancheo_tc', {
        "thuebao_id": data.thuebao_id ? data.thuebao_id : 0,
        "loaihd_id": data.loaihd_id ? data.loaihd_id : 0, 
    }), 
    lay_ds_db_thuebao_theo_tbid: (axios, data) => axios.post('/web-bancheo/tracuu/lay_ds_db_thuebao_theo_tbid', {
        "thuebao_id": data.thuebao_id ? data.thuebao_id : 0,
        "tinhthicong_id": data.tinhthicong_id ? data.tinhthicong_id : 0,
    }), 
    lay_thanhtoan_theo_thuebaoid: (axios, data) => axios.get(`/web-bancheo/tracuu/lay_thanhtoan_theo_thuebaoid?thuebao_id=${data.thuebao_id}`), 
    fn_tt_muccuoc_tb: (axios, data) => axios.post('/web-bancheo/tracuu/fn_tt_muccuoc_tb', {
        "param": 1, 
        "tinhthicong_id": data.tinhthicong_id ? data.tinhthicong_id : 0
    }), 
    lay_ds_db_ims_theo_tbid: (axios, data) => axios.post('/web-bancheo/tracuu/lay_ds_db_ims_theo_tbid', {
        "thuebao_id": data.thuebao_id ? data.thuebao_id : 0,
        "tinhthicong_id": data.tinhthicong_id ? data.tinhthicong_id : 0,
    }), 
    layhuonggiao_tiepnhan_bancheo: (axios, data) => axios.post('/web-bancheo/tracuu/layhuonggiao_tiepnhan_bancheo', {
        "vloaihd_id": data.vloaihd_id ? data.vloaihd_id : 0,
        "tinhthicong_id": data.tinhthicong_id ? data.tinhthicong_id : 0,
        "vloaitb_id": data.vloaitb_id ? data.vloaitb_id : 0,
        "vtocdo_id": data.vtocdo_id ? data.vtocdo_id : 0,
        "vmuccuoc_id": data.vmuccuoc_id ? data.vmuccuoc_id : 0,
        "vkieuld_id": data.vkieuld_id ? data.vkieuld_id : 0,
    }), 
    lay_thongso_thuebao_hdbc: (axios, hdtb_id) => axios.get(`/web-hopdong/thanhly-thuebao-bancheo/lay_thongso_thuebao_hdbc?hdtb_id=${hdtb_id}`),
    lay_ds_loaiip_theo_hdtb_id: async (axios, hdtb_id) => axios.get('/web-hopdong/thanhly-thuebao-bancheo/lay_ds_loaiip_theo_hdtb_id?hdtbid=' + hdtb_id),
    lay_ds_kieunt_theo_hdtb_id: async (axios, hdtb_id) => axios.get('/web-hopdong/thanhly-thuebao-bancheo/lay_ds_kieunt_theo_hdtb_id?hdtbid=' + hdtb_id),
    lay_tinh_theo_thuebaoid: (axios, thuebao_id) => axios.get(`/web-hopdong/thanhly-thuebao-bancheo/lay_tinh_theo_thuebaoid?thuebao_id=${thuebao_id}`),
}