export default {
    getCBDonViQL: (axios) => axios.post('/web-thicong/hoso_datcoc_theofile/lay_ds_donvi_ctv'),
    getCBNhom: (axios, data) => axios.post('/web-thicong/hoso_datcoc_theofile/sp_lay_ds_nhom_nv', data),
    getCBNhanVien: (axios, data) => axios.post('/web-thicong/hoso_datcoc_theofile/ht_ds_nhanvien_ctv_combobox', data),
    getCBDichVu: (axios) => axios.get('/web-quantri/danhmuc-chung/CSS_DICHVU_VT'),
    getCBLoaiHinh: (axios) => axios.get('/web-quantri/danhmuc-chung/CSS_LOAIHINH_TB'),
    getTTUuDai: (axios, data) => axios.get('/web-thicong/hoso_datcoc_theofile/lay_chitiet_km_datcoc_v3', data),
    getCBNhomDatCoc: (axios) => axios.get('/web-quantri/danhmuc-chung/CSS_NHOM_DATCOC'),
    getDsThamSoMD: (axios, data) => axios.post('/web-hopdong/laydulieu/sp_tt_db_adsl', data),
    getDsKhuyenMai: (axios, data) => axios.post('/web-thicong/hoso_datcoc_theofile/sp_lay_ds_khuyenmai', data),
    getTTHopDongKH: (axios, data) => axios.post('/web-thicong/hoso_datcoc_theofile/sp_lay_ds_nhom_nv', data),
    getDsThueBaoDatCoc: (axios, data) => axios.post('/web-thicong/hoso_datcoc_theofile/lay_ds_hdtb_theo_hdkh_v2', data),
    getDsHopDongTuFile: (axios, data) => axios.post('/web-thicong/hoso_datcoc_theofile/lay_ds_hd_datcoc_file', data),
    postGhiLaiHD: (axios, data) => axios.post('/web-thicong/hoinghi_truyenhinh/sp_get_data_sql', data),
    postXoaHD: (axios, data) => axios.post('/web-thicong/hoso_datcoc_theofile/xoa_hdkh_v2', data),
    getLayBCTheoId: (axios, data) => axios.post('/web-thicong/hoso_datcoc_theofile/sp_lay_baocao_theo_id', data),
    getLayThamSoBC: (axios, data) => axios.post('/web-thicong/hoso_datcoc_theofile/sp_lay_thamso_baocao', data),
    postHTHSDatCocFile: (axios, data) => axios.post('/web-thicong/hoso_datcoc_theofile/hths_datcoc_file', data),
    getDsKhuyenMaiChiTiet: (axios, data) => axios.post('/web-thicong/hoso_datcoc_theofile/lay_chitiet_km_datcoc_third', data),
    getDsHDTheoMaGD: (axios, data) => axios.post('/web-thicong/hoinghi_truyenhinh/lay_ds_hopdong_theo_ma_gd', data),
    updateDataCocFromFileTemp: (axios, data) => axios.post('/web-thicong/hoso_datcoc_theofile/fn_capnhat_datcoc_temp', data),
    capnhatDatcocTheoFile: (axios, data) => axios.post('/web-thicong/hoso_datcoc_theofile/fn_capnhat_datcoc_theofile', data),
    kiemTraDatCocTmp: (axios, data) => axios.post('/web-thicong/hoso_datcoc_theofile/kiemtra_datcoc_tmp', data),
    
}