const MODEL = {
    ten_ctv: '',
    kieuhd_id: '',
    kenhthu_id: '0',
    tongtien: '0',
    giohen_tu: false,
    loaihd_id: '0',
    quytrinh_id: '0',
    ten_tb: '',
    ten_kv: '',
    ma_gd: '',
    ma_tb: '',
    diachi_tb: '',
    ten_kieuld: '',
    ma_tb_cu: '',
    diachi_ld: '',
    so_dt: '',
    phanloaikh: '',
    diachi_ld_cu: '',
    host_ld_cu: '',
    laythongtinhoancong: 0,
    ngaygiao: new Date().toLocaleDateString(),
    ngay_ht_gp: new Date().toLocaleDateString(),
    nguoigv_id: '0',
    ten_nv: '',
    nd_giao: '',
    LYDOTRA: '',
    nd_tra_con: '',
    nd_thuchien: '',
    tg_thueso: '',
    sotruot: '',
    noidung_tb: '',
    matb_tn: '',
    host_ld: '',
    host_vl: '',
    ten_nhanvien_yc: '',
    thongtin_lh: '',
    DS_TBLAPKEM: '',
    ne: '',
    tramtb_id: '0',
    loaicap_id: '0',
    lientu: '',
    hopcap_p: '',
    cap_goc: '',
    cap_p: '',
    tuyencap: '',
    tucap_goc: '',
    tucap_p: '',
    doicap_goc: '',
    doicap_p: '',
    culy: ''
}

export default MODEL
