@base = https://api-onebss-dev.vnptit3.vn
@contentType = application/json
@createdAt = {{$datetime iso8601}}

#IT00752
@usr1 = TEST_APP1.HPG
@pwd1 = dhdbtt2017
#IT00753
@usr2 = TEST_APP2.HPG
@pwd2 = dhdbtt2017
#CTV045272
@usr3 = TEST_APP3.HPG
@pwd3 = dhdbtt2017

@usr = TEST_APP.HPG
@pwd = dhdbtt2017
### Login
#CTV: tuannt.hpg / dhdbtt2017
POST {{base}}/quantri/user/login HTTP/1.1
Content-Type: {{contentType}}

{
	"username": "tuannt.hpg",
	"password": "dhdbtt2017"
}

### Get token
## lay secretCode ở Login
## otp fix 159874 cho dev


POST {{base}}/quantri/oauth/token  HTTP/1.1
Content-Type: {{contentType}}

{
	"grant_type": "password",
    "client_id": "clientapp",
    "client_secret": "password",
    "otp": "159874",
	"secretCode": "37:31300110001639038050685923935422:5422:881:2::3420:"
}

### Resend OTP

POST {{base}}/quantri/user/resendotp HTTP/1.1
Content-Type: {{contentType}}

{
	"secretCode": "37:313016200133400090235865298302520:02520:097:2::888888:"
}


@TokenID = 97388db0-6ce9-11ea-bc55-0242ac130003
@BearerToken = Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9uaGFudmllbl9kaHN4IjoiNDUyIiwiaWRlbnRpZnkiOiI2Mj82NDY1NTY0NzQ9MDUxMDU2PTY8NDA3PDU1MTwyMDE2PzAxNj8_Nz8_NT8iLCJtYV90aW5oIjoiSFBHIiwidXNlcl9uYW1lIjoiYWRtaW4iLCJncm91cElkIjoiMCIsImlzcyI6Imh0dHA6Ly9xdWFudHJpL29hdXRoL3Rva2VuX2tleSIsImF1dGhvcml0aWVzIjpbIlBSRV9BVVRIIl0sImlkX2RvbnZpIjoiOTAwIiwiY2xpZW50X2lkIjoiY2xpZW50YXBwIiwiYXVkIjpbInJlc3RzZXJ2aWNlIl0sInNjb3BlIjpbInJlYWQiLCJ3cml0ZSJdLCJtYV9uaGFudmllbl9jY2JzIjoiYWRtaW5faHBnIiwic2VsbGluZ0RlcGFydG1lbnRJZCI6IjAiLCJjc3Nfc2NoIjoiQ1NTX0hQRy4iLCJleHAiOjE2Mzk3MzY1NDEsIm1hX252IjoiSVQwMDEyMiIsImlkX3Rpbmh0aGFuaCI6IjI2Iiwibmd1b2lkdW5nX2lkIjoiMSJ9.MEmbLKkogIauZVJKU1cUZVEmLhexw6hOYk1riTTxkKt-5BHdER4LImopzqB08ynzb8e26PZjvs94xyD6aJgmqmTeMc9D66q79tQL2Dqk-wAp7fjZGwpEXAem2mi_VjRnx3eg6BbPFiOqfy4cIjpuZF3atnsc8ek-wMT7qXwZK8Mt9Q8Sz9PErnG6zJvEYCGv6kLysEAyArhi0acXaj_TrI036yilpv6IWVUbd8WuctiA2JHG04_3TDNrhCVaGqw5v_HyamSymMawKy_NMtGja98FvizTlIRhMZS0GIjyxHDuswf-gP_sO5d9mD1O3Zu4axIN_faeXafiBIRX5Uxa7w
@AppSecret = ewogICJkZXZpY2VfaWQiOiAiMTI0IiwKICAiZGV2aWNlX2lwIjogIjEuMS4xLjEiLAogICJkZXZpY2VfbmFtZSI6ICJJT1MxMzEiLAogICJtYWNfYWRkcmVzcyI6ICI2NC01RC04Ni1EQy04QS0xNSIsCiAgIm1vYmlsZV9pZCI6ICIxMTI0IiwKICAiYXBwX2lkIjogIjEiLAogICJhcHBfdmVyc2lvbiI6ICJJT1MuMS4wLjEiLAogICJvc192ZXJzaW9uIjogIjExIgp9


GET {{base}}/web-tracuu/cntt_tskt/ds_tinh HTTP/1.1
Content-Type: {{contentType}}
Token-id: {{TokenID}}
Mac-address: WEB
App-secret: {{AppSecret}}
Authorization: {{BearerToken}}

    #   "hdkh_id": 5328293,
    #   "ma_gd": "HPG-DA/00737886",
    #   "ma_tb": "hpgmytv848758",
    #   "ten_dvvt": "Băng rộng cố định",
    #   "loaihinh_tb": "MyTV",
    #   "ma_goi": "KPLUS_ADD_ON",
    #   "ten_goi": "K+ Add-on",
    #   "chunhom": 0,
    #   "nhomtb_id": 2379417,
    #   "thang_huong": 0,
    #   "ten_tb": "Nguyễn Thị Lý",
    #   "diachi_ld": "xóm 9, Thôn Bạch Xa Trại, Xã Nam Hưng, Huyện Tiên Lãng, Hải Phòng",
    #   "nhanvien_lhd": "admin - Quản trị hệ thống",
    #   "tocdo": "Nâng cao Mới",
    #   "nhanvien": "admin - Quản trị hệ thống",
    #   "nhanvien_id": 452,
    #   "ngay_yc": "03/04/2021",
    #   "cbcnv_neo": "admin - Quản trị hệ thống",
    #   "ctv_vnp_id": 452
POST  {{base}}/web-quantri/gantbgoictv/lay_ds_hdtb_goi HTTP/1.1
Content-Type: {{contentType}}
Token-id: {{TokenID}}
Mac-address: WEB
App-secret: {{AppSecret}}
Authorization: {{BearerToken}}

{
	"vma_tb": 0,
	"vma_gd": 0,
	"vdenngay": null,
	"vtungay": null,
	"nhanvien_id": 452
}


#"nhanvien_id": 452

POST  {{base}}/web-quantri/gantbgoictv/lay_ds_hdtb_goi HTTP/1.1
Content-Type: {{contentType}}
Token-id: {{TokenID}}
Mac-address: WEB
App-secret: {{AppSecret}}
Authorization: {{BearerToken}}

{
	"vma_tb": 0,
	"vma_gd": 0,
	"vdenngay": "01/02/2021",
	"vtungay": "08/09/2021",
	"nhanvien_id": 452
}

# {
#       "donvi_id": 0,
#       "ten_dv": "Viễn thông Hải Phòng - "
#     }
POST  {{base}}/web-quantri/gantbgoictv/lay_ds_donvi_ctv HTTP/1.1
Content-Type: {{contentType}}
Token-id: {{TokenID}}
Mac-address: WEB
App-secret: {{AppSecret}}
Authorization: {{BearerToken}}

{

}

# {
#       "loainv_id": 903,
#       "ten": "1.CTV Giao dịch"
#     },
POST  {{base}}/web-quantri/gantbgoictv/sp_lay_ds_loai_nv HTTP/1.1
Content-Type: {{contentType}}
Token-id: {{TokenID}}
Mac-address: WEB
App-secret: {{AppSecret}}
Authorization: {{BearerToken}}

{
    "p_nhomlnv_id":6
}

    # {
    #   "nhanvien_id": 452,
    #   "ma_nv": "admin",
    #   "ten_nv": "Quản trị hệ thống",
    #   "diachi_nv": "Hải Phòng",
    #   "so_dt": null,
    #   "ten_ht": "admin - Quản trị hệ thống"
    # },
POST  {{base}}/web-quantri/gantbgoictv/sp_lay_ds_nhanvien_ctv HTTP/1.1
Content-Type: {{contentType}}
Token-id: {{TokenID}}
Mac-address: WEB
App-secret: {{AppSecret}}
Authorization: {{BearerToken}}

{
    "p_loainv_id": 24,
    "p_donvi_id": 2
}

POST  {{base}}/web-quantri/gantbgoictv/sp_lay_ds_nhanvien_ctv HTTP/1.1
Content-Type: {{contentType}}
Token-id: {{TokenID}}
Mac-address: WEB
App-secret: {{AppSecret}}
Authorization: {{BearerToken}}

{
    "p_loainv_id": -1,
    "p_donvi_id": 1
}

Với nhân viên id 18420
{
      "nhanvien_id": 18420,
      "ma_nv": "CTV026729",
      "ten_nv": "Đỗ Thị Liên",
      "diachi_nv": "Phòng BHKV2",
      "so_dt": "0915290620",
      "ten_ht": "CTV026729 - Đỗ Thị Liên"
}
Chạy api cập nhật dưới thành công

POST  {{base}}/web-quantri/gantbgoictv/fn_capnhat_thuebao_ctv HTTP/1.1
Content-Type: {{contentType}}
Token-id: {{TokenID}}
Mac-address: WEB
App-secret: {{AppSecret}}
Authorization: {{BearerToken}}

{
    "p_nhanvien_id": 18420,
    "p_nhomtb_id": 1933645,
    "p_ctv_vnp_id": 18420,
    "p_hdkh_id": 3311902,
    "p_ngay_yc": "25/11/2021"
}

#"hdkh_id": 3311902/Nhân viên id = 452 thuộc tài khoản đăng nhập user: admin
Lấy danh sách sau khi cập nhật

POST  {{base}}/web-quantri/gantbgoictv/lay_ds_hdtb_goi HTTP/1.1
Content-Type: {{contentType}}
Token-id: {{TokenID}}
Mac-address: WEB
App-secret: {{AppSecret}}
Authorization: {{BearerToken}}

{  "vma_tb": "0",  "vma_gd": "0",  "vdenngay": null,  "vtungay": null, "nhanvien_id": 452}

KQ: Row cập nhật ds trả ra không thay đổi nhanvien_id, ctv_vnp_id
    {
      "hdkh_id": 3311902,
      "ma_gd": "HPG-DA/00535991",
      "ma_tb": "hpgmytv530120",
      "ten_dvvt": "Băng rộng cố định",
      "loaihinh_tb": "MyTV",
      "ma_goi": "KPLUS_ADD_ON",
      "ten_goi": "K+ Add-on",
      "chunhom": 0,
      "nhomtb_id": 1933645,
      "thang_huong": 0,
      "ten_tb": "Trần Văn Tuân",
      "diachi_ld": "Xóm Cây Đa, Xã An Lư, Huyện Thủy Nguyên, Hải Phòng",
      "nhanvien_lhd": "IT00122 - Quản trị hệ thống",
      "tocdo": "Nâng cao",
      "nhanvien": "IT00122 - Quản trị hệ thống",
      "nhanvien_id": 452,
      "ngay_yc": "25/11/2021",
      "cbcnv_neo": "IT00122 - Quản trị hệ thống",
      "ctv_vnp_id": 452,
      "muccuoc": null
    },