export default {
  danhmuc_loai_hd: (axios, data) => axios.get(`/web-thicong/danhmuc/loai_hd`, data),
  danhmuc_dichvu: (axios, data) => axios.get(`/web-thicong/danhmuc/dichvu`, data),
  danhmuc_nhanvien: (axios, data) => axios.get(`/web-thicong/danhmuc/dsNguoiGiaoViec?loaiNVId=24`, data),
  danhmuc_nguoigiaoviec: (axios, data) => axios.get(`/web-thicong/danhmuc/dsNguoiGiaoViec?loaiNVId=24`, data),
  danhmuc_kieu_ld: (axios, data) => axios.get(`/web-ccdv/khaibaotsl/sp_lay_ds_kieuld_theo_loaihd_sudung/37`, data),
  danhmuc_loai_cap: (axios, data) => axios.get(`/web-quantri/danhmuc-chung/CSS_LOAI_CAP`, data),
  lay_ds_phieu_thuhoi_dungthu: (axios, data) => axios.post(`/web-thicong/host/lay_ds_phieu_thuhoi_dungthu`, data),
  lay_ds_phieu_giao_thuhoi_tbi: (axios, data) => axios.post(`/web-thicong/host/lay_ds_phieu_giao_thuhoi_tbi`, data),
  lay_ds_phieu_giao_td_khi_dc: (axios, data) => axios.post(`/web-thicong/host/lay_ds_phieu_giao_td_khi_dc`, data),
  lay_dsnv_theo_phieu: (axios, current_phieu_id) => axios.get(`/web-thicong/host/dsNhanVienTHTheoPhieu?phieuId=${current_phieu_id}&kieu=1`),
  get_ds_thietbi_by_hdtb_id: (axios, hdtb_id) => axios.get(`web-thicong/host/dsThietBiTheoHD?hdtbId=${hdtb_id}`),
  capNhatPhieuThuHoiCong: (axios, data) => axios.post(`/web-thicong/host/capNhatPhieuThuHoiCong`, data),
  capnhat_phieu_thuhoi: (axios, data) => axios.post(`/web-thicong/khoiphuccong/capnhat_phieu_thuhoi`, data),
  lay_kqxl_theo_hdtb_id: (axios, hdtbId) => axios.get(`/web-thicong/host/lay_kqxl_theo_hdtb_id?hdtbId=${hdtbId}`),
  lay_tt_ne_theo_id: (axios, neIdCu) => axios.get(`/web-thicong/host/lay_tt_ne_theo_id?neIdCu=${neIdCu}`),
  fnMapId: (axios, data) => axios.post('/web-hopdong/goi-da-dichvu/fn_map_id', data),
  lay_thongtin_host: (axios, hdtbId, kieu) => axios.get(`/web-thicong/host/lay_thongtin_host?hdtbId=${hdtbId}&kieu=${kieu}`),
  lay_kieuyc_theo_hdtb_id: (axios, hdtbId) => axios.get(`/web-thicong/host/lay_kieuyc_theo_hdtb_id?hdtbId=${hdtbId}`),
  capnhat_ndth_theo_phieu_id: (axios, data) => axios.post(`/web-thicong/host/capnhat_ndth_theo_phieu_id`, data),
  capnhat_giaophieunv_isdn: (axios, data) => axios.post(`/web-thicong/host/capnhat_giaophieunv_isdn`, data),
  sTB_PROM_Back: (axios, data) => axios.post(`/tichhop/vasc/sTB_PROM_Back`, data),
  kiemtra_stb_tfof: (axios, data) => axios.post(`/web-thicong/host/kiemtra_stb_tfof`, data),
  sync_stb: (axios, vhdtb_id) => axios.post(`/web-thicong/host/capnhat_syncstb_theo_hdtbid`, {vhdtb_id}),
}
