import type { Config } from 'tailwindcss';
import colors from './src/theme/colors.config';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    screens: {
      xs: '520px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
    },
    extend: {
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      colors,
      fontSize: {
        'caption-3': '10px',
        'caption-2': '11px',
        'caption-1': '12px',
        'label-2': '13px',
        'label-1': '14px',
        'body-2': '15px',
        'body-1': '16px',
        'headline-2': '17px',
        'headline-1': '18px',
        'heading-2': '20px',
        'heading-1': '22px',
        'title-3': '24px',
        'title-2': '28px',
        'title-1': '36px',
        'display-2': '40px',
        'display-1': '56px',
      },
      fontWeight: {
        normal: '400',
        semibold: '600',
        bold: '700',
      },
      lineHeight: {
        'caption-3': '1.479',
        'caption-2': '1.273',
        'caption-1': '1.334',
        'label-2': '1.385',
        'label-1-reading': '1.571',
        'label-1-normal': '1.429',
        'body-2-reading': '1.6',
        'body-2-normal': '1.467',
        'body-1-reading': '1.625',
        'body-1-normal': '1.5',
        'headline-2': '1.412',
        'headline-1': '1.445',
        'heading-2': '1.4',
        'heading-1': '1.364',
        'title-3': '1.334',
        'title-2': '1.358',
        'title-1': '1.334',
        'display-2': '1.3',
        'display-1': '1.286',
      },
      letterSpacing: {
        'caption-3': '0.0145em',
        'caption-2': '0.0311em',
        'caption-1': '0.0252em',
        'label-2': '0.0194em',
        'label-1-reading': '0.0145em',
        'label-1-normal': '0.0145em',
        'body-2-reading': '0.0096em',
        'body-2-normal': '0.0096em',
        'body-1-reading': '0.0057em',
        'body-1-normal': '0.0057em',
        'headline-2': '0em',
        'headline-1': '-0.002em',
        'heading-2': '-0.012em',
        'heading-1': '-0.0194em',
        'title-3': '-0.023em',
        'title-2': '-0.0236em',
        'title-1': '-0.027em',
        'display-2': '-0.0282em',
        'display-1': '-0.0319em',
      },
    },
    fontFamily: {
      eastSeaDokdo: ['var(--font-eastSeaDokdo)'],
    },
  },
  plugins: [
    ({ addUtilities, theme }: { addUtilities: any; theme: any }) => {
      addUtilities({
        '.display-1': {
          fontSize: theme('fontSize.display-1') + ' !important',
          fontWeight: theme('fontWeight.bold'),
          lineHeight: theme('lineHeight.display-1') + ' !important',
          letterSpacing: theme('letterSpacing.display-1'),
        },
        '.display-2': {
          fontSize: theme('fontSize.display-2') + ' !important',
          fontWeight: theme('fontWeight.bold'),
          lineHeight: theme('lineHeight.display-2') + ' !important',
          letterSpacing: theme('letterSpacing.display-2'),
        },
        '.title-1': {
          fontSize: theme('fontSize.title-1') + ' !important',
          fontWeight: theme('fontWeight.bold'),
          lineHeight: theme('lineHeight.title-1') + ' !important',
          letterSpacing: theme('letterSpacing.title-1'),
        },
        '.title-2': {
          fontSize: theme('fontSize.title-2') + ' !important',
          fontWeight: theme('fontWeight.bold'),
          lineHeight: theme('lineHeight.title-2') + ' !important',
          letterSpacing: theme('letterSpacing.title-2'),
        },
        '.title-3': {
          fontSize: theme('fontSize.title-3') + ' !important',
          fontWeight: theme('fontWeight.bold'),
          lineHeight: theme('lineHeight.title-3') + ' !important',
          letterSpacing: theme('letterSpacing.title-3'),
        },
        '.heading-1': {
          fontSize: theme('fontSize.heading-1') + ' !important',
          fontWeight: theme('fontWeight.semibold'),
          lineHeight: theme('lineHeight.heading-1') + ' !important',
          letterSpacing: theme('letterSpacing.heading-1'),
        },
        '.heading-2': {
          fontSize: theme('fontSize.heading-2') + ' !important',
          fontWeight: theme('fontWeight.semibold'),
          lineHeight: theme('lineHeight.heading-2') + ' !important',
          letterSpacing: theme('letterSpacing.heading-2'),
        },
        '.headline-1': {
          fontSize: theme('fontSize.headline-1') + ' !important',
          fontWeight: theme('fontWeight.semibold'),
          lineHeight: theme('lineHeight.headline-1') + ' !important',
          letterSpacing: theme('letterSpacing.headline-1'),
        },
        '.headline-2': {
          fontSize: theme('fontSize.headline-2') + ' !important',
          fontWeight: theme('fontWeight.semibold'),
          lineHeight: theme('lineHeight.headline-2') + ' !important',
          letterSpacing: theme('letterSpacing.headline-2'),
        },
        '.body-1-normal': {
          fontSize: theme('fontSize.body-1') + ' !important',
          fontWeight: theme('fontWeight.normal'),
          lineHeight: theme('lineHeight.body-1-normal') + ' !important',
          letterSpacing: theme('letterSpacing.body-1-normal'),
        },
        '.body-1-reading': {
          fontSize: theme('fontSize.body-1') + ' !important',
          fontWeight: theme('fontWeight.normal'),
          lineHeight: theme('lineHeight.body-1-reading') + ' !important',
          letterSpacing: theme('letterSpacing.body-1-reading'),
        },
        '.body-2-normal': {
          fontSize: theme('fontSize.body-2') + ' !important',
          fontWeight: theme('fontWeight.normal'),
          lineHeight: theme('lineHeight.body-2-normal') + ' !important',
          letterSpacing: theme('letterSpacing.body-2-normal'),
        },
        '.body-2-reading': {
          fontSize: theme('fontSize.body-2') + ' !important',
          fontWeight: theme('fontWeight.normal'),
          lineHeight: theme('lineHeight.body-2-reading') + ' !important',
          letterSpacing: theme('letterSpacing.body-2-reading'),
        },
        '.label-1-normal': {
          fontSize: theme('fontSize.label-1') + ' !important',
          fontWeight: theme('fontWeight.normal'),
          lineHeight: theme('lineHeight.label-1-normal') + ' !important',
          letterSpacing: theme('letterSpacing.label-1-normal'),
        },
        '.label-1-reading': {
          fontSize: theme('fontSize.label-1') + ' !important',
          fontWeight: theme('fontWeight.normal'),
          lineHeight: theme('lineHeight.label-1-reading') + ' !important',
          letterSpacing: theme('letterSpacing.label-1-reading'),
        },
        '.label-2': {
          fontSize: theme('fontSize.label-2') + ' !important',
          fontWeight: theme('fontWeight.normal'),
          lineHeight: theme('lineHeight.label-2') + ' !important',
          letterSpacing: theme('letterSpacing.label-2'),
        },
        '.caption-1': {
          fontSize: theme('fontSize.caption-1') + ' !important',
          fontWeight: theme('fontWeight.normal'),
          lineHeight: theme('lineHeight.caption-1') + ' !important',
          letterSpacing: theme('letterSpacing.caption-1'),
        },
        '.caption-2': {
          fontSize: theme('fontSize.caption-2') + ' !important',
          fontWeight: theme('fontWeight.normal'),
          lineHeight: theme('lineHeight.caption-2') + ' !important',
          letterSpacing: theme('letterSpacing.caption-2'),
        },
        '.caption-3': {
          fontSize: theme('fontSize.caption-3') + ' !important',
          fontWeight: theme('fontWeight.normal'),
          lineHeight: theme('lineHeight.caption-3') + ' !important',
          letterSpacing: theme('letterSpacing.caption-3'),
        },

        '.pack-border-bottom-neutral-30': {
          border: 0,
          borderBottom: '1px solid ' + theme('colors.neutral.30'),
        },
        '.pack-border-right-neutral-30': {
          border: 0,
          borderRight: '1px solid ' + theme('colors.neutral.0'),
        },
        '.pack-border-gray-400': {
          border: '1px solid ' + theme('colors.neutral.40'),
        },
      });
    },
  ],
};
export default config;
