export default {
  getDepartments: (axios, params) => axios.get('web-quantri/danhmuc-chung/ADMIN_DONVI_V2', { params }),
  getDsDonVi: (axios, params) => axios.get('web-quantri/danhmuc-chung/ADMIN_DONVI_V3', { params }),
  getStores: (axios, params) => axios.get('web-quantri/kho/sp_lay_ds_kho_dvi', { params }),
  getStoresBelongAccount: (axios, data) => axios.post('web-quantri/kho/sp_lay_ds_kho_dvi_theo_nv', data),
  getStoreTypes: (axios, params) => axios.get('/web-quantri/danhmuc-chung/QLVT_LOAI_KHO', { params }),
  getProvinces: (axios, params) => axios.get('web-quantri/danhmuc-chung/CSS_TINH', { params }),
  //getEmployees: (axios, params) => axios.get('web-quantri/danhmuc-chung/ADMIN_NHANVIEN', { params }),
  getEmployees: (axios, params) => axios.get('web-hopdong/hopdong/sp_lay_ds_nv_thukho', { params }),
  getEmployeesNotAdded: (axios, data) => axios.post('web-quantri/kho/sp_lay_ds_nv_kho', data),
  getEmployeesAdded: (axios, data) => axios.post('web-quantri/quanlykhobienlai/sp_ds_kho_nv_da_gan', data),
  getPurposesNotAdded: (axios, data) => axios.post('web-quantri/kho/sp_getmucdich_kho', data),
  getPurposesAdded: (axios, data) => axios.post('web-quantri/kho/sp_getmucdich_kho_dagan', data),
  getDepartmentsNotAdded: (axios, data) => axios.post('web-quantri/kho/sp_getdonvi_kho', data),
  getDepartmentsAdded: (axios, data) => axios.post('web-quantri/kho/sp_getdonvi_kho_dagan', data),
  getCSHT: (axios, data) => axios.post('tichhop/qlts/asset_get_station_by_code', data),
  getCSHTByStore: (axios, data) => axios.post('web-quantri/kho/sp_chitiet_kho', data),

  insertEmployeesToStore: (axios, data) => axios.post('web-quantri/kho/sp_insert_nv_kho', data),
  deleteEmployeesFromStore: (axios, data) => axios.post('web-quantri/kho/sp_delete_nv_kho', data),
  insertDepartmentsToStore: (axios, data) => axios.post('web-quantri/kho/sp_insert_dv_kho', data),
  deleteDepartmentsFromStore: (axios, data) => axios.post('web-quantri/kho/sp_delete_dv_kho', data),
  insertPurposesToStore: (axios, data) => axios.post('web-quantri/kho/sp_insert_md_kho', data),
  deletePurposesFromStore: (axios, data) => axios.post('web-quantri/kho/sp_delete_md_kho', data),

  checkStoreCode: (axios, data) => axios.post('web-quantri/kho/fn_kiemtra_makho_tontai', data),
  checkStoreBeforeAddNewRecord: (axios, data) => axios.post('web-quantri/kho/kiemtra_tt_kho_v2', data),
  checkDepartment: (axios, data) => axios.post('web-quantri/kho/fn_kiemtra_donvi_quanly', data),
  checkAndInsertStore: (axios, data) => axios.post('web-quantri/kho/kiemtra_insert_kho', data),
  // insertStore: (axios, data) => axios.post('web-quantri/kho/sp_insert_kho', data),
  checkInvoice: (axios, data) => axios.post('web-quantri/kho/fn_kiemtra_chungtu_tontai', data),
  checkMaterialAdvance: (axios, data) => axios.post('web-quantri/kho/fn_kiemtra_vattu_tamung_theo_kho', data),
  updateModifiedStore: (axios, data) => axios.post('web-quantri/kho/fn_kiemtra_capnhat_kho', data),
  // updateModifiedStore: (axios, data) => axios.post('web-quantri/kho/sp_update_kho', data),
  checkBeforeDeleteStore: (axios, data) => axios.post('web-quantri/kho/kiemtra_xoakho', data),
  deleteSelectedStore: (axios, data) => axios.post('web-quantri/quanlykhobienlai/sp_xoa_kho_bienlai', data),
  insertStoresFromExcelFile: (axios, data) => axios.post('web-hopdong/hopdong/docfile_ds_kho', data)
}
