const DichVuVienThong={
    TATCA:-1,
    CO_DINH:1,
    DI_DONG:2,
    ADSL:4,
    DD_TRATRUOC:5,
    EMAIL:6,
    METRONET:7,
    MEGAWAN:8,
    TSL:9,
    GPHONE:10,
    IMS:11,
    MEGA_EYES:12,
    HOINGHI_TRUYENHINH:13,
    ANTOAN_BAOMAT_TT:14,
    DICHVU_CNTT:15,
    TRUNGTAM_DULIEU:16,
    HATANG_VIENTHONG:19,
    IMS_DOITAC:21,
    BRCD_DOITAC:22,
    MGW_DOITAC:23,
    TSL_DOITAC:24
}
const LoaiHopDong={
    KHAOSATDATMOI: 33,
    KHAOSATCDLH: 34,
    KHAOSATDC: 35,
    TIEPNHANHD: 36,
    TUVAN_DV: 38,

    TIEPNHAN_DATMOI:26
}

const LoaiNV={
    NHANVIEN_KYTHUAT:51,
    NHANVIEN_KINHDOANH:52,
    NHANVIEN_AM:104
}

const KieuLapDat={
    KHAOSATCDLH: 618,
    THAYDOI_TOCDO_ADSL : 24,
    THAYDOI_MUCCUOC_ADSL : 76,
    THAYDOI_TOCDO_MUCCUOC_ADSL : 77,

    THAYDOI_TOCDO_ADSL_TK : 13080,
    THAYDOI_MUCCUOC_ADSL_TK : 13081,
    THAYDOI_TOCDO_MUCCUOC_ADSL_TK : 13082,

    THAYDOI_TOCDOTHUC_ADSL: 655,
    THAYDOI_CONGNGHE_TOCDO_AON_GPON: 885,
    THAYDOI_CONGNGHE_TOCDO_GPON_AON: 886,

    THAYDOI_CONGNGHE_AON_GPON: 934,
    THAYDOI_CONGNGHE_GPON_AON :935,
}
const TrangThaiHD={
    MOI : 1,
    THANH_TOAN : 2,
    DIEUHANH_THI_CONG : 3,
    DANG_THI_CONG : 4,
    DA_THI_CONG_XONG : 5,
    HOAN_THANH : 6,
    THOAITRA : 7,
    DA_LAY_DU_LIEU : 8,
    KHAIBAO_TONGDAI : 9,
    DANGCHO_HOANCONG : 10,
    DOISOAT_HOSO : 11,
    TTVT_XACMINH_NO : 14,
    THOAITRA_TMP : 17,
    TTVT_HOANCONG_DICHVU : 23,
    HTHS_BANCHEO : 26,
    NVKD_XACMINH : 27,
}
const NHOM_QT={
    DIEUHANH_THICONG : 1,
    BAOHONG : 2,
    GIAIQUYET_KN : 3,
    BAOHANH_TBI : 4,
    SLSC_CNTT : 5,
    LUANCHUYEN_HOSO : 6,
    QUANLY_VATTU : 7,
    CAITAO_BAODUONG : 8,
}
const DoiTuong={
    TU_NHAN : 1,
    Y_TE : 18,
    KHDN : 52,//tạm thời chuẩn sau
    THUEBAO_DUNGTHU : 190,
    //SRCR-46 VNP - anh Luyện Văn Hòa Ban KHCN
    CANBO_DIABAN : 374,
}
export {
    DichVuVienThong,
    LoaiHopDong,
    LoaiNV,
    KieuLapDat,
    TrangThaiHD,
    NHOM_QT,
    DoiTuong
}