/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package vn.vnptit.sapi.oneapp.resources.gnms;

import vn.vnptit.sapi.oneapp.models.gnms.BaseResponse;
import java.math.BigDecimal;
import vn.vnptit.sapi.oneapp.models.gnms.FileBackup;
import vn.vnptit.sapi.oneapp.models.gnms.FileBackupListResponse;
import java.util.List;
import vn.vnptit.sapi.oneapp.models.gnms.ListReportWifiResponse;
import vn.vnptit.sapi.oneapp.models.gnms.TemplateInf;
import vn.vnptit.sapi.oneapp.models.gnms.TemplateInfResponse;
import vn.vnptit.sapi.oneapp.models.gnms.TemplateZerotouchListResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import springfox.documentation.annotations.ApiIgnore;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Api(value = "Backup", description = "the Backup API")
public interface BackupApi {

    default BackupApiDelegate getDelegate() {
        return new BackupApiDelegate() {};
    }

    /**
     * GET /backup/backup
     * Backup cấu hình thiết bị
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @param backupName Tên file backup (required)
     * @return Đường dẫn file đã được backup (status code 200)
     */
    @ApiOperation(value = "", nickname = "backup", notes = "Backup cấu hình thiết bị", response = BaseResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "backup", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Đường dẫn file đã được backup", response = BaseResponse.class) })
    @GetMapping(
        value = "/backup/backup",
        produces = { "application/json" }
    )
    default ResponseEntity<BaseResponse> backup(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical,@NotNull @ApiParam(value = "Tên file backup", required = true) @Valid @RequestParam(value = "backupName", required = true) String backupName) {
        return getDelegate().backup(optical, backupName);
    }


    /**
     * GET /backup/delAll
     * Xóa toàn bộ file backup của một thiết bị
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @return Kết quả trả về là một Json object dạng List, mỗi object là log cho từng thiết bị (status code 200)
     */
    @ApiOperation(value = "", nickname = "backupDelAll", notes = "Xóa toàn bộ file backup của một thiết bị", response = BaseResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "backup", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về là một Json object dạng List, mỗi object là log cho từng thiết bị", response = BaseResponse.class) })
    @GetMapping(
        value = "/backup/delAll",
        produces = { "application/json" }
    )
    default ResponseEntity<BaseResponse> backupDelAll(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical) {
        return getDelegate().backupDelAll(optical);
    }


    /**
     * GET /backup/getJsonReportWifi
     * Lấy Report Wifi
     *
     * @param areaId Area Id. Nếu rỗng kết quả trả về sẽ là tất cả Area có trên hệ thống (required)
     * @param listSerialNumber Danh sách serial number cách nhau bởi dấu phẩy “,”. Nếu rỗng kết quả trả về sẽ là tất cả Searial Number có trên hệ thống (required)
     * @param start Vị trí bản ghi đầu tiên muốn lấy. Đối với lần lấy đầu tiên start &#x3D; 0. Với lần lấy tiếp theo check trường start trong kết quả response. Nếu start &#x3D; -1 có nghĩa là người dùng đã lấy được tất cả các bản ghi cần lấy &#x3D;&gt; Hoàn thành. Với start khác -1, lấy giá trị start trong response của request trước để làm input của request tiếp theo. Đối với lần lấy thứ n. Kết quả trả về của start sẽ là vị trí đầu tiên của lần lấy thứ n+1. (required)
     * @param limit Số lượng bản ghi muốn lấy (mặc định là 1000, giá trị cho phép là 0 – 2000). (required)
     * @param startDate Thời gian bắt đầu của báo cáo. (required)
     * @param endDate Thời gian kết thúc. Nếu để rỗng, hệ thống sẽ lấy mặc định là thời gian hiện tại. (optional)
     * @return Kết quả trả về là object Json chứa danh sách thiết bị trong báo cáo (status code 200)
     */
    @ApiOperation(value = "", nickname = "backupGetJsonReportWifi", notes = "Lấy Report Wifi", response = ListReportWifiResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "backup", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về là object Json chứa danh sách thiết bị trong báo cáo", response = ListReportWifiResponse.class) })
    @GetMapping(
        value = "/backup/getJsonReportWifi",
        produces = { "application/json" }
    )
    default ResponseEntity<ListReportWifiResponse> backupGetJsonReportWifi(@NotNull @ApiParam(value = "Area Id. Nếu rỗng kết quả trả về sẽ là tất cả Area có trên hệ thống", required = true) @Valid @RequestParam(value = "areaId", required = true) BigDecimal areaId,@NotNull @ApiParam(value = "Danh sách serial number cách nhau bởi dấu phẩy “,”. Nếu rỗng kết quả trả về sẽ là tất cả Searial Number có trên hệ thống", required = true) @Valid @RequestParam(value = "listSerialNumber", required = true) String listSerialNumber,@NotNull @ApiParam(value = "Vị trí bản ghi đầu tiên muốn lấy. Đối với lần lấy đầu tiên start = 0. Với lần lấy tiếp theo check trường start trong kết quả response. Nếu start = -1 có nghĩa là người dùng đã lấy được tất cả các bản ghi cần lấy => Hoàn thành. Với start khác -1, lấy giá trị start trong response của request trước để làm input của request tiếp theo. Đối với lần lấy thứ n. Kết quả trả về của start sẽ là vị trí đầu tiên của lần lấy thứ n+1.", required = true) @Valid @RequestParam(value = "Start", required = true) BigDecimal start,@NotNull @ApiParam(value = "Số lượng bản ghi muốn lấy (mặc định là 1000, giá trị cho phép là 0 – 2000).", required = true) @Valid @RequestParam(value = "Limit", required = true) BigDecimal limit,@NotNull @ApiParam(value = "Thời gian bắt đầu của báo cáo.", required = true) @Valid @RequestParam(value = "startDate", required = true) String startDate,@ApiParam(value = "Thời gian kết thúc. Nếu để rỗng, hệ thống sẽ lấy mặc định là thời gian hiện tại.") @Valid @RequestParam(value = "endDate", required = false) String endDate) {
        return getDelegate().backupGetJsonReportWifi(areaId, listSerialNumber, start, limit, startDate, endDate);
    }


    /**
     * GET /backup/getTemplate
     * Lấy chuỗi cấu hình cho từng template
     *
     * @param templateCode Template code sử dụng (optional)
     * @return Kết quả trả về là object Json chứa các tham số cần để cấu hình cho template, chú ý tham số serial dùng để lưu trường Serial của thiết bị (status code 200)
     */
    @ApiOperation(value = "", nickname = "backupGetTemplate", notes = "Lấy chuỗi cấu hình cho từng template", response = TemplateInfResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "backup", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về là object Json chứa các tham số cần để cấu hình cho template, chú ý tham số serial dùng để lưu trường Serial của thiết bị", response = TemplateInfResponse.class) })
    @GetMapping(
        value = "/backup/getTemplate",
        produces = { "application/json" }
    )
    default ResponseEntity<TemplateInfResponse> backupGetTemplate(@ApiParam(value = "Template code sử dụng") @Valid @RequestParam(value = "templateCode", required = false) String templateCode) {
        return getDelegate().backupGetTemplate(templateCode);
    }


    /**
     * GET /backup/getTemplateImport
     * Lấy file import cấu hình ZeroTouch
     *
     * @param templateCode Template Code cần để lấy import file (optional)
     * @return Kết quả trả về thành công file excel (.xls) để người dùng cấu hình dịch vụ cho thiết bị. (status code 200)
     */
    @ApiOperation(value = "", nickname = "backupGetTemplateImport", notes = "Lấy file import cấu hình ZeroTouch", response = org.springframework.core.io.Resource.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "backup", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về thành công file excel (.xls) để người dùng cấu hình dịch vụ cho thiết bị.", response = org.springframework.core.io.Resource.class) })
    @GetMapping(
        value = "/backup/getTemplateImport",
        produces = { "application/json" }
    )
    default ResponseEntity<org.springframework.core.io.Resource> backupGetTemplateImport(@ApiParam(value = "Template Code cần để lấy import file") @Valid @RequestParam(value = "templateCode", required = false) String templateCode) {
        return getDelegate().backupGetTemplateImport(templateCode);
    }


    /**
     * POST /backup/importZerotouch
     * Cấu hình zero touch cho 1 thiết bị
     *
     * @param templateCode Template code sử dụng (required)
     * @param objectConfig Thông tin cấu hình zero touch (required)
     * @return Kết quả trả về thành công là url file backup đã tạo cho thiết bị (status code 200)
     */
    @ApiOperation(value = "", nickname = "backupImportZerotouch", notes = "Cấu hình zero touch cho 1 thiết bị", response = BaseResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "backup", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về thành công là url file backup đã tạo cho thiết bị", response = BaseResponse.class) })
    @PostMapping(
        value = "/backup/importZerotouch",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<BaseResponse> backupImportZerotouch(@NotNull @ApiParam(value = "Template code sử dụng", required = true) @Valid @RequestParam(value = "templateCode", required = true) String templateCode,@ApiParam(value = "Thông tin cấu hình zero touch" ,required=true )  @Valid @RequestBody TemplateInf objectConfig) {
        return getDelegate().backupImportZerotouch(templateCode, objectConfig);
    }


    /**
     * GET /backup/searchTemplate
     * Tìm kiếm template ZeroTouch
     *
     * @param templateName Lọc kết quả template theo template Name (optional)
     * @param modelName Lọc kết quả template theo model name dòng thiết bị (optional)
     * @param templateCode Lọc kết quả template theo template Code (optional)
     * @return Kết quả trả về thành công là chuỗi json chứa list các template ZeroTouch tìm kiếm thành công (status code 200)
     */
    @ApiOperation(value = "", nickname = "backupSearchTemplate", notes = "Tìm kiếm template ZeroTouch", response = TemplateZerotouchListResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "backup", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về thành công là chuỗi json chứa list các template ZeroTouch tìm kiếm thành công", response = TemplateZerotouchListResponse.class) })
    @GetMapping(
        value = "/backup/searchTemplate",
        produces = { "application/json" }
    )
    default ResponseEntity<TemplateZerotouchListResponse> backupSearchTemplate(@ApiParam(value = "Lọc kết quả template theo template Name") @Valid @RequestParam(value = "templateName", required = false) String templateName,@ApiParam(value = "Lọc kết quả template theo model name dòng thiết bị") @Valid @RequestParam(value = "modelName", required = false) String modelName,@ApiParam(value = "Lọc kết quả template theo template Code") @Valid @RequestParam(value = "templateCode", required = false) String templateCode) {
        return getDelegate().backupSearchTemplate(templateName, modelName, templateCode);
    }


    /**
     * POST /backup/templateUpload
     * Import cấu hình ZeroTouch cho nhiều thiết bị
     *
     * @param fileExcel File excel chứa cấu hình zerotouch của nhiều thiết bị (optional)
     * @return Kết quả trả về thành công là file excel (.xls) có thêm cột result chứa url file zerotouch (là file backup) vừa được tạo trên hệ thống (status code 200)
     */
    @ApiOperation(value = "", nickname = "backupTemplateUpload", notes = "Import cấu hình ZeroTouch cho nhiều thiết bị", response = org.springframework.core.io.Resource.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "backup", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về thành công là file excel (.xls) có thêm cột result chứa url file zerotouch (là file backup) vừa được tạo trên hệ thống", response = org.springframework.core.io.Resource.class) })
    @PostMapping(
        value = "/backup/templateUpload",
        produces = { "application/xls" },
        consumes = { "multipart/form-data" }
    )
    default ResponseEntity<org.springframework.core.io.Resource> backupTemplateUpload(@ApiParam(value = "File excel chứa cấu hình zerotouch của nhiều thiết bị") @Valid @RequestPart(value = "fileExcel", required = false) MultipartFile fileExcel) {
        return getDelegate().backupTemplateUpload(fileExcel);
    }


    /**
     * POST /backup/delxml
     * Xóa file backup cấu hình
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @param body Chuỗi JSON định danh các object file backup muốn xóa (required)
     * @return OK (status code 200)
     */
    @ApiOperation(value = "", nickname = "delxml", notes = "Xóa file backup cấu hình", response = BaseResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "backup", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = BaseResponse.class) })
    @PostMapping(
        value = "/backup/delxml",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<BaseResponse> delxml(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical,@ApiParam(value = "Chuỗi JSON định danh các object file backup muốn xóa" ,required=true )  @Valid @RequestBody List<FileBackup> body) {
        return getDelegate().delxml(optical, body);
    }


    /**
     * GET /backup/getListBackup
     * Lấy danh sách file backup của thiết bị
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @return OK (status code 200)
     */
    @ApiOperation(value = "", nickname = "getListBackup", notes = "Lấy danh sách file backup của thiết bị", response = FileBackupListResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "backup", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = FileBackupListResponse.class) })
    @GetMapping(
        value = "/backup/getListBackup",
        produces = { "application/json" }
    )
    default ResponseEntity<FileBackupListResponse> getListBackup(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical) {
        return getDelegate().getListBackup(optical);
    }


    /**
     * POST /backup/restore
     * Khôi phục cấu hình thiết bị
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @param body Chuỗi JSON định danh file backup cần backup (required)
     * @return OK (status code 200)
     */
    @ApiOperation(value = "", nickname = "restore", notes = "Khôi phục cấu hình thiết bị", response = BaseResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "backup", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = BaseResponse.class) })
    @PostMapping(
        value = "/backup/restore",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<BaseResponse> restore(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical,@ApiParam(value = "Chuỗi JSON định danh file backup cần backup" ,required=true )  @Valid @RequestBody FileBackup body) {
        return getDelegate().restore(optical, body);
    }

}
