/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package vn.vnptit.sapi.oneapp.resources.gnms;

import vn.vnptit.sapi.oneapp.models.gnms.BaseResponse;
import vn.vnptit.sapi.oneapp.models.gnms.BatchInput;
import vn.vnptit.sapi.oneapp.models.gnms.BatchLogListResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import springfox.documentation.annotations.ApiIgnore;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Api(value = "Batch", description = "the Batch API")
public interface BatchApi {

    default BatchApiDelegate getDelegate() {
        return new BatchApiDelegate() {};
    }

    /**
     * POST /batch/action
     * reboot/reset/xóa file backup thiết bị hàng loạt
     *
     * @param body Chuỗi JSON định danh file backup cần backup (required)
     * @return url trỏ tới api check kết quả thực hiện (status code 200)
     */
    @ApiOperation(value = "", nickname = "batchAction", notes = "reboot/reset/xóa file backup thiết bị hàng loạt", response = BaseResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "batch", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "url trỏ tới api check kết quả thực hiện", response = BaseResponse.class) })
    @PostMapping(
        value = "/batch/action",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<BaseResponse> batchAction(@ApiParam(value = "Chuỗi JSON định danh file backup cần backup" ,required=true )  @Valid @RequestBody BatchInput body) {
        return getDelegate().batchAction(body);
    }


    /**
     * GET /batch/result
     * Kết quả log batch (reboot, reset, …)
     *
     * @param batchID Batch session ID của lệnh cần tra cứu log (required)
     * @return Kết quả trả về là một Json object dạng List, mỗi object là log cho từng thiết bị (status code 200)
     */
    @ApiOperation(value = "", nickname = "batchResult", notes = "Kết quả log batch (reboot, reset, …)", response = BatchLogListResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "batch", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về là một Json object dạng List, mỗi object là log cho từng thiết bị", response = BatchLogListResponse.class) })
    @GetMapping(
        value = "/batch/result",
        produces = { "application/json" }
    )
    default ResponseEntity<BatchLogListResponse> batchResult(@NotNull @ApiParam(value = "Batch session ID của lệnh cần tra cứu log", required = true) @Valid @RequestParam(value = "batchID", required = true) Integer batchID) {
        return getDelegate().batchResult(batchID);
    }

}
