/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package vn.vnptit.sapi.oneapp.resources.gnms;

import vn.vnptit.sapi.oneapp.models.gnms.AccWebGuiListResponse;
import vn.vnptit.sapi.oneapp.models.gnms.AddInterfaceGroupingRequest;
import vn.vnptit.sapi.oneapp.models.gnms.BaseResponse;
import vn.vnptit.sapi.oneapp.models.gnms.BoundInterfacesListResponse;
import vn.vnptit.sapi.oneapp.models.gnms.ConnectedUserListResponse;
import vn.vnptit.sapi.oneapp.models.gnms.DeleteInterfaceGroupingRequest;
import vn.vnptit.sapi.oneapp.models.gnms.DeviceParamResponse;
import vn.vnptit.sapi.oneapp.models.gnms.DeviceWan;
import vn.vnptit.sapi.oneapp.models.gnms.DeviceWanListResponse;
import vn.vnptit.sapi.oneapp.models.gnms.DeviceWirelessAdv;
import vn.vnptit.sapi.oneapp.models.gnms.DeviceWirelessAdvResponse;
import vn.vnptit.sapi.oneapp.models.gnms.DeviceWlan;
import vn.vnptit.sapi.oneapp.models.gnms.DeviceWlanListResponse;
import vn.vnptit.sapi.oneapp.models.gnms.DiagnosticResponse;
import vn.vnptit.sapi.oneapp.models.gnms.GetVoiceListResponse;
import vn.vnptit.sapi.oneapp.models.gnms.InlineObject;
import vn.vnptit.sapi.oneapp.models.gnms.InterfaceGroupingListResponse;
import java.util.List;
import vn.vnptit.sapi.oneapp.models.gnms.ListAdslDeviceResponse;
import vn.vnptit.sapi.oneapp.models.gnms.OpticalInfoListResponse;
import vn.vnptit.sapi.oneapp.models.gnms.PingResultResponse;
import vn.vnptit.sapi.oneapp.models.gnms.WanLanInterfacesListResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import springfox.documentation.annotations.ApiIgnore;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Api(value = "Device", description = "the Device API")
public interface DeviceApi {

    default DeviceApiDelegate getDelegate() {
        return new DeviceApiDelegate() {};
    }

    /**
     * GET /device/delete
     * Xóa thiết bị
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @return Kết quả trả về là một Json object (status code 200)
     */
    @ApiOperation(value = "", nickname = "delete", notes = "Xóa thiết bị", response = BaseResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về là một Json object", response = BaseResponse.class) })
    @GetMapping(
        value = "/device/delete",
        produces = { "application/json" }
    )
    default ResponseEntity<BaseResponse> delete(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical) {
        return getDelegate().delete(optical);
    }


    /**
     * POST /device/addBridgeWan
     * API cài đặt Wan bridge
     *
     * @param serviceDescription Brigde name (Ví dụ: br_eth0) (required)
     * @param vlanMux8021Priority Vlan 802.1P Priority (required)
     * @param vlanMuxID Vlan ID (required)
     * @param enableWan Enable wan (required)
     * @param optical Số serial của thiết bị (required)
     * @return Kết quả trả về là object Json chứa kết quả (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceAddBridgeWan", notes = "API cài đặt Wan bridge", response = BaseResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về là object Json chứa kết quả", response = BaseResponse.class) })
    @PostMapping(
        value = "/device/addBridgeWan",
        produces = { "application/json" }
    )
    default ResponseEntity<BaseResponse> deviceAddBridgeWan(@NotNull @ApiParam(value = "Brigde name (Ví dụ: br_eth0)", required = true) @Valid @RequestParam(value = "serviceDescription", required = true) String serviceDescription,@NotNull @ApiParam(value = "Vlan 802.1P Priority", required = true) @Valid @RequestParam(value = "vlanMux802_1Priority", required = true) Integer vlanMux8021Priority,@NotNull @ApiParam(value = "Vlan ID", required = true) @Valid @RequestParam(value = "vlanMuxID", required = true) Integer vlanMuxID,@NotNull @ApiParam(value = "Enable wan", required = true) @Valid @RequestParam(value = "enableWan", required = true) Boolean enableWan,@NotNull @ApiParam(value = "Số serial của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical) {
        return getDelegate().deviceAddBridgeWan(serviceDescription, vlanMux8021Priority, vlanMuxID, enableWan, optical);
    }


    /**
     * POST /device/addInterfaceGrouping
     * API add Interface Grouping
     *
     * @param serialNumber Mã Serial number của thiết bị (required)
     * @param body Object InterfaceGrouping (required)
     * @return OK (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceAddInterfaceGrouping", notes = "API add Interface Grouping", response = BaseResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = BaseResponse.class) })
    @PostMapping(
        value = "/device/addInterfaceGrouping",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<BaseResponse> deviceAddInterfaceGrouping(@NotNull @ApiParam(value = "Mã Serial number của thiết bị", required = true) @Valid @RequestParam(value = "serialNumber", required = true) String serialNumber,@ApiParam(value = "Object InterfaceGrouping" ,required=true )  @Valid @RequestBody AddInterfaceGroupingRequest body) {
        return getDelegate().deviceAddInterfaceGrouping(serialNumber, body);
    }


    /**
     * POST /device/addWan
     * API add Wan
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @param body Object WAN (required)
     * @return OK (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceAddWan", notes = "API add Wan", response = BaseResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = BaseResponse.class) })
    @PostMapping(
        value = "/device/addWan",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<BaseResponse> deviceAddWan(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical,@ApiParam(value = "Object WAN" ,required=true )  @Valid @RequestBody DeviceWan body) {
        return getDelegate().deviceAddWan(optical, body);
    }


    /**
     * GET /device/configWebGuiPass
     * Lấy cấu hình account đăng nhập thiết bị
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @param username Username login (required)
     * @param password Password mới (required)
     * @return Kết quả trả về là object Json chứa message thông báo kết quả (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceConfigWebGuiPass", notes = "Lấy cấu hình account đăng nhập thiết bị", response = BaseResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về là object Json chứa message thông báo kết quả", response = BaseResponse.class) })
    @GetMapping(
        value = "/device/configWebGuiPass",
        produces = { "application/json" }
    )
    default ResponseEntity<BaseResponse> deviceConfigWebGuiPass(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical,@NotNull @ApiParam(value = "Username login", required = true) @Valid @RequestParam(value = "username", required = true) String username,@NotNull @ApiParam(value = "Password mới", required = true) @Valid @RequestParam(value = "password", required = true) String password) {
        return getDelegate().deviceConfigWebGuiPass(optical, username, password);
    }


    /**
     * POST /device/delWan
     * API xoá wan trên ONT
     *
     * @param optical Mã OpticalNo của thiết bị (required)
     * @param deviceWan  (optional)
     * @return Kết quả trả về là object Json chứa kết quả (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceDelWan", notes = "API xoá wan trên ONT", response = BaseResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về là object Json chứa kết quả", response = BaseResponse.class) })
    @PostMapping(
        value = "/device/delWan",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<BaseResponse> deviceDelWan(@NotNull @ApiParam(value = "Mã OpticalNo của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical,@ApiParam(value = ""  )  @Valid @RequestBody(required = false) DeviceWan deviceWan) {
        return getDelegate().deviceDelWan(optical, deviceWan);
    }


    /**
     * GET /device/deleteDevice
     * API xoá ONT
     *
     * @param optical Danh sách thiết bị xoá (required)
     * @return Kết quả trả về là object Json chứa kết quả (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceDeleteDevice", notes = "API xoá ONT", response = BaseResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về là object Json chứa kết quả", response = BaseResponse.class) })
    @GetMapping(
        value = "/device/deleteDevice",
        produces = { "application/json" }
    )
    default ResponseEntity<BaseResponse> deviceDeleteDevice(@NotNull @ApiParam(value = "Danh sách thiết bị xoá", required = true) @Valid @RequestParam(value = "optical", required = true) String optical) {
        return getDelegate().deviceDeleteDevice(optical);
    }


    /**
     * POST /device/deleteInterfaceGrouping
     * API delete Interface Grouping
     *
     * @param serialNumber Mã Serial number của thiết bị (required)
     * @param body Object InterfaceGrouping (required)
     * @return OK (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceDeleteInterfaceGrouping", notes = "API delete Interface Grouping", response = BaseResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = BaseResponse.class) })
    @PostMapping(
        value = "/device/deleteInterfaceGrouping",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<BaseResponse> deviceDeleteInterfaceGrouping(@NotNull @ApiParam(value = "Mã Serial number của thiết bị", required = true) @Valid @RequestParam(value = "serialNumber", required = true) String serialNumber,@ApiParam(value = "Object InterfaceGrouping" ,required=true )  @Valid @RequestBody DeleteInterfaceGroupingRequest body) {
        return getDelegate().deviceDeleteInterfaceGrouping(serialNumber, body);
    }


    /**
     * GET /device/diagnostic
     * Đo kiểm kết nối của thiết bị
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @param pingto url hoặc ip của host cần kiểm tra kết nối (required)
     * @param downloadurl url test download file (required)
     * @param uploadurl url upload file test (kích thước 10Mb) (required)
     * @return Kết quả trả về là object Json chứa kết quả ping (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceDiagnostic", notes = "Đo kiểm kết nối của thiết bị", response = DiagnosticResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về là object Json chứa kết quả ping", response = DiagnosticResponse.class) })
    @GetMapping(
        value = "/device/diagnostic",
        produces = { "application/json" }
    )
    default ResponseEntity<DiagnosticResponse> deviceDiagnostic(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical,@NotNull @ApiParam(value = "url hoặc ip của host cần kiểm tra kết nối", required = true) @Valid @RequestParam(value = "pingto", required = true) String pingto,@NotNull @ApiParam(value = "url test download file", required = true) @Valid @RequestParam(value = "downloadurl", required = true) String downloadurl,@NotNull @ApiParam(value = "url upload file test (kích thước 10Mb)", required = true) @Valid @RequestParam(value = "uploadurl", required = true) String uploadurl) {
        return getDelegate().deviceDiagnostic(optical, pingto, downloadurl, uploadurl);
    }


    /**
     * GET /device/fetchConnectedUserInfor
     * API lấy số lượng người dùng trong mạng LAN
     *
     * @param serialNumber Mã OpticalNo của thiết bị(phân biệt hoa thường) (required)
     * @return Kết quả trả về là object Json chứa kết quả (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceFetchConnectedUserInfor", notes = "API lấy số lượng người dùng trong mạng LAN", response = ConnectedUserListResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về là object Json chứa kết quả", response = ConnectedUserListResponse.class) })
    @GetMapping(
        value = "/device/fetchConnectedUserInfor",
        produces = { "application/json" }
    )
    default ResponseEntity<ConnectedUserListResponse> deviceFetchConnectedUserInfor(@NotNull @ApiParam(value = "Mã OpticalNo của thiết bị(phân biệt hoa thường)", required = true) @Valid @RequestParam(value = "serialNumber", required = true) String serialNumber) {
        return getDelegate().deviceFetchConnectedUserInfor(serialNumber);
    }


    /**
     * GET /device/fetchOpticalInfo
     * API lấy thông tin nhiệt độ, công suất thu phát của module quang trên ONT
     *
     * @param serialNumber Mã OpticalNo của thiết bị(phân biệt hoa thường) (required)
     * @return Kết quả trả về là object Json chứa kết quả (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceFetchOpticalInfo", notes = "API lấy thông tin nhiệt độ, công suất thu phát của module quang trên ONT", response = OpticalInfoListResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về là object Json chứa kết quả", response = OpticalInfoListResponse.class) })
    @GetMapping(
        value = "/device/fetchOpticalInfo",
        produces = { "application/json" }
    )
    default ResponseEntity<OpticalInfoListResponse> deviceFetchOpticalInfo(@NotNull @ApiParam(value = "Mã OpticalNo của thiết bị(phân biệt hoa thường)", required = true) @Valid @RequestParam(value = "serialNumber", required = true) String serialNumber) {
        return getDelegate().deviceFetchOpticalInfo(serialNumber);
    }


    /**
     * GET /device/getAccWebGui
     * Lấy thông tin account đăng nhập WebGui của thiết bị
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @return Kết quả trả về là object Json chứa thông tin account đăng nhập thiết bị (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceGetAccWebGui", notes = "Lấy thông tin account đăng nhập WebGui của thiết bị", response = AccWebGuiListResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về là object Json chứa thông tin account đăng nhập thiết bị", response = AccWebGuiListResponse.class) })
    @GetMapping(
        value = "/device/getAccWebGui",
        produces = { "application/json" }
    )
    default ResponseEntity<AccWebGuiListResponse> deviceGetAccWebGui(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical) {
        return getDelegate().deviceGetAccWebGui(optical);
    }


    /**
     * GET /device/getBoundInterfacesList
     * API get bound interfaces list
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @return OK (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceGetBoundInterfacesList", notes = "API get bound interfaces list", response = BoundInterfacesListResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = BoundInterfacesListResponse.class) })
    @GetMapping(
        value = "/device/getBoundInterfacesList",
        produces = { "application/json" }
    )
    default ResponseEntity<BoundInterfacesListResponse> deviceGetBoundInterfacesList(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical) {
        return getDelegate().deviceGetBoundInterfacesList(optical);
    }


    /**
     * GET /device/getInfoDeviceConnect
     * Lấy danh sách thông tin thiết bị kết nối wifi
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @return Kết quả trả về là object Json chứa kết quả (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceGetInfoDeviceConnect", notes = "Lấy danh sách thông tin thiết bị kết nối wifi", response = BaseResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về là object Json chứa kết quả", response = BaseResponse.class) })
    @GetMapping(
        value = "/device/getInfoDeviceConnect",
        produces = { "application/json" }
    )
    default ResponseEntity<BaseResponse> deviceGetInfoDeviceConnect(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical) {
        return getDelegate().deviceGetInfoDeviceConnect(optical);
    }


    /**
     * GET /device/getInterfaceGroupingList
     * API get Interface Grouping list
     *
     * @param serialNumber Mã Serial number của thiết bị (required)
     * @return OK (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceGetInterfaceGroupingList", notes = "API get Interface Grouping list", response = InterfaceGroupingListResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = InterfaceGroupingListResponse.class) })
    @GetMapping(
        value = "/device/getInterfaceGroupingList",
        produces = { "application/json" }
    )
    default ResponseEntity<InterfaceGroupingListResponse> deviceGetInterfaceGroupingList(@NotNull @ApiParam(value = "Mã Serial number của thiết bị", required = true) @Valid @RequestParam(value = "serialNumber", required = true) String serialNumber) {
        return getDelegate().deviceGetInterfaceGroupingList(serialNumber);
    }


    /**
     * GET /device/getLanInterfacesList
     * API get LAN Interfaces list
     *
     * @param serialNumber Mã Serial number của thiết bị (required)
     * @return OK (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceGetLanInterfacesList", notes = "API get LAN Interfaces list", response = WanLanInterfacesListResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = WanLanInterfacesListResponse.class) })
    @GetMapping(
        value = "/device/getLanInterfacesList",
        produces = { "application/json" }
    )
    default ResponseEntity<WanLanInterfacesListResponse> deviceGetLanInterfacesList(@NotNull @ApiParam(value = "Mã Serial number của thiết bị", required = true) @Valid @RequestParam(value = "serialNumber", required = true) String serialNumber) {
        return getDelegate().deviceGetLanInterfacesList(serialNumber);
    }


    /**
     * GET /device/getListWan
     * Lấy thông tin các WAN của thiết bị
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @return Kết quả trả về là object Json chứa danh sách các WAN của thiết bị (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceGetListWan", notes = "Lấy thông tin các WAN của thiết bị", response = DeviceWanListResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về là object Json chứa danh sách các WAN của thiết bị", response = DeviceWanListResponse.class) })
    @GetMapping(
        value = "/device/getListWan",
        produces = { "application/json" }
    )
    default ResponseEntity<DeviceWanListResponse> deviceGetListWan(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical) {
        return getDelegate().deviceGetListWan(optical);
    }


    /**
     * GET /device/getListWlan
     * Lấy thông tin wifi
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @return Kết quả trả về là một Json List object các Wlan của thiết bị (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceGetListWlan", notes = "Lấy thông tin wifi", response = DeviceWlanListResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về là một Json List object các Wlan của thiết bị", response = DeviceWlanListResponse.class) })
    @GetMapping(
        value = "/device/getListWlan",
        produces = { "application/json" }
    )
    default ResponseEntity<DeviceWlanListResponse> deviceGetListWlan(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical) {
        return getDelegate().deviceGetListWlan(optical);
    }


    /**
     * GET /device/getResultFactoryReset
     * API xoá ONT
     *
     * @param serialNumber Mã OpticalNo của thiết bị (required)
     * @return Kết quả trả về là object Json chứa kết quả (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceGetResultFactoryReset", notes = "API xoá ONT", response = BaseResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về là object Json chứa kết quả", response = BaseResponse.class) })
    @GetMapping(
        value = "/device/getResultFactoryReset",
        produces = { "application/json" }
    )
    default ResponseEntity<BaseResponse> deviceGetResultFactoryReset(@NotNull @ApiParam(value = "Mã OpticalNo của thiết bị", required = true) @Valid @RequestParam(value = "serialNumber", required = true) String serialNumber) {
        return getDelegate().deviceGetResultFactoryReset(serialNumber);
    }


    /**
     * GET /device/getVoice
     * API get voice configuration
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @return OK (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceGetVoice", notes = "API get voice configuration", response = GetVoiceListResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = GetVoiceListResponse.class) })
    @GetMapping(
        value = "/device/getVoice",
        produces = { "application/json" }
    )
    default ResponseEntity<GetVoiceListResponse> deviceGetVoice(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical) {
        return getDelegate().deviceGetVoice(optical);
    }


    /**
     * GET /device/getWanInterfacesList
     * API get WAN Interfaces list
     *
     * @param serialNumber Mã Serial number của thiết bị (required)
     * @return OK (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceGetWanInterfacesList", notes = "API get WAN Interfaces list", response = WanLanInterfacesListResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = WanLanInterfacesListResponse.class) })
    @GetMapping(
        value = "/device/getWanInterfacesList",
        produces = { "application/json" }
    )
    default ResponseEntity<WanLanInterfacesListResponse> deviceGetWanInterfacesList(@NotNull @ApiParam(value = "Mã Serial number của thiết bị", required = true) @Valid @RequestParam(value = "serialNumber", required = true) String serialNumber) {
        return getDelegate().deviceGetWanInterfacesList(serialNumber);
    }


    /**
     * GET /device/getWirelessAdvance
     * Lấy thông tin cấu hình advance của wifi (channel, công suất phát, …)
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @return Kết quả trả về là object Json chứa thông tin cấu hình wif (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceGetWirelessAdvance", notes = "Lấy thông tin cấu hình advance của wifi (channel, công suất phát, …)", response = DeviceWirelessAdvResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về là object Json chứa thông tin cấu hình wif", response = DeviceWirelessAdvResponse.class) })
    @GetMapping(
        value = "/device/getWirelessAdvance",
        produces = { "application/json" }
    )
    default ResponseEntity<DeviceWirelessAdvResponse> deviceGetWirelessAdvance(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical) {
        return getDelegate().deviceGetWirelessAdvance(optical);
    }


    /**
     * POST /device/onOffWifi
     * Cấu hình on/off wifi
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @param wifis List các object wifi cần bật/tắt (required)
     * @return OK (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceOnOffWifi", notes = "Cấu hình on/off wifi", response = BaseResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = BaseResponse.class) })
    @PostMapping(
        value = "/device/onOffWifi",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<BaseResponse> deviceOnOffWifi(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical,@ApiParam(value = "List các object wifi cần bật/tắt" ,required=true )  @Valid @RequestBody List<DeviceWlan> wifis) {
        return getDelegate().deviceOnOffWifi(optical, wifis);
    }


    /**
     * GET /device/ping
     * Kiểm tra kết nối của thiết bị
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @param host url hoặc ip của host cần kiểm tra kết nối (required)
     * @return Kết quả trả về là object Json chứa kết quả ping (status code 200)
     */
    @ApiOperation(value = "", nickname = "devicePing", notes = "Kiểm tra kết nối của thiết bị", response = PingResultResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về là object Json chứa kết quả ping", response = PingResultResponse.class) })
    @GetMapping(
        value = "/device/ping",
        produces = { "application/json" }
    )
    default ResponseEntity<PingResultResponse> devicePing(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical,@NotNull @ApiParam(value = "url hoặc ip của host cần kiểm tra kết nối", required = true) @Valid @RequestParam(value = "host", required = true) String host) {
        return getDelegate().devicePing(optical, host);
    }


    /**
     * GET /device/rebootDevice
     * API reboot ONT
     *
     * @param serialNumber Mã OpticalNo của thiết bị (required)
     * @return Kết quả trả về là object Json chứa kết quả (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceRebootDevice", notes = "API reboot ONT", response = BaseResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về là object Json chứa kết quả", response = BaseResponse.class) })
    @GetMapping(
        value = "/device/rebootDevice",
        produces = { "application/json" }
    )
    default ResponseEntity<BaseResponse> deviceRebootDevice(@NotNull @ApiParam(value = "Mã OpticalNo của thiết bị", required = true) @Valid @RequestParam(value = "serialNumber", required = true) String serialNumber) {
        return getDelegate().deviceRebootDevice(serialNumber);
    }


    /**
     * GET /device/reset
     * Reset lại thiết bị
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @return OK (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceReset", notes = "Reset lại thiết bị", response = BaseResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = BaseResponse.class) })
    @GetMapping(
        value = "/device/reset",
        produces = { "application/json" }
    )
    default ResponseEntity<BaseResponse> deviceReset(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical) {
        return getDelegate().deviceReset(optical);
    }


    /**
     * GET /device/searchAdslDeviceAdslFirmware
     * API thống kê ONT
     *
     * @param start  (required)
     * @param limit  (required)
     * @param areaName  (required)
     * @param areaId  (optional)
     * @return Kết quả trả về là object Json chứa kết quả (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceSearchAdslDeviceAdslFirmware", notes = "API thống kê ONT", response = ListAdslDeviceResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về là object Json chứa kết quả", response = ListAdslDeviceResponse.class) })
    @GetMapping(
        value = "/device/searchAdslDeviceAdslFirmware",
        produces = { "application/json" }
    )
    default ResponseEntity<ListAdslDeviceResponse> deviceSearchAdslDeviceAdslFirmware(@NotNull @ApiParam(value = "", required = true) @Valid @RequestParam(value = "start", required = true) String start,@NotNull @ApiParam(value = "", required = true) @Valid @RequestParam(value = "limit", required = true) String limit,@NotNull @ApiParam(value = "", required = true) @Valid @RequestParam(value = "areaName", required = true) String areaName,@ApiParam(value = "") @Valid @RequestParam(value = "areaId", required = false) String areaId) {
        return getDelegate().deviceSearchAdslDeviceAdslFirmware(start, limit, areaName, areaId);
    }


    /**
     * POST /device/setVoice
     * API set voice configuration
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @param body  (required)
     * @return OK (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceSetVoice", notes = "API set voice configuration", response = BaseResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = BaseResponse.class) })
    @PostMapping(
        value = "/device/setVoice",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<BaseResponse> deviceSetVoice(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical,@ApiParam(value = "" ,required=true )  @Valid @RequestBody InlineObject body) {
        return getDelegate().deviceSetVoice(optical, body);
    }


    /**
     * POST /device/setWirelessAdvance
     * Cấu hình thông tin wifi advance
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @param newConfig Object cấu hình wifi advance (required)
     * @return Kết quả trả về thành công là chuỗi json (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceSetWirelessAdvance", notes = "Cấu hình thông tin wifi advance", response = BaseResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về thành công là chuỗi json", response = BaseResponse.class) })
    @PostMapping(
        value = "/device/setWirelessAdvance",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<BaseResponse> deviceSetWirelessAdvance(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical,@ApiParam(value = "Object cấu hình wifi advance" ,required=true )  @Valid @RequestBody DeviceWirelessAdv newConfig) {
        return getDelegate().deviceSetWirelessAdvance(optical, newConfig);
    }


    /**
     * POST /device/updateWifi
     * Cấu hình thông tin wifi (wlan)
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @param wifis List các object wifi cần bật/tắt (required)
     * @return OK (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceUpdateWifi", notes = "Cấu hình thông tin wifi (wlan)", response = BaseResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = BaseResponse.class) })
    @PostMapping(
        value = "/device/updateWifi",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<BaseResponse> deviceUpdateWifi(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical,@ApiParam(value = "List các object wifi cần bật/tắt" ,required=true )  @Valid @RequestBody List<DeviceWlan> wifis) {
        return getDelegate().deviceUpdateWifi(optical, wifis);
    }


    /**
     * POST /device/updateWifiType
     * API cấu hình Wifi
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @param wifis List các object wifi cần bật/tắt (required)
     * @return OK (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceUpdateWifiType", notes = "API cấu hình Wifi", response = BaseResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = BaseResponse.class) })
    @PostMapping(
        value = "/device/updateWifiType",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<BaseResponse> deviceUpdateWifiType(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical,@ApiParam(value = "List các object wifi cần bật/tắt" ,required=true )  @Valid @RequestBody List<DeviceWlan> wifis) {
        return getDelegate().deviceUpdateWifiType(optical, wifis);
    }


    /**
     * GET /device/getUptime
     * Lấy thông tin uptime thiết bị
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @return Thời gian uptime tính theo giây (status code 200)
     */
    @ApiOperation(value = "", nickname = "getUptime", notes = "Lấy thông tin uptime thiết bị", response = BaseResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Thời gian uptime tính theo giây", response = BaseResponse.class) })
    @GetMapping(
        value = "/device/getUptime",
        produces = { "application/json" }
    )
    default ResponseEntity<BaseResponse> getUptime(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical) {
        return getDelegate().getUptime(optical);
    }


    /**
     * GET /device/reboot
     * Khởi động lại thiết bị
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @return OK (status code 200)
     */
    @ApiOperation(value = "", nickname = "reboot", notes = "Khởi động lại thiết bị", response = BaseResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = BaseResponse.class) })
    @GetMapping(
        value = "/device/reboot",
        produces = { "application/json" }
    )
    default ResponseEntity<BaseResponse> reboot(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical) {
        return getDelegate().reboot(optical);
    }


    /**
     * GET /device/getByOptical
     * Lấy thông tin chi tiết thiết bị
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @return OK (status code 200)
     */
    @ApiOperation(value = "", nickname = "searchDevice", notes = "Lấy thông tin chi tiết thiết bị", response = DeviceParamResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "device", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = DeviceParamResponse.class) })
    @GetMapping(
        value = "/device/getByOptical",
        produces = { "application/json" }
    )
    default ResponseEntity<DeviceParamResponse> searchDevice(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical) {
        return getDelegate().searchDevice(optical);
    }

}
