/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package vn.vnptit.sapi.oneapp.resources.gnms;

import vn.vnptit.sapi.oneapp.models.gnms.BaseResponse;
import vn.vnptit.sapi.oneapp.models.gnms.DeviceWirelessAdvV2;
import vn.vnptit.sapi.oneapp.models.gnms.DeviceWirelessAdvV2ListResponse;
import vn.vnptit.sapi.oneapp.models.gnms.DeviceWlan;
import vn.vnptit.sapi.oneapp.models.gnms.DeviceWlanListResponse;
import java.util.List;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import springfox.documentation.annotations.ApiIgnore;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Api(value = "Gw040H", description = "the Gw040H API")
public interface Gw040HApi {

    default Gw040HApiDelegate getDelegate() {
        return new Gw040HApiDelegate() {};
    }

    /**
     * GET /device/v2/GW040H/getListWlan
     * API lấy dang sách wlan hiện có của GW040H
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @return Kết quả trả về là object Json chứa kết quả (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceGetListWlanV2", notes = "API lấy dang sách wlan hiện có của GW040H", response = DeviceWlanListResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "GW040H", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về là object Json chứa kết quả", response = DeviceWlanListResponse.class) })
    @GetMapping(
        value = "/device/v2/GW040H/getListWlan",
        produces = { "application/json" }
    )
    default ResponseEntity<DeviceWlanListResponse> deviceGetListWlanV2(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical) {
        return getDelegate().deviceGetListWlanV2(optical);
    }


    /**
     * GET /device/v2/GW040H/getWirelessAdvance
     * API lấy danh sách các wlan advance cho GW040H
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @return Kết quả trả về là object Json chứa thông tin cấu hình wif (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceGetWirelessAdvanceV2", notes = "API lấy danh sách các wlan advance cho GW040H", response = DeviceWirelessAdvV2ListResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "GW040H", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về là object Json chứa thông tin cấu hình wif", response = DeviceWirelessAdvV2ListResponse.class) })
    @GetMapping(
        value = "/device/v2/GW040H/getWirelessAdvance",
        produces = { "application/json" }
    )
    default ResponseEntity<DeviceWirelessAdvV2ListResponse> deviceGetWirelessAdvanceV2(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical) {
        return getDelegate().deviceGetWirelessAdvanceV2(optical);
    }


    /**
     * POST /device/v2/GW040H/setWirelessAdvance
     * API cập nhật thông tin wlan advance cho GW040H
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @param newConfig Object cấu hình wifi advance (required)
     * @return Kết quả trả về thành công là chuỗi json (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceSetWirelessAdvanceV2", notes = "API cập nhật thông tin wlan advance cho GW040H", response = BaseResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "GW040H", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về thành công là chuỗi json", response = BaseResponse.class) })
    @PostMapping(
        value = "/device/v2/GW040H/setWirelessAdvance",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<BaseResponse> deviceSetWirelessAdvanceV2(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical,@ApiParam(value = "Object cấu hình wifi advance" ,required=true )  @Valid @RequestBody DeviceWirelessAdvV2 newConfig) {
        return getDelegate().deviceSetWirelessAdvanceV2(optical, newConfig);
    }


    /**
     * POST /device/v2/GW040H/updateWifi
     * API cập nhật thông tin wlan cho GW040H
     *
     * @param optical Mã Optical Serial number của thiết bị (required)
     * @param wifis List các object wifi cần bật/tắt (required)
     * @return OK (status code 200)
     */
    @ApiOperation(value = "", nickname = "deviceUpdateWifiV2", notes = "API cập nhật thông tin wlan cho GW040H", response = BaseResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "GW040H", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = BaseResponse.class) })
    @PostMapping(
        value = "/device/v2/GW040H/updateWifi",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<BaseResponse> deviceUpdateWifiV2(@NotNull @ApiParam(value = "Mã Optical Serial number của thiết bị", required = true) @Valid @RequestParam(value = "optical", required = true) String optical,@ApiParam(value = "List các object wifi cần bật/tắt" ,required=true )  @Valid @RequestBody List<DeviceWlan> wifis) {
        return getDelegate().deviceUpdateWifiV2(optical, wifis);
    }

}
