/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package vn.vnptit.sapi.oneapp.resources.gnms;

import vn.vnptit.sapi.oneapp.models.gnms.AccConfig;
import vn.vnptit.sapi.oneapp.models.gnms.BaseResponse;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import springfox.documentation.annotations.ApiIgnore;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Api(value = "User", description = "the User API")
public interface UserApi {

    default UserApiDelegate getDelegate() {
        return new UserApiDelegate() {};
    }

    /**
     * POST /user/configNewPassWord
     * API đổi mật khẩu đăng nhập của thiết bị
     *
     * @param accConfig  (optional)
     * @return Kết quả trả về là object Json chứa kết quả (status code 200)
     */
    @ApiOperation(value = "", nickname = "userConfigNewPassWord", notes = "API đổi mật khẩu đăng nhập của thiết bị", response = BaseResponse.class, authorizations = {
        
        @Authorization(value = "ApiKeyAuth")
         }, tags={ "user", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Kết quả trả về là object Json chứa kết quả", response = BaseResponse.class) })
    @PostMapping(
        value = "/user/configNewPassWord",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<BaseResponse> userConfigNewPassWord(@ApiParam(value = ""  )  @Valid @RequestBody(required = false) AccConfig accConfig) {
        return getDelegate().userConfigNewPassWord(accConfig);
    }

}
