export default {
  // api chinh chu tui
  fn_load_hoancongims_net: async (axios, data) => axios.post('/web-ccdv/completion/fn_load_hoancongims_net', data),
  fn_hienthidanhsachhdtb_hoancongims_net: async (axios, data) => axios.post('/web-ccdv/completion/fn_hienthidanhsachhdtb_hoancongims_net', data),
  bancheo_lay_thongtin_hd_thicong: async (axios, data) => axios.post('/web-bancheo/hoan_cong_ims_net/bancheo_lay_thongtin_hd_thicong', data),
  bancheo_lay_thongtin_kichhoat_ims: async (axios, data) => axios.post('/web-bancheo/hoan_cong_ims_net/bancheo_lay_thongtin_kichhoat_ims', data),
  sp_tt_hd_bancheo: async (axios, data) => axios.post('/web-ccdv/completion/sp_tt_hd_bancheo', data),
  lay_ds_nhanvien_theo_phieu_id: async (axios, data) => axios.post('/web-ccdv/completion/lay_ds_nhanvien_theo_phieu_id', data),
  lay_ds_dangky_dvgt: async (axios, data) => axios.post('/web-ccdv/completion/lay_ds_dangky_dvgt', data),
  bancheo_lay_ds_thongtin_kythuat: async (axios, data) => axios.post('/web-ccdv/completion/bancheo_lay_ds_thongtin_kythuat', data),
  bancheo_lay_ds_thongtin_kythuat_2: async (axios, data) => axios.post('/web-ccdv/completion/bancheo_lay_ds_thongtin_kythuat_2', data),
  fn_hienthids_phieuth_hoancongims_net: async (axios, data) => axios.post('/web-ccdv/completion/fn_hienthids_phieuth_hoancongims_net', data),
  sp_tt_tientrinh_tc: async (axios, data) => axios.post('/web-ccdv/completion/sp_tt_tientrinh_tc', data),
  capnhat_thongtin_phieu: async (axios, data) => axios.post('/web-ccdv/completion/capnhat_thongtin_phieu', data),
  bancheo_capnhat_thongtin_kichhoat_ims: async (axios, data) => axios.post('/web-bancheo/hoan_cong_ims_net/bancheo_capnhat_thongtin_kichhoat_ims', data),
  fn_kiemtra_phieucon_dahoanthanh: async (axios, data) => axios.post('/web-ccdv/completion/fn_kiemtra_phieucon_dahoanthanh', data),
  kt_lay_tt_tb_sip_pots_net: async (axios, data) => axios.post('/web-ccdv/completion/kt_lay_tt_tb_sip_pots_net', data),
  lay_thongtin_diachi_ims: async (axios, data) => axios.post('/web-ccdv/completion/lay_thongtin_diachi_ims', data),
  lay_ds_sudung_dvgt: async (axios, data) => axios.post('/web-ccdv/completion/lay_ds_sudung_dvgt', data),
  capnhat_log_action_bnm: async (axios, data) => axios.post('/web-ccdv/completion/capnhat_log_action_bnm', data),
  hoanthien_giao_ph_bancheo: async (axios, data) => axios.post('/web-ccdv/completion/hoanthien_giao_ph_bancheo', data),
  kiemtra_tudong_hoanthien_hs_net_bc: async (axios, data) => axios.post('/web-ccdv/completion/kiemtra_tudong_hoanthien_hs_net_bc', data),
  hoancong_thicong_v3: async (axios, data) => axios.post('/web-ccdv/completion/hoancong_thicong_v3', data),
  update_giaophieu_ph: async (axios, data) => axios.post('/web-ccdv/completion/update_giaophieu_ph', data),
  hoanthanh_thicong: async (axios, data) => axios.post('/web-ccdv/completion/hoanthanh_thicong', data),
  fn_btnndth_click_hoancongims_net: async (axios, data) => axios.post('/web-ccdv/completion/fn_btnndth_click_hoancongims_net', data),
  lay_ds_file_hs_bc: async (axios, data) => axios.post('/web-ccdv/completion/lay_ds_file_hs_bc', data),
  sp_tt_giaophieu: async (axios, data) => axios.post('/web-ccdv/completion/sp_tt_giaophieu', data),
  sp_tt_tientrinh_sms: async (axios, data) => axios.post('/web-ccdv/completion/sp_tt_tientrinh_sms', data),
  sp_delete_tientrinh_tc: async (axios, data) => axios.post('/web-ccdv/completion/sp_delete_tientrinh_tc', data),
  tsbtnDownloadFileNT_Click: async (axios, data) => axios.post('/web-ccdv/completion/tsbtnDownloadFileNT_Click', data),
  upload_file: async (axios, data, header) => axios.post('/web-quantri/upload', data, header),
  bc_kt_va_lay_tt_phieu: async (axios, data) => axios.get(`/web-thicong/khaibao_dichvu_net_mgw/bc_kt_va_lay_tt_phieu?vphanvung_id=${data.vphanvung_id}&vphieu_id=${data.vphieu_id}`),
  bc_tra_phieu_vip: async (axios, data) => axios.post('/web-thicong/khaibao_dichvu_net_mgw/bc_tra_phieu_vip', data),

  phailam: async (axios, data, header) => axios.post('/web-thicong/hoinghi_truyenhinh/phailam', data, header),
  lay_phieu_giao_by_id: async (axios, data) => axios.post('/web-ccdv/khaibaoims/lay_phieu_giao_by_id', data),
  select_lay_ds_dangky_dvgt: async (axios, data) => axios.post('/web-bancheo/hoan_cong_ims_net/select_lay_ds_dangky_dvgt', data),
  hoanthanh: async (axios, data) => axios.post('/web-thicong/khaibao_dichvu_net_ims/hoanthanh', data),

  //api di chom ve
  lay_tinh_thi_cong: async (axios, data) => axios.post('/web-thicong/hoinghi_truyenhinh/lay_tinh_thi_cong', data),
  post_lay_tinh_thi_cong: async (axios, data) => axios.post('/web-thicong/hoinghi_truyenhinh/lay_tinh_thi_cong', data),
  fn_lay_thongtin_lh_lapdat: async (axios, data) => axios.post('/web-ccdv/khaibaoims/fn_lay_thongtin_lh_lapdat', data),
  lay_idx_huonggiao_theoquytrinh_id: async (axios, data) => axios.post('/web-hopdong/thanhly/lay_idx_huonggiao_theoquytrinh_id', data),
  sp_lay_luong_thaotac: async (axios, data) => axios.post(`/web-ccdv/khaibaoims/sp_lay_luong_thaotac`, data),
  sp_lay_ds_quytrinh_v2: (axios, data) => axios.post('/web-thicong/thanhly-thuebao/sp_lay_ds_quytrinh_v2', data),
  // ds_huonggiao: (axios, data) => axios.get(`/web-hopdong/danhmuc/ds_huonggiao/${quyTrinhId}/${tthd_id}`, data),
  get_keys: async (axios, data) => axios.post('/web-hopdong/khoiphucthanhly/get_keys', data),
  fn_bancheo_hienthi_hoso_khdn: async (axios, data) => axios.get(`web-bancheo/hoan_cong_megawan_net/fn_bancheo_hienthi_hoso_khdn?vphanvung_id=${data.vphanvung_id}&vtinh_id=${data.vtinh_id}&vhdtb_id=${data.vhdtb_id}`, data),
  sp_khdn_lay_ds_tientrinh_tc: async (axios, data, header) => axios.post('/web-thicong/giaoviec-vip/sp_khdn_lay_ds_tientrinh_tc', data, header),
}
