export default {
  cols: [
    {
      fieldName: "tiepnhan_id",
      headerText: "Số HTKT",
      allowFiltering: true,
      allowSorting: false,
      width: 120
    },
    {
      fieldName: "ma_tb",
      headerText: "Số máy/ACC",
      allowFiltering: true,
      allowSorting: false,
      width: 120,
    },
    {
      fieldName: "ma_lt",
      headerText: "Số ảo",
      allowFiltering: true,
      allowSorting: false,
      width: 120,
    },
    {
      fieldName: "ten_dvvt",
      headerText: "Dịch vụ",
      allowFiltering: true,
      allowSorting: false,
      width: 120,
    },
    {
      fieldName: "loaihinh_tb",
      headerText: "Loại hình",
      allowFiltering: true,
      allowSorting: false,
      width: 120,
    },
    {
      fieldName: "ngay_tn",
      headerText: "Ngày HTKT",
      allowFiltering: true,
      allowSorting: false,
      width: 120,
    },
    {
      fieldName: "nguoi_lh",
      headerText: "Người LH",
      allowFiltering: true,
      allowSorting: false,
      width: 120,
    },
    {
      fieldName: "sdt_lh",
      headerText: "Điện thoại LH",
      allowFiltering: true,
      allowSorting: false,
      width: 120,
    },
    {
      fieldName: "ten_tiepnhan",
      headerText: "Tên tiếp nhận",
      allowFiltering: true,
      allowSorting: false,
      width: 120,
    },
    {
      fieldName: "noidung_tiepnhan",
      headerText: "Nội dung TN",
      allowFiltering: true,
      allowSorting: false,
      width: 150,
    },
    {
      fieldName: "ten_hotro",
      headerText: "Tên hỗ trợ",
      allowFiltering: true,
      allowSorting: false,
      width: 120,
    },
    {
      fieldName: "noidung_hotro",
      headerText: "Nội dung HT",
      allowFiltering: true,
      allowSorting: false,
      width: 150,
    },
    {
      fieldName: "nhanvien_htkt",
      headerText: "Người tiếp nhận",
      allowFiltering: true,
      allowSorting: false,
      width: 120,
    },
    {
      fieldName: "donvi_htkt",
      headerText: "Nơi tiếp nhận",
      allowFiltering: true,
      allowSorting: false,
      width: 120,
    },
  ],
}
