const collumns = {
    collumnsDSHoSoDD: [
        {
            fieldName: "ngaygiao",
            headerText: "Ngày giao",
            isGroupedColumn: true,
        },
        {
            fieldName: "gio_giao",
            headerText: "Giờ giao",
            allowSorting: true,
            textAlign: 'center',
            width: "150px",
        },
        {
            fieldName: "ma_tb",
            headerText: "Số máy",
            allowSorting: true,
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "ten_kh",
            headerText: "Tên thuê bao",
            allowSorting: true,
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "nd_giao",
            headerText: "Nội dung giao",
            allowSorting: true,
            textAlign: 'left',
            autoFit: "true",
        },     
        {
            fieldName: "nhanviengiao",
            headerText: "Người giao",
            allowSorting: true,
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "donvi_nhan",
            headerText: "Quầy nhận",
            allowSorting: true,
            textAlign: 'left',
            autoFit: "true",
        },      
        {
            fieldName: "loai_nc",
            headerText: "Loại NC",
            allowSorting: true,
            textAlign: 'left',
            autoFit: "true",
        },
    ],
    collumnsDSHoSo: [
        {
            fieldName: "ngaygiao",
            headerText: "Ngày giao",
            isGroupedColumn: true,
        },
        {
            fieldName: "gio_cl",
            headerText: "Giờ còn lại",
            allowSorting: true,
            textAlign: 'center',
            width: 150,
        },
        {
            fieldName: "gio_giao",
            headerText: "Giờ giao",
            allowSorting: true,
            textAlign: 'center',
            autoFit: "true",
        },
        {
            fieldName: "ma_kh",
            headerText: "Mã GD",
            allowSorting: true,
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "ten_kh",
            headerText: "Tên khách hàng",
            allowSorting: true,
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "so_dt",
            headerText: "Số ĐT",
            allowSorting: true,
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "nd_giao",
            headerText: "Nội dung giao",
            allowSorting: true,
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "nhanviengiao",
            headerText: "Người giao",
            allowSorting: true,
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "donvi_giao",
            headerText: "Đơn vị giao",
            allowSorting: true,
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "donvi_nhan",
            headerText: "Đơn vị nhận",
            allowSorting: true,
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "loai_hd",
            headerText: "Loại HD",
            allowSorting: true,
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "loai_nc",
            headerText: "Loại NC",
            allowSorting: true,
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "diachi",
            headerText: "Địa chỉ",
            allowSorting: true,
            textAlign: 'left',
            autoFit: "true",
        },
    ]
}

export default collumns
