export const CURRENT_DATA_THUE_BAO_DEFAULT = {
  congvan_id: "1",
  cuoc_fix_mb: null,
  cuoc_ip: "0",
  cuoc_sd: "0",
  cuoc_tb: "0",
  diachi_ld: "",
  dichvuvt_id: "0",
  ghichu: "",
  hieuluc: "0",
  loaihinh_tb: "",
  loaitb_id: "0",
  ma_tb: "",
  may_cn: "",
  muccuoc: "0",
  ngay_bd: null,
  ngay_cn: "",
  ngay_huy: null,
  ngay_kt: null,
  nguoi_cn: "",
  nguonkm_id: "0",
  rkm_id: "0",
  so_mb: null,
  ten_tb: "",
  thang_bd: "0",
  thang_bd_email: null,
  thang_bdshow: "",
  thang_huy: null,
  thang_kt: "0",
  thang_kt_email: null,
  thang_ktshow: "",
  thuebao_id: "0",
  thuebao_ud_id: "0",
  tien_sodep: "0",
  tinh_dt: "0",
  tyle_csd: "0",
  tyle_ctb: "0",
  tyle_cuocip: "0",
  tyle_giam_email: null,
  tyle_sodep: "0"
};

export const DATA_TEST_IMPORT = [
  {
    MA_TB: "ma_tb",
    LOAITB_ID: 11,
    DICHVU: "ADSL",
    TYLE_CTB: 0,
    CUOC_TB: 0,
    TYLE_CSD: 0,
    CUOC_SD: 0,
    TYLE_SODEP: 0,
    TIEN_SODEP: 0,
    TYLE_CUOCIP: 0,
    CUOC_IP: 0,
    MUCCUOC: 0
  }

  // {
  //   congvan_id: "28",
  //   cuoc_fix_mb: null,
  //   cuoc_ip: "0",
  //   cuoc_sd: "400000",
  //   cuoc_tb: "20000",
  //   diachi_ld: "Cụm 7, Thôn An Bồ, Xã Dũng Tiến, Huyện Vĩnh Bảo, Hải Phòng",
  //   dichvuvt_id: "4",
  //   ghichu: null,
  //   hieuluc: "1",
  //   loaihinh_tb: "Tivi Samsung",
  //   loaitb_id: "266",
  //   ma_tb: "tahuukien",
  //   may_cn: "1.1.1.1",
  //   muccuoc: "400000",
  //   ngay_bd: null,
  //   ngay_cn: "2021-12-12 14:04:40.0",
  //   ngay_huy: null,
  //   ngay_kt: null,
  //   nguoi_cn: "test_app.hpg",
  //   nguonkm_id: "1",
  //   rkm_id: "2395896",
  //   so_mb: null,
  //   ten_tb: "Tạ Hữu Kiên",
  //   thang_bd: "202805",
  //   thang_bd_email: null,
  //   thang_bdshow: "05/2035",
  //   thang_huy: null,
  //   thang_kt: "202806",
  //   thang_kt_email: null,
  //   thang_ktshow: "06/2035",
  //   thuebao_id: "1692876",
  //   thuebao_ud_id: "0",
  //   tien_sodep: "0",
  //   tinh_dt: "1",
  //   tyle_csd: "0",
  //   tyle_ctb: "0",
  //   tyle_cuocip: "0",
  //   tyle_giam_email: null,
  //   tyle_sodep: "0"
  // },

  // {
  //   congvan_id: "28",
  //   cuoc_fix_mb: null,
  //   cuoc_ip: "0",
  //   cuoc_sd: "400000",
  //   cuoc_tb: "20000",
  //   diachi_ld: "Cụm 7, Thôn An Bồ, Xã Dũng Tiến, Huyện Vĩnh Bảo, Hải Phòng",
  //   dichvuvt_id: "4",
  //   ghichu: null,
  //   hieuluc: "1",
  //   loaihinh_tb: "Tivi Samsung",
  //   loaitb_id: "266",
  //   ma_tb: "tahuukien",
  //   may_cn: "1.1.1.1",
  //   muccuoc: "400000",
  //   ngay_bd: null,
  //   ngay_cn: "2021-12-12 14:04:40.0",
  //   ngay_huy: null,
  //   ngay_kt: null,
  //   nguoi_cn: "test_app.hpg",
  //   nguonkm_id: "1",
  //   rkm_id: "2395896",
  //   so_mb: null,
  //   ten_tb: "Tạ Hữu Kiên",
  //   thang_bd: "202803",
  //   thang_bd_email: null,
  //   thang_bdshow: "03/2035",
  //   thang_huy: null,
  //   thang_kt: "202804",
  //   thang_kt_email: null,
  //   thang_ktshow: "04/2035",
  //   thuebao_id: "1692876",
  //   thuebao_ud_id: "0",
  //   tien_sodep: "0",
  //   tinh_dt: "1",
  //   tyle_csd: "0",
  //   tyle_ctb: "0",
  //   tyle_cuocip: "0",
  //   tyle_giam_email: null,
  //   tyle_sodep: "0"
  // }
];

/* variables mau */
const variables = {
  nguoi_cn: "",
  vdichvuvt_id: 0,
  vkieu: 0,
  vloaitb_id: 0,
  vmatb: "",
  vthang_bd: 202104,
  vthang_kt: 209901
};

export const config = [
  { fieldName: "stt", headerText: "STT", allowFiltering: true },
  {
    fieldName: "tenchude",
    headerText: "Tên chủ đề",
    allowFiltering: true
  },
  {
    fieldName: "ten_loai",
    headerText: "Loại KN",
    allowFiltering: true,
    allowHtml: true
  }
];

export const DATA_CURRENT = {
  bosungtb_ID: 0,
  chucdanh_DD: null,
  ctv_ID: null,
  dactrung: null,
  dantoc_ID: 0,
  diachi_KH: "",
  diachi_LD: "",
  diachi_NDD: "",
  diachi_TB: "",
  dichvuvt_ID: 1,
  doituong_ID: 1,
  donhang_ID: null,
  donvi_ID: 186,
  donviql_ID: 10,
  email: null,
  ghichu: null,
  gioitinh: 0,
  hdkh_CHA_ID: null,
  hdkh_ID: 5684533,
  hdkh_ID_HNI: null,
  hdtb_ID: 59312898,
  hokhau: "",
  httthi_ID: null,
  ip_CN: "1.1.1.1",
  kenhtn_ID: 1,
  kh_KT3: null,
  kh_TIEMNANG: null,
  khachhang_ID: null,
  khlon_ID: 0,
  kieuhd_ID: 1,
  kieuld_ID: 1,
  kieutn_ID: 1,
  loaigt_ID: 1,
  loaihd_ID: 1,
  loaikh_ID: 1,
  loainc_IC: null,
  loainc_ID: null,
  loaitb_ID: 1,
  ma_DUAN: null,
  ma_GD: "",
  ma_HD: "",
  ma_KH: "",
  ma_KH_WEB: null,
  ma_TB: "",
  ma_TB_CU: null,
  ma_TB_MOI: "",
  may_CN: "1.1.1.1",
  mst: null,
  mst_KH: null,
  mucdo_ID: null,
  nganhang_ID: null,
  nganhnghe_ID: 1002,
  ngay_CN: "",
  ngay_HK: null,
  ngay_HT: null,
  ngay_SN: "",
  ngay_YC: "",
  ngaycap: "",
  ngayhethan_GT: null,
  ngaylap_HD: "",
  nguoi_CN: "",
  nguoi_DD: "",
  nguoilap_HD: null,
  nhanvien_ID: 13431,
  nhanviengt_ID: null,
  noicap: null,
  noicap_HK: null,
  phanloaikh_ID: 16,
  phanvung_ID: 26,
  phieucskh_ID: null,
  quoctich_ID: 1,
  quoctich_NEO_ID: 232,
  so_DT: null,
  so_FAX: null,
  so_GT: "",
  so_PL: null,
  status: 0,
  stk: null,
  tbtl_ID: null,
  ten_DV: "",
  ten_KH: "",
  ten_LOAIHD: "",
  ten_NV: "",
  ten_TB: "",
  thangnam_TT: null,
  thuebao_ID: null,
  tnc1_ID: 1008,
  tnc2_ID: 1524,
  tnc3_ID: 1556,
  tnc4_ID: 1086,
  tongtien: 3463102,
  trangthai_HD: "Mới tiếp nhận",
  website: null,
  yeucau_ID: null
};

export const TrangThaiHD = {
  MOI: 1,
  THANH_TOAN: 2,
  DIEUHANH_THI_CONG: 3,
  DANG_THI_CONG: 4,
  DA_THI_CONG_XONG: 5,
  HOAN_THANH: 6,
  THOAITRA: 7,
  DA_LAY_DU_LIEU: 8,
  KHAIBAO_TONGDAI: 9,
  DANGCHO_HOANCONG: 10,
  DOISOAT_HOSO: 11,
  TTVT_XACMINH_NO: 14,
  THOAITRA_TMP: 17,
  TTVT_HOANCONG_DICHVU: 23,
  HTHS_BANCHEO: 26,
  NVKD_XACMINH: 27,
  SUA_HD: 100
};

export const DICHVU_VIENTHONG = {
  CO_DINH: 1,
  DI_DONG: 2,
  ADSL: 4,
  DD_TRATRUOC: 5,
  EMAIL: 6,
  METRONET: 7,
  MEGAWAN: 8,
  TSL: 9,
  GPHONE: 10,
  IMS: 11,
  MEGA_EYES: 12,
  HOINGHI_TRUYENHINH: 13,
  ANTOAN_BAOMAT_TT: 14,
  DICHVU_CNTT: 15,
  TRUNGTAM_DULIEU: 16,
  HATANG_VIENTHONG: 19,
  IMS_DOITAC: 21,
  BRCD_DOITAC: 22,
  MGW_DOITAC: 23,
  TSL_DOITAC: 24
};

export const LOAIHINH_THUEBAO = {
  DIENTHOAI_CD: 1,
  TRUNGKE_THUONG: 3,
  TRUNGKE_TUONGTU: 4,
  TRUNGKE_2M: 5,
  PABX: 8,
  MAIL_SMD: 9,
  INTERNET: 10,
  INTERNET_1260: 10,
  MEGA: 11,
  INTERNET_ADSL: 11,
  Web_Hosting: 12,
  EMAIL: 13,
  ISDN2B_CD: 14,
  ISDN30B_CD: 15,
  ISDN2B_CQ: 16,
  ISDN30B_CQ: 17,
  HTVC_FIBERVNN_ANALOG: 18,
  HTVC_FIBERVNN_DIGITAL: 19,
  DIDONGTRASAU: 20,
  DIDONGTRATRUOC: 21,
  LEASEDLINE: 22,
  MEGAWAN_ADSL: 23,
  FSECURE: 24,
  MEGAWAN_SHDSL: 25,
  MEGAWAN_QUANG_FE: 26,
  METRONET_FE: 27,
  METRONET_GE: 28,
  MEGAWAN_QUANG_GE: 30,
  MEGACAMERA: 31,
  GPHONE: 32,
  GPHONE_TRATRUOC: 34,
  IOFFICE: 35,
  TD_1800: 38,
  VNPT_COLOCATION: 39,
  INTERNET_ADSL_TINH_KHAC: 57,
  INTERNET_FTTH: 58,
  INTERNET_FIBER_TINH_KHAC: 59,
  INTERNET_MYTV: 61,
  INTERNET_MYTV_B2B: 171,
  IMS_POTS: 62,
  IMS_SIP: 63,
  IMS_RGW: 64,
  INTERNET_SGTV: 65,
  CAMERA_HOCDUONG: 70,
  MEGAWAN_ADSL_2M: 74,
  METRONET_2FE: 75,
  MEGA_CONFERENCE: 76,
  IMS_SIPTRUNKING: 77,
  SSL: 78,
  WIFI_FIBER: 79,
  VNPT_MEETING: 89,
  HNTH_NGN: 90,
  KTR_Leasedline_GE: 96,
  KTR_Leasedline_E1: 97,
  KTR_Leasedline_STM1: 98,
  KTR_Leasedline_nx64k: 99,
  KTR_TRUCTHONG_DONG: 100,
  KTR_TRUCTHONG_QUANG: 101,
  KTR_DOICAP_QUANG: 102,
  KTR_DOICAP_DONG: 103,
  KTR_Leasedline_FE: 104,
  KTR_Nail_up: 105,
  CDN: 112,
  CA: 116,
  CA_IVAN: 117,
  VN_EDU: 118,
  VNPT_PORTAL: 120,
  TTDL_HDDT: 122,
  TTDL_MAIL_OFFICE: 124,
  TD_1900: 127,
  BRANDNAME: 131,
  IVAN: 132,
  DEDICATED_SERVER: 139,
  TDTH_THUYENHINH: 146,
  VCC: 149,
  MGW_INTERNET_TRUCTIEP: 134,
  COSO_HATANG: 158,
  CAPQUANG_TRANG_TSL: 123,
  MEGAEYES_CLOUD_CAMERA: 83,
  WIFI_MESH: 210,
  INDOOR_CAM: 222,
  OUTDOOR_CAM: 224,
  TIVI_SAMSUNG: 266,
  IMS_DT: 228,
  BRCD_FBDT: 229,
  BRCD_THDT: 230,
  MGW_DT: 231,
  TSL_DT: 232,
  ECABINET: 200,
  ELEARNING: 208,
  ORM: 160,
  VXP: 235,
  VNPT_HIS: 136,
  VNPT_HMIS: 156,
  BIENLAIDT: 175,
  VNPT_MCAP: 267,
  VNPT_HCSN: 202,
  VNPT_SMART_TOURIST: 223,
  VNPT_SMCC: 268,
  VEDU_LIB: 205,
  VNPT_SLL: 215,
  VNPT_LIS: 261
};

export const LoaiHopDong = {
  KHONG_DUNG: 0,
  DAT_MOI: 1,
  CHUYEN_QUYEN: 2,
  DI_CHUYEN: 3,
  CHAMDUT_SD: 4,
  THAYDOI_THONGSO_MEGAWAN: 5,
  CHUYENDOI_LH: 6,
  THAY_DOI_DV: 7,
  THAY_DOI_TOCDO_ADSL: 8,
  THAY_DOI_SOMAY_TN: 9,
  TACHNHAP_TB: 10,
  THAY_TT_KHAC: 11,
  THAY_DOI_SO_SIM: 12,
  THUEBAO_TRATRUOC: 13,
  THAY_DAY_MAY: 13,
  VATTU_THUEBAO: 13,
  DOISO_TB: 14,
  BAN_THIETBI: 15,
  THAY_DOI_TOCDO_TSL: 16,
  THU_KHAC: 17,
  KHAO_SAT: 18,
  TDTT_DV_CNTT: 19,
  GHEP_MA_KHACHHANG: 20,
  KY_LAI_HD_GOC: 24,
  TAMDUNG_SD: 25,
  THAYDOI_THONGSO_MYTV: 25,
  TIEPNHAN_DATMOI: 26,
  DOIGOICUOC_DD: 27,
  TIEPNHAN_CDLH: 28,
  TIEPNHAN_DC: 29,
  KHOIPHUC_SD: 30,

  DANGKY_GOI_DADV: 27,
  THAYDOI_GOI_DADV: 28,

  DATCOC_MOI: 31,
  THAYDOI_DATCOC: 32,

  KHAOSATDATMOI: 33,
  KHAOSATCDLH: 34,
  KHAOSATDC: 35,
  TIEPNHANHD: 36,
  THUCUOC_THUHOIVT: 37,
  TUVAN_DV: 38, //phối hợp tư vấn dịch vụ giữa NVKT và TTKD
  THAYDOI_TT_DD: 100, // vuth them - thay doi thoong tin di dong

  DD_SIPTRUNKING: 40, // Taita thêm đăng ký dịch vụ SIPTRUNKING
  DD_HUYSTKING: 42, // Hủy dịch vụ Siptrunking di động
  DD_DKVCC: 43, //  Đăng ký dịch vụ VCC di động
  DD_HUYVCC: 44, //  Hủy dịch vụ VCC di động
  DD_TAMDUNGVCC: 45, //  Tạm dừng dịch vụ VCC di động
  DD_KICHVCC: 46, //   Kích hoạt lại dịch vụ VCC di động
  DD_CAPNHATGOI: 47, // Cập nhật gói VCC
  DD_XOAGOI: 48, // Xóa gói VCC
  DD_CAPNHATDATA: 49, // Thêm mới dịch vụ data
  DD_XOADATA: 50, // Xóa data VCC

  DD_HSSV: 101, // vuth update before 1509
  DD_DOANVIEN: 102, // vuth update before 1509
  DK_MULTISIM: 39, // vuth them 27/08/2020
  GIAHAN: 41 // vuth them 27/08/2020
};

export const LOAI_DONVI = {
  DONVI_QL: 1,
  DONVIQL_TT: 2,
  DONVIQL_LD: 3,
  GIAODICH: 4,
  TRAM_VT: 5,
  VETINH: 5,
  HOST: 6,
  DONVIQL_TT_BUUDIEN: 7,
  KHACHHANG: 8,
  TRAM_ATM: 9,
  TRAM_MINI: 10,
  DHTC_QLDL: 11,
  DONVI_TSL: 12,
  HOST_VATLY: 16,
  QUAYTHU: 18,
  XULY_NO_KHODOI: 19,
  GIAIQUYET_KHIEUNAI: 20,
  TRAM_IP: 21,
  TO_QUANLY: 22,
  HOANTHIEN_HOSO: 23,
  TRAM_VETINH: 25,
  TRAM_IP_SWITCH: 26,
  CONGTACVIEN: 30,
  PHONGBAN_XM_KHIEUNAI: 31,
  TO_THU_CUOC: 32,
  DAI_BR: 37,
  TRAM_PORT: 39,
  DAILY_XLKN: 45,
  PHONG_BANHANG_KV: 46,
  XULY_YCKM: 49,
  BANHANG_TRUCTIEP: 54,
  GD_NHAN_BANGKE: 61,
  KETOAN_NHAN_BANGKE: 62,
  DIEUHANH_TRUNGTAM_VT: 63,
  CUA_HANG: 63,
  TTDH_NGHIEMTHU: 64,
  TTKD_NGHIEMTHU: 65,
  DONVI_LAPHOPDONG: 72,
  DONVI_LAPHOPDONG_CHA: 73,
  KHO_NHAN_TBI_BAOHANH: 80,
  TO_BHSC: 81,
  KHO_NHAN_TBI_BAOHANH_XONG: 82,
  HOANTHIEN_BAOHANH: 83,
  KENHBAN_THICONG_DV: 98,
  TONGDAI_CABMAN: 100,
  TIEPNHAN_BAOHONG: 66,
  TOKD_XLKN: 427,
  TRAM_CAP_PORT: 504,
  CSHT_NHATRAM: 555,
  NHOM_XLSC: 620,
  BH_QLDH: 635,
  BH_DVXLDH: 636,
  TT_BANHANG_MIEN: 890,
  TTKD_BAOHANH_VT: 998,
  NET_SNOC1: 432,
  PBH_KHAIBAO_DV: 598
};
