export default {
  lay_ds_phieu_giaoden_net_v3: async (axios, data) => axios.post('/web-thicong/khaibao_dichvu_net_mgw/lay_ds_phieu_giaoden_net_v3', data),
  fn_lay_thongtin_lh_lapdat: async (axios, data) => axios.post('/web-hopdong/khaibaoims/fn_lay_thongtin_lh_lapdat', data),
  sp_lay_tinh_tc_theo_tinh_id: async (axios, data) => axios.post('/web-hopdong/lapdatmoi/sp_lay_tinh_tc_theo_tinh_id', data),
  bancheo_lay_thongtin_hd_thicong: async (axios, data) => axios.post('/web-bancheo/tracuu/bancheo_lay_thongtin_hd_thicong', data),
  sp_tt_hd_bancheo: async (axios, data) => axios.post('/web-bancheo/hoan_cong_megawan_net/sp_tt_hd_bancheo', data),
  bancheo_lay_ds_thongtin_kythuat2: async (axios, data) => axios.post('/web-thicong/completion/bancheo_lay_ds_thongtin_kythuat2', data),
  bancheo_lay_ds_thongtin_kythuat_2: async (axios, data) => axios.post('/web-bancheo/hoan_cong_megawan_net/bancheo_lay_ds_thongtin_kythuat_2', data),
  kiemtra_nut_chuyentinh_net_v2: async (axios, data) => axios.get(`/web-thicong/khaibao_dichvu_net_mgw/kiemtra_nut_chuyentinh_net_v2?vhdtb_id=${data.vhdtb_id}`, data),
  pr_get_ds_dangky_dvgt_v2: async (axios, data) => axios.get(`/web-bancheo/hoan_cong_megawan_net/pr_get_ds_dangky_dvgt_v2?vhdtb_id=${data.vhdtb_id}&phanvung_id=${data.phanvung_id}`, data),
  sp_tt_muatbi_v2: async (axios, data) => axios.get(`/web-bancheo/hoan_cong_megawan_net/sp_tt_muatbi_v2?vhdtb_id=${data.vhdtb_id}&phanvung_id=${data.phanvung_id}`),
  lay_danhsach_phieu_net_con: async (axios, data) => axios.post('/web-thicong/hoinghi_truyenhinh/lay_danhsach_phieu_net_con', data),
  lay_danhsach_phieu_net_con_bancheo: async (axios, data) => axios.get(`/web-bancheo/hoan_cong_megawan_net/lay_danhsach_phieu_net_con_bancheo?vphieu_cha_id=${data.vphieu_cha_id}&vphanvung_id=${data.vphanvung_id}`),
  lay_ds_sothuebao_net: async (axios, data) => axios.get(`/web-bancheo/hoan_cong_megawan_net/lay_ds_sothuebao_net?vphanvung_id=${data.vphanvung_id}&vhdtb_id=${data.vhdtb_id}`),
  sp_tt_tientrinh_tc: async (axios, data) => axios.get(`/web-thicong/khaibao_dichvu_net_mgw/sp_tt_tientrinh_tc?vhdtb_id=${data.vhdtb_id}`),
  fn_kiemtra_phieucon_dahoanthanh_v2: async (axios, data) => axios.get(`/web-thicong/khaibao_dichvu_net_mgw/fn_kiemtra_phieucon_dahoanthanh_v2?vphieu_id=${data.vphieu_id}`),
  kiemtra_trangthai_hoanthanh_phieu_net: async (axios, data) => axios.get(`/web-thicong/khaibao_dichvu_net_mgw/kiemtra_trangthai_hoanthanh_phieu_net?vphieu_id=${data.vphieu_id}`),
  kiemtra_thoaitra_hoanthanh_net: async (axios, data) => axios.get(`/web-bancheo/hoan_cong_megawan_net/kiemtra_thoaitra_hoanthanh_net?vphanvung_id=${data.vphanvung_id}&vhdtb_id=${data.vhdtb_id}&vphieu_tinh_id=${data.vphieu_tinh_id}&vloai_check=${data.vloai_check}`),
  capnhat_ttph_giaophieu_ph: async (axios, data) => axios.post('/web-thicong/khaibao_dichvu_net_mgw/capnhat_ttph_giaophieu_ph', data),
  hc_net_sms_vip_ph: async (axios, data) => axios.post('/web-bancheo/tracuu/hc_net_sms_vip_ph', data),
  hoanthien_giao_ph_bancheo: async (axios, data) => axios.post('/web-thicong/completion/hoanthien_giao_ph_bancheo', data),
  lay_idx_huonggiao_theoquytrinh_id: async (axios, data) => axios.post('/web-hopdong/thanhly/lay_idx_huonggiao_theoquytrinh_id', data),
  sp_update_huongiao_tieptheo: async (axios, data) => axios.post('/web-thicong/khaibao_dichvu_net_mgw/sp_update_huongiao_tieptheo', data),
  fn_kiemtra_hoanthienphieu_bancheo_vnpti: async (axios, data) => axios.get(`/web-thicong/khaibao_dichvu_net_mgw/fn_kiemtra_hoanthienphieu_bancheo_vnpti?vloaitb_id=${data.vloaitb_id}`),
  update_nd_thuchien: async (axios, data) => axios.post('/web-hopdong/thaydoi_thongso_megawan/update_nd_thuchien', data),
  capnhat_nd_thuchien_giaophieu_ph_net: async (axios, data) => axios.post('/web-bancheo/hoan_cong_megawan_net/capnhat_nd_thuchien_giaophieu_ph_net', data),
  lay_ds_hdbancheo_theo_hdtb_id: async (axios, data) => axios.get(`/web-bancheo/hoan_cong_megawan_net/lay_ds_hdbancheo_theo_hdtb_id?vphanvung_id=${data.vphanvung_id}&vhdtb_id=${data.vhdtb_id}`),
  sp_tt_nhanvien_2: async (axios, data) => axios.get(`/web-thicong/khaibao_dichvu_net_mgw/sp_tt_nhanvien_2?vnhanvien_id=${data.vnhanvien_id}`),
  sp_tt_nguoidung: async (axios, data) => axios.get(`/web-thicong/khaibao_dichvu_net_mgw/sp_tt_nguoidung?phanvung_id=${data.phanvung_id}&ma_nd=${data.ma_nd}`),
  insert_tientrinh_tc: async (axios, data) => axios.post('/web-thicong/khaibao_dichvu_net_mgw/insert_tientrinh_tc', data),
  update_hdtb_tientrinh_tc: async (axios, data) => axios.post('/web-thicong/khaibao_dichvu_net_mgw/update_hdtb_tientrinh_tc', data),
  update_tientrinh_tc: async (axios, data) => axios.post('/web-thicong/khaibao_dichvu_net_mgw/update_tientrinh_tc', data),
  sp_tt_tientrinh_sms: async (axios, data) => axios.post('/web-bancheo/hoan_cong_megawan_net/sp_tt_tientrinh_sms', data),
  sp_delete_tientrinh_tc: async (axios, data) => axios.post('/web-bancheo/hoan_cong_megawan_net/sp_delete_tientrinh_tc', data),
  capnhat_noidung_thuchien_thuebao: async (axios, data) => axios.post('/web-bancheo/hoan_cong_megawan_net/capnhat_noidung_thuchien_thuebao', data),
  lay_ds_sothuebao_net: async (axios, data) => axios.get(`/web-thicong/khaibao_dichvu_net_mgw/lay_ds_sothuebao_net?vphanvung_id=${data.vphanvung_id}&vhdtb_id=${data.vhdtb_id}`),
  bc_kt_va_lay_tt_phieu: async (axios, data) => axios.get(`/web-thicong/khaibao_dichvu_net_mgw/bc_kt_va_lay_tt_phieu?vphanvung_id=${data.vphanvung_id}&vphieu_id=${data.vphieu_id}`),
  bc_tra_phieu_vip: async (axios, data) => axios.post('/web-thicong/khaibao_dichvu_net_mgw/bc_tra_phieu_vip', data),
  bc_tra_phieu_vip_khdn_v2: async (axios, data) => axios.post('/web-thicong/khaibao_dichvu_net_mgw/bc_tra_phieu_vip_khdn_v2', data),
  tra_phieu_net_sms_vip_ph: async (axios, data) => axios.post('/web-thicong/khaibao_dichvu_net_mgw/tra_phieu_net_sms_vip_ph', data),
  sp_lay_ds_lydotra_vip: async (axios, data) => axios.get(`/web-thicong/khaibao_dichvu_net_mgw/sp_lay_ds_lydotra_vip?phanvung_id=${data.phanvung_id}`),
  lay_ds_file_hs_bc_v2: async (axios, data) => axios.post('/web-bancheo/tracuu/lay_ds_file_hs_bc_v2', data),
  lay_ds_file_hs_bc: async (axios, data) => axios.post('/web-thicong/completion/lay_ds_file_hs_bc', data),
  lay_ds_file_nt_bh_bc: async (axios, data) => axios.get(`/web-tracuu/tracuu-thuebao/lay_ds_file_nt_bh_bc/3172376&phanvung_id=${data.phanvung_id}`),
  sp_them_file_nghiemthu_wan_net: async (axios, data) => axios.post('/web-thicong/khaibao_dichvu_net_mgw/sp_them_file_nghiemthu_wan_net', data),
  hoanthanh: async (axios, data) => axios.post('/web-thicong/khaibao_dichvu_net_mgw/hoanthanh', data),
  fn_capnhat_hoancongmegawan_net: async (axios, data) => axios.post('/web-ccdv/tiepnhanhopdong/fn_capnhat_hoancongmegawan_net', data),
  tsbtnDownloadFileNT_Click: async (axios, data) => axios.post('/web-bancheo/hoan_cong_megawan_net/tsbtnDownloadFileNT_Click', data),
  fn_bancheo_hienthi_hoso_khdn: async (axios, data) => axios.get(`web-bancheo/hoan_cong_megawan_net/fn_bancheo_hienthi_hoso_khdn?vphanvung_id=${data.vphanvung_id}&vtinh_id=${data.vtinh_id}&vhdtb_id=${data.vhdtb_id}`, data),
  upload_file: async (axios, data, header) => axios.post('/web-quantri/upload', data, header),
  chuyen_tc_bancheo: async (axios, data, header) => axios.post('/web-bancheo/bancheo-chuyentc/chuyen_tc_bancheo', data, header),
  sp_khdn_lay_ds_tientrinh_tc: async (axios, data, header) => axios.post('/web-thicong/giaoviec-vip/sp_khdn_lay_ds_tientrinh_tc', data, header),
  

  //api đi chôm về ko biết đúng ko
  lay_tongtien_theo_hdkh_id: (axios, data) => axios.post('/web-ccdv/khaibaotsl/lay_tongtien_theo_hdkh_id', data),
  sp_ht_phieu_tra: async (axios, data) => axios.post('/web-thicong/hoancongmegawan/sp_ht_phieu_tra', data),
  lay_ds_nhanvien_theo_phieu_id: async (axios, data) => axios.post('/web-thicong/hoancongmegawan/lay_ds_nhanvien_theo_phieu_id', data),
  fn_tt_hdtb_dv: async (axios, data) => axios.post('/web-tratruoc/thongtin_tratruoc_dn/fn_tt_hdtb_dv', data),
  lay_thongtin_nhanvien: async (axios, data) => axios.get(`/web-hopdong/danhmuc/lay_thongtin_nhanvien/${data.nhanvien_id}`, data),
  sp_lay_ds_nhanvien_thuchien_theo_dv: (axios, data) => axios.post('/web-thicong/hths-thaydoi-tocdo/sp_lay_ds_nhanvien_thuchien_theo_dv', data),
  sp_get_data_kenhthu: async (axios, data) => axios.post('/web-thicong/hoancongmegawan/sp_get_data_kenhthu', data),
  sp_lay_kenhthu_theo_hdkh: async (axios,data) => axios.post('/web-thicong/hoancongmegawan/sp_lay_kenhthu_theo_hdkh',data),
  sp_lay_ds_kieu_hd: async (axios, data) => axios.post('/web-thicong/hoancongmegawan/sp_lay_ds_kieu_hd', data),
  lay_ds_loai_hd: async (axios,data) => axios.get(`/web-thicong/danhmuc/lay_ds_loai_hd?loaiHdId=${data.loaiHdId}`, data),
  sp_lay_luong_thaotac: async (axios,data) => axios.post('/web-thicong/hoancongmegawan/sp_lay_luong_thaotac',data),
  sp_lay_huonggiao_theo_quytrinh: async (axios,data) => axios.post('/web-thicong/hoancongmegawan/sp_lay_huonggiao_theo_quytrinh',data),
  sp_lay_ds_quytrinh_v2: (axios, data) => axios.post('/web-thicong/thanhly-thuebao/sp_lay_ds_quytrinh_v2', data),
  sp_lay_ds_phieu_giao_den: async (axios,data) => axios.post('/web-thicong/hoancongmegawan/sp_lay_ds_phieu_giao_den',data),
  lay_ds_thamso_md_mats: async (axios, req) => axios.post('/web-hopdong/chuyen-dich-ban-cheo/lay_ds_thamso_md_mats', req),
  get_keys: (axios, data) => axios.post('/web-quantri/donvitinh/get_keys', data),
}