trang_bi = select trangbi_id ID, tentrangbi NAME, trangbi_id CODE from TRANGBI
trang_bi.type = select
loaihinh_thuebao = select loaitb_id ID, ma_lhtb CODE, loaihinh_tb NAME from css_hpg.loaihinh_tb
loaihinh_thuebao.type = select
dum = select 1 ID, '$so_tb' CODE, '${name.toUpperCase()}' NAME from dual
dum.type = select