export enum OSSUARY_ROOM {
  USAGE_INFORMATION = 'USAGE_INFORMATION',
  USAGE_HISTORY = 'USAGE_HISTORY',
  SETTLEMENT_HISTORY = 'SETTLEMENT_HISTORY',
}

export enum PLACE_STATUS {
  CHECK_OUT = 'CHECK_OUT',
  CHECK_IN = 'CHECK_IN',
}
