var state = {
    button: {
        nhapmoi: false,
        ghilai: false,
        xoa: false,
        xoatb: false,
        huybo: false,
        themtt: false,
        themtb: false,
        themtb_ds: false,
        thanhtoan: false,
        HTHS: false,
        inhd: false,
        giaophieu: false,
        lienhe: true,
        themtt: false,
        xoatt: false
    },
    header: {
        title: "Tách, Ghép hóa đơn thuê bao",
        list: [
            { name: "Lập hợp đồng", link: { name: "Ui.cards" } },
            {
                name: "Lắp đặt mới",
                link: { name: "Ui.buttons" },
            },
        ],
    },
    collumnDSHD: [
        {
            fieldName: "hdtb_id",
            headerText: "STT",
            allowSorting: false,
            width: "60",
            textAlign: 'center',
            autoFit: "true",
        },
        {
            fieldName: "ma_tt",
            headerText: "Mã thanh toán",
            allowSorting: false,
            textAlign: 'center',
            autoFit: "true",
        },
        {
            fieldName: "ten_tt",
            headerText: "Tên thanh toán",
            allowSorting: false,
            textAlign: 'center',
            autoFit: "true",
        },
        {
            fieldName: "diachi_tt",
            headerText: "Địa chỉ thanh toán",
            allowSorting: false,
            textAlign: 'center',
            autoFit: "true",
        },
        {
            fieldName: "diachi_ct",
            headerText: "Địa chỉ chứng từ",
            allowSorting: false,
            textAlign: 'center',
            autoFit: "true",
        }
    ],
    collumnDSTB: [
        {
            fieldName: "hdtb_id",
            headerText: "STT",
            allowSorting: false,
            width: "60",
            textAlign: 'center',
            autoFit: "true",
        },
        {
            fieldName: "ma_tb",
            headerText: "Số máy/Acc",
            allowSorting: false,
            textAlign: 'center',
            autoFit: "true",
        },
        {
            fieldName: "ten_tb",
            headerText: "Tên thuê bao",
            allowSorting: false,
            textAlign: 'center',
            autoFit: "true",
        },
        {
            fieldName: "diachi_ld",
            headerText: "Địa chỉ lắp đặt",
            allowSorting: false,
            textAlign: 'center',
            autoFit: "true",
        },
        {
            fieldName: "ten_dvvt",
            headerText: "Dịch vụ VT",
            allowSorting: false,
            textAlign: 'center',
            autoFit: "true",
        },
        {
            fieldName: "ten_kieuld",
            headerText: "Kiểu lắp đặt",
            allowSorting: false,
            textAlign: 'center',
            autoFit: "true",
        },
        {
            fieldName: "trangthai_dongbo",
            headerText: "Trạng thái",
            allowSorting: false,
            textAlign: 'center',
            autoFit: "true",
        },
    ],
    ds_tien_khoanmuc: null,
    m_dsThueBao_DichVu: [],
    options: {
        dichvuVT: [],
        loaihinhTB: [],
        doituong: [],
        nganhang: [],
        hinhthucTT: [],
        loaiDV: [],
        dsThuebao: [],
        dsHopdong: [],
        thanhtoan: []
    },
    diachi: {
        apbc_id: 0,
        apkh_id: 0,
        apld_id: 0,
        aptb_id: 0,
        aptt_id: 0,
        dacdiembc_id: 0,
        dacdiemkh_id: 0,
        dacdiemld_id: 0,
        dacdiemtb_id: 0,
        dacdiemtt_id: 0,
        diachibc_id: 0,
        diachikh_id: 0,
        diachild_id: 0,
        diachitb_id: 0,
        diachitt_id: 0,
        khubc_id: 0,
        khukh_id: 0,
        khuld_id: 0,
        khutb_id: 0,
        khutt_id: 0,
        phobc_id: 0,
        phokh_id: 0,
        phold_id: 0,
        photb_id: 0,
        phott_id: 0,
        phuongbc_id: 0,
        phuongkh_id: 0,
        phuongld_id: 0,
        phuongtb_id: 0,
        phuongtt_id: 0,
        quanbc_id: 0,
        quankh_id: 0,
        quanld_id: 0,
        quantb_id: 0,
        quantt_id: 0,
        sonhabc: 0,
        sonhakh: "",
        sonhald: 0,
        sonhatb: 0,
        sonhatt: 0,
        tinhbc_id: 0,
        tinhkh_id: 0,
        tinhld_id: 0,
        tinhtb_id: 0,
        tinhtt_id: 0

    },
    thamso: {

    }
}

export default state