import moment from "moment"
export default {  
  DichVuVienThong: {
    TATCA: -1,
    CO_DINH: 1,
    DI_DONG: 2,
    ADSL: 4,
    DD_TRATRUOC: 5,
    EMAIL: 6,
    METRONET: 7,
    MEGAWAN: 8,
    TSL: 9,
    GPHONE: 10,
    IMS: 11,
    MEGA_EYES: 12,
    HOINGHI_TRUYENHINH: 13,
    ANTOAN_BAOMAT_TT: 14,
    DICHVU_CNTT: 15,
    TRUNGTAM_DULIEU: 16,
    HATANG_VIENTHONG: 19,

    IMS_DOITAC: 21,
    BRCD_DOITAC: 22,
    MGW_DOITAC: 23,
    TSL_DOITAC: 24
  },
  LOAI_NODE:[    
    {loainode_id: 1, loainode:'Node chính'},
    {loainode_id: 2, loainode:'Node phụ'},
    {loainode_id: 3, loainode:'Node dự phòng cổng + tốc độ'},
    {loainode_id: 4, loainode:'Node dự phòng tốc độ'},
  ],
  LoaiHinhTB :
    {
      DIENTHOAI_CD : 1,
      TRUNGKE_THUONG : 3,
      TRUNGKE_TUONGTU : 4,
      TRUNGKE_2M : 5,// Có số chính, số phụ
      PABX : 8,
      MAIL_SMD : 9,
      INTERNET : 10,
      INTERNET_1260 : 10,
      MEGA : 11,
      INTERNET_ADSL : 11,//Hiếu bổ sung ngày 25/08/2010
      Web_Hosting : 12,
      EMAIL : 13,
      ISDN2B_CD : 14,//megawan cổng FE
      ISDN30B_CD : 15,//megawan cổng GE
      ISDN2B_CQ : 16,
      ISDN30B_CQ : 17,
      HTVC_FIBERVNN_ANALOG : 18,
      HTVC_FIBERVNN_DIGITAL : 19,
      DIDONGTRASAU : 20,
      DIDONGTRATRUOC : 21,
      LEASEDLINE : 22,//Hiếu bổ sung ngày 29/08/2010
      MEGAWAN_ADSL : 23,
      FSECURE : 24,
      MEGAWAN_SHDSL : 25,
      MEGAWAN_QUANG_FE : 26,
      METRONET_FE : 27,
      METRONET_GE : 28,
      MEGAWAN_QUANG_GE : 30,
      MEGACAMERA : 31,
      GPHONE : 32,
      GPHONE_TRATRUOC : 34,
      IOFFICE : 35,
      TD_1800 : 38,
      VNPT_COLOCATION : 39,
      INTERNET_ADSL_TINH_KHAC : 57,
      INTERNET_FTTH : 58,
      INTERNET_FIBER_TINH_KHAC : 59,
      INTERNET_MYTV : 61,//B2C
      INTERNET_MYTV_B2B : 171,
      IMS_POTS : 62,
      IMS_SIP : 63,
      IMS_RGW : 64,
      INTERNET_SGTV : 65,
      CAMERA_HOCDUONG : 70,
      MEGAWAN_ADSL_2M : 74,
      METRONET_2FE : 75,
      MEGA_CONFERENCE : 76,
      IMS_SIPTRUNKING : 77,
      SSL : 78,
      WIFI_FIBER : 79,//Hiếu bổ sung ngày 10/01/2017
      VNPT_MEETING : 89,
      HNTH_NGN : 90,
      KTR_Leasedline_GE : 96,
      KTR_Leasedline_E1 : 97,
      KTR_Leasedline_STM1 : 98,
      KTR_Leasedline_nx64k : 99,
      KTR_TRUCTHONG_DONG : 100,
      KTR_TRUCTHONG_QUANG : 101,
      KTR_DOICAP_QUANG : 102,
      KTR_DOICAP_DONG : 103,
      KTR_Leasedline_FE : 104,
      KTR_Nail_up : 105,
      CDN : 112,
      CA : 116,
      CA_IVAN : 117,
      VN_EDU : 118,
      VNPT_PORTAL : 120,
      TTDL_HDDT : 122,
      TTDL_MAIL_OFFICE : 124,
      TD_1900 : 127,
      BRANDNAME : 131,
      IVAN : 132,
  
      DEDICATED_SERVER : 139,
      TDTH_THUYENHINH : 146,
      VCC : 149,
      MGW_INTERNET_TRUCTIEP : 134,
      COSO_HATANG : 158,
      CAPQUANG_TRANG_TSL : 123,
      MEGAEYES_CLOUD_CAMERA : 83,
      WIFI_MESH : 210,
      INDOOR_CAM : 222,
      OUTDOOR_CAM : 224,
      TIVI_SAMSUNG : 266,
  
      IMS_DT : 228,
      BRCD_FBDT : 229,
      BRCD_THDT : 230,
      MGW_DT : 231,
      TSL_DT : 232,
  
  
      // nhóm dịch vụ CNTT
      ECABINET : 200,
      ELEARNING : 208,
      ORM : 160,
      VXP : 235,
      VNPT_HIS : 136,
      VNPT_HMIS : 156,
      BIENLAIDT : 175,
      VNPT_MCAP : 267,
      VNPT_HCSN : 202,
      VNPT_SMART_TOURIST : 223,
      VNPT_SMCC : 268,
      VEDU_LIB : 205,
      VNPT_SLL : 215,
      VNPT_LIS : 261,
    },
  kieugoi_id:0,
  Tag:'',
  initDVVTArr:'',
  initLoaiHdArr:'',
  ThHdId:'',
  DONVIQL_HTTT:0,
  TUYENTHU_HTTT:0,
  DN_KHONG_THU_TAI_DIACHILD:-1,
  THONGBAO_TRACUU:0,
  kycuoc:null,
  chuky:null,
  kyhoadon:null,
  phantap_kh:false,
  ht_khl:0,
  kt_kylai: true,//Biến kiểm tra xem khách hàng đã ký lại hợp đồng chưa, defaule=true: đã ký lại
  khachhang_id:0,
  hdkh_id:0,
  loaikh_id:0,
  load_nvtc:true,
  pt_diem_tn:0,
  pt_doanhthu:0,    
  searchTerm:null,
  totalRecords: 0,
  isClick: false,
  visibles: {
    tsbtnGhiLai : false,
    tsbtnHuyBo  : false,
    tsbtnNhapMoi:  false,
    tsbtnToaNha : false,
    btnKhuvuc:true,
    
  },
  dataDiachi:{},
  dataPopupThietbiIDC:[],
  form: {

  },
  options:{
    cbx_dsloaigt:[],
    cbx_quoctich:[],
    cbx_nganhnghe:[],
    cbx_dantoc:[],
    cbx_loaikh:[],
    cbx_nganhang:[],
    //thanh toán
    cbx_nganhangtt:[],
    cbx_donvitt:[],
    cbx_httt:[],
    cbx_thuebao_dd:[], //load riêng
    //thuebao
    cbx_loaihd:[],
    cbx_dichvuvt:[],
    cbx_kieuld:[],
    cbx_muccuoctb:[],
    tmp_cbx_muccuoctb:[],
    cbx_thanhtoan:[], //load theo thuê bao
    cbx_loaihinh:[],
    cbx_doituong:[],
    cbx_trangbi:[],
    cbx_donvi:[],	
    
    //db_adsl
    cbx_muccuoc:[],
    cbx_tocdo:[],
    cbx_tocdothuc:[],
    cbx_tothicong:[],
    cbx_bras:[],
    cbx_dslam:[],
    cbx_loaicap:[],

    //dbims
    cbx_thietbi_ims:[],
    //db tsl
    cbx_loaikenh:[],
    cbx_loaitb:[],
    cbx_doitac:[],
    cbx_donvi_dau:[],
    cbx_donvi_cuoi:[],
    cbx_tocdo_kenh:[],
    cbx_chuquan:[],
    //db mgwan
    cbx_loai_modem:[],
    cbx_loainode:[], //để ý lúc clear dữ liệu
    cbx_thoihan:[],

    //data
    data_phanloaikh:[],

    //combobox enable
    enables: {    
      cbx_dsloaigt:true,
      cbx_quoctich:true,
      cbx_nganhnghe:true,
      cbx_dantoc:true,
      cbx_loaikh:true,
      cbx_nganhang:true,
      //thanh toán
      cbx_nganhangtt:true,
      cbx_donvitt:true,
      cbx_httt:true,
      cbx_thuebao:true, //load riêng
      //thuebao
      cbx_loaihd:true,
      cbx_dichvuvt:true,
      cbx_kieuld:true,
      cbx_muccuoctb:true,
      cbx_thanhtoan:true, //load theo thuê bao
      cbx_loaihinh:true,
      cbx_doituong:true,
      cbx_trangbi:true,
      cbx_donvi:true,
    },
    //check
    chkquoctich:false,
    chkdantoc:false,
    chknganhang_kh:false,
    chknganhang_tt:false,
  },
  title:{
    title_sl:null,
  },
  form_TTKH:{
    ma_hd:null,
    ngaylap_hd:null,    
    ma_kh:null,
    ten_kh:null,
    diem_tn:null,
    diachi_kh:null,
    loaigt_id:0,
    so_gt:null,
    ngaycap:null,
    noicap:null,
    ngayhethan_gt:null,
    ngay_sn:null,
    gioitinh:null,
    quoctich_id:0,
    nganhnghe_id:0,
    dantoc_id:0,
    loaikh_id:0,
    phanloai_kh:null,
    nguoi_dd:null,
    chucdanh:null,
    diachi_ndd:null,
    so_dt:null,
    so_fax:null,
    hokhau:null,
    noicap_hk:null,
    ngay_hk:null,
    nganhang_id:0,
    mst:null,
    stk:null,
    dactrung:null,
    ghichu:null,
    d_tieunganh:{
      TNC1_ID:0,
      TNC2_ID:0,
      TNC3_ID:0,
      TNC4_ID:0,
    },    
    d_diachi_kh:{
      tinh_id : 0,
      quan_id : 0,
      phuong_id : 0,
      pho_id : 0,
      ap_id : 0,
      khu_id : 0,
      dacdiem_id : 0,
      sonha : null,
      so_nha : null,
      kinhdo:null,
      vido:null,
      block:null,
      tang:null,
      phong:null,
      mota:null,
    },
    d_diachi_ndd:{
      tinh_id : 0,
      quan_id : 0,
      phuong_id : 0,
      pho_id : 0,
      ap_id : 0,
      khu_id : 0,
      dacdiem_id : 0,
      sonha : null,
      so_nha : null,
      kinhdo:null,
      vido:null,
      block:null,
      tang:null,
      phong:null,
      mota:null,
    }
    
  },
  form_TTTT:{
    ma_tt:null,
    matb_dd:null, //load danh sách cho vào combobox
    matt_ccbs:null,
    ten_tt:null,
    diachi_tt:null,
    diachi_ct:null,
    diachi_bc:null,
    main_ghep:null,
    httt_id:0,
    nganhang_id:0,
    chu_tk:null,
    ghichu:null,
    email:null,
    donvi_id:0,
    manv_tc:null,
    ma_tuyen:null,
    stk:null,
    mst:null,
    ma_nvql:null,
    so_dt:null,
    dv_khac:null,
    d_diachi_tt:{
      tinh_id : 0,
      quan_id : 0,
      phuong_id : 0,
      pho_id : 0,
      ap_id : 0,
      khu_id : 0,
      dacdiem_id : 0,
      sonha : null,
      kinhdo:null,
      vido:null,
      block:null,
      tang:null,
      phong:null,
      mota:null,
    },
    d_diachi_ct:{
      tinh_id : 0,
      quan_id : 0,
      phuong_id : 0,
      pho_id : 0,
      ap_id : 0,
      khu_id : 0,
      dacdiem_id : 0,
      sonha : null,
      so_nha : null,
      kinhdo:null,
      vido:null,
      block:null,
      tang:null,
      phong:null,
      mota:null,
    },
    d_diachi_bc:{
      tinh_id : 0,
      quan_id : 0,
      phuong_id : 0,
      pho_id : 0,
      ap_id : 0,
      khu_id : 0,
      dacdiem_id : 0,
      sonha : null,
      so_nha : null,
      kinhdo:null,
      vido:null,
      block:null,
      tang:null,
      phong:null,
      mota:null,
    }
  },
  form_TTTB:  {
    phanvung_id:0,
    loaihd_id:0, //TODO load theo kiểu LĐ
    dichvuvt_id:0,
    kieuld_id:0,
    mucuoctb_id:0,
    ma_tb:null,
    thanhtoan_id:0,
    ten_tb:null,
    trangthai_tb:null,
    loaitb_id:0,
    khuvuc:null,
    khuvuc_id:0,
    doituong_id:0,
    ma_lt:null,
    ngay_sn:null,
    diachi_tb:null,
    diachi_ld:null,
    donvi_id:0,
    ma_dhvip:null,
    ghichu:null,
    sothang_ck:null,
    ngay_ktck:null,
    dv_khac:null, //load riêng
    dv_congthem:null, //load riêng
    ngay_sd:null,
    cuoc_tb:null,
    trangbi_id:0,
    goi_kt:null,  //load tùy theo dịch vụ
    cuoc_dv:null,
    soluong:null, //load tùy theo dịch vụ
    khuvuc_id_cuoi:0,   
    dataPopupKhuVuc:{
      quan_id:0,
      phuong_id:0,
      pho_id:0,
      ap_id:0,
      khu_id:0,
      dacdiem_id:0,
      khuvuc_id:0,
      donviql_id:0,
      hdtb_id:0
    },
    dataPopupNVDB:[],
    d_diachi_tb:{
      tinh_id : 0,
      quan_id : 0,
      phuong_id : 0,
      pho_id : 0,
      ap_id : 0,
      khu_id : 0,
      dacdiem_id : 0,
      sonha : null,
      so_nha : null,
      kinhdo:null,
      vido:null,
      block:null,
      tang:null,
      phong:null,
      mota:null,
    },
    d_diachi_ld:{
      tinh_id : 0,
      quan_id : 0,
      phuong_id : 0,
      pho_id : 0,
      ap_id : 0,
      khu_id : 0,
      dacdiem_id : 0,
      sonha : null,
      so_nha : null,
      kinhdo:null,
      vido:null,
      block:null,
      tang:null,
      phong:null,
      mota:null,
    },
    db_con: {
      email:"",
      donvi_id: 0,
      bras_id: 0,
      dslam_id: 0,
      tocdo_id: 0,
      tocdothuc_id: 0,
      muccuoc_id: 0,
      chuquan_id: 0,
      loainode_id: 1,
      doitac_id: 0,
      tocdo_pir_id: 0,
      tocdocir_id: 0,
      loaikenh_id: 0,
      loaimd_id: 0,
      thoihan_id: 0,
      quoctich_id: 0,
      tocdokenh_id: 0,
      thietbid_id: 0,
      trangbi_id: 0,
      cuoc_dv: 0,
      username: "",
      password: "",
      slot: "",
      port: "",
      rack: "",
      shelf: "",
      vpi: "",
      vci: "",
      loaicap_id: 0,
      tucap_goc: "",
      doicap_goc: "",
      cap_goc: "",
      hopcap_p: "",
      tucap_p: "",
      doicap_p: "",
      cap_ngon: "",
      cap_p:"",
      tendslam: "",
      tuyencap: "",
      lientu: "",
      culy: "",
      thietbi_id: 0,
      system: "",
      email: "",
      ip_dslam: "",
      nasportid: "",
      port_mdf: "",
      adsl_port: "",
      onu_password: "",
      ip: "",
      matb_tn: "",
      congnghe: "",
      mac_addr: "",
      diachi_pop: "",
      soluong: 0,
      cuoc_tk: 0,
      cuoc_tc: 0,
      cuoc_ht: 0,
      cuoc_tbi: 0,
      cuoc_tkdt: 0,
      cuoc_tcdt: 0,
      cuoc_isp: 0,
      cuoc_nix: 0,
      cuoc_ip: 0,
      mahd_dt: "",
      diachi_dau: "",
      diachi_cuoi: "",
      donvi_id_dau: 0,
      donvi_id_cuoi: 0,
      site_id_dau: 0,
      site_id_cuoi: 0,
      khuvuc_id_dau: 0,
      khuvuc_id_cuoi: 0,
      khuvuc_dau: "",
      khuvuc_cuoi: "",
      huong_kn: "",
      huong_ut: "",
      vmp: 0,
      vmp_checked: false,
      capngoai: 0,
      luonggiua: 0,
      mahd_dt: "",
      ne: "",
      sochinh: "",
      simcard: "",
      sodu_tk: 0,
      goicuoc_id: 0,
      madoicap: "",
      mc_tbgp_id: "",
      toado: "",
      cell1: "",
      tramtb_id:0,
      tram_ne:"",
      tengoicuoc:"",
      thietbidc_id:0, //tsl
	    huongketnoi_megawan:"",
	    vrf:"",
      capngoai_vnpt:"",
	    site_id:0,
      giu_kenh:false,
      quocgia_pop:0,
      infoDBTB:"",
    },
    dsThuocTinhHDTB_CNTT: [],
  },
  gvDSTT: {
    list: [],
    header: [
      {
        fieldName: "so_tt",
        headerText: "STT",
        allowSorting: false,
        width: "40",
        textAlign: 'center',
        autoFit: "true",
        allowFiltering: true
      },
      {
        fieldName: "ma_tt",
        headerText: "Mã TT",
        allowSorting: false,
        width: "100",        
        autoFit: "true",
        allowFiltering: true
      },
      {
        fieldName: "ten_tt",
        headerText: "Tên thanh toán",
        allowSorting: false,
        width: "100",        
        autoFit: "true",
        allowFiltering: true
      },
      {
        fieldName: "diachi_tt",
        headerText: "Địa chỉ thanh toán",
        allowSorting: false,
        width: "100",
        autoFit: "true",
        allowFiltering: true
      },
      {
        fieldName: "diachi_ct",
        headerText: "Địa chỉ chứng từ",
        allowSorting: false,
        width: "100",
        autoFit: "true",
        allowFiltering: true
      }
    ]
  },
  gvDSTB: {
    list: [],
    header: [
      {
        fieldName: "ma_tt",
        headerText: "Mã TT",
        allowSorting: false,
        width: "100",        
        autoFit: "true",
        allowFiltering: true
      },
      {
        fieldName: "ma_tb",
        headerText: "Số máy/Acc",
        allowSorting: false,
        width: "100",        
        autoFit: "true",
        allowFiltering: true
      },
      {
        fieldName: "ma_lt",
        headerText: "Số ảo",
        allowSorting: false,
        width: "100",        
        autoFit: "true",
        allowFiltering: true
      },
      {
        fieldName: "ten_tb",
        headerText: "Tên thuê bao",
        allowSorting: false,
        width: "100",        
        autoFit: "true",
        allowFiltering: true
      },
      {
        fieldName: "diachi_ld",
        headerText: "Địa chỉ lắp đặt",
        allowSorting: false,
        width: "100",        
        autoFit: "true",
        allowFiltering: true
      },
      {
        fieldName: "ngay_sd",
        headerText: "Ngày sử dụng",
        allowSorting: false,
        width: "100",
        format: {type: 'date', format: 'dd/MM/yyyy'},
        type: 'date',
        textAlign: 'right',
        autoFit: "true",
        allowFiltering: true
      },
      {
        fieldName: "chuquan",
        headerText: "Chủ quản",
        allowSorting: false,
        width: "100",        
        autoFit: "true",
        allowFiltering: true
      },
      {
        fieldName: "splitter",
        headerText: "Splitter",
        allowSorting: false,
        width: "100",        
        autoFit: "true",
        allowFiltering: true
      },
      {
        fieldName: "ma_vip",
        headerText: "Mã VIP",
        allowSorting: false,
        width: "100",        
        autoFit: "true",
        allowFiltering: true
      },
      {
        fieldName: "ten_cksd",
        headerText: "Tên CKSĐ",
        allowSorting: false,
        width: "100",        
        autoFit: "true",
        allowFiltering: true
      },
      {
        fieldName: "sothang_cksd",
        headerText: "Số tháng CKSĐ",
        allowSorting: false,
        width: "100",
        textAlign: 'right',
        autoFit: "true",
        allowFiltering: true
      }
    ]


  },
}
