const DichVuVienThong={
    TATCA:-1,
    CO_DINH:1,
    DI_DONG:2,
    ADSL:4,
    DD_TRATRUOC:5,
    EMAIL:6,
    METRONET:7,
    MEGAWAN:8,
    TSL:9,
    GPHONE:10,
    IMS:11,
    MEGA_EYES:12,
    HOINGHI_TRUYENHINH:13,
    ANTOAN_BAOMAT_TT:14,
    DICHVU_CNTT:15,
    TRUNGTAM_DULIEU:16,
    HATANG_VIENTHONG:19,
    IMS_DOITAC:21,
    BRCD_DOITAC:22,
    MGW_DOITAC:23,
    TSL_DOITAC:24
}
const LoaiHinhTB={
    INTERNET_1260:10,
    INTERNET_ADSL:11,
    INTERNET_FTTH:58,
    INTERNET_MYTV:61,
    INTERNET_SGTV:65,
    INTERNET_FIBER_TINH_KHAC: 59,
    INTERNET_ADSL_TINH_KHAC:57

}
const TRANGTHAI_DONGBO={
    DONGBO_CM: 5,
    DONGBO_HT: 6
}
const DONGBO_TEST={
    TEST:false
}

const KieuLapDat={
    HA_TOCDO_DUYTRI: 14,
    NANG_TOCDO:15
}

export {
    DichVuVienThong,
    LoaiHinhTB,
    TRANGTHAI_DONGBO,
    DONGBO_TEST,
    KieuLapDat
}