spring:
  application:
    name: app-cskh
  profiles:
    active: prod
  defaultconfigs:
    database: css_hpg
    executor-database: css
    sqli:
      normal-length: 400
      max-length: 9000
      number-of-long-parameter: 2
    crypto_key: ${crypto_key:x}
    dhsx_img_url: ${dhsx_img_url:10.165.11.174}
  databases:
    css:
      url: ${css_url:jdbc:oracle:thin:@10.165.33.26:1521/PDB_ONEBSS}
      username: ${css_usr:css}
      password: ${css_pwd:itEnhWy!Qxbb}
      max-pool-size: ${css_max:200}
      minimum-idle: ${css_min:2}
      max-lifetime: ${css_max_lifetime:180000}
  httpservices:
    vnptpay:
#      url: ${pay_url:http://10.156.4.86:9092/mediagw/g/}
#      username: ${pay_username:onebss}
#      password: ${pay_password:admin}
      url: ${pay_url:http://10.156.4.85/mediagw/g/}
      username: ${pay_username:onebss}
      password: ${pay_password:admin}
    mnp:
      url: ${mnp_url:http://10.156.3.100:4001/mapi/services/}
    smcs:
      url: ${smcs_url:https://smcsapi.vnpt.vn/mapi/g}
    vnptinvoice:
      url: ${vnptinvoice_url:https://hcmservicetest2.vnpt-invoice.com.vn/}
      publicservice:
        path: PublishService.asmx
        usr: hcmservice
        pwd: 123456aA@
        acc: hcmadmin
        acc-pwd: 123456aA@
      bizservice:
        path: BusinessService.asmx
        usr: hcmservice
        pwd: 123456aA@
        acc: hcmadmin
        acc-pwd: 123456aA@
      portalservice:
        path: PortalService.asmx
        usr: hcmservice
        pwd: 123456aA@
        acc: hcmadmin
        acc-pwd: 123456aA@
  object-storages:
    onebss-develop:
      host: ${obj_storage_host:storage-onebss.vnpt.vn}
      port: ${obj_storage_port:443}
      protocol: ${obj_storage_protocol:https}
      username: ${obj_storage_access_key:minio}
      password: ${obj_storage_secret_key:bWluaW8tZXJwLW9uZWJzcwo=}
      default-location: ${obj_storage_default_bucket:onebss-production}
      extras:
        region: ${obj_storage_region:us-east-1}
    minio-storage:
      host: ${obj_storage_url:https://minio.vnptit3.vn}
      protocol: ${obj_storage_protocol:https}
      username: ${obj_storage_access_key:minioit3}
      password: ${obj_storage_secret_key:minioit3it3IT3IT3IT3}
      bucket: ${obj_storage_bucket:onebss-develop}
      default-location: ${obj_storage_default_bucket:onebss-develop}
      extras:
        region: ${obj_storage_region:us-east-1}
  ftps:
    vnpDktt:
      host: localhost
      port: 21
      protocol: ftp
      username: ${ftp_vnp_usr:admin}
      password: ${ftp_vnp_pwd:adminadmin}
      default-location: ${ftp_vnp_default_location:dktt}
      extras:
        #epsv: true
        #pasv: true
        #mode: local-passive
        file-type: 2 #binary
        #format-or-byte-size: -1
        #file-transfer-mode: -1
  jackson:
    date-format: dd/MM/yyyy HH:mm:ss
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  zalo:
    hpg:
      access-token: arHfDlEA7rgMLcmyyeyQMvLSQZFmc5HPx2TdQDw7HthN0ZPspzWWJl5ZDJp1n1S9zbaa0Cxv0ZtANpOezEebHjPYA4t9uozDx7ikGulG236EQHixhjKlLAbe1Mcs-pL5iYT4RulWDc6JMq9zYUPyLvjlJ5oPq7nBXc90997YQm-2IXOraf5g4g0S7Xw7Wmfug10cRf_D06Y8VWOEXEOw08OXA2ZfyWiG-I0h5kEXDNlI1Xjtu9aKV-ym4NIEb3fUu3zDU8A_PK3dBL4gqAHVEia2Lb3pstvYQLRgH5_sa1zU
      oa-id: 1539782949193229694
      secret-key: BXBt4n8NefCF5qMXes1U
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
server:
  port: ${PORT_DEBT:8088}
  tomcat:
     accesslog:
        enabled: true
        directory: /dev
        prefix: stdout
        suffix:
        file-date-format:
  app-secret: ${app-secret:eyJkZXZpY2VfaWQiOiI2MUVDNDg2RS02RUE2LTQ0OTUtQkRBRS0xQkFDMDExRjQzMDAiLCJkZXZpY2VfaXAiOiJlcnJvciIsImRldmljZV9uYW1lIjoiaVBob25lIC0gaVBob25lIDEyIFBybyBNYXgiLCJtYWNfYWRkcmVzcyI6IlVua25vdyIsIm1vYmlsZV9pZCI6IlVua25vdyIsImFwcF9pZCI6IjIiLCJhcHBfdmVyc2lvbiI6IjIuNC4xLjQwIiwib3NfdmVyc2lvbiI6ImlPUyAtIDE0LjUifQ==}
object-storage:
  enabled: ${obj_storage_enabled:true}
  url: ${obj_storage_url:http://localhost:9001}
  access-key: ${obj_storage_access_key:admin}
  secret-key: ${obj_storage_secret_key:adminadmin}  
logging:
  mode: ${fluentd_mode:fluentd}
  #mode: local
  fluentd:
    tag: ${fluentd_tag:VNPTIT.ERP.ONE_APP_DEBT_TEST}
    host: ${fluentd_host:10.159.28.112}
    port: ${fluentd_post:24224}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
---
eureka:   #<1>
  instance:
    lease-renewal-interval-in-seconds: ${lease_renewal:5}
    lease-expiration-duration-in-seconds: ${lease_expiration:15}
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
#---
#logging:
#  level:
#    root: WARN
---
eureka:
  instance:
    ip-address: ${CLIENT_IP_ADDRESS:local.idg.vnpt.vn}
    prefer-ip-address: ${PREFER_IP_ADDRESS:false}
    hostname: ${HOSTNAME:auth-service}
---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    discovery:
      enabled: false
  redis:
    host: localhost
    port: 6379
logging:
  mode: local
  fluentd:
    tag: ${fluentd_tag:VNPTIT.ERP.ONE_APP_THICONG}
    host: ${fluentd_host:10.159.28.112}
    port: ${fluentd_post:24224}
---
spring:
  config:
    activate:
      on-profile: prod
logging:
  mode: ${fluentd_mode:fluentd}
  #mode: local
  fluentd:
    tag: ${fluentd_tag:VNPTIT.ERP.ONE_APP_THICONG}
    host: ${fluentd_host:10.159.28.112}
    port: ${fluentd_post:24224}
---
spring:
  config:
    activate:
      on-profile: prod
  cache:
    type: redis
#    redis:
#      time-to-live: 20000000
  redis:
    cluster:
      nodes:
        - ${REDIS_URL1:10.165.24.35:31891}
        - ${REDIS_URL2:10.165.24.31:30456}
        - ${REDIS_URL3:10.165.24.28:30638}
        - ${REDIS_URL4:10.165.24.30:30953}
        - ${REDIS_URL5:10.165.24.34:31429}
        - ${REDIS_URL6:10.165.24.36:31150}
      max-redirects: 3
    database: ${REDIS_DATA:0}
    password: ${REDIS_PASSWORD:vnptRedis2021}
    lettuce:
        pool:
          max-active: 7
          max-idle: 7
          min-idle: 2
          max-wait: -1ms
        shutdown-timeout: 200ms
--- 
management:
  endpoint:
    health:
      show-details: never
  health:
    db:
      enabled: false
    redis:
      enabled: false       
---
internal:
  esb:
    url: ${esb_url:http://esb}
    token-key: ${esb_token_key:c3a29ef8edab977cb2ab43e68d759f9b1}
    token-id: ${esb_token_id:NET_XLSC}
  tichhop:
    url: ${tichhop_url:http://tichhop}
  app-com:
    url: ${app_com_url:http://app-com}
external:
  tts-url: ${tts_url:https://tts.vnpt.vn/ws/api/APIDHSXKD/SaveCSSAPI}
---
