export default {
  fn_xuat_hddt_tq_load: (axios, body) => axios.post('web-ccdv/hoadondientu/fn_xuat_hddt_tq_load', body),
  sp_lay_ds_seri_dientu_v2: (axios, body) => axios.post('web-ccdv/thanhtoan/sp_lay_ds_seri_dientu_v2', body),
  xuatHddtTQHienThiThongTinHopDong: (axios, body) => axios.post('web-ccdv/hoadondientu/fn_xuat_hddt_tq_hienthi_thongtin_hopdong', body),
  getThongTinNganHang: (axios, body) => axios.post('web-tratruoc/thongtin_tratruoc_dn/fn_tt_nganhang', body),
  xuatHddtTQHienThiThongTin: (axios, body) => axios.post('web-ccdv/hoadondientu/fn_xuat_hddt_tq_hienthi_thongtin', body),
  xuatHddtTQCapNhat: (axios, body) => axios.post('web-ccdv/hoadondientu/fn_fn_xuat_hddt_tq_capnhat', body),
  listInvByCus: (axios, body) => axios.post('tichhop/vnptinvoice/listInvByCus', body),
  downloadInvNoPay: (axios, body) => axios.post('tichhop/vnptinvoice/downloadInvNoPay', body),
  UpdateCus: (axios, body) => axios.post('tichhop/vnptinvoice/updateCus', body),
  sinh_ma_kh_hddt: (axios, kieu) => axios.get(`web-ccdv/thanhtoan/sinh_ma_kh_hddt?kieu=${kieu}`),
  importAndPublishInv: (axios, body) => axios.post('tichhop/vnptinvoice/importAndPublishInv', body),
  sinh_fkey: (axios, kieu) => axios.get(`web-ccdv/thanhtoan/sinh_fkey?kieu=${kieu}`),
  AdjustInvoiceAction: (axios, body) => axios.post('tichhop/vnptinvoice/adjustInvoiceAction', body),
  ReplaceInvoiceAction: (axios, body) => axios.post('tichhop/vnptinvoice/replaceInvoiceAction', body),
  cancelInv: (axios, body) => axios.post('tichhop/vnptinvoice/cancelInv', body),
  UnConfirmPaymentFkey: (axios, body) => axios.post('tichhop/vnptinvoice/unConfirmPaymentFkey', body),
  confirmPaymentFkey: (axios, body) => axios.post('tichhop/vnptinvoice/confirmPaymentFkey', body),
  convertForVerifyFkey: (axios, body) => axios.post('tichhop/vnptinvoice/convertForVerifyFkey', body),
  convertForStoreFkey: (axios, body) => axios.post('tichhop/vnptinvoice/convertForStoreFkey', body),
  convertForStore: (axios, body) => axios.post('tichhop/vnptinvoice/convertForStore', body),
  lay_ds_thamso_md: (axios) => axios.get('web-thicong/tientrinh_thicong/lay_ds_thamso_md'),
  getInvViewNoPay: (axios, body) => axios.post('tichhop/vnptinvoice/getInvViewNoPay', body),
  getInvViewFkeyNoPay: (axios, body) => axios.post('tichhop/vnptinvoice/getInvViewFkeyNoPay', body),
  getThongTinNguoiDung2: (axios) => axios.post('quantri/user/thongtin_nguoidung2', {}),
  getMachine: (axios) => axios.get('web-quantri/nguoidung/thongtin')
}
