const collumns = {
    collumnsSimphu: [
        {
            fieldName: "ma_tb",
            headerText: "Số máy",
            allowFiltering: true,
            width: "150",
            autoFit: "true",
            cellCssClass: 'text-left',
        },
        {
            fieldName: "sosim_phu",
            headerText: "Số sim phụ",
            allowFiltering: true,
            width: "100",
            textAlign: 'right',
            autoFit: "true",
            cellCssClass: 'text-left',
        },
        {
            fieldName: "ngay_dang_ky",
            headerText: "Ngày đăng ký",
            allowFiltering: true,
            width: "150",
            autoFit: "true",
            cellCssClass: 'text-left',
        },
        {
            fieldName: "trangthai_hd",
            headerText: "Trạng thái",
            allowFiltering: true,
            width: "180",
            autoFit: "true",
            cellCssClass: 'text-left',
        },
        {
            fieldName: "ghichu",
            headerText: "Ghi chú",
            allowFiltering: true,
            width: "150",
            autoFit: "true",
            cellCssClass: 'text-left',
        }
    ],
    collumnsThuebao: [
        {
            fieldName: "ma_gd",
            headerText: "Mã giao dịch",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            cellCssClass: 'text-left',
        },
        {
            fieldName: "ma_tb",
            headerText: "Số máy",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            cellCssClass: 'text-left',
        },
        {
            fieldName: "ten_tb",
            headerText: "Tên thuê bao",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            cellCssClass: 'text-left',
        },
        {
            fieldName: "ngay_cn",
            headerText: "Thời gian tạo",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            cellCssClass: 'text-left',
        },
        {
            fieldName: "diachi_tb",
            headerText: "Địa chỉ thuê bao",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            cellCssClass: 'text-left',
        },
        {
            fieldName: "trangthai_hd",
            headerText: "Trạng thái",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            cellCssClass: 'text-left',
        },
        {
            fieldName: "ghichu",
            headerText: "Ghi chú",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            cellCssClass: 'text-left',
        },
    ],
    collumnsPhieu: [
        {
            fieldName: "ma_tb",
            headerText: "Số máy/ACC",
            allowSorting: false,
            allowFiltering: true,
            width: "50",
            textAlign: 'center',
            autoFit: "true",
        },
        {
            fieldName: "ten_tb",
            headerText: "Tên thuê bao",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            textAlign: 'left',
        },
        {
            fieldName: "diachi_tb",
            headerText: "Địa chỉ thuê bao",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            textAlign: 'left',
        },
        {
            fieldName: "diachi_ld",
            headerText: "Địa chỉ lắp đặt",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            textAlign: 'left',
        },
        {
            fieldName: "ghichu",
            headerText: "Ghi chú",
            allowFiltering: true,
            width: "100",
            autoFit: "false",
            textAlign: 'left',
        },
    ],
}

export default collumns
