export default {
  getLastCall: async (axios, userCode) => axios.get(`/web-danhba/danhmuc/getLastCall?userCode=${userCode}`),
  getLastCall2: async (axios, userCode) => axios.get(`/web-ipcc/IPCCNotify/getLastCall?userCode=${userCode}`),
  sp_lay_user_ipcc_theo_nguoidung_id: async (axios, nguoidung_id) => axios.get(`/web-tracuu/tracuu/sp_lay_user_ipcc_theo_nguoidung_id?nguoidung_id=${nguoidung_id}`),
  sp_capnhat_cuocgoi_ipcc: async (axios, input) => axios.post(`/web-bancheo/tiepnhan_cuocgoi_tongdai/sp_capnhat_cuocgoi_ipcc`, input),
  sp_batdau_cuocgoi_ipcc: async (axios, input) => axios.post(`/web-bancheo/tiepnhan_cuocgoi_tongdai/sp_batdau_cuocgoi_ipcc`, input),
  sp_ketthuc_cuocgoi_ipcc: async (axios, input) => axios.post(`/web-bancheo/tiepnhan_cuocgoi_tongdai/sp_ketthuc_cuocgoi_ipcc`, input),
  sp_lay_ds_cuocgoi: async (axios, input) => axios.post(`/web-bancheo/tiepnhan_cuocgoi_tongdai/lay_ds_cuocgoi`, input),
  changeAgentState: (axios, data) => axios.post('/tichhop/ipcc/changeAgentState', data),
  changeAgentStateV2: (axios, data) => axios.post('/tichhop/ipcc/changeAgentStateV2', data),
  getListRecentCallByUser: (axios, data) => axios.post('/tichhop/ipcc/getListRecentCallByUser', data),
  setNode: (axios, data) => axios.post('/web-danhba/danhmuc/changeNodeIPCC', data),
  getNode: async (axios, userCode) => axios.get(`/web-danhba/danhmuc/getNodeIPCC?userCode=${userCode}`),
  getResultOBDetails:(axios, {vphanvung_id, vkhachhang_id}) => axios.post(`/web-tratruoc/ob_ghtt/sp_lay_ct_kqob_theo_khachhang_id`, {vphanvung_id, vkhachhang_id}),
}
