export enum ADVISORY_TYPE {
  ONE_ON_ONE = 'ONE_ON_ONE',
  FOCUS_GROUP = 'FOCUS_GROUP',
  USER_SURVEY = 'USER_SURVEY',
  WRITTEN_ADVISORY = 'WRITTEN_ADVISORY',
  CONSULTING_PROJECT = 'CONSULTING_PROJECT',
  TBC = 'TBC',
}
