export enum MEETING_FORMAT_ENUM {
  VIDEO_MEETING = 'VIDEO_MEETING',
  FACE_TO_FACE_MEETING = 'FACE_TO_FACE_MEETING',
}

export enum TIMESLOT_ENUM {
  MEETING = 'MEETING',
  TIME_SLOT = 'TIME_SLOT',
  FINAL_MEETING = 'FINAL_MEETING',
}
