const columns = {
    columnsImport: [
        {
            fieldName: "MA_NV",
            headerText: "MA_NV",
            allowSorting: true,
            allowFiltering: true,
            textAlign: 'left',
            width: "150px",
        },
        {
            fieldName: "SO_VI",
            headerText: "SO_VI",
            allowSorting: true,
            allowFiltering: true,
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "SO_TIEN",
            headerText: "SO_TIEN",
            allowSorting: true,
            allowFiltering: true,
            textAlign: 'right',
            width: "120px",
        },
        {
            fieldName: "NOI_DUNG",
            headerText: "NOI_DUNG",
            allowSorting: true,
            allowFiltering: true,
            textAlign: 'left',
            autoFit: "true",
        },
    ],
    columnsImportError: [
        {
            fieldName: "MA_NV",
            headerText: "MA_NV",
            allowSorting: true,
            allowFiltering: true,
            textAlign: 'left',
            width: "150px",
        },
        {
            fieldName: "SO_VI",
            headerText: "SO_VI",
            allowSorting: true,
            allowFiltering: true,
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "SO_TIEN",
            headerText: "SO_TIEN",
            allowSorting: true,
            allowFiltering: true,
            textAlign: 'right',
            width: "120px",
        },
        {
            fieldName: "NOI_DUNG",
            headerText: "NOI_DUNG",
            allowSorting: true,
            allowFiltering: true,
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "TRANGTHAI",
            headerText: "LỖI",
            allowSorting: true,
            allowFiltering: true,
            customAttributes: {class: 'cl_loi'},
            textAlign: 'left',
            autoFit: "true",
        },
    ],
    columnsDSLLCT: [
        {
            fieldName: "ma_nv",
            headerText: "MA_NV",
            allowSorting: true,
            allowFiltering: true,
            textAlign: 'left',
            width: "150px",
        },
        {
            fieldName: "ten_nv",
            headerText: "TEN_NV",
            allowSorting: true,
            allowFiltering: true,
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "so_vi",
            headerText: "SO_VI",
            allowSorting: true,
            allowFiltering: true,
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "so_tien",
            headerText: "SO_TIEN",
            allowSorting: true,
            allowFiltering: true,
            textAlign: 'right',
            width: "120px",
        },
        {
            fieldName: "noi_dung",
            headerText: "NOI_DUNG",
            allowSorting: true,
            allowFiltering: true,
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "trangthai",
            headerText: "Trạng thái",
            allowSorting: true,
            allowFiltering: true,
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "trangthai_ct",
            headerText: "Trạng thái CT",
            allowSorting: true,
            allowFiltering: true,
            textAlign: 'left',
            autoFit: "true",
        },
    ],
    columnsDSLL: [
        {
            allowHtml: true,
            fieldName: "view_ct",
            headerText: "",
            allowSorting: false,
            allowFiltering: false,
            textAlign: 'center',
            width: "50px",
        },
        {
            fieldName: "ma_luot",
            headerText: "Mã lượt",
            allowSorting: true,
            allowFiltering: true,
            textAlign: 'center',
            width: "150px",
        },
        {
            fieldName: "nd_duyet",
            headerText: "Nội dung",
            allowSorting: true,
            allowFiltering: true,
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "trangthai_luot",
            headerText: "Trạng thái",
            allowSorting: true,
            allowFiltering: true,
            textAlign: 'left',
            width: "120px",
        },
        {
            fieldName: "nhanvien_pd",
            headerText: "Người duyệt",
            allowSorting: true,
            allowFiltering: true,
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "ngay_duyet",
            headerText: "Ngày duyệt",
            allowSorting: true,
            allowFiltering: true,
            textAlign: 'center',
            autoFit: "true",
        },
        {
            fieldName: "nd_duyet",
            headerText: "ND duyệt",
            allowSorting: true,
            allowFiltering: true,
            textAlign: 'center',
            autoFit: "true",
        },
    ],
}

export default columns
