const GRID_COLUMS = {
  1: [	
	{fieldName: 'MA_KN', width : 200 , headerText: 'Mã khiếu nại', allowFiltering: true },
	{fieldName: 'NGAY_TN', width : 200 , textAlign: 'Center', headerText: 'Ngày tiếp nhận', allowFiltering: true},
	{fieldName: 'TEN_NV', width : 250 , headerText: 'Người tiếp nhận', allowFiltering: true},
	{fieldName: 'MA_TB', width : 150 , headerText: 'Số máy/Acc', allowFiltering: true },
	{fieldName: 'TEN_TB', width : 150 , headerText: 'Tên thuê bao', allowFiltering: true},
	{fieldName: 'MA_KH', width : 150 , headerText: 'Mã khách hàng', allowFiltering: true},
	{fieldName: 'TEN_DVVT', width : 150 , headerText: 'Dịch vụ', allowFiltering: true},
	{fieldName: 'LOAIHINH_TB', width : 150 , headerText: 'Loại hình', allowFiltering: true},
	{fieldName: 'NHOM_CHUDE', width : 150 , headerText: 'Nhóm chủ đề', allowFiltering: true},
	{fieldName: 'CHUDE_C1', width : 150 , headerText: 'Chủ đề cấp 1', allowFiltering: true},
	{fieldName: 'CHUDE_C2', width : 150 , headerText: 'Chủ đề cấp 2', allowFiltering: true},
	{fieldName: 'KN_LAPLAI', width : 150 , headerText: 'Khiếu nại lặp', allowFiltering: true},
	{fieldName: 'KN_VUOTCAP', width : 150 , headerText: 'Khiếu nại vượt', allowFiltering: true},
	{fieldName: 'KN_KHANCAP', width : 150 , headerText: 'Khiếu nại khẩn', allowFiltering: true},
	{fieldName: 'NGUOI_KN', width : 150 , headerText: 'Người khiếu nại', allowFiltering: true},
	{fieldName: 'DIENTHOAI_LH', width : 150 , headerText: 'Điện thoại LH', allowFiltering: true},
	{fieldName: 'DIACHI_LH', width : 150 , headerText: 'Địa chỉ LH', allowFiltering: true},
	{fieldName: 'HENGQ_TU', width : 150 , headerText: 'Hẹn từ', allowFiltering: true},
	{fieldName: 'HENGQ_DEN', width : 150 , headerText: 'Hẹn đến', allowFiltering: true},
	{fieldName: 'NGAY_CAMKET', width : 150 , headerText: 'Ngày cam kết', allowFiltering: true},
	{fieldName: 'GIO_CAMKET', width : 150 , headerText: 'Giờ cam kết', allowFiltering: true},
	{fieldName: 'ND_XULY', width : 250 , headerText: 'Kết quả xử lý', allowFiltering: true},
	{fieldName: 'NGAY_TRAPHIEU', width : 150 , headerText: 'Ngày trả', allowFiltering: true},
	{fieldName: 'NBGUOI_TRAPHIEU', width : 150 , headerText: 'Người trả', allowFiltering: true},
	{fieldName: 'KIEU_TRAPHIEU', width : 150 , headerText: 'Kiểu trả', allowFiltering: true},
	{fieldName: 'TRANGTHAI', width : 150 , headerText: 'Trạng thái', allowFiltering: true},	
],
  2: [
    {fieldName: 'MA_KN', width : 200 , headerText: 'Mã khiếu nại', allowFiltering: true },
	{fieldName: 'NGAY_TN', width : 200 , textAlign: 'Center', headerText: 'Ngày tiếp nhận', allowFiltering: true},
	{fieldName: 'TEN_NV', width : 250 , headerText: 'Người tiếp nhận', allowFiltering: true},
	{fieldName: 'MA_TB', width : 150 , headerText: 'Số máy/Acc', allowFiltering: true },
	{fieldName: 'TEN_TB', width : 150 , headerText: 'Tên thuê bao', allowFiltering: true},
	{fieldName: 'MA_KH', width : 150 , headerText: 'Mã khách hàng', allowFiltering: true},
	{fieldName: 'TEN_DVVT', width : 150 , headerText: 'Dịch vụ', allowFiltering: true},
	{fieldName: 'LOAIHINH_TB', width : 150 , headerText: 'Loại hình', allowFiltering: true},
	{fieldName: 'NHOM_CHUDE', width : 150 , headerText: 'Nhóm chủ đề', allowFiltering: true},
	{fieldName: 'CHUDE_C1', width : 150 , headerText: 'Chủ đề cấp 1', allowFiltering: true},
	{fieldName: 'CHUDE_C2', width : 150 , headerText: 'Chủ đề cấp 2', allowFiltering: true},
	{fieldName: 'KN_LAPLAI', width : 150 , headerText: 'Khiếu nại lặp', allowFiltering: true},
	{fieldName: 'KN_VUOTCAP', width : 150 , headerText: 'Khiếu nại vượt', allowFiltering: true},
	{fieldName: 'KN_KHANCAP', width : 150 , headerText: 'Khiếu nại khẩn', allowFiltering: true},
	{fieldName: 'NGUOI_KN', width : 150 , headerText: 'Người khiếu nại', allowFiltering: true},
	{fieldName: 'DIENTHOAI_LH', width : 150 , headerText: 'Điện thoại LH', allowFiltering: true},
	{fieldName: 'DIACHI_LH', width : 150 , headerText: 'Địa chỉ LH', allowFiltering: true},
	{fieldName: 'HENGQ_TU', width : 150 , headerText: 'Hẹn từ', allowFiltering: true},
	{fieldName: 'HENGQ_DEN', width : 150 , headerText: 'Hẹn đến', allowFiltering: true},
	{fieldName: 'NGAY_CAMKET', width : 150 , headerText: 'Ngày cam kết', allowFiltering: true},
	{fieldName: 'GIO_CAMKET', width : 150 , headerText: 'Giờ cam kết', allowFiltering: true},
	{fieldName: 'ND_XULY', width : 250 , headerText: 'Kết quả xử lý', allowFiltering: true},
	{fieldName: 'NGAY_GIAO', width : 150 , headerText: 'Ngày giao', allowFiltering: true},
	{fieldName: 'NGUOI_GIAO', width : 150 , headerText: 'Người giao', allowFiltering: true},
	{fieldName: 'DONVI_NHAN', width : 150 , headerText: 'Đơn vị nhận', allowFiltering: true},
	{fieldName: 'NGUOI_NHAN', width : 150 , headerText: 'Người nhận', allowFiltering: true},	
	{fieldName: 'TRANGTHAI', width : 150 , headerText: 'Trạng thái', allowFiltering: true},	
  ],
	3: [
		{fieldName: 'MA_KN', width : 200 , headerText: 'Mã khiếu nại', allowFiltering: true },
		{fieldName: 'NGAY_TN', width : 200 , textAlign: 'Center', headerText: 'Ngày tiếp nhận', allowFiltering: true},
		{fieldName: 'TEN_NV', width : 250 , headerText: 'Người tiếp nhận', allowFiltering: true},
		{fieldName: 'MA_TB', width : 150 , headerText: 'Số máy/Acc', allowFiltering: true },
		{fieldName: 'TEN_TB', width : 150 , headerText: 'Tên thuê bao', allowFiltering: true},
		{fieldName: 'MA_KH', width : 150 , headerText: 'Mã khách hàng', allowFiltering: true},
		{fieldName: 'TEN_DVVT', width : 150 , headerText: 'Dịch vụ', allowFiltering: true},
		{fieldName: 'LOAIHINH_TB', width : 150 , headerText: 'Loại hình', allowFiltering: true},
		{fieldName: 'NHOM_CHUDE', width : 150 , headerText: 'Nhóm chủ đề', allowFiltering: true},
		{fieldName: 'CHUDE_C1', width : 150 , headerText: 'Chủ đề cấp 1', allowFiltering: true},
		{fieldName: 'CHUDE_C2', width : 150 , headerText: 'Chủ đề cấp 2', allowFiltering: true},
		{fieldName: 'KN_LAPLAI', width : 150 , headerText: 'Khiếu nại lặp', allowFiltering: true},
		{fieldName: 'KN_VUOTCAP', width : 150 , headerText: 'Khiếu nại vượt', allowFiltering: true},
		{fieldName: 'KN_KHANCAP', width : 150 , headerText: 'Khiếu nại khẩn', allowFiltering: true},
		{fieldName: 'NGUOI_KN', width : 150 , headerText: 'Người khiếu nại', allowFiltering: true},
		{fieldName: 'DIENTHOAI_LH', width : 150 , headerText: 'Điện thoại LH', allowFiltering: true},
		{fieldName: 'DIACHI_LH', width : 150 , headerText: 'Địa chỉ LH', allowFiltering: true},
		{fieldName: 'HENGQ_TU', width : 150 , headerText: 'Hẹn từ', allowFiltering: true},
		{fieldName: 'HENGQ_DEN', width : 150 , headerText: 'Hẹn đến', allowFiltering: true},
		{fieldName: 'NGAY_CAMKET', width : 150 , headerText: 'Ngày cam kết', allowFiltering: true},
		{fieldName: 'GIO_CAMKET', width : 150 , headerText: 'Giờ cam kết', allowFiltering: true},
		{fieldName: 'ND_XULY', width : 250 , headerText: 'Kết quả xử lý', allowFiltering: true},
		{fieldName: 'NGUOI_XULY', width : 150 , headerText: 'Người xử lý', allowFiltering: true},
		{fieldName: 'NGAY_XULY', width : 150 , headerText: 'Ngày xử lý', allowFiltering: true},
		{fieldName: 'NGUYENNHAN_KN', width : 150 , headerText: 'Nguyên nhân lỗi', allowFiltering: true},
		{fieldName: 'PHUONG_AN', width : 150 , headerText: 'Phương án xử lý', allowFiltering: true},
		{fieldName: 'NOIDUNG_GQ', width : 150 , headerText: 'Nội dung trả lời', allowFiltering: true},	
		{fieldName: 'TRANGTHAI', width : 150 , headerText: 'Trạng thái', allowFiltering: true},	
	]	
};

export default GRID_COLUMS;
