const collumns = {
    columnsTT: [
        {
            fieldName: "MALO_HS",
            headerText: "Mã lô hồ sơ",
            allowFiltering: true,
            allowSorting: true,
            textAlign: 'center',
            autoFit: "true",
            customAttributes: {class: 'clbrown'}
        },
        {
            fieldName: "NGAYTAO",
            headerText: "Ngày tạo",
            allowFiltering: true,
            allowSorting: true,
            textAlign: 'center',
            autoFit: "true",
        },
        {
            fieldName: "TEN_DV",
            headerText: "Đơn vị giao",
            allowFiltering: true,
            allowSorting: true,
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "TEN_NV",
            headerText: "Nhân viên tạo",
            allowFiltering: true,
            allowSorting: true,
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "GHICHU",
            headerText: "Ghi chú",
            allowFiltering: true,
            allowSorting: true,
            textAlign: 'left',
            autoFit: "true",
        },
    ],
    columnsHSDG: [
        {
            fieldName: "stt",
            headerText: "STT",
            allowSorting: true,
            textAlign: 'left',
            width: "100px",
        },
        {
            fieldName: "ma_gd",
            headerText: "Mã GD",
            allowFiltering: true,
            allowSorting: true,
            textAlign: 'left',
            width: "130px",
            customAttributes: {class: 'clblue'}
        },
        {
            fieldName: "ma_bo_hs",
            headerText: "Mã bộ HS",
            allowFiltering: true,
            allowSorting: true,
            textAlign: 'left',
            width: "130px",
            customAttributes: {class: 'clbrown'}
        },
        {
            fieldName: "ma_kh",
            headerText: "Mã KH",
            allowFiltering: true,
            allowSorting: true,
            textAlign: 'left',
            width: "130px",
        },
        {
            fieldName: "ten_kh",
            headerText: "Tên KH",
            allowFiltering: true,
            allowSorting: true,
            textAlign: 'left',
            width: "150px",
        },
        {
            fieldName: "diachi_kh",
            headerText: "Địa chỉ KH",
            allowFiltering: true,
            allowSorting: true,
            textAlign: 'left',
            width: "180px",
        },
    ],
    columnsHSCG: [
        {
            fieldName: "ma_gd",
            headerText: "Mã GD",
            allowFiltering: true,
            allowSorting: true,
            textAlign: 'left',
            width: "100px",
            customAttributes: {class: 'clblue'}
        },
        {
            fieldName: "ma_bo_hs",
            headerText: "Mã bộ HS",
            allowFiltering: true,
            allowSorting: true,
            textAlign: 'left',
            width: "130px",
            customAttributes: {class: 'clbrown'}
        },
        {
            fieldName: "ma_kh",
            headerText: "Mã KH",
            allowFiltering: true,
            allowSorting: true,
            textAlign: 'left',
            width: "130px",
        },
        {
            fieldName: "ten_kh",
            headerText: "Tên KH",
            allowFiltering: true,
            allowSorting: true,
            textAlign: 'left',
            width: "130px",
        },
    ],
    // columnsDSHS: [
    //     { fieldName: "stt", headerText: "STT", allowSorting: true, textAlign: 'center', width: "100px", freeze: 'left' },
    //     { fieldName: "ma_gd", headerText: "Mã GD", allowSorting: true, textAlign: 'left', autofit: "true", customAttributes: {class: 'clblue'}, freeze: 'left' },
    //     { fieldName: "ma_kh", headerText: "Mã KH", allowSorting: true, textAlign: 'left', autofit: "true" },
    //     { fieldName: "ten_kh", headerText: "Tên KH", allowSorting: true, textAlign: 'left', autofit: "true" },
    //     { fieldName: "diachi_kh", headerText: "Địa chỉ KH", allowSorting: true, textAlign: 'left', autofit: "true" },
    //     { fieldName: "ngaygiao", headerText: "Ngày giao", allowSorting: true, textAlign: 'center', autofit: "true" },
    //     { fieldName: "malo_hs", headerText: "Số lô", allowSorting: true, textAlign: 'left', autofit: "true", customAttributes: {class: 'clred'} },
    //     { fieldName: "dv_giao", headerText: "Đơn vị giao", allowSorting: true, textAlign: 'left', autofit: "true" },
    //     { fieldName: "ma_bhs", headerText: "Mã bộ HS", allowSorting: true, textAlign: 'left', autofit: "true", customAttributes: {class: 'clbrown'} },
    //     { fieldName: "tendv_next", headerText: "Đơn vị nhận", allowSorting: true, textAlign: 'left', autofit: "true" },
    //     { fieldName: "nhanvien_phat", headerText: "Nhân viên phát", allowSorting: true, textAlign: 'left', autofit: "true", visible: true },
    //     { fieldName: "tt_phat_hs", headerText: "Trạng thái HS", allowSorting: true, textAlign: 'left', autofit: "true", visible: true },
    //     { fieldName: "nguoitao", headerText: "Người tạo", allowSorting: true, textAlign: 'left', autofit: "true" },
    //     { fieldName: "tuyenthutt", headerText: "Tuyến thu", allowSorting: true, textAlign: 'left', autofit: "true" },
    //     { fieldName: "trangthai_up_file_img", headerText: "UpFile", allowHtml: true, textAlign: 'center', autofit: "true" },
    //     { fieldName: "ckb_xacnhan_img", headerText: "Đã xác nhận", allowHtml: true, textAlign: 'center', autofit: "true" },
    // ],
    columnsCTHS: [
        { fieldName: "nhom_file", headerText: "Nhóm file", isGroupedColumn: true },
        { fieldName: "ma_tb", headerText: "Số máy/Acc", allowFiltering: true, allowSorting: true, textAlign: 'left', width: "121px", customAttributes: {class: 'clblue'} },
        { fieldName: "ma_gd", headerText: "Mã GD", allowFiltering: true, allowSorting: true, textAlign: 'left', autofit: "true", customAttributes: {class: 'clbrown'} },
        { fieldName: "loai_file", headerText: "Loại file", allowFiltering: true, allowSorting: true, textAlign: 'left', autofit: "true" },
        { fieldName: "loai_hd", headerText: "Loại HĐ/PL", allowFiltering: true, allowSorting: true, textAlign: 'left', autofit: "true" },
        { fieldName: "ma_kh", headerText: "Mã KH", allowFiltering: true, allowSorting: true, textAlign: 'left', autofit: "true" },
        { fieldName: "ngay_yc", headerText: "Ngày YC", allowFiltering: true, allowSorting: true, textAlign: 'center', autofit: "true" },
        { fieldName: "nguoi_cn", headerText: "Người Upload", allowFiltering: true, allowSorting: true, textAlign: 'left', autofit: "true" },
        { fieldName: "ngay_cn", headerText: "Ngày Upload", allowFiltering: true, allowSorting: true, textAlign: 'center', autofit: "true" },
        { fieldName: "ten_file", headerText: "Tên file", allowSorting: true, textAlign: 'left', autofit: "true" },
        { fieldName: "xem_taive", headerText: "Xem/Tải về", allowHtml: true, textAlign: 'center', width: "110px" },
    ],
    columnsDSTB: [
        {
            fieldName: "LOAI_HD",
            headerText: "Nhóm",
            isGroupedColumn: true,
        },
        {
            fieldName: "MA_TB",
            headerText: "Số máy/Acc",
            allowFiltering: true,
            allowSorting: true,
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "LOAIHINH_TB",
            headerText: "Loại hình",
            allowFiltering: true,
            allowSorting: true,
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "TRANGTHAI_TB",
            headerText: "Trạng thái",
            allowFiltering: true,
            allowSorting: true,
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "NGUOI_BH",
            headerText: "Người báo hỏng",
            allowFiltering: true,
            allowSorting: true,
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "NGAY_BH",
            headerText: "Ngày báo hỏng",
            allowFiltering: true,
            allowSorting: true,
            textAlign: 'center',
            autoFit: "true",
        },
        {
            fieldName: "NGAY_HT",
            headerText: "Ngày nghiệm thu",
            allowFiltering: true,
            allowSorting: true,
            textAlign: 'center',
            autoFit: "true",
        },
    ]
}

export default collumns
