// https://docs.google.com/spreadsheets/d/1-L0ojT6OkWz4CTJR5sUeHlbzChRzO5i_tE9G_RrZ9Vc/edit#gid=620043524&range=A984:E984
// Khao sat moi : https://docs.google.com/spreadsheets/d/1-L0ojT6OkWz4CTJR5sUeHlbzChRzO5i_tE9G_RrZ9Vc/edit#gid=177639690&range=F360
// WinUI.WinUILapHopDong.frmThayDoiThongSoWanBC
// URD2.1.033
export default {
  /*
  getDmTtHDSeflCare: (axios, data) => axios.post('/web-quantri/danhmuc/nghiepvu/DS_TRANGTHAI_GIAO_HD_SEFLCARE', data),
  getDsDonViQLTT: (axios, data) => axios.post('/web-quantri/danhmuc/nghiepvu/DS_DONVI_QL_TT', data),
  getDsDonViPBH: (axios, data) => axios.post('/web-quantri/danhmuc/nghiepvu/DS_DONVI_QL_TT_PBH', data),
  getDsHopDong: (axios, data) => axios.post('/web-ccdv/HDSeflCare/lay_ds_hd_selfcare', data),
  getDsLogXuLy: (axios, data) => axios.post('/HDSeflCare/sp_layds_logxl_seflcare', data),
  giaoPhieu: (axios, data) => axios.post('/web-ccdv/HDSeflCare/giaonv_hd_selfcare', data),
  layDsNhanVienTheoDonVi: (axios, data) => axios.post('/web-ccdv/HDSeflCare/lay_ds_nlv_theo_donvi', data)
  */
  sp_ds_tienkhoanmuc_loaihd: (axios, data) => axios.post('/web-hopdong/thuebao_datcoc_thunghiem/sp_ds_tienkhoanmuc_loaihd', data),
  sp_ht_dichvuvt_combobox: (axios, data) => axios.post('/web-hopdong/thaydoitocdoadsl/sp_ht_dichvuvt_combobox', data),
  loai_kenh: (axios, data) => axios.get('/web-hopdong/thaydoimegawan/loai_kenh', data),
  loai_modem: (axios, data) => axios.get('/web-hopdong/thaydoimegawan/loai_modem', data),
  tocdo_kenh: (axios, data) => axios.get(`/web-hopdong/thaydoimegawan/tocdo_kenh`, data),
  trangbi: (axios, data) => axios.get(`/web-hopdong/thaydoimegawan/trangbi`, data),
  lay_ds_loai_tb_megawan: (axios, data) => axios.get(`/web-hopdong/thaydoimegawan/lay_ds_loai_tb_megawan`, data),
  chuquan: (axios, data) => axios.get(`/web-hopdong/thaydoimegawan/chuquan`, data),
  thoihan: (axios, data) => axios.get(`/web-hopdong/thaydoimegawan/thoihan`, data),
  sp_lay_ds_tinh_kn: (axios, data) => axios.get(`/web-hopdong/thaydoimegawan/sp_lay_ds_tinh_kn`, data),
  sp_lay_ds_tatca_vetinh: (axios, data) => axios.post('/web-hopdong/thanhly/sp_lay_ds_tatca_vetinh', data),
  doitac: (axios, data) => axios.get(`/web-hopdong/thaydoimegawan/doitac`, data),
  congnghe: (axios, data) => axios.get(`/web-hopdong/thaydoimegawan/congnghe`, data),
  lay_khuyenmai_hdtb: (axios, data) => axios.post('/web-hopdong/khuyenmai_tocdo_internet/lay_khuyenmai_hdtb', data),
  phanloai_dv_cu_moi: (axios, data) => axios.get(`/web-hopdong/thaydoimegawan/phanloai_dv_cu_moi`, data),
  phanloai_tocdo_cu_moi_loi: (axios, data) => axios.get(`/web-hopdong/thaydoimegawan/phanloai_tocdo_cu_moi?vkieu=${data.vkieu}`, data),
  phanloai_tocdo_cu_moi: (axios, data) => axios.get(`/web-bancheo/thaydoimegawan/phanloai_tocdo_cu_moi?vkieu=${data.vkieu}`, data),
  loaihinh_tb: (axios, data) => axios.post(`web-hopdong/thaydoimegawan/loaihinh_tb`, data),
  kieuld: (axios, data) => axios.get(`/web-quantri/danhmuc-chung/CSS_KIEU_LD`, data),
  //  map_id: (axios, data) => axios.post(`/web-hopdong/thanhly/thanh_ly_map_id`, data),
  fn_tt_khuyenmai: (axios, data) => axios.post(`/web-tratruoc/thongtin_tratruoc_dn/fn_tt_khuyenmai`, data),
  fn_tt_db_khachhang: (axios, data) => axios.post(`/web-tratruoc/thongtin_tratruoc_dn/fn_tt_db_khachhang`, data),
  fn_tt_db_thuebao: (axios, data) => axios.post(`/web-tratruoc/thongtin_tratruoc_dn/fn_tt_db_thuebao`, data),
  fn_tt_hd_thuebao: (axios, data) => axios.post(`/web-tratruoc/thongtin_tratruoc_dn/fn_tt_hd_thuebao`, data),
  fn_tt_nhanvien: (axios, data) => axios.post(`/web-tratruoc/thongtin_tratruoc_dn/fn_tt_nhanvien`, data),
  fn_tt_doitac: (axios, data) => axios.post(`/web-tratruoc/thongtin_tratruoc_dn/fn_tt_doitac`, data),
  fn_tt_db_mgwan: (axios, data) => axios.post(`/web-tratruoc/thongtin_tratruoc_dn/fn_tt_db_mgwan`, data),
  fn_tt_muccuoc_tb: (axios, data) => axios.post(`/web-tratruoc/thongtin_tratruoc_dn/fn_tt_muccuoc_tb`, data),
  //
  lay_ds_hopdong_theo_ma_gd: (axios, data) => axios.post(`/web-hopdong/khoiphucthanhly/lay_ds_hopdong_theo_ma_gd`, data),
  lay_ds_hopdong_theo_ma_tb: (axios, data) => axios.post(`/web-hopdong/khoiphucthanhly/lay_ds_hopdong_theo_ma_tb`, data),
  lay_ds_hopdong_thuebao_theo_hdkh: (axios, data) => axios.get(`/web-hopdong/hopdong/lay_ds_hopdong_thuebao_theo_hdkh?hdKhId=${data.hdKhId}`, data),
  lay_ds_hopdong_thuebao_mgwan: (axios, data) => axios.get(`/web-hopdong/hopdong/lay_ds_hopdong_thuebao_mgwan?hdtbId=${data.hdtbId}`, data),
  lay_tien_hd_km_theo_hdtb: (axios, data) => axios.post(`/web-thicong/thicong/lay_tien_hd_km_theo_hdtb`, data),
  fn_lay_text_huongketnoi: (axios, data) => axios.post(`/web-hopdong/khoiphucthanhly/fn_lay_text_huongketnoi`, data),
  lay_ds_bddb_mgwan_theo_hdtb_id: (axios, data) => axios.post(`/web-hopdong/hopdong/lay_ds_bddb_mgwan_theo_hdtb_id`, data),
  lay_chitiet_km_theo_hdtb_id: (axios, data) => axios.post(`/web-thicong/thicong/lay_chitiet_km_theo_hdtb_id`, data),
  lay_ds_diachi_theo_dbtbid: (axios, data) => axios.post(`/web-hopdong/dichvu-ca/lay_ds_diachi_theo_dbtbid`, data),
  lay_ds_danhba_megawan: (axios, data) => axios.get(`/web-hopdong/hopdong/lay_ds_danhba_megawan?thueBaoId=${data.thuebaoId}`, data),
  lay_ds_db_megawan_theo_tbid: (axios, data) => axios.get(`/web-hopdong/hopdong/lay_ds_danhba_megawan?thueBaoId=${data.thuebaoId}`, data),
  lay_ds_db_megawan_theo_tbid_v2: (axios, data) => axios.post(`/web-hopdong/thaydoi_thongso_megawan/lay_ds_db_megawan_theo_tbid_v2`, data),
  lay_tien_hd_km_theo_hdtb1: (axios, data) => axios.get(`/web-hopdong/hoanthien-hs-doisim/lay_tien_hd_km_theo_hdtb/${data.hdtb_id}`, data),
  lay_danhba_theo_matb: (axios, data) => axios.post(`/web-hopdong/dichvu-ca/lay_danhba_theo_matb`, data),
  kiemtra_thuebao_lap_hopdong_khac: (axios, data) => axios.post(`/web-hopdong/hopdong/kiemtra_thuebao_lap_hopdong_khac`, data),
  kiemtra_hd_bancheo_tc: (axios, data) => axios.post(`/web-hopdong/thaydoidichvu/kiemtra_hd_bancheo_tc`, data),
  kiemtra_makh_mtt: (axios, data) => axios.post(`/web-thicong/thicong/kiemtra_makh_mtt`, data),
  xoa_hdkh_v2: (axios, data) => axios.post(`/web-hopdong/khoiphucthanhly/xoa_hdkh_v2`, data),
  xoa_hdtb: (axios, data) => axios.post(`/web-hopdong/khoiphucthanhly/xoa_hdtb`, data),
  lay_huonggiao_tiepnhan: (axios, data) => axios.post(`/web-hopdong/hopdong/lay_huonggiao_tiepnhan`, data),

  lay_huonggiao_tiepnhan_v2: (axios, data) => axios.post(`/web-hopdong/khoiphucthanhly/layhuonggiao_tiepnhan_v2`, data),
  sinh_magd_v2: (axios, data) => axios.post(`/web-hopdong/khoiphucthanhly/sinh_magd_v2`, data),
  sinh_magd: (axios, data) => axios.post(`/web-hopdong/khoiphucthanhly/sinh_magd`, data),
  lay_tien_khoanmuc_ld: (axios, data) => axios.post(`/web-hopdong/khoiphucthanhly/lay_tien_khoanmuc_ld`, data),
  sp_lay_cuoctk_cuoctc: (axios, data) => axios.post(`web-hopdong/lapdatmoi/sp_lay_cuoctk_cuoctc`, data),
  kiemtra_thoihan_km: (axios, data) => axios.post(`/web-hopdong/lapdatmoi/kiemtra_thoihan_km`, data),
  kiemtra_hdtb_khi_themmoi: (axios, data) => axios.post(`/web-hopdong/hopdong/kiemtra_hdtb_khi_themmoi`, data),
  kiemtra_danhba_khi_themmoi: (axios, data) => axios.post(`/web-hopdong/hopdong/kiemtra_danhba_khi_themmoi`, data),
  kiemtra_tb_cung_makh_tb_pl: (axios, data) => axios.post(`/web-hopdong/khoiphucthanhly/kiemtra_tb_cung_makh_tb_pl`, data),
  // kiemtra_thuebao_lap_hopdong_khac: (axios, data) => axios.post(`/web-hopdong/hopdong/kiemtra_thuebao_lap_hopdong_khac`, data),
  sp_themmoi_hd_tdts_megawan: (axios, data) => axios.post(`/web-hopdong/thaydoimegawan/sp_themmoi_hd_tdts_megawan`, data),
  sp_capnhat_hd_tdts_megawan: (axios, data) => axios.post(`/web-hopdong/thaydoimegawan/sp_capnhat_hd_tdts_megawan`, data),
  sp_themmoi_hdtb_tdts_megawan: (axios, data) => axios.post(`/web-hopdong/thaydoimegawan/sp_themmoi_hdtb_tdts_megawan`, data),
  getKey: (axios, data) => axios.post(`/web-quantri/donvitinh/get_keys`, data),
  get_donvi_id_loaidvId_kieudv_id: (axios, data) => axios.post(`/web-hopdong/thaydoiloaihinhtb/ur2_1_035_038_temp`, data),
  huonggiao_ldv: (axios, data) => axios.post(`/web-hopdong/lapdatmoi/huonggiao_ldv1`, data),
  update_huonggiao_tiepnhan: (axios, data) => axios.post(`/web-hopdong/khoiphucthanhly/update_huonggiao_tiepnhan`, data),
  luong_dv: (axios, data) => axios.get(`/web-hopdong/thaydoimegawan/luong_dv?luongId=${data.luongId}`, data),
  post_lay_khoanmuc_tt_theo_loaihd: async (axios, data) => axios.post('/web-hopdong/lapdatmoi/lay_khoanmuc_tt_theo_loaihd', data),
  post_lay_ds_tien_kmtt: async (axios, data) => axios.post('/web-hopdong/lapdatmoi/lay_ds_tien_kmtt', data),
  lay_dulieu_bang_theo_dieukien: async (axios, data) => axios.post('/web-quantri/hodan/sp_lay_dulieu_bang_theo_dieukien', data),
  getThamSoMacDinhNguoiDung: (axios, data) => axios.post('/web-ccdv/tienhopdong/fn_lay_thamso_macdinh', data),
  thamso_md_theo_ma: (axios, data) => axios.get(`/web-quantri/danhmuc/thamso_md_theo_ma?MA_TS=${data.ma_ts}`, data),
  lay_ds_hopdong_tb_theo_hdtb_id: (axios, data) => axios.post(`/web-quantri/thutienphatsinh/lay_ds_hopdong_tb_theo_hdtb_id`, data),
  lay_ds_kieu_ld: (axios, data) => axios.post(`/web-ccdv/ds_yeucau_khaosat/lay_ds_kieu_ld`, data),

  // ban cheo
  // lay_dichvuvt_loaitb_id: (axios, data) => axios.post(`/web-bancheo/thaydoimegawan/lay_dichvuvt_loaitb_id`, data),
  lay_dichvuvt_loaitb_id: (axios, data) => axios.get(`/web-bancheo/thaydoimegawan/lay_dichvuvt_loaitb_id?loaitbId=${data.loaitbId}`),
  // fn_thaydoi_thongso_wan_bc_capnhat: (axios, data) => axios.post(`http://localhost:8088/thaydoimegawan/fn_thaydoi_thongso_wan_bc_capnhat`, data),
  fn_thaydoi_thongso_wan_bc_capnhat: (axios, data) => axios.post(`/web-bancheo/thaydoimegawan/fn_thaydoi_thongso_wan_bc_capnhat`, data),
  fn_thaydoi_thongso_wan_bc_themhdthuebao: (axios, data) => axios.post(`/web-bancheo/thaydoimegawan/fn_thaydoi_thongso_wan_bc_themhdthuebao`, data),
  fn_thaydoi_thongso_wan_bc_xoa_hdtb: (axios, data) => axios.post(`/web-bancheo/thaydoimegawan/fn_thaydoi_thongso_wan_bc_xoa_hdtb`, data),
  lay_danhba_theo_matb_bc: (axios, data) => axios.post(`/web-bancheo/thaydoimegawan/lay_danhba_theo_matb`, data),
  lay_tinh_theo_matb: (axios, data) => axios.get(`/web-bancheo/thaydoimegawan/lay_tinh_theo_matb?matb=${data.matb}`, data),
  tra_cuu_lay_ds_hopdong_theo_ma_tb: (axios, data) => axios.post(`/web-bancheo/thaydoimegawan/lay_ds_hopdong_theo_ma_tb`, data),
  lay_thuebaoid_thicong: (axios, data) => axios.post(`/web-bancheo/thaydoimegawan/lay_thuebaoid_thicong`, data),
  // tc_lay_thuebaoid_thicong: (axios, data) => axios.post(`/web-bancheo/tracuu/lay_thuebaoid_thicong`, data),
  tc_lay_thuebaoid_thicong: (axios, data) => axios.post(`/web-hopdong/chuyendoi-codinh-sang-ims-bancheo/lay_thuebaoid_thicong`, data),
  lay_ds_hopdong_tb_theo_hdkh_id: (axios, data) => axios.get(`/web-bancheo/thaydoimegawan/lay_ds_hopdong_tb_theo_hdkh_id?hdkhid=${data.hdkhid}`, data),
  lay_thongso_thuebao_thuebaoid: (axios, data) => axios.get(`/web-hopdong/hopdong/lay_thongso_thuebao_thuebaoid?thueBaoId=${data.thuebaoid}`, data),
  lay_thongso_thuebao_thuebaoid_bc: (axios, data) => axios.post(`/web-bancheo/thaydoimegawan/lay_thongso_thuebao_thuebaoid`, data),
  bc_lay_thongso_thuebao_thuebaoid: (axios, data) => axios.post(`/web-bancheo/tracuu/lay_thongso_thuebao_thuebaoid`, data),
  tinh_thicong: (axios, data) => axios.post(`/web-bancheo/danhmuc/tinh_thicong`, data),
  lay_ds_tinh_thicong_combobox: (axios, data) => axios.post(`/web-hopdong/bss_group1/lay_ds_tinh_thicong_combobox`, data),
  lay_danhba_theo_thuebaoid: (axios, data) => axios.post(`/web-bancheo/tracuu/lay_danhba_theo_thuebaoid`, data),
  lay_ds_db_megawan_theo_tbid_bc: (axios, data) => axios.post(`/web-bancheo/tracuu/lay_ds_db_megawan_theo_tbid`, data),
  lay_thongso_thuebao_hdbc: (axios, data) => axios.post(`/web-bancheo/tracuu/lay_thongso_thuebao_bancheo_hdtbid`, data),
  lay_tinh_theo_thuebaoid: (axios, data) => axios.get(`/web-hopdong/thanhly-thuebao-bancheo/lay_tinh_theo_thuebaoid?thuebaoid=${data.thuebaoid}`, data),
  lay_huonggiao_tiepnhan_tinh: (axios, data) => axios.post(`/web-bancheo/thaydoimegawan/lay_huonggiao_tiepnhan`, data),
  layhuonggiao_tiepnhan_bancheo: (axios, data) => axios.post(`/web-bancheo/tracuu/layhuonggiao_tiepnhan_bancheo`, data),
  kiemtra_tocdo_internet_tt: (axios, data) => axios.post(`/web-bancheo/thaydoimegawan/kiemtra_tocdo_internet_tt`, data),
  bancheo_kiemtra_thongsokt: (axios, data) => axios.post(`/web-bancheo/thaydoimegawan/bancheo_kiemtra_thongsokt`, data),
  lay_ds_tb_wan: (axios, data) => axios.post(`/web-bancheo/thaydoimegawan/lay_ds_tb_wan`, data),
  ht_kieu_ld_bancheo_combobox: (axios, data) => axios.post(`/web-bancheo/thaydoimegawan/ht_kieu_ld_bancheo_combobox`, data),
  sp_lay_ds_kieu_ld_bc: (axios, data) => axios.post(`/web-hopdong/thanhly-thuebao-bancheo/sp_lay_ds_kieu_ld_bc`, data),
  load_tuhopdong_tuvan: (axios, data) => axios.get(`/web-bancheo/thaydoimegawan/load_tuhopdong_tuvan?hdkhchaId=${data.hdkhchaId}`, data),
  fn_tt_db_thuebao_tinh: (axios, data) => axios.post(`/web-bancheo/thaydoimegawan/fn_tt_db_thuebao`, data)
}
