export default {
  getDSChinhSachThuLao : (axios, data) => axios.post('/web-khdn/csthulao/dsKhaiBaoCSTL', data),
  getDSDichVu: (axios, data) => axios.post('/web-khdn/csthulao/dsDichVu',data),
  getDSLoaiHinh: (axios, data) => axios.post('/web-khdn/csthulao/dsLoaiHinh',data),
  getDSGoiCuoc: (axios, data) => axios.post('/web-khdn/csthulao/dsGoiCuoc',data),
  getDSDoiTuongBan: (axios, data) => axios.post('/web-khdn/csthulao/dsDoiTuongBan',data),
  getDSPVApDung: (axios, data) => axios.post('/web-khdn/csthulao/dsPVApdung',data),
  getDSDVBanHanh: (axios, data) => axios.post('/web-khdn/csthulao/dsDVBanHanh',data),
  getDSLoaiThuLao: (axios, data) => axios.post('/web-khdn/csthulao/dsLoaiThuLao',data),
  getDSCongVan: (axios, data) => axios.post('/web-khdn/csthulao/dsCongVan',data),
  getDSTinhTrang: (axios, data) => axios.post('/web-khdn/csthulao/dsTinhtrangCC',data),
  chiTietCoChe: (axios, data) => axios.post('/web-khdn/csthulao/chiTietKhaiBaoCSTL',data),
  getDSCongDoan: (axios, data) => axios.post('/web-khdn/csthulao/dsCongDoan',data),
  deleteCoChe: (axios, data) => axios.post('/web-khdn/csthulao/xoaKhaiBaoCSTL',data),
  insertCoChe: (axios, data) => axios.post('/web-khdn/csthulao/themMoiKhaiBaoCSTL',data),
  updateCoChe: (axios, data) => axios.post('/web-khdn/csthulao/capNhatKhaiBaoCSTL',data),
  updateCongDoan: (axios, data) => axios.post('/web-khdn/csthulao/capNhatCongDoanCS',data),
  insertCongDoan: (axios, data) => axios.post('/web-khdn/csthulao/themMoiCongDoanCS',data),
  deleteCongDoan: (axios, data) => axios.post('/web-khdn/csthulao/xoaCongdoanKHCS',data),
  uploadFile: (axios, data) => axios.post('/web-quantri/upload',data, {headers: {'Content-Type': 'multipart/form-data'}}),
  getDSLoaiFile: (axios, data) => axios.post('/web-khdn/kenhban/dsLoaiFile',data),
  capNhatFileCSTL: (axios, data) => axios.post('/web-khdn/csthulao/capNhatFileCSTL',data),
  deleteFile: (axios, data) => axios.post('/web-khdn/csthulao/xoaFileChinhSach',data),
  link_view_file: async (axios, data) => axios.post('/web-quantri/upload/link_view_file', data),
  getDSFile: (axios, data) => axios.post('/web-khdn/csthulao/dsFileCSTL',data),
}