export default {
  fn_tt_loaihinh_tb: async (axios, data) => axios.post('/web-ccdv/khaibao-ims/fn_tt_loaihinh_tb', data),
  thanh_ly_map_id: async (axios, data) => axios.post('/web-hopdong/thanhly/thanh_ly_map_id', data),
  capnhat_ngaykh_status_v2: async (axios, data) => axios.post('/web-ccdv/khaibaoims/capnhat_ngaykh_status_v2', data),
  sp_capnhat_slgoicuoc_ip_ims: async (axios, data) => axios.post('/web-ccdv/khaibao-ims/sp_capnhat_slgoicuoc_ip_ims', data),
  sp_capnhat_status_hdtb: async (axios, data) => axios.post('/web-ccdv/khaibao-ims/sp_capnhat_status_hdtb', data),
  sp_capnhat_ngayht: async (axios, data) => axios.post('/web-ccdv/khaibao-ims/sp_capnhat_ngayht', data),
  sp_kt_taodb_thang: async (axios, data) => axios.get(`web-ccdv/khaibao-ims/sp_kt_taodb_thang?p_phanvung_id=${data.phanvung_id}&p_kyhoadon=${data.kyhoadon}`),
  sp_capnhat_ngaykh: async (axios, data) => axios.post('/web-ccdv/khaibao-ims/sp_capnhat_ngaykh', data),
  datmoithuebao: async (axios, data) => axios.post('/web-ccdv/kichhoatims/datmoithuebao', data),
  fn_tt_bd_thuebao: async (axios, data) => axios.post('/web-tratruoc/thongtin_tratruoc_dn/fn_tt_bd_thuebao', data),
  fn_tt_loaihinh_tb: async (axios, data) => axios.post('/web-tratruoc/thongtin_tratruoc_dn/fn_tt_loaihinh_tb', data),
  lay_ds_phieu_giaoden_ims: async (axios, data) => axios.post('/web-ccdv/khaibaoims/lay_ds_phieu_giaoden_ims', data),
  sp_lay_luong_thaotac: async (axios, data) => axios.post('/web-ccdv/khaibaoims/sp_lay_luong_thaotac', data),
  sp_lay_ds_dangky_dvgt_by_hdtb_id: async (axios, data) => axios.post('/web-tracuu/tracuu_chitiet_thicong/sp_lay_ds_dangky_dvgt_by_hdtb_id', data),
  lay_ds_nhanvien_theo_phieu_id: async (axios, data) => axios.post('/web-ccdv/HoanThanhKhaoSat/lay_ds_nhanvien_theo_phieu_id', data),
  sp_lay_ds_thamso_md: async (axios, data) => axios.post('/web-hopdong/thanhly/sp_lay_ds_thamso_md', data),
  kiemtra_tramvt1: async (axios, data) => axios.post('/web-ccdv/khaibaoims/kiemtra_tramvt1', data),
  kiemtra_port: async (axios, data) => axios.post('/web-ccdv/khaibaoims/kiemtra_port', data),
  sp_lay_ds_nhanvien_theocap_hdtb: async (axios, data) => axios.post('/web-ccdv/khaibaoims/sp_lay_ds_nhanvien_theocap_hdtb', data),
  xoa_phieu: async (axios, data) => axios.get(`/web-ccdv/tiepnhanhopdong/xoa_phieu/${data.phieuId}`),
  insert_giaophieu_nv: async (axios, data) => axios.post('/web-ccdv/tiepnhanhopdong/insert_giaophieu_nv', data),
  sp_update_tt_giaoviec: async (axios, data) => axios.post('/web-ccdv/khaibaoims/sp_update_tt_giaoviec', data),
  sp_ktra_dk_port: async (axios, data) => axios.post('/web-ccdv/khaibaoims/sp_ktra_dk_port', data),
  fn_capnhat_trangthai_port: async (axios, data) => axios.post('/web-ccdv/khaibaoims/fn_capnhat_trangthai_port', data),
  fn_capnhat_ds_matb: async (axios, data) => axios.post('/web-ccdv/khaibaoims/fn_capnhat_ds_matb', data),
  capnhat_thongtin_port_ims: async (axios, data) => axios.post('/web-ccdv/khaibaoims/capnhat_thongtin_port_ims', data),
  capnhat_thongtin_thicong_ims: async (axios, data) => axios.post('/web-ccdv/khaibaoims/capnhat_thongtin_thicong_ims', data),
  sp_lay_ds_huonggiao_giaophieu_theo_hdtb: async (axios, data) => axios.post('/web-ccdv/khaibaoims/sp_lay_ds_huonggiao_giaophieu_theo_hdtb', data),
  giaophieu_td_host_khoiphuclai: async (axios, data) => axios.post('/web-ccdv/khaibaoims/giaophieu_td_host_khoiphuclai', data),
  lay_idx_huonggiao_theoquytrinh_id: async (axios, data) => axios.post('/web-hopdong/thanhly/lay_idx_huonggiao_theoquytrinh_id', data),
  lay_huonggiao_theo_luong_id: async (axios, data) => axios.post('/web-ccdv/khaibaotsl/lay_huonggiao_theo_luong_id', data),
  lay_thongtin_table: async (axios, data) => axios.post('/web-ccdv/khaibaoims/lay_thongtin_table', data),
  lay_ds_thamso_md_mats: async (axios, data) => axios.post('/web-thicong/hoancongmegawan/lay_ds_thamso_md_mats', data),
  sp_lay_ds_phieuvt_hdbh: async (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/sp_lay_ds_phieuvt_hdbh', data),
  fn_hths_hoancongims: async (axios, data) => axios.post('/web-ccdv/khaibaoims/fn_hths_hoancongims', data),
  hoancong: async (axios, data) => axios.post('/web-ccdv/khaibaoims/hoancong', data),
  kiemtra_giao_omc: async (axios, data) => axios.post('/web-ccdv/ht_hoso_thaydoidichvu/kiemtra_giao_omc', data),
  fn_capnhat_hoancongims: async (axios, data) => axios.post('/web-ccdv/khaibaoims/fn_capnhat_hoancongims', data),

  capnhat_tt_phieu: async (axios, data) => axios.post('/web-hopdong/DiemChiaTrungGianTSL/capnhat_tt_phieu', data),
  capnhat_huykh_status: async (axios, data) => axios.post('/web-ccdv/khaibaocodinh/capnhat_huykh_status', data),
  fn_tt_diachi_tb: async (axios, data) => axios.post('/web-tratruoc/thongtin_tratruoc_dn/fn_tt_diachi_tb', data),
  giaophieu_td_host_thuhoi_1: async (axios, data) => axios.post(`/web-ccdv/dongbo_tb_codinh_lentongdai/giaophieu_td_host_thuhoi_1?hdtb_id=${data.hdtb_id}&phieu_id=${data.phieu_id}`, data),

  fn_tt_kieu_ld: async (axios, data) => axios.post('/web-tratruoc/thongtin_tratruoc_dn/fn_tt_kieu_ld', data),
  fn_kt_lap_kem_co_san: async (axios, data) => axios.post('/web-ccdv/tienhopdong/fn_kt_lap_kem_co_san', data),
  sp_lay_ds_port_theo_ma_tb: async (axios, data) => axios.post('/web-ccdv/tienhopdong/sp_lay_ds_port_theo_ma_tb', data),
  lay_ds_port_matb_tn: async (axios, data) => axios.get(`web-ccdv/khaibaoims/lay_ds_port_matb_tn?hdtb_id=${data.hdtb_id}&matb_tn=${data.matb_tn}`, data),
  fn_tt_diachi_hdtb: async (axios, data) => axios.post(`web-tratruoc/thongtin_tratruoc_dn/fn_tt_diachi_hdtb`, data),
  sp_tt_diachi: async (axios, data) => axios.post(`web-hopdong/laydulieu/sp_tt_diachi`, data),
  lay_dslam_theo_port_id: async (axios, data) => axios.get(`web-ccdv/khaibaoims/lay_dslam_theo_port_id?portId=${data.portId}`, data),
  sp_lay_ds_dslam_tt: async (axios, data) => axios.post(`web-ccdv/tienhopdong/sp_lay_ds_dslam_tt`, data),
  lay_ds_port_tudong: async (axios, data) => axios.post(`web-ccdv/khaibaoims/lay_ds_port_tudong`, data),
  lay_ds_port_tudong_hni: async (axios, data) => axios.post(`web-ccdv/khaibaoims/lay_ds_port_tudong_hni`, data),

  sp_lay_dauso_ims_theo_tinh: async (axios, data) => axios.post(`/web-hopdong/khaibao-ims-bosung/sp_lay_dauso_ims_theo_tinh`, data),
  sps_service_ims_7ts: async (axios, data) => axios.post(`/web-hopdong/hopdong/sps_service_ims_7ts`, data),
  sp_capnhat_kieuxt_ims: async (axios, data) => axios.post(`/web-thicong/capnhatthongtin/sp_capnhat_kieuxt_ims`, data),
  // getThongTinKichHoatThueBao
  fn_tt_bd_thuebao: async (axios, data) => axios.post(`/web-tratruoc/thongtin_tratruoc_dn/fn_tt_bd_thuebao`, data),

}

