export default {
    getDSDichVu: async (axios) => axios.get('/web-quantri/danhmuc-chung/CSS_DICHVU_VT'),
    getLoaiHinhTB: async (axios,id) =>axios.get('/web-thicong/danhmuc/lay_ds_loaihinh_thuebao_dichvu?dichVuVtId='+id),
    getDmKieuYC: async (axios, data) => axios.get(`web-hopdong/danhmuc/ds_kieu_ld/${data.loaihd_id}/${data.loaitb_id}`, data),
    getDsThietbiDC: async (axios, data) => axios.post('/web-hopdong/lapdatmoi/sp_lay_ds_thietbi_dc_lhtb', data),
    LaytientheoKM_Loaihd: async (axios, data) => axios.post('/web-hopdong/tachnhapthuebao/sp_lay_tienkhoanmuc_loaihd', data),
    getThamSo: (axios, data) => axios.post('/web-gqkn/GiaoPhieuXulyKhieuNai/gqkn_lay_ds_thamso_md', data),
    kiemtrathaythestb: (axios, data) => axios.post('/web-ccdv/thaythe_vattu_wifi/kiemtra_thaythe_stb', data),
    kiemtra_db_khi_themmoi: (axios, data) => axios.post('/web-hopdong/khoiphucthanhly/kiemtra_db_khi_themmoi', data),
    map_id: (axios, data) => axios.post('/web-hopdong/thanhly/thanh_ly_map_id', data),
    LAY_DS_HDTB_DV: (axios, data) => axios.post("/web-hopdong/hopdong/khac/lay_ds_hdtb_dv", data),
    lay_ds_donvi_theo_tbid: async (axios,data) => axios.get(`web-hopdong/hopdong/lay_ds_donvi_theo_tbid?thueBaoId=${data.thueBaoId}`,data),
    getTTDanhBa_MaTB:async (axios, data) => axios.post('/web-hopdong/hopdong/lay_danhba_theo_matb', data),
    Lay_tt_thuebao_mytv: (axios, data) => axios.post('/web-ccdv/thaythe_vattu_wifi/lay_tt_thuebao_mytv', data),
    Lay_ds_danhba_adsl: async (axios,data) =>axios.get(`/web-hopdong/hopdong/lay_ds_danhba_adsl?thueBaoId=${data.thuebao_id}`,data),
    Lay_ds_danhba_megawan: async (axios,data) =>axios.get(`/web-hopdong/hopdong/lay_ds_danhba_megawan?thueBaoId=${data.thuebao_id}`,data),
    Lay_ds_danhba_tsl: async (axios,data) =>axios.get(`/web-hopdong/hopdong/lay_ds_danhba_tsl?thueBaoId=${data.thuebao_id}`,data),
    Lay_ds_danhba_codinh: async (axios,data) =>axios.get(`/web-hopdong/hopdong/lay_ds_danhba_codinh?thueBaoId=${data.thuebao_id}`,data),
    Lay_ds_diachi: (axios, data) => axios.post('/web-hopdong/khoiphucthanhly/lay_ds_diachi_theo_dbtbid', data),
    Xoa_hdkh_v2: (axios, data) => axios.post('/web-hopdong/khoiphucthanhly/xoa_hdkh_v2', data),
    Lay_ds_hopdong_tb_theo_hdkh_id: (axios, data) => axios.post('/web-hopdong/khuyenmai_tocdo_internet/lay_ds_hopdong_tb_theo_hdkh_id', data),
    Lay_ds_hopdong_theo_ma_gd: (axios, data) => axios.post('/web-hopdong/khoiphucthanhly/lay_ds_hopdong_theo_ma_gd', data),
    Lay_ds_hopdong_theo_ma_tb: (axios, data) => axios.post('/web-hopdong/khoiphucthanhly/lay_ds_hopdong_theo_ma_tb', data),
    LayTienKhoanMuc: (axios, data) => axios.post('/web-hopdong/khoiphucthanhly/lay_tien_khoanmuc_ld', data),
    get_keys: async (axios, keyname) => axios.post('/web-hopdong/khoiphucthanhly/get_keys',{keyname: keyname}),
    lay_magd: async (axios, loaihd_id) => axios.post('/web-hopdong/khoiphucthanhly/sinh_magd',{loaihd_id: loaihd_id}),
    lay_magd_v2: async (axios, data) => axios.post('/web-hopdong/thongtin_tratruoc_dn/sinh_magd_v2',data),
    post_fn_lay_tt_taodl_hdkh : async (axios, data) => axios.post('/web-hopdong/lapdatmoi/fn_lay_tt_taodl_hdkh',data),
    Lay_ds_db_dd_theo_tbid : async (axios, data) => axios.post('/web-quantri/thutienphatsinh/lay_ds_db_dd_theo_tbid',data),
    Lay_ds_danhba_gp: async (axios,data) =>axios.get(`/web-hopdong/hopdong/lay_ds_danhba_gp?thueBaoId=${data.thuebao_id}`,data),
    Lay_ds_danhba_ims: async (axios,data) =>axios.get(`/web-hopdong/hopdong/lay_ds_danhba_ims?thueBaoId=${data.thuebao_id}`,data),
    Fn_them_hopdong_vattu_tb: async (axios,data) =>axios.post('/web-ccdv/thaythe_vattu_wifi/fn_them_hopdong_vattu_tb',data),
    Fn_sua_hopdong_vattu_tb: async (axios,data) =>axios.post('/web-ccdv/thaythe_vattu_wifi/fn_sua_hopdong_vattu_tb',data),
    Layds_tram_quanly_thuebao: async (axios,data) =>axios.post('/web-ccdv/thaythe_vattu_wifi/layds_tram_quanly_thuebao',data),
    Lay_ds_hd_bh: async (axios,data) =>axios.post('/web-ccdv/thaythe_vattu_wifi/lay_ds_hd_bh',data),
    Fn_hths_vattu_tb: async (axios,data) =>axios.post('/web-ccdv/thaythe_vattu_wifi/fn_hths_vattu_tb',data),
    Lay_ds_hopdong_tb_theo_hdtb_id: async (axios,data) =>axios.post('/web-quantri/thutienphatsinh/lay_ds_hopdong_tb_theo_hdtb_id',data),
    Lay_tienhd_km_theo_hdtb: async (axios,data) =>axios.post('/web-hopdong/khoiphucthanhly/lay_tienhd_km_theo_hdtb',data),
    Capnhat_hd_bh_vattu_tb: async (axios,data) =>axios.post('/web-ccdv/thaythe_vattu_wifi/capnhat_hd_bh_vattu_tb',data),
    Lay_ds_thaythe_vattu_tb: async (axios,data) =>axios.post('/web-ccdv/thaythe_vattu_wifi/sp_lay_ds_thaythe_vattu_tb',data),
    LayHuongGiao_TiepNhan: async (axios, data) => axios.post('/web-hopdong/hopdong/lay_huonggiao_tiepnhan', data),
    Lay_ds_thaythe_file: async (axios, data) => axios.post('/web-ccdv/thaythe_vattu_wifi/lay_ds_thaythe_file', data),
    Kiemtra_tontai_makho: async (axios, data) => axios.post('/web-ccdv/thaythe_vattu_wifi/css_kho', data),
    Qlvt_mucdich: async (axios, data) => axios.post('/web-ccdv/thaythe_vattu_wifi/qlvt_mucdich', data),
    Lay_ds_tuvt_lhd_v2: async (axios, data) => axios.post('/web-ccdv/khaibaotsl/lay_ds_tuvt_lhd_v2', data),
    Fn_kiemtra_dm_vt: async (axios, data) => axios.post('/web-ccdv/khaibaotsl/fn_kiemtra_dm_vt', data),
    Qlvt_phieu_vt: async (axios, data) => axios.post('/web-ccdv/thaythe_vattu_wifi/qlvt_phieu_vt', data),
    Kiemtra_vtcapra: async (axios, data) => axios.post('/web-ccdv/khaibaotsl/kiemtra_vtcapra', data),
    Insert_phieu_vattu_v2: async (axios, data) => axios.post('/web-ccdv/khaibaotsl/insert_phieu_vattu_v2', data),
    sp_getdanhmucvt_dvt_vattu_id: async (axios, data) => axios.post('/web-ccdv/thaythe_vattu_wifi/sp_getdanhmucvt_dvt_vattu_id', data),
    sp_kiemtratb_sdvt: async (axios, data) => axios.post('/web-ccdv/khaibaotsl/sp_kiemtratb_sdvt', data),
    gan_thietbi_dacap: async (axios, data) => axios.post('/web-ccdv/thaythe_vattu_wifi/gan_thietbi_dacap', data),
    fn_kiemtra_vt_thuhoi: async (axios, data) => axios.post('/web-ccdv/khaibaotsl/fn_kiemtra_vt_thuhoi', data),
    sp_getthietbi: async (axios, data) => axios.post('/web-ccdv/khaibaotsl/sp_getthietbi', data),
    lay_ds_vattu_sd: async (axios, data) => axios.post('/web-ccdv/khaibaotsl/lay_ds_vattu_sd', data),
    get_sl_dd: async (axios, data) => axios.post('/web-ccdv/thaythe_vattu_wifi/get_sl_dd', data),
    capnhat_phieuvt_thuhoi: async (axios, data) => axios.post('/web-ccdv/khaibaotsl/capnhat_phieuvt_thuhoi', data),
    lay_tt_tranggbi: async (axios, data) => axios.post('/web-ccdv/khaibaotsl/lay_tt_tranggbi', data),
    lay_ds_vattu_th: async (axios, data) => axios.get(`/web-ccdv/thaythe_vattu_wifi/lay_ds_vattu_th?hdtb_id=${data.hdtb_id}&thuebao_id=${data.thuebao_id}`,data),
    KIEMTRA_MA_TB_LAP_HOPDONG_KHAC: async (axios, data) => axios.post('/web-hopdong/chuyendich/kiemtra_ma_tb_lap_hopdong_khac', data),
    sp_delete_hdtb_sub_by_hdtb_id: async (axios, data) => axios.post('/web-baohong/TiepNhanBaoHong/sp_delete_hdtb_sub_by_hdtb_id', data),
    fn_tt_giaophieu: async (axios, data) => axios.post('/web-tratruoc/thongtin_tratruoc_dn/fn_tt_giaophieu', data),
    fn_tt_tinh: async (axios, data) => axios.post('/web-tratruoc/thongtin_tratruoc_dn/fn_tt_tinh', data),
    kiemtra_phieu_3000_ttph: async (axios, data) => axios.get(`/web-thicong/tiepnhan-yc-tongdai/kiemtra_phieu_3000_ttph?vthuebao_id=${data.thuebao_id}`,data),

    Fn_them_hopdong_vattu_tb_v2: async (axios,data) =>axios.post('/web-ccdv/thaythe_vattu_wifi/fn_them_hopdong_vattu_tb_v2',data),
    Fn_sua_hopdong_vattu_tb_v2: async (axios,data) =>axios.post('/web-ccdv/thaythe_vattu_wifi/fn_sua_hopdong_vattu_tb_v2',data),
    lay_ds_hopdong_thuebao_ims: async (axios, hdtbId) => axios.get(`/web-hopdong/hopdong/lay_ds_hopdong_thuebao_ims?hdtbId=${hdtbId}`),
    lay_ds_hopdong_thuebao_codinh: async (axios,hdtbId) => axios.get(`web-hopdong/hopdong/lay_ds_hopdong_thuebao_codinh?hdtbId=${hdtbId}`),
    lay_ds_hopdong_thuebao_adsl: async (axios,hdtbId) => axios.get(`web-hopdong/hopdong/lay_ds_hopdong_thuebao_adsl?hdtbId=${hdtbId}`),
    lay_ds_hopdong_thuebao_mgwan: async (axios,hdtbId) => axios.get(`web-hopdong/hopdong/lay_ds_hopdong_thuebao_mgwan?hdtbId=${hdtbId}`),
    lay_ds_hdtb_tsl_theo_hdtb_id: async (axios,hdtbId) => axios.get(`web-hopdong/hopdong/lay_ds_hdtb_tsl_theo_hdtb_id?hdtbId=${hdtbId}`),
    lay_ds_hopdong_thuebao_gp: async (axios,hdtbId) => axios.get(`web-hopdong/hopdong/lay_ds_hopdong_thuebao_gp?hdtbId=${hdtbId}`),
    lay_ds_hopdong_thuebao_cntt: async (axios,hdtbId) => axios.get(`web-hopdong/hopdong/lay_ds_hopdong_thuebao_cntt?hdtbId=${hdtbId}`),
    lay_ds_dbtb_theo_khid_v3: async (axios, data) => axios.post('/web-ccdv/ban_thietbi_ttvt/lay_ds_dbtb_theo_khid_v3', data),
    lay_goi_cuoc_ban_tbi: async (axios, data) => axios.post('/web-ccdv/ban_thietbi_ttvt/lay_goi_cuoc_ban_tbi', data),
    lay_ds_gui_chitiet: async (axios, data) => axios.post('/web-ccdv/ban_thietbi_ttvt/lay_ds_gui_chitiet', data),
    kiemtra_kichhoat_mesh: async (axios,data) => axios.get(`tichhop/mesh_wifi/verifyDeviceActivation?serialNumber=${data.serialNumber}&areaCode=${data.areaCode}`,data),
    layds_tram_quanly_thuebao: async (axios,data) => axios.post(`/web-hopdong/thaythe_vattu_wifi/layds_tram_quanly_thuebao?thuebao_id=${data.thuebao_id}`,data),
    docfile_vt_thuebao: async (axios, data) => axios.post('/web-hopdong/hopdong/docfile_vt_thuebao', data),
    fn_hths_vattu_tb_docfile: async (axios, data) => axios.post('/web-quantri/vattu/fn_hths_vattu_tb_docfile', data),
    lay_ds_vattu_thanhtoan_thaythe: async (axios, data) => axios.post('/web-tratruoc/ob_ghtt/lay_ds_vattu_thanhtoan_thaythe', data),
    
}
