const collumns = {
    collumnsDSThueBao: [
        {
            fieldName: "ma_tb",
            headerText: "Mã thuê bao",
            allowSorting: false,
            allowFiltering: true,
            width: "150",
            textAlign: 'left',
            autoFit: "true",
        },
        {
            fieldName: "so_ao",
            headerText: "Số ảo",
            allowSorting: false,
            allowFiltering: true,
            textAlign: 'left',
            width: "100",
            autoFit: "true",
        },
        {
            fieldName: "ten_dvvt",
            headerText: "Dịch vụ",
            allowSorting: false,
            allowFiltering: true,
            textAlign: 'left',
            width: "150",
            autoFit: "true",
        },
        {
            fieldName: "loaihinh_tb",
            headerText: "Loại hình",
            allowSorting: false,
            allowFiltering: true,
            textAlign: 'left',
            width: "100",
            autoFit: "true",
        },
        {
            fieldName: "ten_tb",
            headerText: "Tên thuê bao",
            allowSorting: false,
            allowFiltering: true,
            textAlign: 'left',
            width: "100",
            autoFit: "true",
        },
        {
            fieldName: "diachi_ld",
            headerText: "Địa chỉ lắp đặt",
            allowSorting: false,
            allowFiltering: true,
            textAlign: 'left',
            width: "120",
            autoFit: "true",
        },
        {
            fieldName: "ttbl_ten",
            headerText: "HT Chuyển dổi",
            allowSorting: false,
            allowFiltering: true,
            textAlign: 'left',
            width: "100",
            autoFit: "true",
        },
        {
            fieldName: "trangthai_hd",
            headerText: "Trạng thái HĐ",
            textAlign: 'left',
            width: "100",
            autoFit: "true",
        },
        {
            fieldName: "tocdo",
            headerText: "Tốc độ",
            textAlign: 'left',
            width: "100",
            autoFit: "true",
        },
    ],
    collumnsDsPhieu: [
        {
            fieldName: "huonggiao",
            headerText: "",
            isGroupedColumn: true,
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            textAlign: 'left',
        },
        {
            fieldName: "dvg",
            headerText: "Đơn vị giao",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            textAlign: 'left',
        },
        {
            fieldName: "ngay_giao",
            headerText: "Ngày giao",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            textAlign: 'left',
        },
        {
            fieldName: "nv_giao",
            headerText: "Người giao",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            textAlign: 'left',
        },
        {
            fieldName: "nd_giao",
            headerText: "Nội dung giao",
            allowSorting: false,
            allowFiltering: true,
            textAlign: 'left',
            width: "100",
            autoFit: "true",
        },
        {
            fieldName: "dvn",
            headerText: "Đơn vị nhận",
            allowSorting: false,
            allowFiltering: true,
            textAlign: 'left',
            width: "100",
            autoFit: "true",
        },
        {
            fieldName: "ngay_tra",
            headerText: "Ngày trả",
            allowSorting: false,
            allowFiltering: true,
            textAlign: 'left',
            width: "100",
            autoFit: "true",
        },
        {
            fieldName: "nd_tra",
            headerText: "Nội dung trả",
            allowSorting: false,
            allowFiltering: true,
            textAlign: 'left',
            width: "120",
            autoFit: "true",
        },
        {
            fieldName: "lydotra",
            headerText: "Lý do trả",
            allowFiltering: true,
            width: "100",
            autoFit: "true",
            textAlign: 'left',
        },
        {
            fieldName: "ngay_th",
            headerText: "Ngày CN",
            allowSorting: false,
            allowFiltering: true,
            textAlign: 'left',
            width: "100",
            autoFit: "true",
        },
        {
            fieldName: "so_dt",
            headerText: "Điện thoại liên hệ",
            allowSorting: false,
            allowFiltering: true,
            textAlign: 'left',
            width: "100",
            autoFit: "true",
        },
        {
            fieldName: "trangthai_ph",
            headerText: "Trạng thái phiếu",
            allowSorting: false,
            allowFiltering: true,
            textAlign: 'left',
            width: "120",
            autoFit: "true",
        },
    ],
}

export default collumns
