import axios from "axios"
import { data } from "jquery"
export default {
    LAY_DS_THAMSO_MD: (data) => axios.post("web-ccdv/khaibaotsl/lay_ds_thamso_md_mats", { ma_ts: "" }).then(rs => rs.data.data),
    LAY_THAMSO_MACDINH: (data) => axios.post("web-hopdong/lapdatmoi/lay_thamso_macdinh", { vma_ts: "" }).then(rs => rs.data.data),
    THANH_LY_MAP: (id_neo, tinh_id, phanvung_id) => axios.post("web-hopdong/thanhly/thanh_ly_map_id", {
        "id_neo": id_neo,
        "in_table":"css.tinh",
        "in_dk": `where tinh_id = ${tinh_id} AND phanvung_id = ${phanvung_id}`
      }).then(rs => rs.data.data),
    Ht_NhomTon_Combobox: () => axios.get("web-quantri/danhmuc-chung/BAOHONG_NHOMTON").then(rs => rs.data.data),
    HT_DichVuVT_Combobox_BH: () => axios.get("/web-quantri/danhmuc-chung/CSS_DICHVU_VT").then(rs => rs.data.data),
    Lay_ds_nhanvien_thuchien_theo_dv: () => axios.get("web-ccdv/khaibaoims/sp_lay_ds_nhanvien_theo_donvi").then(rs => rs.data.data),
    LayDSTramVT: () => axios.post("web-ccdv/xuly_nghiemthubaohong/sp_lay_ds_tramthicong_v2", {"loaidv_id":5}).then(rs => rs.data.data),
    Lay_ds_phieu_hoancong_bh_v4: (body) => axios.post("web-ccdv/xuly_nghiemthubaohong/lay_ds_phieu_hoancong_bh_v4", body).then(rs => rs.data.data),
    Lay_ds_phieu_hoancong_bh_v5: (body) => axios.post("web-ccdv/xuly_nghiemthubaohong/lay_ds_phieu_hoancong_bh_v5", body).then(rs => rs.data.data),
    Lay_ds_phieu_baoduong_ttdh: (body) => axios.post("web-ccdv/xuly_nghiemthubaohong/lay_ds_phieu_baoduong_ttdh", body).then(rs => rs.data.data),
    Lay_ds_phieu_hoancong_bh_v6: (body) => axios.post("web-ccdv/xuly_nghiemthubaohong/lay_ds_phieu_hoancong_bh_v6", body).then(rs => rs.data.data),
    Lay_ds_phieu_theodoi_cho_ht: (body) => axios.post("web-ccdv/xuly_nghiemthubaohong/lay_ds_phieu_theodoi_cho_ht", body).then(rs => rs.data.data),
    Laythongtin_table: (body) => axios.post("web-ccdv/khaibaoims/lay_thongtin_table", body).then(rs => rs.data.data),
    lay_ds_thaotac_theo_luong_id: (body) => axios.post("web-ccdv/xuly_nghiemthubaohong/sp_lay_ds_thaotac_theo_luong_id", body).then(rs => rs.data.data),
    Lay_ds_nhom_NN: (body) => axios.post("web-ccdv/xuly_nghiemthubaohong/sp_lay_ds_nhom_nn", body).then(rs => rs.data.data),
    HT_NHOM_NN_V2: (body) => axios.post("web-ccdv/xuly_nghiemthubaohong/sp_lay_ds_nhom_nn_v2", body).then(rs => rs.data.data),
    Lay_ds_quytrinh_bh: (body) => axios.post("web-ccdv/xuly_nghiemthubaohong/sp_lay_ds_quytrinh_bh_theo_dichvuvt_id", body).then(rs => rs.data.data),
    Lay_ds_TinhTrang: (body) => axios.post("web-ccdv/xuly_nghiemthubaohong/sp_lay_ds_tinhtrang", body).then(rs => rs.data.data),
    Lay_ds_nguyennhan_baohong_v2: (body) => axios.post("web-ccdv/xuly_nghiemthubaohong/lay_ds_nguyennhan_baohong_v2", body).then(rs => rs.data.data),
    Lay_ds_nguyennhan: (body) => axios.post("web-ccdv/xuly_nghiemthubaohong/sp_lay_ds_nguyennhan_hong", body).then(rs => rs.data.data),
    Lay_ds_lydoton_theo_lhtb: (body) => axios.post("web-ccdv/xuly_nghiemthubaohong/sp_lay_ds_baohong_bc_thicong", body).then(rs => rs.data.data),
    LAY_DS_NHANVIEN_THEO_PHIEU_ID: (body) => axios.get(`/web-baohong/baohong/lay_ds_nhanvien_theo_phieu_id?phieu_id=${body.phieu_id}&kieu_id=${body.kieu_id}`, body).then(rs => rs.data.data),
    Lay_ds_thongtin_kythuat: (body) => axios.post("web-baohong/TiepNhanBaoHong/lay_ds_thongtin_kythuat", body).then(rs => rs.data.data),
    HT_DonVi_loaidv_Combobox: (data) => axios.post('web-ccdv/tien_trinh_bao_hong/sp_lay_donvi_quanly_ldv', data).then(rs => rs.data.data),
    LAY_DS_THAMSO_MD_MATS: (data) => axios.post('web-ccdv/khaibaotsl/lay_ds_thamso_md_mats', data).then(rs => rs.data.data),
    HT_DonViCon_loaidv_Combobox: (data) => axios.post('web-thicong/hoinghi_truyenhinh/ht_donvicon_loaidv_combobox', data).then(rs => rs.data.data),
    LAY_DS_NHANVIEN_THEO_PHIEU_V2: (data) => axios.post('web-ccdv/tien_trinh_bao_hong/lay_ds_nhanvien_theo_phieu_v2', data).then(rs => rs.data.data),
    Delete_giaophieu_nv_all: (data) => axios.post('web-ccdv/tien_trinh_bao_hong/sp_xoa_giaophieu_nv_all', data).then(rs => rs.data.data),
    Delete_giaophieu_nv: (data) => axios.post('web-ccdv/hoanthien_hoso_doiso_account/sp_delete_giaophieu_nv', data).then(rs => rs.data.data),
    LAY_NOIDUNG_SMS_GIAOVIEC_V2: (data) => axios.post('web-ccdv/hoanthien_hoso_doiso_account/sp_delete_giaophieu_nv', data).then(rs => rs.data.data),
    SendSMS: (data) => axios.post('web-hopdong/xac_nhan_giahan_datcoc_tt/send_sms', data).then(rs => rs.data.data),
    CapNhat_status: (data) => axios.post('web-ccdv/tien_trinh_bao_hong/sp_capnhat_status', data).then(rs => rs.data.data),
    insert_giaophieu_nv: (data) => axios.post('web-ccdv/hoanthien_hoso_doiso_account/sp_insert_giaophieu_nv', data).then(rs => rs.data.data),
    LAY_DS_PHIEUVT_HDBH: (data) => axios.post('web-ccdv/xuly_nghiemthubaohong/sp_lay_ds_phieuvt_hdbh', data).then(rs => rs.data.data),
    Giaophieu_chuyen_theodoi_v2: (data) => axios.post('web-ccdv/xuly_nghiemthubaohong/giaophieu_chuyen_theodoi_v2', data).then(rs => rs.data.data),
    LAY_DS_THAMSO_MACDINH_DV: (data) => axios.post('web-ccdv/xuly_nghiemthubaohong/lay_ds_thamso_macdinh_dv', data).then(rs => rs.data.data),
    CSS_TINH: async (data, header) => axios.get('web-quantri/danhmuc-chung/CSS_TINH', data, header),
    LAY_DS_DB_ADSL_THEO_TBID: async (data, header) => axios.get(`web-hopdong/hopdong/lay_ds_danhba_adsl?thueBaoId=${data.thueBaoId}`, data, header),
    fn_ntbh_nghiemthu: (data) => axios.post('web-ccdv/xuly_nghiemthubaohong/fn_ntbh_nghiemthu', data),
    fn_ntbh_hoanthanh_nhieuphieu: (data) => axios.post('web-ccdv/xuly_nghiemthubaohong/fn_ntbh_hoanthanh_nhieuphieu', data),
    fn_ntbh_kiemtra_phieu: (data) => axios.post('web-ccdv/xuly_nghiemthubaohong/fn_ntbh_kiemtra_phieu', data),
    ay_ds_thongbao_suco_ttvt: (data) => axios.post('web-ccdv/xuly_nghiemthubaohong/lay_ds_thongbao_suco_ttvt', data),
    fn_ntbh_capnhatkq_nhieuphieu: (data) => axios.post('web-ccdv/xuly_nghiemthubaohong/fn_ntbh_capnhatkq_nhieuphieu', data),
    lay_ds_phieu_hoancong_bh_119: (data) => axios.post('web-ccdv/xuly_nghiemthubaohong/lay_ds_phieu_hoancong_bh_119', data),
    lay_toado_lapdat: (data) => axios.post('web-ccdv/xuly_nghiemthubaohong/lay_toado_lapdat', data),
    capnhat_toado_thuebao_v2: (data) => axios.post('web-ccdv/xuly_nghiemthubaohong/capnhat_toado_thuebao_v2', data),
    fn_ntbh_chuyenttvt: (data) => axios.post('web-ccdv/xuly_nghiemthubaohong/fn_ntbh_chuyenttvt', data),
    fn_lay_ttbh_id_theo_phieu_id: (data) => axios.post('web-ccdv/xuly_nghiemthubaohong/fn_lay_ttbh_id_theo_phieu_id', data),
    fn_ntbh_baoton: (data) => axios.post('web-ccdv/xuly_nghiemthubaohong/fn_ntbh_baoton', data),
    fn_ntbh_chuyenttdh: (data) => axios.post('web-ccdv/xuly_nghiemthubaohong/fn_ntbh_chuyenttdh', data),
    fn_ntbh_capnhatkq: (data) => axios.post('web-ccdv/xuly_nghiemthubaohong/fn_ntbh_capnhatkq', data),
    sp_lay_nvtn_theo_baohong_id: (data) => axios.post('web-tracuu/tracuubaohong/sp_lay_nvtn_theo_baohong_id', data),
    Lay_tinnhan_mau_nhacviec: (data) => axios.post('web-tracuu/tracuubaohong/lay_tinnhan_mau_nhacviec', data),
    LoadTienTrinhSMS: (data) => axios.post('web-tracuu/tracuubaohong/sp_lay_tientrinh_nvn_theo_id', data),
    fn_LAY_NOIDUNG_SMS_GIAOVIEC_V2: (data) => axios.post('web-thicong/hoinghi_truyenhinh/lay_noidung_sms_giaoviec_v2', data),
    LoadTreeview: (data) => axios.post('web-quantri/donvi/SP_GIAOSIM_GET_TREEVIEW', data),
    getUserMap: (data) => axios.post('web-thicong/hths-thaydoi-tocdo/fn_map_id', data),
    LAY_NV_GIAO_PHKH_V2: (data) => axios.post('web-ccdv/tientrinh-khieunai/lay_nv_giao_phkh_v2', data),
    SP_LAY_DONVI_ID_THEO_MA_ND: (data) => axios.post('web-gqkn/TraCuuPhieuKN/sp_lay_donvi_id_theo_ma_nd', data),
    Kiemtra_thoigian_nhacviec_bh: (data) => axios.post('web-tracuu/tracuubaohong/kiemtra_thoigian_nhacviec_bh', data),
    SendSMS_NhacViec: (data) => axios.post('/tichhop/sms/send', data),
    sp_capnhat_tientrinh_sms: (data) => axios.post('web-tracuu/tracuubaohong/sp_capnhat_tientrinh_sms', data),
    get_data_by_url: (data) => axios.get(`/tichhop/util/download?url=${data.url}`, data),
    fn_ntbh_hoancong: (data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/fn_ntbh_hoancong', data),
    lay_ds_phieu_phoihop_khdn: (data) => axios.post(`/web-ccdv/xuly_nghiemthubaohong/lay_ds_phieu_phoihop_khdn`, data),
    capnhat_giaophieu_ph: (data) => axios.post(`/web-bancheo/tracuu/capnhat_giaophieu_ph`, data),
    thongtin_nguoidung2: () => axios.post('quantri/user/thongtin_nguoidung2', {}),
    sp_capnhat_nhanvien_giuphieu: (data) => axios.post(`/web-ccdv/xuly_nghiemthubaohong/sp_capnhat_nhanvien_giuphieu`, data),
    lay_thongtin_nghiemthu_bh: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/lay_thongtin_nghiemthu_bh', data),
    fn_capnhat_trangthai_baohongbc: (data) => axios.post('/web-baohong/baohong/fn_capnhat_trangthai_baohongbc', data),
    hoanthanh_bh_giaophieu_ph: (data) => axios.post('/web-baohong/xuly_nghiemthubaohong/hoanthanh_bh_giaophieu_ph', data),
    hoanthanh_bh_giaophieu_ph_v2: (data) => axios.post('/web-baohong/xuly_nghiemthubaohong/hoanthanh_bh_giaophieu_ph_v2', data),
    fn_capnhat_trangthai_baohongbc_v2: (data) => axios.post('/web-baohong/baohong/fn_capnhat_trangthai_baohongbc_v2', data),
    fn_tt_nguoidung: (axios, data) => axios.post(`/web-tratruoc/thongtin_tratruoc_dn/fn_tt_nguoidung`, data),
  }