/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.25).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.dto.*;
import io.swagger.model.request.*;
import io.swagger.model.response.BasePageResponse;
import io.swagger.model.response.BaseResponse;
import io.swagger.model.response.PageInfo;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import vn.vnptit.sapi.oneapp.model.request.PrecheckXlscKpiRequest;
import vn.vnptit.sapi.oneapp.model.request.SP_GIAOVIEC_NHANVIEN_XHH_REQUEST;

import javax.annotation.Generated;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;
import java.util.Map;

@Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2021-03-16T07:34:18.357Z[GMT]")
@Validated
@RequestMapping(value = "/cskh")
public interface ChamSocKhachHangApi {
    @Operation(summary = "", description = "STT 36 - Đơn vị", tags = {"Danh mục"})
    @RequestMapping(value = "/donVi", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> danhMucDonViGet();

    @Operation(summary = "CSKH-Xóa phiếu sự cố", tags = {"CSKH"})
    @RequestMapping(value = "/xoaPhieuSuCo", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> xoaPhieuSuCo(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Mã sự cố", required = true, schema = @Schema()) @Valid @RequestParam(value = "maSc", required = false) String maSc);

    @Operation(summary = "CSKH-Đăng ký sự cố", tags = {"CSKH"})
    @RequestMapping(value = "/dangKySuCo", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> dangKySuCo(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody DangKySuCoRequest requestBody);

    @Operation(summary = "CSKH-Đăng ký sự cố", tags = {"CSKH"})
    @RequestMapping(value = "/dangKySuCoV2", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> dangKySuCoV2(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody Map<?,?> requestBody);

    @Operation(summary = "CSKH-Khóa phiếu sự cố", tags = {"CSKH"})
    @RequestMapping(value = "/khoaPhieuSuCo", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> khoaPhieuSuCoV2(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody KhoaPhieuSuCoRequest requestBody);

//    @Operation(summary = "CSKH-Khóa phiếu sự cố", tags = {"CSKH"})
//    @RequestMapping(value = "/khoaPhieuSuCoV2", produces = {"application/json"}, method = RequestMethod.POST)
//    ResponseEntity<BaseResponse<Void>> khoaPhieuSuCoV2(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody KhoaPhieuSuCoRequest requestBody);
    @RequestMapping(value = "/khoaPhieuSuCoV3", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> khoaPhieuSuCoV3(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody KhoaPhieuSuCoV3Request requestBody);

    @Operation(summary = "CSKH-Khóa phiếu sự cố MNV", tags = {"CSKH"})
    @RequestMapping(value = "/khoaPhieuSuCoV4", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> khoaPhieuSuCoV4(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody KhoaPhieuSuCoRequest requestBody);

    @Operation(summary = "CSKH-Khóa phiếu sự cố MNV", tags = {"CSKH"})
    @RequestMapping(value = "/khoaPhieuSuCoV5", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> khoaPhieuSuCoV5(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody KhoaPhieuSuCoV3Request requestBody);

    @Operation(summary = "CSKH-Trả phiếu xử lý sự cố", tags = {"CSKH"})
    @RequestMapping(value = "/traPhieuSuCo", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> traPhieuXuLySuCo(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody TraPhieuRequest requestBody);

    @Operation(summary = "CSKH-Trả phiếu nghiệm thu", tags = {"CSKH"})
    @RequestMapping(value = "/traPhieuNghiemThu", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> traPhieuNghiemThu(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody TraPhieuRequest requestBody);

    @Operation(summary = "CSKH-Báo tồn phiếu xử lý sự cố", tags = {"CSKH"})
    @RequestMapping(value = "/baoTonPhieuSuCo", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> baoTonPhieuSuCo(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody BaoTonRequest requestBody);

    @Operation(summary = "CSKH-Giao phiếu xử lý sự cố/ Giao phiếu sự cố - Giao phiếu xử lý", tags = {"CSKH"})
    @RequestMapping(value = "/giaoPhieuXuLy", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> giaoPhieuXuLy(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody GiaoPhieuXuLyRequest requestBody);

    @Operation(summary = "CSKH-Giao phiếu xử lý sự cố/ Giao phiếu sự cố - Giao phiếu xử lý", tags = {"CSKH"})
    @RequestMapping(value = "/giaoPhieuXuLyTTS", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> giaoPhieuXuLyTTSV2(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody GiaoPhieuXuLyTTSRequest requestBody);

//    @Operation(summary = "CSKH-Giao phiếu xử lý sự cố/ Giao phiếu sự cố - Giao phiếu xử lý", tags = {"CSKH"})
//    @RequestMapping(value = "/giaoPhieuXuLyTTSV2", produces = {"application/json"}, method = RequestMethod.POST)
//    ResponseEntity<BaseResponse<Void>> giaoPhieuXuLyTTSV2(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody GiaoPhieuXuLyTTSRequest requestBody);

    @Operation(summary = "CSKH-Giao phiếu xử lý sự cố/ Giao phiếu sự cố - Lấy danh sách mức độ sự cố", tags = {"CSKH"})
    @RequestMapping(value = "/layDSMucDoSuCo", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<MucDoSuCo>>> layDSMucDoSuCo();

    @Operation(summary = "CSKH-Giao phiếu xử lý sự cố/ Giao phiếu sự cố - Lấy danh sách hướng giao", tags = {"CSKH"})
    @RequestMapping(value = "/layDSHuongGiao", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<HuongGiao>>> layDSHuongGiao(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Quy trinh ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "quyTrinhId", required = false) String quyTrinhId);

    @Operation(summary = "CSKH-Giao phiếu xử lý sự cố/ Giao phiếu sự cố - Lấy danh sách quy trình", tags = {"CSKH"})
    @RequestMapping(value = "/layDSQuyTrinh", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<QuyTrinh>>> layDSQuyTrinh();

    @Operation(summary = "CSKH-Giao phiếu xử lý sự cố/ Giao phiếu sự cố - Lấy danh sách tình trạng xử lý", tags = {"CSKH"})
    @RequestMapping(value = "/layDSTinhTrangXuLy", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<List<TinhTrangXuLy>>> layDSTinhTrangXuLy(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody LayDSTinhTrangXuLyRequest requestBody);

    @Operation(summary = "CSKH-Giao phiếu xử lý sự cố/ Giao phiếu sự cố - Lấy danh sách nguồn sự cố", tags = {"CSKH"})
    @RequestMapping(value = "/layDSNguonSuCo", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<NguonSuCo>>> layDSNguonSuCo();

    @Operation(summary = "CSKH-Giao phiếu xử lý sự cố/ Giao phiếu sự cố - Lấy danh sách phiếu giao xử lý sự cố", tags = {"CSKH"})
    @RequestMapping(value = "/layDSPhieuGiaoXuLySuCo", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<List<PhieuGiaoXuLySuCo>>> layDSPhieuGiaoXuLySuCo(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody LayDSPhieuGiaoXuLySuCoRequest requestBody);

    @Operation(summary = "CSKH-Giao phiếu xử lý sự cố/ Giao phiếu sự cố - Lấy danh sách đơn vị giao phiếu", tags = {"CSKH"})
    @RequestMapping(value = "/layDSDonViGiaoPhieu", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DonViGiaoPhieu>>> layDSDonViGiaoPhieu(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Hướng giao ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "huongGiaoId", required = false) String huongGiaoId);

    @Operation(summary = "CSKH-Giao phiếu xử lý sự cố/ Giao phiếu sự cố - Lấy danh sách trạng thái phiếu", tags = {"CSKH"})
    @RequestMapping(value = "/layDSTrangThaiPhieu", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<TrangThaiPhieu>>> layDSTrangThaiPhieu();

    @Operation(summary = "CSKH-Danh sách sự cố/ Thông tin tiếp nhận sự cố mạng viễn thông - Xóa phiếu sự cố", tags = {"CSKH"})
    @RequestMapping(value = "/xoaPhieuTMP", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<Void>> xoaPhieuTMP(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Mã sự cố", required = true, schema = @Schema()) @Valid @RequestParam(value = "maSC", required = false) String maSC);

    @Operation(summary = "CSKH-Danh sách sự cố/ Thông tin tiếp nhận sự cố mạng viễn thông - Lấy sự cố ID", tags = {"CSKH"})
    @RequestMapping(value = "/laySuCoId", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<String>> laySuCoId();

    @Operation(summary = "CSKH-Danh sách sự cố/ Thông tin tiếp nhận sự cố mạng viễn thông - Tiếp nhận sự cố tạm version 2", tags = {"CSKH"})
    @RequestMapping(value = "/tiepNhanSuCoV2", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> tiepNhanSuCoV2(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody TiepNhanSuCoV2Request requestBody);

    @Operation(summary = "CSKH-Danh sách sự cố/ Thông tin tiếp nhận sự cố mạng viễn thông - Tiếp nhận sự cố tạm version 3", tags = {"CSKH"})
    @RequestMapping(value = "/tiepNhanSuCoV3", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> tiepNhanSuCoV3(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody TiepNhanSuCoV3Request requestBody);

    @Operation(summary = "CSKH-Danh sách sự cố/ Thông tin tiếp nhận sự cố mạng viễn thông - Lấy danh sách tình trạng cntt", tags = {"CSKH"})
    @RequestMapping(value = "/layDSTrangThaiCNTT", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<TrangThaiCNTT>>> layDSTrangThaiCNTT(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Sự cố ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "suCoId", required = false) String suCoId);

    @Operation(summary = "CSKH-Danh sách sự cố/ Thông tin tiếp nhận sự cố mạng viễn thông - Lấy danh sách tình trạng mvt", tags = {"CSKH"})
    @RequestMapping(value = "/layDSTinhTrangMVT", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<TrangThaiMVT>>> layDSTinhTrangMVT(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Sự cố ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "suCoId", required = false) String suCoId);

    @Operation(summary = "CSKH-Danh sách sự cố/ Thông tin tiếp nhận sự cố mạng viễn thông - Lấy danh sách tình trạng", tags = {"CSKH"})
    @RequestMapping(value = "/layDSTinhTrang", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<TinhTrang>>> layDSTinhTrang();

    @Operation(summary = "CSKH-Danh sách sự cố/ Thông tin tiếp nhận sự cố mạng viễn thông - Lấy danh sách nhân viên", tags = {"CSKH"})
    @RequestMapping(value = "/layDSNhanVien", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<NhanVien>>> layDSNhanVien(@Parameter(in = ParameterIn.QUERY, description = "Tên nhân viên", required = true, schema = @Schema()) @Valid @RequestParam(value = "tenNV", required = false) String tenNV);

    @Operation(summary = "CSKH-Danh sách sự cố/ Thông tin tiếp nhận sự cố mạng viễn thông - Lấy danh sách nhóm sự cố theo nhân viên", tags = {"CSKH"})
    @RequestMapping(value = "/layDSNhomSuCoTheoNV", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<NhomSuCo>>> layDSNhomSuCoTheoNV();

    @Operation(summary = "CSKH-Danh sách sự cố/ Thông tin tiếp nhận sự cố mạng viễn thông - Cập nhật sự cố tmp", tags = {"CSKH"})
    @RequestMapping(value = "/capNhatSuCoTmp", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> capNhatSuCoTmp(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody CapNhatSuCoTMPRequest requestBody);

    @Operation(summary = "CSKH-Danh sách sự cố/ Thông tin tiếp nhận sự cố mạng viễn thông - Cập nhật sự cố", tags = {"CSKH"})
    @RequestMapping(value = "/capNhatSuCo", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> capNhatSuCo(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody CapNhatSuCoRequest requestBody);

    @Operation(summary = "CSKH-Danh sách sự cố/ Thông tin tiếp nhận sự cố mạng viễn thông - Lấy danh sách ảnh chụp sự cố smp", tags = {"CSKH"})
    @RequestMapping(value = "/layDSAnhChupSuCoSMP", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<AnhChupSuCoSMP>> layDSAnhChupSuCoSMP(@Parameter(in = ParameterIn.QUERY, description = "Mã sự cố", required = true, schema = @Schema()) @Valid @RequestParam(value = "maSC", required = false) String maSC);

    @Operation(summary = "CSKH-Danh sách sự cố/ Thông tin tiếp nhận sự cố mạng viễn thông - Cập nhật ảnh chụp tiếp nhận sự cố", tags = {"CSKH"})
    @RequestMapping(value = "/capNhatAnhChupTiepNhanSC", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<String>> capNhatAnhChupTiepNhanSC(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody CapNhatAnhChupTiepNhanSCRequest requestBody);

    @Operation(summary = "CSKH-Tiến trình sự cố/ Tiến trình sự cố - Lấy danh sách tiến trình sự cố", tags = {"CSKH"})
    @RequestMapping(value = "/layDSTienTrinhSuCo", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<List<TienTrinhSuCo>>> layDSTienTrinhSuCo(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody LayDSTienTrinhSuCoRequest requestBody);

    @Operation(summary = "CSKH-Tiến trình sự cố/ Tiến trình sự cố - Lấy danh sách tiến trình sự cố", tags = {"CSKH"})
    @RequestMapping(value = "/layDSTienTrinhSuCoPT", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BasePageResponse<List<TienTrinhSuCo>, PageInfo>> layDSTienTrinhSuCoPT(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody LayDSTienTrinhSuCoRequest requestBody);

    @Operation(summary = "CSKH-Tiến trình sự cố/ Tiến trình sự cố - Lấy danh sách đơn vị", tags = {"CSKH"})
    @RequestMapping(value = "/layDSDonVi", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DonVi>>> layDSDonVi();

    @Operation(summary = "CSKH-Tiến trình sự cố/ Tiến trình sự cố - Lấy danh sách trạng thái sự cố", tags = {"CSKH"})
    @RequestMapping(value = "/layDSTrangThaiSuCo", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<TrangThaiSuCo>>> layDSTrangThaiSuCo();

    @Operation(summary = "CSKH-Tiến trình sự cố/ Danh sách tiến trình - Lấy danh sách tiến trình sự cố 2", tags = {"CSKH"})
    @RequestMapping(value = "/layDSTienTrinhSuCo2", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<TienTrinhSuCo2>>> layDSTienTrinhSuCo2(@Parameter(in = ParameterIn.QUERY, description = "Sự cố ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "suCoId", required = false) String suCoId);

    @Operation(summary = "CSKH-Tiến trình sự cố/ Danh sách tiến trình - Thêm tiến trình (them_tientrinh)", tags = {"CSKH"})
    @RequestMapping(value = "/themTienTrinh", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<String>> themTienTrinh(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody ThemTienTrinhRequest requestBody);

    @Operation(summary = "CSKH-Tiến trình sự cố/ Danh sách tiến trình - Update tiến trình", tags = {"CSKH"})
    @RequestMapping(value = "/capNhatTienTrinh", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<String>> capNhatTienTrinh(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody CapNhatTienTrinhRequest requestBody);

    @Operation(summary = "CSKH-Tiến trình sự cố/ Danh sách tiến trình - Xóa tiến trình", tags = {"CSKH"})
    @RequestMapping(value = "/xoaTienTrinh", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<String>> xoaTienTrinh(@Parameter(in = ParameterIn.QUERY, description = "Tiến trình sự cố ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "tienTrinhScId", required = false) String tienTrinhScId);

    @Operation(summary = "CSKH-Danh sách sự cố/ Danh sách sự cố đã phân nhóm - Lấy danh sách sự cố đã phân nhóm", tags = {"CSKH"})
    @RequestMapping(value = "/layDSSuCoDPN", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<SuCoDPN>>> layDSSuCoDPN(@Parameter(in = ParameterIn.QUERY, description = "Nguồn sự cố ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "nguonScId", required = false) String nguonScId);

    @Operation(summary = "CSKH-Danh sách sự cố/ Danh sách sự cố đã phân nhóm - Lấy danh sách sự cố đã phân nhóm", tags = {"CSKH"})
    @RequestMapping(value = "/layDSSuCoDPNPT", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BasePageResponse<List<SuCoDPN>, PageInfo>> layDSSuCoDPNPT(@Parameter(in = ParameterIn.QUERY, description = "Nguồn sự cố ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "nguonScId", required = false) String nguonScId, Integer pageNum, Integer pageRec, Long totalRow);

    @Operation(summary = "CSKH-Danh sách sự cố/ Danh sách sự cố đã phân nhóm - SP_go_nhom_suco", tags = {"CSKH"})
    @RequestMapping(value = "/goNhomSuCo", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<Void>> goNhomSuCo(@Parameter(in = ParameterIn.QUERY, description = "Sự cố ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "suCoId", required = false) String suCoId);

    @Operation(summary = "CSKH-Danh sách sự cố/ Danh sách sự cố đã phân nhóm - Xóa phiếu sự cố", tags = {"CSKH"})
    @RequestMapping(value = "/xoaPhieu", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<SuCoDPN>> xoaPhieu(@Parameter(in = ParameterIn.QUERY, description = "Sự cố ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "suCoId", required = false) String suCoId);

    @Operation(summary = "CSKH-Danh sách sự cố/ Danh sách sự cố chưa phân nhóm - Lấy danh sách sự cố chưa phân nhóm", tags = {"CSKH"})
    @RequestMapping(value = "/layDSSuCoCPN", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<SuCoCPN>>> layDSSuCoCPN(@Parameter(in = ParameterIn.QUERY, description = "Nguồn sự cố ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "nguonScId", required = false) String nguonScId);

    @Operation(summary = "CSKH-Danh sách sự cố/ Danh sách sự cố chưa phân nhóm - Lấy danh sách sự cố chưa phân nhóm", tags = {"CSKH"})
    @RequestMapping(value = "/layDSSuCoCPNPT", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BasePageResponse<List<SuCoCPN>, PageInfo>> layDSSuCoCPNPT(@Parameter(in = ParameterIn.QUERY, description = "Nguồn sự cố ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "nguonScId", required = false) String nguonScId, Integer pageNum, Integer pageRec, Long totalRow);

    @Operation(summary = "CSKH-Danh sách sự cố/ Danh sách sự cố chưa phân nhóm - Gán nhóm sự cố", tags = {"CSKH"})
    @RequestMapping(value = "/ganNhomSuCo", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> ganNhomSuCo(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody GanNhomSuCoRequest requestBody);

    @Operation(summary = "CSKH-Giao phiếu xử lý sự cố/ Khóa phiếu sự cố - Lấy danh sách nguyên nhân", tags = {"CSKH"})
    @RequestMapping(value = "/layDSNguyenNhan", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<NguyenNhan>> layDSNguyenNhan(@Parameter(in = ParameterIn.QUERY, description = "Nhóm nguyên nhân ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "nhomNNId", required = false) String nhomNNId);

    @Operation(summary = "CSKH-Nghiệm thu/ Nghiệm thu xử lý sự cố - Lấy danh sách phiếu nghiệm thu xử lý", tags = {"CSKH"})
    @RequestMapping(value = "/layDSPhieuNghiemThuXL", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<List<PhieuNghiemThuXL>>> layDSPhieuNghiemThuXL(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody LayDSPhieuNghiemThuXLRequest requestBody);

    @Operation(summary = "CSKH-Nghiệm thu/ Nghiệm thu xử lý sự cố - Lấy danh sách phiếu nghiệm thu xử lý", tags = {"CSKH"})
    @RequestMapping(value = "/layDSPhieuNghiemThuXLPT", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BasePageResponse<List<PhieuNghiemThuXL>, PageInfo>> layDSPhieuNghiemThuXLPT(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody LayDSPhieuNghiemThuXLRequest requestBody);

    /*
    @Operation(summary = "CSKH-Nghiệm thu/ Nghiệm thu xử lý sự cố - Lấy danh sách phiếu nghiệm thu xử lý V2", tags = {"CSKH"})
    @RequestMapping(value = "/layDSPhieuNghiemThuXLPT2", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BasePageResponse<List<PhieuNghiemThuXL>, PageInfo>> layDSPhieuNghiemThuXLPT2(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody LayDSPhieuNghiemThuXLRequest requestBody);
    */
    @Operation(summary = "CSKH-Nghiệm thu/ Nghiệm thu xử lý sự cố - Lấy danh sách phiếu cập nhật kết quả xử lý sự cố", tags = {"CSKH"})
    @RequestMapping(value = "/layDSPhieuCapNhatKQXL", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<List<PhieuCapNhatKQXL>>> layDSPhieuCapNhatKQXL(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody LayDSPhieuCapNhatKQXLRequest requestBody);

    @Operation(summary = "CSKH-Nghiệm thu/ Nghiệm thu xử lý sự cố - Lấy danh sách phiếu cập nhật kết quả xử lý sự cố", tags = {"CSKH"})
    @RequestMapping(value = "/layDSPhieuCapNhatKQXLPT", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BasePageResponse<List<PhieuCapNhatKQXL>, PageInfo>> layDSPhieuCapNhatKQXLPT(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody LayDSPhieuCapNhatKQXLRequest requestBody);

    @Operation(summary = "CSKH-Nghiệm thu/ Nghiệm thu xử lý sự cố - Cập nhật ghi chú xử lý phiếu Cập nhật kết quả xử lý sự cố", tags = {"CSKH"})
    @RequestMapping(value = "/capNhatGhiChu", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> capNhatGhiChu(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody CapNhatGhiChuRequest requestBody);

    @Operation(summary = "CSKH-Nghiệm thu/ Chi tiết nghiệm thu sự cố - Lấy danh sách phần tử mạng cần XL", tags = {"CSKH"})
    @RequestMapping(value = "/layDSPhanTuMangCanXL", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<PhanTuMangCanXL>>> layDSPhanTuMangCanXL(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Phiếu ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "phieuId", required = false) String phieuId);

    @Operation(summary = "CSKH-Nghiệm thu/ Chi tiết nghiệm thu sự cố - Lấy danh sách phiếu điều nghiệm thu của phiếu Nghiệm thu sự cố", tags = {"CSKH"})
    @RequestMapping(value = "/layDSPhieuDieuNghiemThu", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<PhieuDieuNghiemThu>>> layDSPhieuDieuNghiemThu(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Sự cố ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "suCoId", required = false) String suCoId);

    @Operation(summary = "CSKH-Nghiệm thu/ Nghiệm thu xử lý sự cố - Cập nhật ghi chú phần tử mạng", tags = {"CSKH"})
    @RequestMapping(value = "/capNhatGhiChuPtm", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> capNhatGhiChuPtm(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody CapNhatGhiChuPtmRequest requestBody);

    @Operation(summary = "CSKH-Nghiệm thu/ Nghiệm thu xử lý sự cố - Hoàn công phiếu xử lý sự cố", tags = {"CSKH"})
    @RequestMapping(value = "/hoanCongXLSuCo", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> hoanCongXLSuCo(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody HoanCongXLSuCoRequest requestBody);

    @Operation(summary = "CSKH-Nghiệm thu/ Nghiệm thu xử lý sự cố - Cập nhật ghi chú và phiếu điều xử lý", tags = {"CSKH"})
    @RequestMapping(value = "/nghiemThuPhieuXL", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> nghiemThuPhieuXL(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody NghiemThuPhieuXLRequest requestBody);

    @Operation(summary = "CSKH-Nghiệm thu/ Nghiệm thu xử lý sự cố - Lấy ảnh chụp nghiệm thu sự cố", tags = {"CSKH"})
    @RequestMapping(value = "/layAnhNghiemThuSC", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<AnhNghiemThuSc>> layAnhNghiemThuSC(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody LayAnhNghiemThuSCRequest requestBody);

    @Operation(summary = "CSKH-Nghiệm thu/ Nghiệm thu xử lý sự cố - Cập nhật ảnh chụp nghiệm thu sự cố", tags = {"CSKH"})
    @RequestMapping(value = "/capNhatAnhNghiemThuSC", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<String>> capNhatAnhNghiemThuSC(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody CapNhatAnhNghiemThuSCRequest requestBody);

    @Operation(summary = "CSKH-lấy ds thuê bao ảnh hưởng", tags = {"CSKH"})
    @RequestMapping(value = "/danhSachTbscLoaihinhSel", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<String>> danhSachTbscLoaihinhSel(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody LayDsTbscLoaiHinhSelRequest requestBody);


    @Operation(summary = "giao viec cho nhan vien xhh", tags = {"CSKH"})
    @RequestMapping(value = "/sp_giaoviec_nhanvien_xhh", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> spGiaoViecNhanVienXhh(@Valid @RequestBody SP_GIAOVIEC_NHANVIEN_XHH_REQUEST requestBody);

    @Operation(summary = "CSKH - Precheck XLSC KPI (FMS)", tags = {"CSKH"})
    @RequestMapping(value = "/precheckXlscKpi", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Object>> precheckXlscKpi(@Valid @RequestBody PrecheckXlscKpiRequest requestBody);

}