/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.25).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.dto.*;
import io.swagger.model.request.ChonThietBiRequest;
import io.swagger.model.request.PhieuXuLyRequest;
import io.swagger.model.request.TraCuuDanhBaRequest;
import io.swagger.model.response.BaseResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import vn.vnptit.sapi.oneapp.model.request.DichVuVTKieuYeuCauRequest;

import javax.annotation.Generated;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2021-03-16T07:34:18.357Z[GMT]")
@Validated
@RequestMapping(value = "/danhMuc")
public interface DanhMucApi {
    @Operation(summary = "", description = "STT 36 - Đơn vị", tags = {"Danh mục"})
    @RequestMapping(value = "/donVi", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> danhMucDonViGet();

    @Operation(summary = "CSKH-Danh sách tiếp nhận sự cố tạm thời", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/dsTiepNhanSuCoTamThoi", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<TiepNhanSuCo>>> dsTiepNhanSuCoTamThoi(@Parameter(in = ParameterIn.QUERY, description = "Mã sự cố", required = true, schema = @Schema()) @Valid @RequestParam(value = "maSc", required = false) String maSc,
                                                                           @Parameter(in = ParameterIn.QUERY, description = "Nguồn sự cố Id", required = true, schema = @Schema()) @Valid @RequestParam(value = "nguonScId", required = false) Long nguonScId);
    @Operation(summary = "CSKH-Danh sách tiếp nhận sự cố tạm thời theo nhân viên", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/dsTiepNhanSuCoTamThoiTheoNhanVien", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<TiepNhanSuCo>>> dsTiepNhanSuCoTamThoiTheoNhanVien(@Parameter(in = ParameterIn.QUERY, description = "Mã sự cố", required = true, schema = @Schema()) @Valid @RequestParam(value = "maSc", required = false) String maSc,
                                                                                       @Parameter(in = ParameterIn.QUERY, description = "Nguồn sự cố Id", required = true, schema = @Schema()) @Valid @RequestParam(value = "nguonScId", required = false) Long nguonScId);
    @Operation(summary = "CSKH-Danh sách yêu cầu hỗ trợ", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/dsYeuCauHoTro", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<YeuCauHoTro>>> dsYeuCauHoTro(@Parameter(in = ParameterIn.QUERY, description = "Mã sự cố", required = true, schema = @Schema()) @Valid @RequestParam(value = "maSc", required = false) String maSc,
                                                                  @Parameter(in = ParameterIn.QUERY, description = "Từ ngày", required = true, schema = @Schema()) @Valid @RequestParam(value = "fdate", required = false) String fdate,
                                                                  @Parameter(in = ParameterIn.QUERY, description = "Đến ngày", required = true, schema = @Schema()) @Valid @RequestParam(value = "tdate", required = false) String tdate,
                                                                  @Parameter(in = ParameterIn.QUERY, description = "Trạng thái xử lý", required = true, schema = @Schema()) @Valid @RequestParam(value = "trangThai", required = true) Integer trangThai);
    @Operation(summary = "CSKH-Chi tiết phản hồi", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/chiTietPhanHoi", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<ThongTinPhanHoi>> chiTietPhanHoi(
            @Parameter(in = ParameterIn.QUERY, description = "Mã yêu cầu", required = true)
            @RequestParam(value = "yeuCauId") Integer yeuCauId);
    @Operation(summary = "ChiTietYeuCau", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/chiTietYeuCau", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<ThongTinYeuCau>> chiTietYeuCau(
            @Parameter(in = ParameterIn.QUERY, description = "Mã yêu cầu", required = true)
            @RequestParam(value = "yeuCauId") Integer yeuCauId);
    @Operation(summary = "CSKH-Danh sách dữ liệu", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/dsDuLieu", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsDuLieu(@Parameter(in = ParameterIn.QUERY, description = "Kiểu", required = true, schema = @Schema()) @Valid @RequestParam(value = "kieu", required = false) Long kieu);

    @Operation(summary = "CSKH-Danh sách dung lượng thiết bị", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/dsDungLuongThietBi", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsDungLuongThietBi(@Parameter(in = ParameterIn.QUERY, description = "Loại thiết bị Id", required = true, schema = @Schema()) @Valid @RequestParam(value = "loaiTbId", required = false) Long loaiTbId);

    @Operation(summary = "CSKH-Danh sách kiểu thiết bị", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/dsKieuThietBi", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<KieuThietBi>>> dsKieuThietBi(@Parameter(in = ParameterIn.QUERY, description = "Loại thiết bị Id", required = true, schema = @Schema()) @Valid @RequestParam(value = "loaiTbId", required = false) Long loaiTbId);

    @Operation(summary = "CSKH-Danh sách loại thiết bị", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/dsLoaiThietBi", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<LoaiThietBi>>> dsLoaiThietBi(@Parameter(in = ParameterIn.QUERY, description = "Nhóm thiết bị Id", required = true, schema = @Schema()) @Valid @RequestParam(value = "nhomTbId", required = false) Long nhomTbId);

    @Operation(summary = "CSKH-Danh sách chọn thiết bị", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/dsChonThietBi", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<List<ChonThietBi>>> dsChonThietBi(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody ChonThietBiRequest requestBody);

    @Operation(summary = "CSKH-Danh sách tình trạng xử lý", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/dsTinhTrangXuLy", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<TinhTrangXuLy>>> dsTinhTrangXuLy(@Parameter(in = ParameterIn.QUERY, description = "Sự cố Id", required = true, schema = @Schema()) @Valid @RequestParam(value = "suCoId", required = false) Long suCoId,
                                                                      @Parameter(in = ParameterIn.QUERY, description = "Trạng thái", required = true, schema = @Schema()) @Valid @RequestParam(value = "trangThai", required = false) Long trangThai);

    @Operation(summary = "CSKH-Lấy cây thiết bị", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/dsCayThietBi", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<CayThietBi>>> dsCayThietBi(@Parameter(in = ParameterIn.QUERY, description = "Loại thiết bị Id", required = true, schema = @Schema()) @Valid @RequestParam(value = "loaiTbId", required = false) Long loaiTbId,
                                                                @Parameter(in = ParameterIn.QUERY, description = "Thiết bị id", required = true, schema = @Schema()) @Valid @RequestParam(value = "thietBiId", required = false) Long thietBiId);

    @Operation(summary = "CSKH-Danh sách nhóm sự cố theo nhân viên", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/dsNhomSuCoTheoNv", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsNhomSuCoTheoNv(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Nhân viên Id", required = true, schema = @Schema()) @Valid @RequestParam(value = "nhanVienId", required = true) Long nhanVienId);

    @Operation(summary = "Tiện ích-Danh sách điều kiện tra cứu", tags = {"Danh mục"})
    @RequestMapping(value = "/tienIch/dsDieuKienTraCuu", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsDieuKienTraCuu();

    @Operation(summary = "Tiện ích-Tra cứu danh bạ", tags = {"Danh mục"})
    @RequestMapping(value = "/tienIch/traCuuDanhBa", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<List<DanhBaBase>>> traCuuDanhBa(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody TraCuuDanhBaRequest requestBody);

    @Operation(summary = "Tiện ích-Danh sách kiểu đo kiểm", tags = {"Danh mục"})
    @RequestMapping(value = "/tienIch/dsKieuDoKiem", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<KieuDoKiem>>> dsKieuDoKiem();

    @Operation(summary = "Tiện ích-Danh sách kiểu xác thực", tags = {"Danh mục"})
    @RequestMapping(value = "/tienIch/dsKieuXacThuc", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsKieuXacThuc();

    @Operation(summary = "Tiện ích-Danh sách kiểu mã hóa", tags = {"Danh mục"})
    @RequestMapping(value = "/tienIch/dsKieuMaHoa", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsKieuMaHoa(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Kiểu xác thực Id", required = true, schema = @Schema()) @Valid @RequestParam(value = "kieuXtId", required = true) Long kieuXtId);

    @Operation(summary = "CSKH-Danh sách nhân viên", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/dsNhanVien", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<NhanVien>>> dsNhanVien(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Tên nhân viên", required = true, schema = @Schema()) @Valid @RequestParam(value = "tenNv", required = true) String tenNv);

    @Operation(summary = "CSKH-Danh sách tính trạng CNTT", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/dsTinhTrangCntt", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<TinhTrangCntt>>> dsTinhTrangCntt(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Sự cố ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "suCoId", required = true) Long suCoId);

    @Operation(summary = "CSKH-Danh sách tình trạng mạng viễn thông", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/dsTinhTrangMvt", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<TinhTrangMvt>>> dsTinhTrangMvt(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Sự cố ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "suCoId", required = true) Long suCoId);

    @Operation(summary = "CSKH-Danh sách nguyên nhân", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/dsNguyenNhan", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsNguyenNhan(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Nhóm nguyên nhân ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "nhomNguyenNhanId", required = true) Long nhomNguyenNhanId);

    @Operation(summary = "CSKH-Danh sách hướng giao", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/dsHuongGiao", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsHuongGiao(@Parameter(in = ParameterIn.QUERY, description = "Quy trình ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "quyTrinhId", required = false) Long quyTrinhId);

    @Operation(summary = "CSKH-Danh sách phiếu xử lý", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/dsPhieuXuLy", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<List<PhieuXuLy>>> dsPhieuXuLy(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody PhieuXuLyRequest requestBody);

    @Operation(summary = "CSKH-Danh sách bước xử lý", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/dsBuocXL", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List>> dsBuocXL(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Mã Quy trình Net", required = true, schema = @Schema()) @Valid @RequestParam(value = "maQT", required = true) String maQT);

    @Operation(summary = "CSKH-Danh sách bước xử lý", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/dsBuocXL-v2", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List>> dsBuocXLV2(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Mã Quy trình Net", required = true, schema = @Schema()) @Valid @RequestParam(value = "maQT", required = true) String maQT, @Parameter(in = ParameterIn.QUERY, description = "Mã Bước", required = false, schema = @Schema()) @Valid @RequestParam(value = "maBuoc", required = false) String maBuoc);

    @Operation(summary = "CSKH-Danh sách bước xử lý v3", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/dsBuocXL-v3", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List>> dsBuocXLV3(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Mã Quy trình Net", required = true, schema = @Schema()) @Valid @RequestParam(value = "maQT", required = true) String maQT, @Parameter(in = ParameterIn.QUERY, description = "Mã Bước", required = false, schema = @Schema()) @Valid @RequestParam(value = "maBuoc", required = false) String maBuoc,@NotNull @Parameter(in = ParameterIn.QUERY, description = "Mã phiếu giao", required = true, schema = @Schema()) @Valid @RequestParam(value = "idPhieu", required = false) Long idPhieu);

    @Operation(summary = "CSKH-Danh sách đơn vị xử lý", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/dsDVTheoBuoc", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List>> dsDVTheoBuoc(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Mã Quy trình Net", required = true, schema = @Schema()) @Valid @RequestParam(value = "maQT", required = true) String maQT, @NotNull @Parameter(in = ParameterIn.QUERY, description = "Mã Bước", required = true, schema = @Schema()) @Valid @RequestParam(value = "maBuoc", required = true) String maBuoc);

    @Operation(summary = "CSKH-Danh sách phiếu đã giao", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/dsPhieuDaGiao", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List>> dsPhieuDaGiao(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Sự cố ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "suCoId", required = true) String suCoId);

    @Operation(summary = "CSKH-Danh sách nhân viên báo tồn", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/dsNhanVienBaoTon", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsNhanVienBaoTon();

    @Operation(summary = "CSKH-Danh sách chi tiết tồn", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/dsChiTietTon", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsChiTietTon(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Nhóm tồn ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "nhomTonId", required = true) Long nhomTonId);

    @Operation(summary = "CSKH-Danh sách nhóm sự cố", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/dsNhomSuCo", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsNhomSuCo(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Sự cố ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "suCoId", required = true) Long suCoId);

    @Operation(summary = "CSKH-Danh sách nhóm tồn", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/dsNhomTon", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsNhomTon(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Nhóm sự cố ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "nhomSuCoId", required = true) Long nhomSuCoId);

    @Operation(summary = "CSKH-Danh sách báo tồn", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/dsBaoTon", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<BaoTon>>> dsBaoTon(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Nhóm sự cố ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "phieuId", required = true) Long phieuId);

    @Operation(summary = "Tiện ích-Lấy thông tin port", tags = {"Danh mục"})
    @RequestMapping(value = "/tienIch/layThongTinPort", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<ThongTinPort>>> layThongTinPort(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Mã thiết bị", required = true, schema = @Schema()) @Valid @RequestParam(value = "maTb", required = true) String maTb,
                                                                     @NotNull @Parameter(in = ParameterIn.QUERY, description = "0: lay tu hop dong,1: lay tu danh ba, 2: uu tien lay hop dong roi den danh ba", required = true, schema = @Schema()) @Valid @RequestParam(value = "kieu", required = true) Long kieu);

    @Operation(summary = "Danh sách tỉnh/TP", tags = {"Danh mục"})
    @RequestMapping(value = "/dsTinh", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsTinh();

    @Operation(summary = "Danh sách quận/huyện", tags = {"Danh mục"})
    @RequestMapping(value = "/dsQuan", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsQuan(@NotNull @Parameter(in = ParameterIn.QUERY, description = "ID tỉnh/TP", required = true, schema = @Schema()) @RequestParam(value = "tinhId", required = false) Long tinhId);

    @Operation(summary = "Danh sách phường/xã", tags = {"Danh mục"})
    @RequestMapping(value = "/dsPhuong", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsPhuong(@NotNull @Parameter(in = ParameterIn.QUERY, description = "ID quận/huyện", required = true, schema = @Schema()) @Valid @RequestParam(value = "quanId", required = true) Long quanId);

    @Operation(summary = "Danh sách đường/phố(type = 1) - ngõ/ấp(type = 2) - khu(type = 3)", tags = {"Danh mục"})
    @RequestMapping(value = "/dsPhoApKhu", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsPhoApKhu(@NotNull @Parameter(in = ParameterIn.QUERY, description = "ID phường/xã", required = true, schema = @Schema()) @Valid @RequestParam(value = "phuongId", required = true) Long phuongId,
                                                           @NotNull @Parameter(in = ParameterIn.QUERY, description = "Loại", required = true, schema = @Schema()) @Valid @RequestParam(value = "type", required = true) Integer type);

    @Operation(summary = "Danh sách đặc điểm", tags = {"Danh mục"})
    @RequestMapping(value = "/dsDacDiem", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsDacDiem(@NotNull @Parameter(in = ParameterIn.QUERY, description = "ID phường/xã", required = true, schema = @Schema()) @Valid @RequestParam(value = "phuongId", required = true) Long phuongId,
                                                          @NotNull @Parameter(in = ParameterIn.QUERY, description = "ID đường/phố", required = true, schema = @Schema()) @Valid @RequestParam(value = "duongId", required = true) Long duongId,
                                                          @NotNull @Parameter(in = ParameterIn.QUERY, description = "ID ấp/ngõ", required = true, schema = @Schema()) @Valid @RequestParam(value = "apId", required = true) Long apId,
                                                          @NotNull @Parameter(in = ParameterIn.QUERY, description = "ID khu", required = true, schema = @Schema()) @Valid @RequestParam(value = "khuId", required = true) Long khuId);

    @Operation(summary = "Đánh giá nhân viên - Trạng thái hợp đồng", description = "Danh mục trạng thái hợp đồng - Đánh giá nhân viên", tags = {"Danh mục"})
    @RequestMapping(value = "/danhGiaNV/dsTrangThaiHD", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsTrangThaiHD();

    @Operation(summary = "", description = "Danh mục dịch vụ VT - Kiểu yêu cầu", tags = {"Danh mục dịch vụ VT"})
    @RequestMapping(value = "/ds_dichvuvt_kieuyeucau", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<List<DanhMuc>>> ds_dichvuvt_kieuyeucau(@Parameter(in = ParameterIn.QUERY, description = "Loại danh mục VT - Kiểu YC", required = true, schema = @Schema()) @Valid @RequestBody DichVuVTKieuYeuCauRequest requestBody);

    @Operation(summary = "", description = "Danh mục dịch vụ B2A", tags = {"Danh mục B2A"})
    @RequestMapping(value = "/b2a_phantap", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> b2a_phantap();

    @Operation(summary = "", description = "Danh mục dịch vụ B2A", tags = {"Danh mục B2A"})
    @RequestMapping(value = "/b2a_trangthai", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> b2a_trangthai();

    @Operation(summary = "", description = "Danh mục dịch vụ B2A", tags = {"Danh mục B2A"})
    @RequestMapping(value = "/b2a_kenh_tc", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> b2a_kenh_tc();

    @Operation(summary = "", description = "Danh mục dịch vụ B2A", tags = {"Danh mục B2A"})
    @RequestMapping(value = "/b2a_chiendich", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> b2a_chiendich();

    @Operation(summary = "CSKH-Danh sách quy trình cấp 5 theo bước proc", tags = {"Danh mục"})
    @RequestMapping(value = "/cskh/lay-quytrinh-cap5", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<QuyTrinhCap5>> getCap5ByBuoc(
            @NotNull
            @Parameter(in = ParameterIn.QUERY, description = "Mã proc", required = true, schema = @Schema())
            @Valid @RequestParam(value = "maProc", required = true) String maProc,

            @NotNull
            @Parameter(in = ParameterIn.QUERY, description = "Bước proc", required = true, schema = @Schema())
            @Valid @RequestParam(value = "buocProc", required = true) String buocProc
    );
}
