/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.25).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.request.CapNhatDanhBaFileRequest;
import io.swagger.model.response.BaseResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.annotation.Generated;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;

@Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2021-03-16T07:34:18.357Z[GMT]")
@Validated
@RequestMapping(value = "/file")
public interface FileApi {
    @Operation(summary = "Download", tags = {"File"})
    @RequestMapping(value = "/download", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<?> getFile(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Đường dẫn file", required = true, schema = @Schema()) @Valid @RequestParam(value = "path", required = true) String path);

    @Operation(summary = "Update link file", tags = {"File"})
    @RequestMapping(value = "/updateFileUrl", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<String>> updateFileUrl(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody CapNhatDanhBaFileRequest requestBody);

    // @Operation(summary = "Lấy data file pdf", tags = {"File"})
    // @RequestMapping(value = "/getFile", produces = {"application/json"}, method = RequestMethod.GET)
    // ResponseEntity<BaseResponse<String>> getFileData(@NotNull @Parameter(in = ParameterIn.QUERY, description = "filePath", required = true, schema = @Schema()) @Valid @RequestParam(value = "filePath", required = true) String filePath);
}

