/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.25).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.dto.*;
import io.swagger.model.request.ChuyenChinhThucRequest;
import io.swagger.model.request.HuyDungThuRequest;
import io.swagger.model.response.BaseResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.annotation.Generated;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2021-03-16T07:34:18.357Z[GMT]")
@Validated
@RequestMapping(value = "/hdDungThu")
public interface HopDongDungThuApi {
    @Operation(summary = "dsDonVi", description = "Hàm lấy danh mục cho combobox danh sách đơn vị có thuê bao dùng thử", tags = {"Hợp đồng dùng thử"})
    @RequestMapping(value = "/dsDonVi", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsDonVi();

    @Operation(summary = "dsKhuVuc", description = "Hàm lấy danh mục cho combobox danh sách khu vực có thuê bao dùng thử", tags = {"Hợp đồng dùng thử"})
    @RequestMapping(value = "/dsKhuVuc", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsKhuVuc();

    @Operation(summary = "dsHopDong", description = "Lấy danh sách hợp đồng dùng thử chưa hoàn thành", tags = {"Hợp đồng dùng thử"})
    @RequestMapping(value = "/dsHopDong", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<HopDongDungThu>>> dsHopDong(@Parameter(in = ParameterIn.QUERY, description = "Khu vực ID (0: tất cả hoặc ds khu vực: 663,666,659)", required = true, schema = @Schema()) @Valid @RequestParam(value = "khuVucId", required = false) String khuVucId,
                                                                           @Parameter(in = ParameterIn.QUERY, description = "Đơn vị ID (0: tất cả hoặc ds đơn vị: 10060,10219 )", required = true, schema = @Schema()) @Valid @RequestParam(value = "donViId", required = false) String donViId);

    @Operation(summary = "dsNhomHuy", description = "Hàm lấy danh sách nhóm hủy", tags = {"Hợp đồng dùng thử"})
    @RequestMapping(value = "/dsNhomHuy", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsNhomHuy(@Parameter(in = ParameterIn.QUERY, description = "Loại LD ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "loaiLDId", required = false) String loaiLDId,
                                                          @Parameter(in = ParameterIn.QUERY, description = "Loại TB ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "loaiTBId", required = false) String loaiTBId,
                                                          @Parameter(in = ParameterIn.QUERY, description = "Kiểu", required = true, schema = @Schema()) @Valid @RequestParam(value = "kieu", required = false) String kieu);

    @Operation(summary = "dsLyDoHuy", description = "Hàm lấy danh sách lý do hủy", tags = {"Hợp đồng dùng thử"})
    @RequestMapping(value = "/dsLyDoHuy", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsLyDoHuy(@Parameter(in = ParameterIn.QUERY, description = "Loại LD ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "loaiLDId", required = false) String loaiLDId,
                                                          @Parameter(in = ParameterIn.QUERY, description = "Loại TB ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "loaiTBId", required = false) String loaiTBId,
                                                          @Parameter(in = ParameterIn.QUERY, description = "Kiểu", required = true, schema = @Schema()) @Valid @RequestParam(value = "kieu", required = false) String kieu,
                                                          @Parameter(in = ParameterIn.QUERY, description = "Nhóm hủy ID lấy từ combobox Nhóm hủy", required = true, schema = @Schema()) @Valid @RequestParam(value = "nhomHuyId", required = false) String nhomHuyId);


    @Operation(summary = "dsDoiTuongThueBao", description = "Hàm lấy danh sách đối tượng thuê bao", tags = {"Hợp đồng dùng thử"})
    @RequestMapping(value = "/dsDoiTuongThueBao", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DoiTuongThueBao>>> dsDoiTuongThueBao();

    @Operation(summary = "dsNhom", description = "Lấy dữ liệu combobox 'Chọn nhóm' cho CTV và Người GT", tags = {"Hợp đồng dùng thử"})
    @RequestMapping(value = "/dsNhom", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsNhom(@Parameter(in = ParameterIn.QUERY, description = "Kiểu", required = true, schema = @Schema()) @Valid @RequestParam(value = "kieu", required = false) String kieu,
                                                       @Parameter(in = ParameterIn.QUERY, description = "Input (6: CTV; 11: Người GT)", required = true, schema = @Schema()) @Valid @RequestParam(value = "input", required = false) String input);

    @Operation(summary = "dsNhanVien", description = "Hàm tra cứu danh sách CTV, Nhân viên GT", tags = {"Hợp đồng dùng thử"})
    @RequestMapping(value = "/dsNhanVien", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<NhanVienResponse>>> dsNhanVien(@Parameter(in = ParameterIn.QUERY, description = "Kiểu (1: CTV, 2: Người giới thiệu)", required = true, schema = @Schema()) @Valid @RequestParam(value = "kieu", required = false) String kieu,
                                                           @Parameter(in = ParameterIn.QUERY, description = "Loại nhân viên ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "loaiNVId", required = false) String loaiNVId,
                                                           @Parameter(in = ParameterIn.QUERY, description = "Đơn vị ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "donViId", required = false) String donViId);

    @Operation(summary = "kiemTra", description = "Hàm kiểm tra khi nhấn nút 'Chuyển dùng thật' gọi hàm kiểm tra xem có được hiển thị form chuyển không, trong trường hợp thành công => hiển thị form chuyển dùng thật, còn lại hiển thị thông báo theo hàm và không chuyển form.", tags = {"Hợp đồng dùng thử"})
    @RequestMapping(value = "/kiemTra", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<String>> kiemTra(@Parameter(in = ParameterIn.QUERY, description = "HĐTB ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "hdtbId", required = false) String hdtbId);


    @Operation(summary = "Chuyển chính thức", description="Chuyển chính thức", tags = {"Hợp đồng dùng thử"})
    @RequestMapping(value = "/chuyenChinhThuc", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<String>> chuyenChinhThuc(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody ChuyenChinhThucRequest requestBody);

    @Operation(summary = "Hủy dùng thử", description="Hủy dùng thử", tags = {"Hợp đồng dùng thử"})
    @RequestMapping(value = "/huyDungThu", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<String>> huyDungThu(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody HuyDungThuRequest requestBody);

}

