/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.25).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.dto.*;
import io.swagger.model.request.*;
import io.swagger.model.response.BaseResponse;
import io.swagger.model.response.KhachHangTiemNangResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.annotation.Generated;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2021-03-16T07:34:18.357Z[GMT]")
@Validated
@RequestMapping(value = "/khachHangTiemNang")
public interface KhachHangTiemNangApi {
    @Operation(summary = "dsLoaiGiayTo", description = "Hàm lấy danh mục cho combobox danh sách loai giay to", tags = {"Khách hàng tiềm năng"})
    @RequestMapping(value = "/dsLoaiGiayTo", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsLoaiGiayTo();

    @Operation(summary = "dsDichVuKHTiemNang", description = "Hàm lấy danh mục cho combobox danh sách dich vu - Them/Sua KH tiem nang", tags = {"Khách hàng tiềm năng"})
    @RequestMapping(value = "/dsDichVuKHTiemNang", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsDichVuKHTiemNang();

    @Operation(summary = "layTTKhachHang", description = "Lấy thông tin khách hàng", tags = {"Khách hàng tiềm năng"})
    @RequestMapping(value = "/layTTKhachHang", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<TTKhachHang>> layTTKhachHang(@Parameter(in = ParameterIn.QUERY, description = "khachHangId", required = true, schema = @Schema()) @Valid @RequestParam(value = "khachHangId", required = false) Long khachHangId);

    @Operation(summary = "dsLoaiHinhThueBaoKHTiemNang", description = "Hàm lấy danh mục cho combobox danh sách loai hinh thue bao - Them/Sua KH tiem nang", tags = {"Khách hàng tiềm năng"})
    @RequestMapping(value = "/dsLoaiHinhThueBaoKHTiemNang", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsLoaiHinhThueBaoKHTiemNang(@Parameter(in = ParameterIn.QUERY, description = "Lấy từ API dsDichVuKHTiemNang", required = true, schema = @Schema()) @Valid @RequestParam(value = "dichVuVTId", required = false) Long dichVuVTId);

    @Operation(summary = "dsLoaiYC", description = "Hàm lấy danh mục cho combobox danh sách loai YC", tags = {"Khách hàng tiềm năng"})
    @RequestMapping(value = "/dsLoaiYC", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsLoaiYC();

    @Operation(summary = "dsDichVu", description = "Hàm lấy danh mục cho combobox danh sách dịch vụ", tags = {"Khách hàng tiềm năng"})
    @RequestMapping(value = "/dsDichVu", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsDichVu();

    @Operation(summary = "dsKetQuaXuLy", description = "Hàm lấy danh mục cho combobox Kết quả xử lý", tags = {"Khách hàng tiềm năng"})
    @RequestMapping(value = "/dsKetQuaXuLy", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsKetQuaXuLy();

    @Operation(summary = "dsKetQuaXuLyV2", description = "Hàm lấy danh mục cho combobox Kết quả xử lý", tags = {"Khách hàng tiềm năng"})
    @RequestMapping(value = "/dsKetQuaXuLyV2", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsKetQuaXuLyV2();

    @Operation(summary = "dsNhanVien", description = "Hàm lấy danh sách nhân viên", tags = {"Khách hàng tiềm năng"})
    @RequestMapping(value = "/dsNhanVien", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsNhanVien();

    @Operation(summary = "dsHinhThucTiepCan", description = "Hàm lấy danh sách hình thức tiếp cận", tags = {"Khách hàng tiềm năng"})
    @RequestMapping(value = "/dsHinhThucTiepCan", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsHinhThucTiepCan();

    @Operation(summary = "dsNhaMang", description = "Hàm lấy danh sách nhà mạng", tags = {"Khách hàng tiềm năng"})
    @RequestMapping(value = "/dsNhaMang", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsNhaMang();

    @Operation(summary = "dsNhomLyDo", description = "Hàm lấy danh mục cho combobox Nhóm lý do", tags = {"Khách hàng tiềm năng"})
    @RequestMapping(value = "/dsNhomLyDo", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsNhomLyDo();

    @Operation(summary = "dsLydo", description = "Hàm lấy danh mục cho combobox danh sách lý do", tags = {"Khách hàng tiềm năng"})
    @RequestMapping(value = "/dsLydo", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsLydo(@Parameter(in = ParameterIn.QUERY, description = "Lấy từ API dsNhomLyDo", required = true, schema = @Schema()) @Valid @RequestParam(value = "nhomLyDoId", required = false) Long nhomLyDoId);

    @Operation(summary = "dsLoaiHinhThueBao", description = "Hàm lấy danh mục cho combobox danh sách loại hình thuê bao", tags = {"Khách hàng tiềm năng"})
    @RequestMapping(value = "/dsLoaiHinhThueBao", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsLoaiHinhThueBao(@Parameter(in = ParameterIn.QUERY, description = "Lấy từ API dsDichVu", required = true, schema = @Schema()) @Valid @RequestParam(value = "dichVuVTId", required = false) Long dichVuVTId);

    @Operation(summary = "dsKHTiemNang", description = "Lấy danh sách theo dõi khách hàng tiềm năng(Tab Danh sách) + Combobox tháng hết hạn", tags = {"Khách hàng tiềm năng"})
    @RequestMapping(value = "/dsKHTiemNang", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<KhachHangTiemNangResponse>> dsKHTiemNang(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody KhachHangTiemNangRequest requestBody);

    @Operation(summary = "dsKHTiemNangV2", description = "Lấy danh sách theo dõi khách hàng tiềm năng(Tab Danh sách) + Combobox tháng hết hạn", tags = {"Khách hàng tiềm năng"})
    @RequestMapping(value = "/dsKHTiemNangV2", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<KhachHangTiemNangResponse>> dsKHTiemNangV2(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody KhachHangTiemNangRequest requestBody);

    @Operation(summary = "dsPhieuKHTiemNang", description = "Lấy danh sách phiếu khách hàng tiềm năng(Tab Cập nhật)", tags = {"Khách hàng tiềm năng"})
    @RequestMapping(value = "/dsPhieuKHTiemNang", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<PhieuKhachHangTiemNang>>> dsPhieuKHTiemNang();

    @Operation(summary = "dsTapKH", description = "Lấy danh sách tập khách hàng", tags = {"Khách hàng tiềm năng"})
    @RequestMapping(value = "/dsTapKH", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<TapKH>>> dsTapKH();

    @Operation(summary = "layChiTietKHTiemNang", description = "Hàm lấy chi tiet khach hang tiem nang", tags = {"Khách hàng tiềm năng"})
    @RequestMapping(value = "/layChiTietKHTiemNang", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<CTKhachHangTiemNang>> layChiTietKHTiemNang(@Parameter(in = ParameterIn.QUERY, description = "Lấy từ API dsPhieuKHTiemNang", required = true, schema = @Schema()) @Valid @RequestParam(value = "phieuId", required = false) Long phieuId,
                                                                           @Parameter(in = ParameterIn.QUERY, description = "Lấy từ API dsPhieuKHTiemNang", required = true, schema = @Schema()) @Valid @RequestParam(value = "hdkhId", required = false) Long hdkhId);

    @Operation(summary = "xoaPhieuKHTiemNang", description = "Hàm lấy danh mục cho combobox danh sách lý do", tags = {"Khách hàng tiềm năng"})
    @RequestMapping(value = "/xoaPhieuKHTiemNang", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> xoaPhieuKHTiemNang(@Parameter(in = ParameterIn.PATH, description = "Lấy từ API dsPhieuKHTiemNang", required = true, schema = @Schema()) @Valid @RequestParam(value = "hdkhId", required = false) Long hdkhId);

    @Operation(summary = "henKhachHang", description = "Hẹn khách hàng", tags = {"Khách hàng tiềm năng"})
    @RequestMapping(value = "/henKhachHang", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> henKhachHang(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody HenKhachHangRequest requestBody);

    @Operation(summary = "capNhatKQXL", description = "Cập nhật kết quả xử lý", tags = {"Khách hàng tiềm năng"})
    @RequestMapping(value = "/capNhatKQXL", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> capNhatKQXL(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody CapNhatKQXLRequest requestBody);

    @Operation(summary = "capNhatKHTiemNang", description = "Them/Cập nhật khach hang tiem nang", tags = {"Khách hàng tiềm năng"})
    @RequestMapping(value = "/capNhatKHTiemNang", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> capNhatKHTiemNang(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody CNKhachHangTiemNangRequest requestBody);

    @Operation(summary = "capNhatKHTiemNangV2", description = "Them/Cập nhật khach hang tiem nang", tags = {"Khách hàng tiềm năng"})
    @RequestMapping(value = "/capNhatKHTiemNangV2", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> capNhatKHTiemNangV2(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody CNKhachHangTiemNangRequest requestBody);
}

