/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.25).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.dto.*;
import io.swagger.model.request.*;
import io.swagger.model.response.BasePageResponse;
import io.swagger.model.response.BaseResponse;
import io.swagger.model.response.PageInfo;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.annotation.Generated;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2021-03-16T07:34:18.357Z[GMT]")
@Validated
@RequestMapping(value = "/khieunai")
public interface KhieuNaiApi {
    @Operation(summary = "Danh sách khiếu nại", tags = {"Khiếu nại"})
    @RequestMapping(value = "/dsKhieuNai", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<KhieuNai>>> dsKhieuNai(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Trạng thái (0: Chưa giao, 1: Đã giao)", required = true, schema = @Schema()) @Valid @RequestParam(value = "trangThai", required = true) String trangThai);

    @Operation(summary = "Danh sách khiếu nại", tags = {"Khiếu nại"})
    @RequestMapping(value = "/dsKhieuNaiPT", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BasePageResponse<List<KhieuNai>, PageInfo>> dsKhieuNaiPT(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Trạng thái (0: Chưa giao, 1: Đã giao)", required = true, schema = @Schema()) @Valid @RequestParam(value = "trangThai", required = true) String trangThai, Integer pageNum, Integer pageRec, Long totalRow);

    @Operation(summary = "Danh sách kết quả", tags = {"Khiếu nại"})
    @RequestMapping(value = "/dsKetQuaXL", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsKetQuaXL();

    @Operation(summary = "Danh sách nhân viên", tags = {"Khiếu nại"})
    @RequestMapping(value = "/dsNhanVien", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsNhanVien();

    @Operation(summary = "Danh sách phương án xử lý", tags = {"Khiếu nại"})
    @RequestMapping(value = "/dsPhuongAnXL", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsPhuongAnXL();

    @Operation(summary = "Danh sách kết quả lỗi", tags = {"Khiếu nại"})
    @RequestMapping(value = "/dsKetQuaLoi", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsKetQuaLoi();

    @Operation(summary = "Danh sách hình thức trả lời", tags = {"Khiếu nại"})
    @RequestMapping(value = "/dsHTTraLoi", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsHTTraLoi();

    @Operation(summary = "Danh sách đơn vị chuyển tổ", tags = {"Khiếu nại"})
    @RequestMapping(value = "/dsDonViChuyenTo", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DonViTree>>> dsDonViChuyenTo();

    @Operation(summary = "Chuyển tổ", description = "Khiếu nại", tags = {"Khiếu nại"})
    @RequestMapping(value = "/chuyenTo", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> chuyenTo(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody ChuyenToKNRequest requestBody);

    @Operation(summary = "Khóa phiếu", description = "Khiếu nại", tags = {"Khiếu nại"})
    @RequestMapping(value = "/khoaPhieu", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> khoaPhieu(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody XacMinhKNRequest requestBody);

    @Operation(summary = "Hoàn thành", description = "Khiếu nại", tags = {"Khiếu nại"})
    @RequestMapping(value = "/hoanThanh", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> hoanThanh(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody XacMinhKNRequest requestBody);

    @Operation(summary = "Danh sách loại phiếu", tags = {"Khiếu nại"})
    @RequestMapping(value = "/dsLoaiPhieu", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsLoaiPhieu();

    @Operation(summary = "Danh sách phiếu", tags = {"Khiếu nại"})
    @RequestMapping(value = "/dsPhieu", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<PhieuKhieuNai>>> dsPhieu(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Trạng thái", required = true, schema = @Schema()) @Valid @RequestParam(value = "trangThai", required = true) String trangThai);

    @Operation(summary = "Danh sách phiếu", tags = {"Khiếu nại"})
    @RequestMapping(value = "/dsPhieuPT", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BasePageResponse<List<PhieuKhieuNai>, PageInfo>> dsPhieuPT(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Trạng thái", required = true, schema = @Schema()) @Valid @RequestParam(value = "trangThai", required = true) String trangThai, Integer pageNum, Integer pageRec, Long totalRow);

    @Operation(summary = "Xóa phiếu khiếu nại", tags = {"Khiếu nại"})
    @RequestMapping(value = "/xoaPhieu", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<Void>> xoaPhieu(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Khiếu nại ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "khieuNaiId", required = true) String khieuNaiId);

    @Operation(summary = "Chi tiết phiếu khiếu nại", tags = {"Khiếu nại"})
    @RequestMapping(value = "/ctPhieu", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<ChiTietKhieuNai>> ctPhieu(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Khiếu nại ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "khieuNaiId", required = true) String khieuNaiId,
                                                          @NotNull @Parameter(in = ParameterIn.QUERY, description = "Phiếu khiếu nại ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "phieuKNId", required = true) String phieuKNId);


    @Operation(summary = "Lấy danh sách hình thức phản hồi", tags = {"Khiếu nại"})
    @RequestMapping(value = "/dsHTPhanHoi", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsHTPhanHoi();

    @Operation(summary = "Lấy danh sách loại chủ đề", tags = {"Khiếu nại"})
    @RequestMapping(value = "/dsLoaiChuDe", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsLoaiChuDe();

    @Operation(summary = "Lấy danh sách chủ đề", tags = {"Khiếu nại"})
    @RequestMapping(value = "/dsChuDe", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<ChuDeKN>>> dsChuDe(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Loại chủ đề ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "loaiChuDeId", required = true) String loaiChuDeId);

    @Operation(summary = "Lấy danh sách nhân viên xử lý", tags = {"Khiếu nại"})
    @RequestMapping(value = "/dsNVXuLy", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsNVXuLy();

    @Operation(summary = "Lấy danh sách kết quả lỗi", tags = {"Khiếu nại"})
    @RequestMapping(value = "/dsKQKhieuNai", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsKQKhieuNai();

    @Operation(summary = "Cập nhật/Khóa phiếu", description = "Khiếu nại", tags = {"Khiếu nại"})
    @RequestMapping(value = "/capNhat", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<String>> capNhat(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody PhieuKNRequest requestBody);

    @Operation(summary = "Lấy danh sách đơn vị nhận", tags = {"Khiếu nại"})
    @RequestMapping(value = "/dsDVNhan", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DonViTree>>> dsDVNhan(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Khiếu nại ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "khieuNaiId", required = true) String khieuNaiId,
                                                         @NotNull @Parameter(in = ParameterIn.QUERY, description = "Loại đơn vị đích ID", required = true, schema = @Schema()) @Valid @RequestParam(value = "loaiDVDichId", required = true) String loaiDVDichId);

    @Operation(summary = "Giao phiếu", description = "Khiếu nại", tags = {"Khiếu nại"})
    @RequestMapping(value = "/giaoPhieu", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<String>> giaoPhieu(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody GiaoPhieuKhieuNaiRequest requestBody);
}

