/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.25).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.dto.*;
import io.swagger.model.request.*;
import io.swagger.model.response.BaseResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import vn.vnptit.sapi.oneapp.model.request.ChuyenDoiMytvVMPRequest;
import vn.vnptit.sapi.oneapp.model.request.LayDSThietBiTheoThueBaoRequest;
import vn.vnptit.sapi.oneapp.model.request.TraCuuTTTBFiberMyTVBeta2Request;
import vn.vnptit.sapi.oneapp.model.request.TraCuuTTTBFiberMyTVBetaRequest;

import javax.annotation.Generated;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2021-03-16T07:34:18.357Z[GMT]")
@Validated
@RequestMapping(value = "/tienIch")
public interface TienIchApi {
    @Operation(summary = "", description = "STT 36 - Đơn vị", tags = {"Tiện ích"})
    @RequestMapping(value = "/donVi", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> danhMucDonViGet();

    @Operation(summary = "Tiện ích-Tra cứu port", tags = {"Tiện ích"})
    @RequestMapping(value = "/traCuuPort", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<Port>> traCuuPort(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Mã đối tượng", required = true, schema = @Schema()) @Valid @RequestParam(value = "maDt", required = true) String maDt);

    @Operation(summary = "Tiện ích-Reset port", tags = {"Tiện ích"})
    @RequestMapping(value = "/resetPort", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> resetPort(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Account", required = true, schema = @Schema()) @Valid @RequestParam(value = "account", required = true) String account);

    @Operation(summary = "Tiện ích-Xem thông tin Wifi", tags = {"Tiện ích"})
    @RequestMapping(value = "/xemThongTinWifi", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<Wifi>>> xemThongTinWifi(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Account", required = true, schema = @Schema()) @Valid @RequestParam(value = "account", required = true) String account);

    @Operation(summary = "Tiện ích-Set Port Profile", tags = {"Tiện ích"})
    @RequestMapping(value = "/setPortProfile", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Port>> setPortProfile(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Account", required = true, schema = @Schema()) @Valid @RequestParam(value = "account", required = true) String account,
                                                      @NotNull @Parameter(in = ParameterIn.QUERY, description = "Speed", required = true, schema = @Schema()) @Valid @RequestParam(value = "speed", required = true) String speed);

    @Operation(summary = "Tiện ích-Đổi pass wifi", tags = {"Tiện ích"})
    @RequestMapping(value = "/doiPassWifi", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> doiPassWifi(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody DoiPassWifiRequest requestBody);

    @Operation(summary = "Tiện ích-Tra cứu thông tin Visa", tags = {"Tiện ích"})
    @RequestMapping(value = "/traCuuVisa", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<Visa>> traCuuVisa(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Account", required = true, schema = @Schema()) @Valid @RequestParam(value = "account", required = true) String account);

    @Operation(summary = "Tiện ích-Tra cứu thông tin Vasc", tags = {"Tiện ích"})
    @RequestMapping(value = "/traCuuVasc", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<Vasc>> traCuuVasc(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Account", required = true, schema = @Schema()) @Valid @RequestParam(value = "account", required = true) String account);

    @Operation(summary = "Tiện ích-Tra cứu thông tin Vtn", tags = {"Tiện ích"})
    @RequestMapping(value = "/traCuuVtn", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<Vtn>> traCuuVtn(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Account", required = true, schema = @Schema()) @Valid @RequestParam(value = "account", required = true) String account);

    @Operation(summary = "Tiện ích-Tra cứu thông tin hỗ trợ cài app MyTV", tags = {"Tiện ích"})
    @RequestMapping(value = "/traCuuThongTinHoTroMyTv", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<Vtn>> traCuuThongTinHoTroMyTv(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Model", required = true, schema = @Schema()) @Valid @RequestParam(value = "model", required = true) String model);

    @Operation(summary = "Tiện ích-Đổi pass ADSL, FTTH, MyTV", tags = {"Tiện ích"})
    @RequestMapping(value = "/doiPassAdslFtthMytv", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> doiPassAdslFtthMytv(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Account", required = true, schema = @Schema()) @Valid @RequestParam(value = "account", required = true) String account,
                                                           @NotNull @Parameter(in = ParameterIn.QUERY, description = "Pass", required = true, schema = @Schema()) @Valid @RequestParam(value = "pass", required = true) String pass);

    @Operation(summary = "Tiện ích-Tra cứu chi tiết thuê bao theo mã thuê bao", tags = {"Tiện ích"})
    @RequestMapping(value = "/traCuuChiTietThueBao", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<ChiTietThueBao>> traCuuChiTietThueBao(@Parameter(in = ParameterIn.QUERY, description = "Mã thuê bao", required = true, schema = @Schema()) @Valid @RequestParam(value = "maTb", required = false) String maTb);

    @Operation(summary = "Tiện ích-Tra cứu chi tiết thuê bao theo mã thuê bao", tags = {"Tiện ích"})
    @RequestMapping(value = "/traCuuChiTietThueBao_vt", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<ChiTietThueBao>>> traCuuChiTietThueBao_vt(@Parameter(in = ParameterIn.QUERY, description = "Mã thuê bao", required = true, schema = @Schema()) @Valid @RequestParam(value = "maTb", required = false) String maTb);

    @Operation(summary = "Tiện ích-Chuyển đổi MyTV-VMP", tags = {"Tiện ích"})
    @RequestMapping(value = "/chuyenDoiMytvVMP", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Integer>> chuyenDoiMytvVMP(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody ChuyenDoiMytvVMPRequest requestBody);


    @Operation(summary = "Tiện ích-Lấy thông tin kiểm tra trạng thái VMP", tags = {"Tiện ích"})
    @RequestMapping(value = "/kiemTraTrangThaiVMP", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<String>> kiemTraTrangThaiVMP(@Parameter(in = ParameterIn.QUERY, description = "Mã thuê bao", required = true, schema = @Schema()) @Valid @RequestParam(value = "maTb", required = false) String maTb,
                                                             @Parameter(in = ParameterIn.QUERY, description = "Kiểu VMP(0 - MyTV thường; 1 - VMP)", required = true, schema = @Schema()) @Valid @RequestParam(value = "kieuVmp", required = false) Integer kieuVmp);

    @Operation(summary = "Tiện ích-Reset modem", tags = {"Tiện ích"})
    @RequestMapping(value = "/resetModem", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> resetModem(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Account", required = true, schema = @Schema()) @Valid @RequestParam(value = "account", required = true) String account);

    @Operation(summary = "Tiện ích-Backup cấu hình Modem", tags = {"Tiện ích"})
    @RequestMapping(value = "/backupCauHinhModem", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> backupCauHinhModem(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Account", required = true, schema = @Schema()) @Valid @RequestParam(value = "account", required = true) String account);

    @Operation(summary = "Tiện ích-Xóa file backup cấu hình Modem", tags = {"Tiện ích"})
    @RequestMapping(value = "/xoaFileBackupCauHinhModem", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> xoaFileBackupCauHinhModem(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Account", required = true, schema = @Schema()) @Valid @RequestParam(value = "account", required = true) String account);

    @Operation(summary = "Tiện ích-Lấy thông tin đơn vị theo mã thuê bao", tags = {"Tiện ích"})
    @RequestMapping(value = "/layThongTinDonViTheoMaTb", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<Integer>> layThongTinDonViTheoMaTb(@Parameter(in = ParameterIn.QUERY, description = "Mã thuê bao", required = true, schema = @Schema()) @Valid @RequestParam(value = "maTb", required = false) String maTb);

    @Operation(summary = "Tiện ích-Kiểm tra quyền nhân viên được phép thao tác trên kết cuối", tags = {"Tiện ích"})
    @RequestMapping(value = "/kiemTraQuyenNvThaoTacKetCuoi", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> kiemTraQuyenNvThaoTacKetCuoi(@Parameter(in = ParameterIn.QUERY, description = "Đơn vị Id", required = true, schema = @Schema()) @Valid @RequestParam(value = "donViId", required = false) Long donViId);

    @Operation(summary = "Tiện ích-Thay đổi Settopbox", tags = {"Tiện ích"})
    @RequestMapping(value = "/thayDoiSettopbox", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> thayDoiSettopbox(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody ThayDoiSettopboxRequest requestBody);

    @Operation(summary = "Tiện ích-Lấy danh sách hợp đồng phụ lục", tags = {"Tiện ích"})
    @RequestMapping(value = "/dsHopDongPhuLuc", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<HopDongPhuLuc>>> dsHopDongPhuLuc(@Parameter(in = ParameterIn.QUERY, description = "Mã giao dịch", required = true, schema = @Schema()) @Valid @RequestParam(value = "maGD", required = false) String maGD);

    @Operation(summary = "Tiện ích-Tư vấn cài Mobile Money-Lấy thông tin ghi nhận", tags = {"Tiện ích"})
    @RequestMapping(value = "/mobileMoney/layThongTinGhiNhan", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<ThongTinGhiNhanP2P>>> layThongTinGhiNhan(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Mã thuê bao", required = true, schema = @Schema()) @Valid @RequestParam(value = "maTB", required = true) String maTB);

    @Operation(summary = "Tiện ích-Tư vấn cài Mobile Money-Ghi nhận tư vấn", tags = {"Tiện ích"})
    @RequestMapping(value = "/mobileMoney/ghiNhanTuVan", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> ghiNhanTuVan(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody TuVanMobileMoneyRequest requestBody);

    @Operation(summary = "Tiện ích-Tư vấn cài Mobile Money-Lấy thông tin ghi nhận", tags = {"Tiện ích"})
    @RequestMapping(value = "/mobileMoney/layThongTinGhiNhanV2", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<ThongTinGhiNhanP2Pv2>> layThongTinGhiNhanV2(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Mã thuê bao", required = true, schema = @Schema()) @Valid @RequestParam(value = "maTB", required = true) String maTB);

    @Operation(summary = "Tiện ích-Tư vấn cài Mobile Money-Lấy thông tin ghi nhận", tags = {"Tiện ích"})
    @RequestMapping(value = "/mobileMoney/layThongTinGhiNhanV3", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<ThongTinGhiNhanP2Pv2New>> layThongTinGhiNhanV3(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Mã thuê bao", required = true, schema = @Schema()) @Valid @RequestParam(value = "maTB", required = true) String maTB);


    @Operation(summary = "Tiện ích-Tư vấn cài Mobile Money-Ghi nhận tư vấn", tags = {"Tiện ích"})
    @RequestMapping(value = "/mobileMoney/ghiNhanTuVanV2", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> ghiNhanTuVanV2(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody TuVanMobileMoneyRequest requestBody);

    @Operation(summary = "Lấy danh sách câu hỏi khảo sát", tags = {"Tiện ích"})
    @RequestMapping(value = "/tuVanGoiPH/dsCauHoiKS", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<CauHoiKS>>> dsCauHoiKS();

    @Operation(summary = "Lấy danh sách câu hỏi khảo sát", tags = {"1. Lấy danh sách câu hỏi"})
    @RequestMapping(value = "/tuVanGoiPH/dsCauHoiKS_NT", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<List<CauHoiKS>>> dsCauHoiKS_NT(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody DVITCareLayDsCauhoiTheoLoaiNVRequest requestBody);

    @Operation(summary = "Lấy danh sách câu đã trả lời", tags = {"Tiện ích"})
    @RequestMapping(value = "/tuVanGoiPH/dsDaTraLoi", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<CauHoiKS>>> dsDaTraLoi(@NotNull @Parameter(in = ParameterIn.QUERY, description = "tltbId", required = true, schema = @Schema()) @Valid @RequestParam(value = "tltbId", required = true) Long tltbId);

    @Operation(summary = "Đánh giá nhân viên", description = "Đánh giá nhân viên", tags = {"Tiện ích"})
    @RequestMapping(value = "/tuVanGoiPH/cnDanhGia", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> cnDanhGia(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody CapNhatKSRequest body);

    @Operation(summary = "Tiện ích-Đổi pass IMS", tags = {"Tiện ích"})
    @RequestMapping(value = "/doiPassIMS", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> doiPassIMS(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody DoiPassIMSRequest body);

    @Operation(summary = "Lấy danh sách thiết bị theo mã thuê bao/mã khách hàng", tags = {"Tiện ích"})
    @RequestMapping(value = "/LayDSThietBiTheoThueBao", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<List>> LayDSThietBiTheoThueBao(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody LayDSThietBiTheoThueBaoRequest body);

    @Operation(summary = "API tra cứu thông tin thuê bao fiber trên tập myTVBeta", tags = {"Tiện ích"})
    @RequestMapping(value = "/TraCuuTTTBFiberMyTVBeta", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<List>> TraCuuTTTBFiberMyTVBeta(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody TraCuuTTTBFiberMyTVBetaRequest body);

    @Operation(summary = "API tra cứu thông tin thuê bao fiber trên tập myTVBeta 2", tags = {"Tiện ích"})
    @RequestMapping(value = "/TraCuuTTTBFiberMyTVBeta2", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<?>> TraCuuTTTBFiberMyTVBeta2(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody TraCuuTTTBFiberMyTVBeta2Request body);

}

