/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.25).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.dto.*;
import io.swagger.model.request.*;
import io.swagger.model.response.BaseResponse;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.annotation.Generated;
import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.util.List;

@Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2021-03-16T07:34:18.357Z[GMT]")
@Validated
@RequestMapping(value = "/xlKhieuNai")
public interface XuLyKhieuNaiApi {
    @Operation(summary = "Danh sách Xử lý Khiếu nại", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/dsTBKhieuNaiXL", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<TBKhieuNaiXL>>> dsTBKhieuNaiXL(@NotNull @Parameter(in = ParameterIn.QUERY, description = "Trạng thái - combo kiểu hiển thị", required = true, schema = @Schema()) @Valid @RequestParam(value = "trangThai", required = true) Integer trangThai,
                                                                    @NotNull @Parameter(in = ParameterIn.QUERY, description = "Tổ trưởng - api tổ trưởng", required = true, schema = @Schema()) @Valid @RequestParam(value = "toTruong", required = true) Integer toTruong);

    @Operation(summary = "Input tổ trưởng", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/toTruong", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<Integer>> toTruong();

    @Operation(summary = "Danh sách kiểu hiển thị", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/dsKieuHienThi", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsKieuHienThi();

    @Operation(summary = "Danh sách KQXL", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/dsKQXL", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsKQXL();

    @Operation(summary = "Danh sách Nhân viên thực hiện", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/dsNhanVienTH", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<NhanVienXLKN>>> dsNhanVienTH();

    @Operation(summary = "Danh sách phương án xử lý", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/dsPhuongAnXL", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsPhuongAnXL();

    @Operation(summary = "Danh sách đơn vị chuyển tổ", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/dsKQLoi", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<KetQuaLoi>>> dsKQLoi();

    @Operation(summary = "Danh sách mức độ hài lòng", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/dsMucDoHL", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsMucDoHL();

    @Operation(summary = "Danh sách kiểu trả phiếu", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/dsKieuTra", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DanhMuc>>> dsKieuTra();

    @Operation(summary = "Danh sách Nhân viên chịu trách nhiệm", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/dsNVChiuTrachNhiem", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<NVChiuTrachNhiemXLKN>>> dsNVChiuTrachNhiem(@NotNull @Parameter(in = ParameterIn.QUERY, description = "khieuNaiId", required = true, schema = @Schema()) @Valid @RequestParam(value = "khieuNaiId", required = true) Long khieuNaiId);

    @Operation(summary = "Danh sách Nhân viên đang chịu lỗi", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/dsNVDangChiuLoi", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<NVDangChiuLoi>>> dsNVDangChiuLoi(@NotNull @Parameter(in = ParameterIn.QUERY, description = "khieuNaiId", required = true, schema = @Schema()) @Valid @RequestParam(value = "khieuNaiId", required = true) Long khieuNaiId);

    @Operation(summary = "Cập nhật/Xóa/Thêm mới nhân viên lỗi", description = "kieu --- 1: thêm; 2: cập nhật; 3: xóa.", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/cnNhanVienLoi", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> cnNhanVienLoi(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody CNNhanVienLoiRequest requestBody);

    @Operation(summary = "Danh sách Đơn vị chịu trách nhiệm", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/dsDVChiuTrachNhiem", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DVChiuTrachNhiemXLKN>>> dsDVChiuTrachNhiem(@NotNull @Parameter(in = ParameterIn.QUERY, description = "khieuNaiId", required = true, schema = @Schema()) @Valid @RequestParam(value = "khieuNaiId", required = true) Long khieuNaiId);

    @Operation(summary = "Danh sách Đơn vị đang chịu lỗi", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/dsDVDangChiuLoi", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DVDangChiuLoi>>> dsDVDangChiuLoi(@NotNull @Parameter(in = ParameterIn.QUERY, description = "khieuNaiId", required = true, schema = @Schema()) @Valid @RequestParam(value = "khieuNaiId", required = true) Long khieuNaiId);

    @Operation(summary = "Cập nhật/Xóa/Thêm mới Đơn vị lỗi", description = "kieu --- 1: thêm; 2: cập nhật; 3: xóa.", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/cnDonViLoi", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> cnDonViLoi(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody CNDonViLoiRequest requestBody);

    @Operation(summary = "Danh sách thuê bao chèn nợ", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/dsTBChenNo", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<ThueBaoChenNo>>> dsTBChenNo(@NotNull @Parameter(in = ParameterIn.QUERY, description = "kyHD", required = true, schema = @Schema()) @Valid @RequestParam(value = "kyHD", required = true) String kyHD,
                                                                 @NotNull @Parameter(in = ParameterIn.QUERY, description = "maTT", required = true, schema = @Schema()) @Valid @RequestParam(value = "maTT", required = true) String maTT);

    @Operation(summary = "Lấy chu kỳ theo kỳ hóa đơn", description = "Format Kỳ hóa đơn: YYYYMM", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/dsChuKy", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<String>>> dsChuKy(@NotNull @Parameter(in = ParameterIn.QUERY, description = "kyHD: YYYYMM", required = true, schema = @Schema()) @Valid @RequestParam(value = "kyHD", required = true) String kyHD);

    @Operation(summary = "Lấy danh sách thông tin giảm cước", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/dsGiamCuoc", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<ThongTinGiamCuoc>>> dsGiamCuoc(@NotNull @Parameter(in = ParameterIn.QUERY, description = "khieuNaiId", required = true, schema = @Schema()) @Valid @RequestParam(value = "khieuNaiId", required = true) Long khieuNaiId);

    @Operation(summary = "Cập nhật chèn nợ", description = "", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/cnChenNo", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> cnChenNo(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody CNChenNoRequest requestBody);

    @Operation(summary = "Hoàn thiện hồ sơ khiếu nại", description = "traLoi: kq xu ly duoc: nd tra loi; kq ko xu ly duoc: nd ton", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/hoanThienHSKN", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> hoanThienHSKN(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody HoanThienHSKhieuNaiRequest requestBody);

    @Operation(summary = "Hoàn thiện hồ sơ khiếu nại", description = "traLoi: kq xu ly duoc: nd tra loi; kq ko xu ly duoc: nd ton", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/khoaPhieu", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> khoaPhieu(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody KhoaPhieuKhieuNaiRequest requestBody);

    @Operation(summary = "Lấy danh sách phiếu khiếu nại", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/dsPhieuKN", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<PhieuKN>>> dsPhieuKN(@NotNull @Parameter(in = ParameterIn.QUERY, description = "maTB", required = true, schema = @Schema()) @Valid @RequestParam(value = "maTB", required = true) String maTB);

    @Operation(summary = "Trả phiếu", description = "", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/traPhieu", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> traPhieu(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody TraPhieuKhieuNaiRequest requestBody);

    @Operation(summary = "Giao việc", description = "", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/giaoViec", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> giaoViec(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody GiaoViecXLKhieuNaiRequest requestBody);

    @Operation(summary = "Danh sách hướng giao", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/dsHuongGiao", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<HuongGiaoPhieuKN>>> dsHuongGiao(@NotNull @Parameter(in = ParameterIn.QUERY, description = "quyTrinhId", required = true, schema = @Schema()) @Valid @RequestParam(value = "quyTrinhId", required = true) Long quyTrinhId);

    @Operation(summary = "Danh sách đơn vị giao", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/dsDonViGiao", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<DVGiaoPhieuKN>>> dsDonViGiao(@NotNull @Parameter(in = ParameterIn.QUERY, description = "huongGiaoId", required = true, schema = @Schema()) @Valid @RequestParam(value = "huongGiaoId", required = true) Long huongGiaoId);

    @Operation(summary = "Danh sách phiếu đã giao", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/dsPhieuDaGiao", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<PhieuDaGiaoKN>>> dsPhieuDaGiao(@NotNull @Parameter(in = ParameterIn.QUERY, description = "phieuKNId", required = true, schema = @Schema()) @Valid @RequestParam(value = "phieuKNId", required = true) Long phieuKNId);

    @Operation(summary = "Giao phiếu phối hợp", description = "", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/giaoPhieuPH", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> giaoPhieuPH(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody GiaoPhieuPHKhieuNaiRequest requestBody);

    @Operation(summary = "Danh sách hồ sơ khiếu nại", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/dsHoSoKN", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<HoSoKN>>> dsHoSoKN(@NotNull @Parameter(in = ParameterIn.QUERY, description = "khieuNaiId", required = true, schema = @Schema()) @Valid @RequestParam(value = "khieuNaiId", required = true) Long khieuNaiId,
                                                                     @NotNull @Parameter(in = ParameterIn.QUERY, description = "kyHD", required = true, schema = @Schema()) @Valid @RequestParam(value = "kyHD", required = true) String kyHD);

    @Operation(summary = "Cập nhật hồ sơ khiếu nại", description = "", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/cnHoSoKN", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> cnHoSoKN(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody CNHoSoKhieuNaiRequest requestBody);

    @Operation(summary = "Xóa hồ sơ khiếu nại", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/xoaHoSoKN", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<Void>> xoaHoSoKN(@NotNull @Parameter(in = ParameterIn.QUERY, description = "hoSoKNId", required = true, schema = @Schema()) @Valid @RequestParam(value = "hoSoKNId", required = true) Long hoSoKNId);

    @Operation(summary = "Danh sách giao việc nhân viên", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/dsGiaoViecNV", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<GiaoViecNV>>> dsGiaoViecNV(@NotNull @Parameter(in = ParameterIn.QUERY, description = "phieuKNId", required = true, schema = @Schema()) @Valid @RequestParam(value = "phieuKNId", required = true) Long phieuKNId);

    @Operation(summary = "Xóa giao việc nhân viên", description = "", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/xoaGiaoViecNV", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> xoaGiaoViecNV(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody XoaGiaoViecNVRequest requestBody);

    @Operation(summary = "Danh sách tháng giảm cước", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/dsThangGC", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<ThangGC>>> dsThangGC(@NotNull @Parameter(in = ParameterIn.QUERY, description = "maTT", required = true, schema = @Schema()) @Valid @RequestParam(value = "maTT", required = true) String maTT,
                                                        @NotNull @Parameter(in = ParameterIn.QUERY, description = "maTB", required = true, schema = @Schema()) @Valid @RequestParam(value = "maTB", required = true) String maTB);

    @Operation(summary = "Danh sách kỳ áp GC", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/dsKyApGC", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<List<KyApGC>>> dsKyApGC();

    @Operation(summary = "Chuyển Net Media", description = "", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/chuyenNetMedia", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<?>> chuyenNetMedia(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody ChuyenNetMediaXLKN requestBody);

    @Operation(summary = "Hủy giao việc", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/huyGiaoViec", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<Void>> huyGiaoViec(@NotNull @Parameter(in = ParameterIn.QUERY, description = "phieuKNId", required = true, schema = @Schema()) @Valid @RequestParam(value = "phieuKNId", required = true) Long phieuKNId);

    @Operation(summary = "Hủy giao phiếu", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/huyGiaoPhieu", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<Void>> huyGiaoPhieu(@NotNull @Parameter(in = ParameterIn.QUERY, description = "phieuKNId", required = true, schema = @Schema()) @Valid @RequestParam(value = "phieuKNId", required = true) Long phieuKNId);

    @Operation(summary = "Hủy giao phiếu phối hợp", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/huyGiaoPhieuPH", produces = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<BaseResponse<Void>> huyGiaoPhieuPH(@NotNull @Parameter(in = ParameterIn.QUERY, description = "phieuKNId", required = true, schema = @Schema()) @Valid @RequestParam(value = "phieuKNId", required = true) Long phieuKNId);

    @Operation(summary = "Cập nhật/Xóa/Thêm mới NHÂN VIÊN lỗi", tags = {"Xử lý Khiếu nại"})
    @RequestMapping(value = "/capNhatLoiNVXLKN", produces = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<BaseResponse<Void>> capNhatLoiNVXLKN(@NotNull @Parameter(in = ParameterIn.DEFAULT, description = "", required = true, schema = @Schema()) @Valid @RequestBody CapNhatLoiNVXLKN requestBody);
}

