export default {
    ur_41003_000_CSS_TINH: async (axios, data, header) => axios.get('/web-quantri/danhmuc-chung/CSS_TINH', data, header),
    ur_41003_001_lay_ds_thamso_md_mats: (axios, data) => axios.post('/web-ccdv/khaibaotsl/lay_ds_thamso_md_mats', data),
    ur_41003_002_lay_thamso_macdinh: (axios, data) => axios.post('/web-hopdong/lapdatmoi/lay_thamso_macdinh', data),
    fn_tt_tinh: (axios, data) => axios.post('/web-tratruoc/thongtin_tratruoc_dn/fn_tt_tinh', data),
    ur_41003_004_BAOHONG_NHOMTON: async (axios, data, header) => axios.get('/web-quantri/danhmuc-chung/BAOHONG_NHOMTON', data, header),
    ur_41003_005_CSS_DICHVU_VT: async (axios, data, header) => axios.get('/web-quantri/danhmuc-chung/CSS_DICHVU_VT', data, header),
    ur_41003_006_sp_lay_ds_nhanvien_theo_donvi: async (axios, data, header) => axios.get('/web-ccdv/khaibaoims/sp_lay_ds_nhanvien_theo_donvi', data, header),
    ur_41003_007_sp_lay_ds_tramthicong_v2: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/sp_lay_ds_tramthicong_v2', data),
    ur_41003_008_lay_ds_phieu_hoancong_bh_v4: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/lay_ds_phieu_hoancong_bh_v4', data),
    ur_41003_009_lay_ds_phieu_hoancong_bh_v5: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/lay_ds_phieu_hoancong_bh_v5', data),
    ur_41003_010_lay_ds_phieu_baoduong_ttdh: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/lay_ds_phieu_baoduong_ttdh', data),
    ur_41003_011_lay_ds_phieu_theodoi_cho_ht: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/lay_ds_phieu_theodoi_cho_ht', data),
    ur_41003_012_lay_ds_phieu_hoancong_bh_v6: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/lay_ds_phieu_hoancong_bh_v6', data),
    ur_41003_013_lay_thongtin_diachi: (axios, data) => axios.post('/web-baohong/TiepNhanBaoHong/lay_thongtin_diachi', data),
    ur_41003_014_lay_ds_thongtin_kythuat: (axios, data) => axios.post('/web-baohong/TiepNhanBaoHong/lay_ds_thongtin_kythuat', data),
    ur_41003_015_sp_lay_ds_nhom_nn: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/sp_lay_ds_nhom_nn', data),
    ur_41003_016_sp_lay_ds_nhom_nn_v2: (axios, data) => axios.post('/web-baohong/xuly_nghiemthubaohong/sp_lay_ds_nhom_nn_v2', data),
    ur_41003_017_sp_lay_ds_quytrinh_bh_theo_dichvuvt_id: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/sp_lay_ds_quytrinh_bh_theo_dichvuvt_id', data),
    ur_41003_018_lay_ds_nhomton_theoloai: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/lay_ds_nhomton_theoloai', data),
    ur_41003_019_sp_lay_ds_nguyennhan_hong: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/sp_lay_ds_nguyennhan_hong', data),
    ur_41003_020_lay_ds_nguyennhan_baohong_v2: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/lay_ds_nguyennhan_baohong_v2', data),
    ur_41003_021_lay_ds_danhba_adsl: async (axios, data, header) => axios.get(`/web-hopdong/hopdong/lay_ds_danhba_adsl?thueBaoId=${data.thueBaoId}`, data, header),
    ur_41003_022_sp_lay_ds_baohong_bc_thicong: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/sp_lay_ds_baohong_bc_thicong', data),
    ur_41003_023: "Mở form frmGiaoPhieuBHNV_v2",
    ur_41003_024_lay_ds_nhanvien_theo_phieu_id: (axios, data) => axios.get(`/web-baohong/baohong/lay_ds_nhanvien_theo_phieu_id?phieu_id=${data.phieu_id}&kieu_id=${data.kieu_id}`, data),
    ur_41003_025_lay_ds_thongbao_suco_ttvt: (axios, data) => axios.post('/web-baohong/xuly_nghiemthubaohong/lay_ds_thongbao_suco_ttvt', data),
    ur_41003_026: "ur_41003_009_lay_ds_phieu_hoancong_bh_v5",
    ur_41003_027_lay_ds_phieu_hoancong_bh_119: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/lay_ds_phieu_hoancong_bh_119', data),
    ur_41003_028_sp_lay_ds_tinhtrang: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/sp_lay_ds_tinhtrang', data),
    ur_41003_029: "ur_41003_020_lay_ds_nguyennhan_baohong_v2",
    ur_41003_030: "ur_41003_019_sp_lay_ds_nguyennhan_hong",
    ur_41003_031: "ur_41003_024_lay_ds_nhanvien_theo_phieu_id",
    ur_41003_032_lay_thongtin_nghiemthu_bh: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/lay_thongtin_nghiemthu_bh', data),
    ur_41003_033_sp_lay_ds_thaotac_theo_luong_id: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/sp_lay_ds_thaotac_theo_luong_id', data),
    ur_41003_034: "Mở form frmThongSoTSL (không tìm thấy trong form)",
    ur_41003_035_lay_toado_lapdat: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/lay_toado_lapdat', data),
    ur_41003_036_capnhat_toado_thuebao_v2: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/capnhat_toado_thuebao_v2', data),
    ur_41003_037: "Mở form Giao phiếu điểm chia Trung gian TSL (UR2.3.017) - frmGiaoPhieu_DiemChia_TrungGian_TSL",
    ur_41003_038_fn_lay_ttbh_id_theo_phieu_id: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/fn_lay_ttbh_id_theo_phieu_id', data),
    ur_41003_039_capnhat_baoton_119: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/capnhat_baoton_119', data),
    sp_tt_donvi: (axios, data) => axios.post('/web-hopdong/laydulieu/sp_tt_donvi', data),
    ur_41003_040_giaophieu_doitac: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/giaophieu_doitac', data),
    ur_41003_041_giaophieu_chuyen_theodoi_v2: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/giaophieu_chuyen_theodoi_v2', data),

    ur_41003_043_sp_lay_ds_phieuvt_hdbh: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/sp_lay_ds_phieuvt_hdbh', data),
    ur_41003_044_fn_ntbh_chuyenttdh: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/fn_ntbh_chuyenttdh', data),

    ur_41003_057_fn_ntbh_hoancong: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/fn_ntbh_hoancong', data),

    ur_41003_070_fn_ntbh_hoanthanh: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/fn_ntbh_hoanthanh', data),
    
    ur_41003_077_fn_ntbh_nghiemthu: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/fn_ntbh_nghiemthu', data),
    ur_41003_078_fn_ntbh_hoanthanh_nhieuphieu: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/fn_ntbh_hoanthanh_nhieuphieu', data),

    ur_41003_112_fn_ntbh_chuyenttvt: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/fn_ntbh_chuyenttvt', data),
    ur_41003_113_fn_ntbh_capnhatkq: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/fn_ntbh_capnhatkq', data),
    ur_41003_114_fn_ntbh_chuyentheodoi: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/fn_ntbh_chuyentheodoi', data),
    ur_41003_115_fn_ntbh_baoton: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/fn_ntbh_baoton', data),
    ur_41003_116_fn_ntbh_capnhatkq_nhieuphieu: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/fn_ntbh_capnhatkq_nhieuphieu', data),

    ur_41003_fn_ntbh_kiemtra_phieu: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/fn_ntbh_kiemtra_phieu', data),
  
    lay_ds_thamso_macdinh_dv: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/lay_ds_thamso_macdinh_dv', data),
    get_data_by_url: (axios, data) => axios.get(`/tichhop/util/download?url=${data.url}`, data),

    lay_ds_phieu_phoihop_khdn: (axios, data) => axios.post('/web-ccdv/xuly_nghiemthubaohong/lay_ds_phieu_phoihop_khdn', data),
    capnhat_giaophieu_ph: (axios, data) => axios.post('/web-bancheo/tracuu/capnhat_giaophieu_ph', data),
}
  