const NghiepVu = Object.freeze({
  LOAI_CT: 'LOAI_CT',
  NHOM_BC: 'NHOM_BC',
  LOAI_HD: 'LOAI_HD',
  BAOCAO: 'BAOCAO',
  NHOM_QT: 'NHOM_QT',
  QUYTRINH: 'QUYTRINH',
  HUONGGIAO_DAGAN: 'HUONGGIAO_DAGAN',
  HUONGGIAO_CHUAGAN: 'HUONGGIAO_CHUAGAN',
  TINH_DAGAN: 'TINH_DAGAN',
  TINH_CHUAGAN: 'TINH_CHUAGAN'
});
export default NghiepVu
