export const RESEND_OTP_SECONDS = 90;

export const PARAM_ACCESS_TOKEN = 'accessToken';
export const PARAM_USER_ROLE = 'role';
export const PARAM_CALENDAR = { START: 'start', END: 'end' };
export const PARAM_SCROLL_POSITION = 'position';
export const PARAM_REDIRECT = 'redirect';

export const GOOGLE_CLIENT_ID = '645927891352-h36tpru1ldbbuttfifotr5qe21o4plbv.apps.googleusercontent.com';
export const KAKAO_CLIENT_ID = '8b73be52c9ec8918656be5fdbcdb7300';

export const ERROR_MESSAGE = {
  INVALID_DATE: 'Invalid date',
  INVALID_USER_ROLE: 'Invalid user role',
  INVALID_USER_STATUS: 'Invalid user status',
  INVALID_AUTH_SOCIAL_PROVIDER: 'Invalid auth social provider',
};

export const QUERY_KEYS = {
  USER_DETAILS: 'USER_DETAILS',
  BUSINESS_FIELD_CATEGORIES: 'BUSINESS_FIELD_CATEGORIES',
  ADVISORY_FIELD_CATEGORIES: 'ADVISORY_FIELD_CATEGORIES',
  MEDICAL_FIELD_CATEGORIES: 'MEDICAL_FIELD_CATEGORIES',
  NEWS: 'NEWS',
  STORAGE_PRESIGNED_URL: 'STORAGE_PRESIGNED_URL',
  PROJECTS: {
    INDIVIDUAL: {
      LIST: 'PROJECTS_INDIVIDUAL_LIST',
      STATISTICS: 'PROJECTS_INDIVIDUAL_STATISTICS',
      PROPOSAL_MEETINGS: 'PROPOSAL_MEETINGS',
      CAN_CONFIRM_MEETING: 'CAN_CONFIRM_MEETING',
    },
    EXPERT: {
      LIST: 'PROJECTS_EXPERT_LIST',
      STATISTICS: 'PROJECTS_EXPERT_STATISTICS',
      PROPOSAL_MEETINGS: 'PROPOSAL_MEETINGS',
      CAN_CONFIRM_MEETING: 'CAN_CONFIRM_MEETING',
    },
    EXPERT_MATCHING: 'EXPERT_MATCHING',
  },
  TERMS: 'TERMS',
  FAQS: 'FAQs',
  ANNOUNCEMENTS: 'ANNOUNCEMENTS',
  INQUIRIES: 'INQUIRIES',
  INQUIRY_CATEGORIES: 'INQUIRIES_CATEGORIES',
  PRIVACIES: 'PRIVACIES',
};
