import { NavbarVariant } from '@/components/core/navbar/Navbar';
import { ROUTES } from '@/router/routes.constant';

export const NAVBAR_MAPPER: Record<NavbarVariant, string[]> = {
  'with-links': [
    ROUTES.HOME,

    ROUTES.FAQ,

    ROUTES.ANNOUNCEMENT.self,
    ROUTES.ANNOUNCEMENT.DETAIL,

    ROUTES.NEWS.self,
    ROUTES.NEWS.DETAIL,

    ROUTES.INQUIRY.self,
    ROUTES.INQUIRY.DETAIL,

    ROUTES.PROJECT_MANAGEMENT.INDIVIDUAL,
    ROUTES.PROJECT_MANAGEMENT.EXPERT,
    ROUTES.PROJECT_REQUEST.INDIVIDUAL.REQUEST,
    ROUTES.PROJECT_MANAGEMENT.DETAIL.INDIVIDUAL,
    ROUTES.PROJECT_MANAGEMENT.DETAIL.EXPERT,

    ROUTES.MY_PAGE.EXPERT.self,
    ROUTES.MY_PAGE.INDIVIDUAL.self,
    ROUTES.MY_PAGE.self,
  ],

  'with-sign-up-btn': [ROUTES.LOGIN, ROUTES.FIND.self, ROUTES.FIND.ID, ROUTES.FIND.PASSWORD, ROUTES.ACCOUNT.CHANGE_PASSWORD],
  'with-login-btn': [
    ROUTES.SIGN_UP.self,
    ROUTES.SIGN_UP.INDIVIDUAL.STEP_1,
    ROUTES.SIGN_UP.INDIVIDUAL.STEP_2,
    ROUTES.SIGN_UP.EXPERT.STEP_1,
    ROUTES.SIGN_UP.EXPERT.STEP_2,
  ],
};
