export default {
  getDanhSachThamSoMacDinh: (axios, body) => axios.post('web-ccdv/khaibaotsl/sp_lay_ds_thamso_md', body),
  getDanhSachHopDongByMaTB: (axios, body) => axios.post('web-hopdong/thanhly/lay_ds_hd_theo_ma_tb', body),
  getDanhSachHDTBByHDKHId: (axios, body) => axios.post('web-hopdong/tracuu_chitiet_thicong/lay_ds_hd_tb_theo_hdkh_id_v3', body),
  getDanhSachDiaChiByHDTBId: (axios, hdtbId) => axios.get(`web-hopdong/hopdong/lay_ds_diachi_theo_hdtb?hdtbId=${hdtbId}`),
  getDanhSachTienKhoanMuc: (axios, body) => axios.post('web-hopdong/khoiphucthanhly/sp_lay_tienkhoanmuc_theo_loaihd', body),
  getDanhSachKhuyenMaiHDTB: (axios, body) => axios.post('web-ccdv/sua-tien-hop-dong/lay_khuyenmai_hdtb', body),
  getDanhSachThueBaoDichVu: (axios, body) => axios.post('web-hopdong/khoiphucthanhly/lay_ds_thuebao_dichvu', body),
  getDanhSachDVGT: (axios, body) => axios.post('web-ccdv/sua-tien-hop-dong/sp_lay_ctkm_dvgt', body),
  getDanhSachMuaThietBi: (axios, body) => axios.post('web-hopdong/thanhly/lay_ds_mua_tbi', body),
  getTienHDKhuyenMaiHDTB: (axios, body) => axios.post('web-ccdv/sua-tien-hop-dong/sp_Lay_tienhd_km_theo_hdtb', body),
  getChiTietKMByHDTBId: (axios, hdtbId, loaiKM) => axios.get(`web-ccdv/HoanCongThuTienPhatSinh/lay_chitiet_km_theo_hdtb_id?vhdtb_id=${hdtbId}&vloai_km=${loaiKM}`),
  countCTKMTraGopTbi: (axios, body) => axios.post('web-tratruoc/thongtin_tratruoc_dn/fn_tt_ctkm_tragop_tbi', body),
  getHtTtctThietbiLoaitbi: (axios, body) => axios.post('web-ccdv/ban-thiet-bi/sp_ht_ttct_thietbi_loaitbi', body),
  getCTKMLoaiTbi: (axios, body) => axios.post('web-ccdv/ban-thiet-bi/sp_lay_ctkm_loai_tbi', body),
  getDanhSachTraGopTbi: (axios, body) => axios.post('web-hopdong/thaydoiloaihinhtb/sp_lay_ds_tragop_thietbi', body),
  kiemTraThayDoiKM: (axios, body) => axios.post('web-hopdong/lapdatmoi/kiemtra_thaydoi_km', body),
  getDsKMThietBiByCTKMId: (axios, body) => axios.post('web-ccdv/sua-tien-hop-dong/sp_layds_km_thietbi_theoctkmid', body),
  capNhatKMTienHd: (axios, body) => axios.post('web-ccdv/sua-tien-hop-dong/fn_capnhat_khuyenmai_tienhd', body),
  getKeys: (axios, body) => axios.post('web-quantri/donvitinh/get_keys', body),
  ts_laphd_hoamangmoi_layds_cuocld: (axios, body) => axios.post('ccbs/executor/ts_laphd_hoamangmoi_layds_cuocld', body),
  getDanhSachPhieuChuaTT: (axios, body) => axios.post('web-hopdong/khuyenmai-thaydoi-loaihinhtb/lay_ds_phieu_chuatt', body),
  kiemTraHienThiThietBi: (axios, body) => axios.post('web-hopdong/dichvu-cntt-gtgt/fn_kiemtra_hienthi_thietbi_theo_loaitb', body),
  getDanhSachTBiByTocDo: (axios, body) => axios.post('web-hopdong/lapdatmoi/lay_ds_thietbi_theo_tocdo', body),
  getDanhSachTbi: (axios, body) => axios.post('web-hopdong/lapdatmoi/lay_ds_thietbi', body),
  getDanhSachTienKMTT: (axios, body) => axios.post('web-hopdong/lapdatmoi/lay_ds_tien_kmtt', body),
  getKhoanMucByLoaiHD: (axios, body) => axios.post('web-hopdong/lapdatmoi/lay_khoanmuc_tt_theo_loaihd', body),
  getThongTinNguoiDung2: (axios) => axios.post('quantri/user/thongtin_nguoidung2', {}),
  getThongTinCN: (axios) => axios.get('web-quantri/nguoidung/thongtin'),
  getThongTinHdtbCntt: (axios, body) => axios.post('web-tratruoc/thongtin_tratruoc_dn/fn_tt_hdtb_cntt', body)
}
