# Maven build container
#FROM maven:3.5.2-jdk-8-alpine AS maven_build
FROM crelease.devops.vnpt.vn:10000/maven:3.6.2-jdk-8 AS maven_build
WORKDIR /tmp/
COPY pom.xml /tmp/
RUN mvn dependency:go-offline
COPY src /tmp/src/
RUN mvn package


#pull base image
FROM crelease.devops.vnpt.vn:10000/openjdk:8u242-jdk-slim
EXPOSE 80
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]
COPY --from=maven_build /tmp/target/*.jar /app.jar
