 # Unique ID for this project
sonar.projectKey=VNPT-IT.OneBSS.api_tichhop
sonar.projectName=VNPT-IT.OneBSS.api_tichhop
sonar.projectVersion=1.0
sonar.sources=src/.
sonar.java.source=src/main/java
sonar.java.binaries=src/main/java/vn/vnptit/sapi/oneapp
#sonar.java.binaries=**/target/classes
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/*.sh
sonar.login=c9c6bf81184ef5eb21b480c13ecf8ca495f7ccd5
#sonar.nodejs.executable=/usr/bin/nodejs
# sonar.css.node=/usr/bin/node
#sonar.skippedModules=ShellCheck
