const GRID_COLUMS = {
	1: [	
	  {fieldName: 'MA_KN', width : 200 , headerText: 'Mã khiếu nại', allowFiltering: true },
	  {fieldName: 'NGAY_TN', width : 200 , textAlign: 'Center', headerText: 'Ngày tiếp nhận', allowFiltering: true},
	  {fieldName: 'TEN_NV', width : 250 , headerText: 'Người tiếp nhận', allowFiltering: true},
	  {fieldName: 'MA_TB', width : 150 , headerText: 'Số máy/Acc', allowFiltering: true },
	  {fieldName: 'TEN_TB', width : 150 , headerText: 'Tên thuê bao', allowFiltering: true},
	  {fieldName: 'MA_KH', width : 150 , headerText: 'Mã khách hàng', allowFiltering: true},
	  {fieldName: 'TEN_DVVT', width : 150 , headerText: 'Dịch vụ', allowFiltering: true},
	  {fieldName: 'LOAIHINH_TB', width : 150 , headerText: 'Loại hình', allowFiltering: true},
	  {fieldName: 'NHOM_CHUDE', width : 150 , headerText: 'Nhóm chủ đề', allowFiltering: true},
	  {fieldName: 'CHUDE_C1', width : 150 , headerText: 'Chủ đề cấp 1', allowFiltering: true},
	  {fieldName: 'CHUDE_C2', width : 150 , headerText: 'Chủ đề cấp 2', allowFiltering: true},
	  {fieldName: 'KN_LAPLAI', width : 150 , headerText: 'Khiếu nại lặp', allowFiltering: true},
	  {fieldName: 'KN_VUOTCAP', width : 150 , headerText: 'Khiếu nại vượt', allowFiltering: true},
	  {fieldName: 'KN_KHANCAP', width : 150 , headerText: 'Khiếu nại khẩn', allowFiltering: true},
	  {fieldName: 'NGUOI_KN', width : 150 , headerText: 'Người khiếu nại', allowFiltering: true},
	  {fieldName: 'DIENTHOAI_LH', width : 150 , headerText: 'Điện thoại LH', allowFiltering: true},
	  {fieldName: 'DIACHI_LH', width : 150 , headerText: 'Địa chỉ LH', allowFiltering: true},
	  {fieldName: 'HENGQ_TU', width : 150 , headerText: 'Hện từ', allowFiltering: true},
	  {fieldName: 'HENGQ_DEN', width : 150 , headerText: 'Hẹn đến', allowFiltering: true},
	  {fieldName: 'NGAY_CAMKET', width : 150 , headerText: 'Ngày cam kết', allowFiltering: true},
	  {fieldName: 'GIO_CAMKET', width : 150 , headerText: 'Giờ cam kết', allowFiltering: true},
	  {fieldName: 'ND_XULY', width : 250 , headerText: 'Kết quả xử lý', allowFiltering: true},
	  {fieldName: 'NGAY_TRAPHIEU', width : 150 , headerText: 'Ngày trả', allowFiltering: true},
	  {fieldName: 'NBGUOI_TRAPHIEU', width : 150 , headerText: 'Người trả', allowFiltering: true},
	  {fieldName: 'KIEU_TRAPHIEU', width : 150 , headerText: 'Kiểu trả', allowFiltering: true},
	  {fieldName: 'TRANGTHAI', width : 150 , headerText: 'Trạng thái', allowFiltering: true},	
  ],
	2: [
	  {fieldName: 'MA_KN', width : 200 , headerText: 'Mã khiếu nại', allowFiltering: true },
	  {fieldName: 'NGAY_TN', width : 200 , textAlign: 'Center', headerText: 'Ngày tiếp nhận', allowFiltering: true},
	  {fieldName: 'TEN_NV', width : 250 , headerText: 'Người tiếp nhận', allowFiltering: true},
	  {fieldName: 'MA_TB', width : 150 , headerText: 'Số máy/Acc', allowFiltering: true },
	  {fieldName: 'TEN_TB', width : 150 , headerText: 'Tên thuê bao', allowFiltering: true},
	  {fieldName: 'MA_KH', width : 150 , headerText: 'Mã khách hàng', allowFiltering: true},
	  {fieldName: 'TEN_DVVT', width : 150 , headerText: 'Dịch vụ', allowFiltering: true},
	  {fieldName: 'LOAIHINH_TB', width : 150 , headerText: 'Loại hình', allowFiltering: true},
	  {fieldName: 'NHOM_CHUDE', width : 150 , headerText: 'Nhóm chủ đề', allowFiltering: true},
	  {fieldName: 'CHUDE_C1', width : 150 , headerText: 'Chủ đề cấp 1', allowFiltering: true},
	  {fieldName: 'CHUDE_C2', width : 150 , headerText: 'Chủ đề cấp 2', allowFiltering: true},
	  {fieldName: 'KN_LAPLAI', width : 150 , headerText: 'Khiếu nại lặp', allowFiltering: true},
	  {fieldName: 'KN_VUOTCAP', width : 150 , headerText: 'Khiếu nại vượt', allowFiltering: true},
	  {fieldName: 'KN_KHANCAP', width : 150 , headerText: 'Khiếu nại khẩn', allowFiltering: true},
	  {fieldName: 'NGUOI_KN', width : 150 , headerText: 'Người khiếu nại', allowFiltering: true},
	  {fieldName: 'DIENTHOAI_LH', width : 150 , headerText: 'Điện thoại LH', allowFiltering: true},
	  {fieldName: 'DIACHI_LH', width : 150 , headerText: 'Địa chỉ LH', allowFiltering: true},
	  {fieldName: 'HENGQ_TU', width : 150 , headerText: 'Hện từ', allowFiltering: true},
	  {fieldName: 'HENGQ_DEN', width : 150 , headerText: 'Hẹn đến', allowFiltering: true},
	  {fieldName: 'NGAY_CAMKET', width : 150 , headerText: 'Ngày cam kết', allowFiltering: true},
	  {fieldName: 'GIO_CAMKET', width : 150 , headerText: 'Giờ cam kết', allowFiltering: true},
	  {fieldName: 'ND_XULY', width : 250 , headerText: 'Kết quả xử lý', allowFiltering: true},
	  {fieldName: 'NGAY_GIAO', width : 150 , headerText: 'Ngày giao', allowFiltering: true},
	  {fieldName: 'NGUOI_GIAO', width : 150 , headerText: 'Người giao', allowFiltering: true},
	  {fieldName: 'DONVI_NHAN', width : 150 , headerText: 'Đơn vị nhận', allowFiltering: true},
	  {fieldName: 'NGUOI_NHAN', width : 150 , headerText: 'Người nhận', allowFiltering: true},	
	  {fieldName: 'TRANGTHAI', width : 150 , headerText: 'Trạng thái', allowFiltering: true},	
	],
	  3: [
		  {fieldName: 'MA_TT', width : 200 , headerText: 'Mã thanh toán', allowFiltering: true },
		  {fieldName: 'MA_TB', width : 200 , headerText: 'Mã thuê bao', allowFiltering: true },
		  {fieldName: 'HOADON', width : 200 , headerText: 'Thông tin hóa đươn', allowFiltering: true },
  
		  {fieldName: 'THANG_GC', width : 200 , headerText: 'Tháng GC', allowFiltering: true },
		  {fieldName: 'KY_GC', width : 200 , textAlign: 'Center', headerText: 'Kỳ giảm', allowFiltering: true},
		  {fieldName: 'TIEN', width : 250 , headerText: 'Tiền giảm trừ', allowFiltering: true},
		  {fieldName: 'TIEN_GC', width : 150 , headerText: 'Tiền', allowFiltering: true },
		  {fieldName: 'VAT_GC', width : 150 , headerText: 'Thuế', allowFiltering: true},
		  {fieldName: 'VAT_PT', width : 150 , headerText: 'VAT%', allowFiltering: true},
		  {fieldName: 'MA_DT', width : 150 , headerText: 'Mã doanh thu', allowFiltering: true},
		  {fieldName: 'TEN_CHITIEU', width : 150 , headerText: 'Tên chỉ tiêu', allowFiltering: true},
		  {fieldName: 'PHUONG_AN', width : 150 , headerText: 'Phương án điều chỉnh', allowFiltering: true},
		  
	  ]	,
	 
  };
  
  export default GRID_COLUMS;
  